### ISSUE TITLE
[Vote Crates] Incorrect Reward Distribution Amount

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1782]
**Bug Description:**
I was opening vote crates and won a x16 Great Balls reward, but only received x10.

**Screenshots:**
![2022-08-25_02 41 44](https://user-images.githubusercontent.com/112078351/186637335-7a0cc387-8c24-4487-9406-78681d189cc7.png)
![2022-08-25_02 41 51](https://user-images.githubusercontent.com/112078351/186637345-5ffd24a2-4206-4c65-bfe7-6ea66b2420f1.png)

**Username:**
Dracten

**Server Name:**
Titan

**Additional Info:**
I'm not concerned about getting the missing reward reimbursed. I just want to make sure this feature is working properly for other players.

**Comment by HackuJacku** [comment]
This has now been fixed, thank you for reporting it :)
