### ISSUE TITLE
Kicking players does not boot from the network.

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1784]
Using /kick on the 3 playable servers results in the player being moved to hub, and if /kick from hub they end up on atlas instead of being booted from the network.

**Comment by KittyKatzyn** [comment]
Currently, being /kick'd from Orion caused me to be sent to the Hub, but being /kick'd from the Hub booted me from the network altogether.  Will need clarification whether this is the intended behaviour, or not.

**Comment by chefburne** [comment]
no longer an issue, closing
