### ISSUE TITLE
Wonder Trade

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1785]
If you Wondertrade a Pokemon that is currently sent out the model doesn't not despawn and is still rideable. 
It despawns when the area is unloaded.

Screenies:
![carkolwt](https://user-images.githubusercontent.com/17133410/186675291-5e3694f9-2000-4595-8a5e-67190f648019.png)

**Comment by HackuJacku** [comment]
This is fixed from the next reboot, thank you for reporting it :)
