### ISSUE TITLE
[Feature] Didnt get final rewards bingo

### ISSUE THREAD

**Issue by Westpaint15** [ObliqueNetwork/Terra#1786]
Was busy with bingo but the server crashed and it added pokemon to my bingo card that I already caught. I have a screenshot of my bingocard before the crash and after the crash. IGN is Westpaint15 and server titan

before the crash:
![image](https://user-images.githubusercontent.com/112103336/186703436-a9873339-6e0c-4f06-8df8-bbd96db8e952.png)

afther the crash:
![image](https://user-images.githubusercontent.com/112103336/186703690-191effdc-d645-4087-9649-73eb24074346.png)

second crash:
![image](https://user-images.githubusercontent.com/112103336/186719516-c4aef54f-0007-4a0f-89b4-e764df9193be.png)

crashed again when I was literally catching the scyther

afther the second crash:
![image](https://user-images.githubusercontent.com/112103336/186720485-580f40db-ba4e-495f-980d-60d75d5f97f1.png)

completed my bingo but didnt get my final rewards for completing it (7,500 coins, 1 random shiny, 1 HA or shiny, 1 random legendary item)
 
 Can I get this refunded

**Comment by MissElyri** [comment]
I have refunded the money and the legendary item, however I need you to be online for me to refund the random mon; Closing for now
