### ISSUE TITLE
[Feature] 5x astral key bug

### ISSUE THREAD

**Issue by Westpaint15** [ObliqueNetwork/Terra#1787]
**Describe the bug**
5 astral crate keys disappeared after opening the crate

**Expected behavior**
I bought 5 astral crate keys and wanted to open them. The moment I tried to open the astral crate all my keys disappeared and I didnt get a single reward. 

**Screenshots**
![image](https://user-images.githubusercontent.com/112103336/186705616-9be2771a-fc3e-44c9-867d-b1c504acc1ca.png)

**Username: Westpaint15 

**Server name (all applicable): Titan 

**Additional context**
Foxxarcher (Trialmod server titan) saw the astral crate keys disappear from my inventory

**Comment by fatyg5** [comment]
Please message me on Discord (Fatyg5#0001) the next time you are online!
