### ISSUE TITLE
Master rank unluck: did not receive IV mod and abillity mod

### ISSUE THREAD

**Issue by PirateBae1** [ObliqueNetwork/Terra#1788]
**Describe the bug**
At the time of claiming the kit my inventory was to full to accept all items. Some items like the masterball and 32 rare candies fell on the ground however, there was no IV mod or Nature mod as a reward. 

**To Reproduce**
1. Go to 'dexrewards, with not enough inventory space'
2. Click on 'claim master kit'

**Expected behavior**
Receive all items mentioned in the rewards for obtaining master. Have them fall on the ground if inventory is too full or be able to claim them later.
**Screenshots**
see attached files
![adfasd](https://user-images.githubusercontent.com/112118668/186742992-7e9615bb-b2eb-4e0f-8e1f-9a45b4e421b7.png)

**Username:**
PirateBae
**Server name (all applicable):**
Titan
**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by KittyKatzyn** [comment]
This issue has been resolved!  Closing!
