### ISSUE TITLE
[Feature] Didn't get bingo rewards due to server crash

### ISSUE THREAD

**Issue by K3NZIE666** [ObliqueNetwork/Terra#1789]
**Didn't receive Bingo rewards due to server crash**

I was on my last catch for my Bingo which was a Axew, I started the fight but exactly as I threw the pokeball the server went down, I was in discord with the Helper EVIE the time, when the server went down I was forced back to lobby and writ in the chat " I hope the bingo card doesn't reset as I was on my last catch when it went down"  When I logged back in all my bingo card was green but I hadn't received any loot, the server crash happened at 4:09pm 25/08/22

**To Reproduce**
Steps to reproduce the behaviour:
1. Make the server crash just as you catch your last bingo pokemon

**Expected behaviour**

Log back in and would've had to try and find Axew again due to the server crashing whilst throwing pokeballs at him.

**Screenshots**
Screen shots show the messages and screenshots I sent to Evie and the time showing him I hadn't received anything and that my bingo card was full.

![image](https://user-images.githubusercontent.com/112122535/186753397-22d9a37b-4d6a-480f-bb2b-b1bcfbdd9641.png)

**Username:**
K3NZIE666
**Server name (all applicable):**
Titan
**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**
Evie is a Helper and was helping me complete my bingo at the time and can corroborate my story if needed.

**Comment by K3NZIE666** [comment]
The same thing also happened to Vosje in discord.

![image](https://user-images.githubusercontent.com/112122535/186935689-d6e16d37-8a3f-40e1-a47a-49860dd63f39.png)

**Comment by MissElyri** [comment]
Both players have been refunded; Closing

**Comment by MissElyri** [comment]
Refunded; Closing
