### ISSUE TITLE
Non-shop ranks have access to /glow

### ISSUE THREAD

**Issue by Chunkkss** [ObliqueNetwork/Terra#1791]
![2022-08-25_15 32 20](https://user-images.githubusercontent.com/107234416/186773001-96486df3-44c6-49f0-ab87-0978d8ebddf0.png)

Player's have access to /glow username
Only white glow is accessable

**Comment by Gealt** [comment]
Also works in the hub

**Comment by Chunkkss** [comment]
It's good to note that these players cannot turn off the glow once activated.

**Comment by StrideMate** [comment]
In a effort to reduce old threads, I will be closing this for the time being! I believe this has been fixed since the report. Please reopen the same ticket, Or make another ticket if this issue arises in the future! Thank you!

**Comment by StrideMate** [comment]
Updating this issue. This is still currently a issue on Atlas, Non-donors can use **/glow on**.

**Comment by KittyKatzyn** [comment]
Confirmed!  Needs to be migrated!

**Comment by KittyKatzyn** [comment]
Forwarded to Internal! Will be updated here when fixed!

**Comment by chefburne** [comment]
no longer relevant, closing
