### ISSUE TITLE
/dexrewards not showing percentage of dex completion

### ISSUE THREAD

**Issue by FoxArcher** [ObliqueNetwork/Terra#1792]
When using /dexrewards, normally your completed dex percentage is shown when hovering over your dex info. Instead it is being replaced by static chat "You have completed %percentage% of the Pokedex."

![image](https://user-images.githubusercontent.com/108157492/186781691-55936e26-e374-465e-990c-68e95abad3df.png)
SS above from Titan

![image](https://user-images.githubusercontent.com/108157492/186781905-1033fdbb-a993-4f4f-ac6e-23b636459620.png)
SS above from Orion

![image](https://user-images.githubusercontent.com/108157492/186782011-11684c2e-8ae0-4f89-b49a-1073ebab96cc.png)
SS above from Altas

**Username:** FoxxArcher

**Server name (all applicable):** TITAN ONLY

**Logs:**

[dexrewards bug.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9428654/dexrewards.bug.txt)

**Comment by Deathnight7976** [comment]
This is now also an issue on Orion and Atlas.

**Comment by HackuJacku** [comment]
Hi, this is now fixed. Thank you for reporting :)
