### ISSUE TITLE
[Form Mod] Potentially Causes Palettes to Disappear

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1793]
**Describe the bug**
I was messing around with a form mod just to check a few things, but didn't actually select anything to change. I simply exited out of the interface. It wasn't until later that I noticed my Strike palette Nintales was no longer Strike palette. Ninetales is also one of the mons I was messing around with. Notably, I had a Strike Gallade in my party that wasn't changed by this interaction. I also never tried to mess with it using the mod.

**To Reproduce**
1. Use a form mod on a mon with a palette.
2. Exit out of the interface without actually changing anything.
3. Observe the loss of the special palette texture..

**Expected behavior**
I would've expected there to be no change whatsoever since the mod wasn't actually used.

**Screenshots**
I don't take a lot of screenshots during general gameplay, so the first one isn't great. The chat is mostly covering Ninetales sprite, but you're still able to make out the darker Strike sprite it has compared to the 2nd picture.
![2022-08-24_02 27 07](https://user-images.githubusercontent.com/112078351/186824106-2d679851-987e-42ee-8b98-714b203684ca.png)
![2022-08-25_21 38 44](https://user-images.githubusercontent.com/112078351/186824114-e0f7c553-f5f7-46e2-bd1a-a1586a1d81d6.png)

**Username:**
Dracten

**Server name (all applicable):**
Titan

**Additional context**
I can't say with 100% certainty that the interaction occurred exactly as I've listed, as I didn't notice until a fair bit later that the change had occurred. I would appreciate receiving a palette mod to fix this, and would be willing to further test the issue if I knew that I could definitely change it back with a provided mod.

**Comment by Malphir** [comment]
I've received further reports of this occurring to other players. One player even had their shiny palette stripped. I'd say it's safe to assume the form mods are definitely the issue. Every instance so far has involved them.

**Comment by HackuJacku** [comment]
Thank you for the report, I have confirmed that this is now fixed :)
