### ISSUE TITLE
Mewtwo Y dropping wrong stone

### ISSUE THREAD

**Issue by MissElyri** [ObliqueNetwork/Terra#1794]
Megas should be dropping their respective stones;
 Mega Mewtwo X should drop Mewtwonite X, and Mega Mewtwo Y should drop Mewtwonite Y; 
  I defeated Mega Mewtwo Y and received Mewtwonite X. Sadly I don't have a screenshot of the Mega Mewtwo itself; but Evie (Titan) was there when I defeated it  
  
![image](https://user-images.githubusercontent.com/78369601/186867736-194cc422-3bd7-44c8-8577-e2f0a049ede8.png)

**Comment by Rasgnarok** [comment]
Already reported in the main mod, pending fix: https://pixelmonmod.com/tracker.php?p=2&t=18680
