### ISSUE TITLE
Rayquaza's mega not working 

### ISSUE THREAD

**Issue by Kryla** [ObliqueNetwork/Terra#1795]
When in a battle you click the mega button and choose a move, when rayquaza attacks, it doesn't transform in his mega form.
Necrozma infused with lunala/solgaleo with ultranecrozmanite-z, when in a battle you click the mega button and choose a move it doesn't work
Ign kryla 
Server titan

**Comment by CenizaRey** [comment]
These are both known issues with the Pixelmon Mod itself, there's nothing we can do for them serverside, unfortunately. Closing.
