### ISSUE TITLE
[/wiki] /wiki Spewpa evo info is ridiculous

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1796]
**Describe the bug**
When using the /wiki Spewpa evo command your chat will be filled with so much info that it gets completely wiped and can't even display all of the info. This also includes info for biomes we don't even have on the server.

**To Reproduce**
1. Enter the '/wiki Spewpa evo' command.
2. Observe the mass text wall that wipes all other chat.

**Expected behavior**
To get info that would actually fit in chat.

**Screenshots**
![2022-08-26_17 24 07](https://user-images.githubusercontent.com/112078351/187006874-e47b795c-2ee0-4ce4-a3d6-472e957e73c6.png)
![2022-08-26_17 24 03](https://user-images.githubusercontent.com/112078351/187006879-00894b63-8e33-45be-8027-9f1a0342efc3.png)

**Username:**
Dracten

**Server name (all applicable):**
Titan

**Comment by HackuJacku** [comment]
This command is being overhauled in Pixelmon 9.0.9 - please see the #upcoming-changelog in discord.gg/pixelmon
