### ISSUE TITLE
Hisiuan Zoroark Move learning capabilities via TM/TR seem Bugged

### ISSUE THREAD

**Issue by NebulaEvie** [ObliqueNetwork/Terra#1798]
**Describe the bug**
Hisuian Zoroark cannot learn moves it is supposed to be able to learn via TM. I have tested 3x Moves (Alolan TM36: Sludge Bomb/ TR02: Flamethrower/ TR33: ShadowBall). When I right click the TM/TR on Hisuian Zoroark, the message comes up in chat: Zoroark Cannot Learn X. Although in Hisuian Form, It is supposed to be able to learn all 3 of those moves. Cannot test with other TM's as I dont have cash to waste in game.

**To Reproduce**
1. Get a regular Zoroark and Form Mod it into Hisuian Zoroark (All Moves will become "Struggle")
2. Buy the needed TM/TR's Its meant to be able to learn
3. Throw out Hisuian Zoroark and right click the TM/TR on it

**Expected behavior**
It is expected to be able to learn all 3 of these moves without issue. Not sure if other TM/TR's dont work on it, may need further testing. I was thinking it is possible it believes its regular Zoroark, who maybe cannot learn these skills?

**Screenshots**
![image](https://user-images.githubusercontent.com/112235116/187017203-1c0da337-0a3c-485c-8410-07c276a38197.png)

**Username:**
Evie666

**Server name (all applicable):**
Titan (could be a problem on all)

**Logs:**
N/A

**Additional context**
N/A

**Comment by CenizaRey** [comment]
Given that Hisuian Zoroark is an 'ancient' pokemon, and exists in a time before TMs/TRs are invented - all of these moves are tutor moves. Unfortunately that means it cannot learn these moves until move tutors are introduced alongside the adventure map. Sorry for the inconvenience, and thank you for the report!
