### ISSUE TITLE
[/breed & /hatch] Cooldown Reset Upon Server Restart

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1799]
**Describe the bug**
The cooldowns of both /breed and /hatch get fully reset to 0 with a server restart. Confirmed this by breeding and hatching just before a scheduled restart, then again immediately after.

**To Reproduce**
1. /breed and /hatch an egg
2. do the same upon server restart, regardless of timeframe

**Expected behavior**
I expected the cooldown to carry over and continue rather than reset.

**Username:**
Dracten

**Server name (all applicable):**
Titan

**Comment by WisconsinWinters** [comment]
fixed
