### ISSUE TITLE
[Feature]/r not working propperly

### ISSUE THREAD

**Issue by dvos1998** [ObliqueNetwork/Terra#1800]
/r Doesn't always seem to respond to the last person who DMs you

**Comment by Chunkkss** [comment]
It responds to the person you last responded to.

**Comment by dvos1998** [comment]
Ely asked if someone could at it to the tracker, so i did

**Comment by MissElyri** [comment]
/r used to reply to the last person who DMed you, so I wasn't sure if it was ment to be this way, as it frustrates a lot of players.

**Comment by Vavalur** [comment]
![image](https://user-images.githubusercontent.com/107285589/187798447-c3f2c359-16b9-43a4-a983-d776e267402c.png)

Dev's website implies that it should be to whoever sent you a message last

**Comment by KittyKatzyn** [comment]
Still an issue!  Needs to be migrated to internal!

**Comment by KittyKatzyn** [comment]
Forwarded to the Internal tracker!  Will update here when fixed!
