### ISSUE TITLE
[Hidden Power Mod] Hidden power mod isn't staying changed

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1801]
**Describe the bug**
Using a hidden power mod doesn't seem to stay in place long term. It still shows the hidden power you selected if you use another mod to check the interface, but it isn't actually using that new hidden power type. I used it to change my Ninetales from Dark to Ice hidden power and it seemed to work at first. At this point it is 100% Dark type again. Still shows Ice in the interface, but is definitely Dark. It's also notable that the command to check hidden powers, /hiddenpower, was still showing Dark type immediately after use of the mod.

**To Reproduce**
1. use a hidden power mod to change the type
2. use /hiddenpower to check it and see that it still displays the old type
3. use another hidden power mod to double check interface
4. wait for the hidden power to revert fully to the original type

**Expected behavior**
I expected the hidden power to fully change to the new one and not reset.

**Screenshots**
![2022-08-24_02 27 07](https://user-images.githubusercontent.com/112078351/187030323-3b3a7776-9010-409c-bd5c-97b83d96003b.png)
![2022-08-27_04 59 36](https://user-images.githubusercontent.com/112078351/187030333-71a6ed41-b0ba-4932-a5a0-8e871d00ca4d.png)

**Username:**
Dracten

**Server name (all applicable):**
Titan

**Comment by Azazels696** [comment]
Hi ! :) I Used a Hidden Power mod on my 100% Zygarde to change is hidden dragon to grass. In the interface thats said i do with success but when i do ./hiddenpower still be dragon and definitly is...i left the game and reloag to see if that was just a lagg and saddly see that doesnt change anything...what can i do in that case ... please help me ! :/

**Comment by HackuJacku** [comment]
Thank you for reporting this, it is now fixed from the next server reboot :)
