### ISSUE TITLE
[UI] Orbs show completed orb stitched to the bottom

### ISSUE THREAD

**Issue by Vavalur** [ObliqueNetwork/Terra#1803]
**Describe the bug**
Empty orbs have the completed orb stitched below their texture

**To Reproduce**
1. Craft any orb
2. open a double chest
3. drag the orb up

**Expected behavior**
Only see the empty orb

**Screenshots**
![image](https://user-images.githubusercontent.com/107285589/187046032-5b63799e-b401-4600-90f4-b7b02d0006b1.png)

**Comment by CenizaRey** [comment]
Known Pixelmon bug. Nothing to be done on our end :( Closing.
