### ISSUE TITLE
Green color chat issue

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#1804]
The color chat for pay ranks is something interesting and funny, but there is an issue, and happens when someone with pay rank can change his color chat as the same of the legendary messages, could be by mistake or just for troll knowing is the same of the legendary messages.

Someone did that and i missed a legendary message, happily was not on me, but is not the first time im struggling to see the message when he writte a lot in the chat, if the legendary spawn on me and i miss it for that won't be funny. So would be nice a solution for that, cause as i said, is not funny.

**Comment by CenizaRey** [comment]
In the near future, we will be adding custom colours to important ingame messages, including legendary spawn announcements, that won't be able to be replicated by /chatcolor. This should mean you never miss a legendary message in the rainbow chat again! Thanks for the report.
