### ISSUE TITLE
Tab menu not showing correct dex ranks

### ISSUE THREAD

**Issue by Kaslan9** [ObliqueNetwork/Terra#1805]
**Describe the bug**
Tab menu does not show the correct dex ranks of people.

**To Reproduce**
N/A

**Expected behavior**
The tab menu should show current player dex rank.

**Screenshots**
https://i.imgur.com/stBVaW0.png Screenshot of tab menu showing I and others have the [Ultra] Rank
https://i.imgur.com/hXRrIXE.png   Screenshot of chat showing that I have the [Dream] rank

**Username:**
Kaslan

**Server name (all applicable):**
Titan
(Have not checked on other servers.

**Comment by HackuJacku** [comment]
This has been fixed, thank you for reporting it :)
