### ISSUE TITLE
when i have the orb for zapdos it says i need 100 more kayos that i kill another pokemon it says i need 101 kayo isnt it suppose to go down?

### ISSUE THREAD

**Issue by na3ht** [ObliqueNetwork/Terra#1806]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Username:**

**Server name (all applicable):**

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by Khrisstias** [comment]
Hello! Sorry for not getting to this sooner but there is now a ticket for it https://pixelmonmod.com/tracker.php?p=2&t=19186 and will be fixed in the future.
