### ISSUE TITLE
[Supernova Solrock] Z plane fighting on the model

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1808]
**Describe the bug**
There's some z plane fighting that occurs with the new Solrock/Lunatone models that really detracts from the look of it.

**To Reproduce**
1. Observe the z plane fighting in-game on a Supernova Solrock/Tidal Lunatone models.

**Expected behavior**
No z plane fighting for a crisp and clean look.

**Screenshots**
It's best seen in-game, but you can see a little from a screenshot.
![2022-08-28_23 47 05](https://user-images.githubusercontent.com/112078351/187140795-bab22020-0f3e-4728-b9aa-2cee1e7c9b8b.png)
![2022-08-29_00 47 58](https://user-images.githubusercontent.com/112078351/187152772-5f3f36bb-6c83-462d-a843-43543708dda6.png)

**Username:**
Dracten

**Server name (all applicable):**
Titan

**Comment by Malphir** [comment]
Updated to include Tidal Lunatone for the same issue.

**Comment by CenizaRey** [comment]
This was a issue with transparency overlapping with an opaque model. It has been fixed in Resource Pack V1.1.1. Thanks for the report!
