### ISSUE TITLE
[Non-OT Legend Dex] Mewtwo Dex w/o OT is possible

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1812]
**Describe the bug**
Mewtwo's dex entry can be acquired simply by possessing a Mewtwo, regardless of who the OT is.

**To Reproduce**
1. Find a player that doesn't have a Mewtwo dex entry
2. Trade or gift them a Mewtwo that has someone else's OT

**Expected behavior**
No dex entry for a legend, Mewtwo, that doesn't have a player's own OT.

**Username:**
Dracten

**Server name (all applicable):**
Titan

**Comment by Malphir** [comment]
Upon acquiring further info, thought to be related to the removal of a shiny palette and not necessarily a Mewtwo specific bug.

**Comment by Deathnight7976** [comment]
How did one remove the shiny palette from the mewtwo? Ive confirmed that simply getting traded a regular mewtwo does not result in its dex.

**Comment by StrideMate** [comment]
I am unsure how you can remove the shiny palette off a Pokemon, However Deathnight tested this with a normal Mewtwo and it seemed fine. I will say that for now, We will close this old ticket and if this ever comes up in the future please do report it! Closing!
