### ISSUE TITLE
/wt confirmation doesn't work

### ISSUE THREAD

**Issue by Blaius** [ObliqueNetwork/Terra#1814]
**Describe the bug**
Wondertrade confirmation doesn't work if numbers are switched

**To Reproduce**
1. /wt 1
2. when wondertrade confirmation shows, do /wt 2 or any other number
3. the /wt 2 or any other number pokemon will automatically be sent into wondertrade with no confirmation

**Expected behavior**
If the number is changed after first attempt to wondertrade, it should ask for another confirmation

**Server name (all applicable):**
All

**Comment by KittyKatzyn** [comment]
This issue was caused by the mod Wondertrade itself, and has been fixed by its Dev.  :)  Mod will be updated on all live servers today!
