### ISSUE TITLE
Cosmic Crate not openable

### ISSUE THREAD

**Issue by xWattzz** [ObliqueNetwork/Terra#1815]
Cosmic crate not being able to be opened or looked at. It says require admin even though I have the cosmic keys to do so
![cosmic](https://user-images.githubusercontent.com/112552426/187660435-85b5f71b-c38c-4be5-bb80-6a98195a655c.png)

**Comment by WisconsinWinters** [comment]
what server was this on and your ingame name?

**Comment by Malphir** [comment]
Was online at the time this was occurring.

**Username:**
xWattzz

**Server:**
Titan

**Comment by WisconsinWinters** [comment]
did you have the key at all in your inventory? I couldn't reproduce this on any server
