### ISSUE TITLE
No Boss Loot

### ISSUE THREAD

**Issue by KayzKenny69** [ObliqueNetwork/Terra#1816]
**Describe the bug**
Fought a Mega Salamence boss abt 100+ blocks in the air, once the battle started I fell to the ground, presumably putting the boss too far away from me to load

**To Reproduce**
Fight boss in the air
Fall

**Expected behavior**
To get sweet epic loot

**Screenshots**
N/A

**Username:**
KayzKenny

**Server name (all applicable):**
Titan

**Additional context**
I've teleported across the map mid-battle with wild Pokemon before with no issue, maybe this is loot specific since I still got xp. No loot GUI popped up either, the battle just ended once I killed it.

**Comment by HackuJacku** [comment]
This bug was previously fixed in a recent PixelmonMod update. Thank you for reporting it :)
