### ISSUE TITLE
[WonderTrade] No gender mon have extra N in gender

### ISSUE THREAD

**Issue by Vavalur** [ObliqueNetwork/Terra#1817]
**Describe the bug**
Mons with no gender have an extra N in none and white text color instead of yellow

**To Reproduce**
1. Use /wt list
2. find no gender mon
3. hover over no gender mon

**Expected behavior**
Gender: None

**Screenshots**
![image](https://user-images.githubusercontent.com/107285589/187748305-86e4bafb-6b16-47c7-a337-2fb91ba8b225.png)

**Server name (all applicable):**
Titan

**Comment by fatyg5** [comment]
Fixed on all servers for next restart.
