### ISSUE TITLE
Modifiers

### ISSUE THREAD

**Issue by Puccadawg21** [ObliqueNetwork/Terra#1821]
about 2-3 months ago there was a bug where getting modifiers from crates was bugged and they wouldn't give it to you. I posted about this problem in the thread they posted but my problem didn't get fixed I never got a refund. I then typed in support a about my problem again but nobody reach out to me. 

![Screenshot_20220904_020309](https://user-
images.githubusercontent.com/112797244/188301763-a4fd5136-5e6d-4200-a4f1-43bd2a850d13.jpg)

![Screenshot_20220904-020254_Discord](https://user-images.githubusercontent.com/112797244/188301783-5c766495-14fe-4efe-915b-efd9b03e7c9f.jpg)

^^^ here are the photos of me messaging the support channels

if anyone can help me my user is

user: Puccadawg21
server: Orion

**Comment by MissElyri** [comment]
This has been refunded to you. :) Closing
