### ISSUE TITLE
[Nebula] Crate Keys Disappearing

### ISSUE THREAD

**Issue by daske12** [ObliqueNetwork/Terra#1822]
**Describe the bug**
I bought 5 keys received them, went to open the chest and then they disappeared 
d

**To Reproduce**
Go to the crate ,

**Expected behavior**
To keep the keys and open the crates

Disc: kski#9661

**Username:**
daske_

**Server name (all applicable):**
daske_

**Additional context**
Had confirmation of purchase at 5:29 aest

**Comment by fatyg5** [comment]
Closing as many updates of Aquacrates as well as randomness of issue prevents easy testing. Will assumed fixed unless reopened.
