### ISSUE TITLE
crash and ghost keys

### ISSUE THREAD

**Issue by killercreechan** [ObliqueNetwork/Terra#1823]
**Describe the bug**
i had just got master rank on titan and i used 2 keys and then on the final key the server crashed and when we relogged my keys were in my inventory then as i went to use them they dissapeared i had 1 cosmetic 1 megastone and 1 astrial keys

i would like to have my keys back

killercreechan

Titan

**Logs:**
couldn't find them

**Additional context**

**Comment by MissElyri** [comment]
Refunded
