### ISSUE TITLE
[Feature] Dark workplace can only face to the north

### ISSUE THREAD

**Issue by dvos1998** [ObliqueNetwork/Terra#1824]
**Bug description**
When you place the dark workplace, (no mather from what side you place it) it will always face only north.

**To Reproduce**
1. Get a black workplace
2. Place the black workplace from any direction
3. It will now face north

**Expected behavior**
The expectation is that it can be placed from any direction and does not only face north

**Screenshots**
Facing north while placing
![image](https://user-images.githubusercontent.com/39247897/188318853-95b62701-1a95-45a6-93c4-ce50640e8360.png)

Facing east while placing
![image](https://user-images.githubusercontent.com/39247897/188318768-92812030-25db-4aa5-ab7b-c07fd169ab4c.png)

Facing south while placing
![image](https://user-images.githubusercontent.com/39247897/188318894-e457f118-abe0-48eb-b3f5-499941e60a14.png)

Facing west while placing
![image](https://user-images.githubusercontent.com/39247897/188318734-00eb67f8-effa-45b5-b9b6-0fc721e3f818.png)

**Username:**
DomiVos

**Server name:**
Titan

**Additionally:**
The light workplace also seems to have this problem

**Comment by Khrisstias** [comment]
Yeah there are a list of decor items that have this issue https://pixelmonmod.com/tracker.php?p=2&t=17575 as it was already reported to the mod i will close this. Thank you for the report!
