### ISSUE TITLE
[Pixelmon] Ultra Necrozma z move

### ISSUE THREAD

**Issue by MclovinHI** [ObliqueNetwork/Terra#1825]
When I try to get ultra necrozma it doesn't have the z move and instead has a mega evolve button. I have everything that I should have to get him it's just the process of "evolving" him doesn't work.
Atlas

**Comment by Khrisstias** [comment]
Hello! This is a known bug in the mod: https://pixelmonmod.com/tracker.php?p=2&t=18478 despite this being a dupe ticket it better describes your issue than the original ticket. Thank you very much for the report!
