### ISSUE TITLE
[Spec Modifiers] -5 Level Modifier does not work

### ISSUE THREAD

**Issue by davmaster10234** [ObliqueNetwork/Terra#1826]
**Describe the bug**
The lvl 5 De leveler seems to be not working when i tried to use it 

**To Reproduce**
1. I clicked it and no prompt popped up

**Expected behavior**
It should have opened a menu to select a mon that I was going to de level

**Screenshots**
![image](https://user-images.githubusercontent.com/45674274/188671309-36907154-f242-48b2-b1c2-3c6eac2ab4ad.png)
**Username:**
Davmaster_GN
**Server name (all applicable):**
Titan

**Comment by HackuJacku** [comment]
After looking into this, I am unable to reproduce this bug as per the image below:
![image](https://user-images.githubusercontent.com/18508413/190879251-d54f09e0-a0cd-46ac-880b-b4ceaebd23c2.png)
