### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1827]
**Describe the bug**
Vote crate currently bugged, Unable to click on it at all.

**To Reproduce**
1. Go to /warp crates.
2. Right/Left click on the vote crate.
3. Opens up a UI menu/Let's you open the crate with left click.

**Expected behavior**
To open the UI menu showing what you can get, And also letting you left click to instantly use your key on it.

**Image**
![2022-09-07_20 22 49](https://user-images.githubusercontent.com/78794976/188855634-7e78fbe3-779b-4252-831d-6da319c256cd.png)
![2022-09-07_20 22 48](https://user-images.githubusercontent.com/78794976/188855640-8ddb2ab0-673a-4f7d-9eb5-fb15897c9f4f.png)
**Username:**
Strideii
**Server name (all applicable):**
Orion

**Additional context**
I've tried all other crates they allow me to click/use them, It's only the vote crate.

**Comment by HackuJacku** [comment]
Fixed :)
