### ISSUE TITLE
Keys not received from 5x Astral key purchase.

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1828]
I just purchased 5x Astral keys and received none at all, I don't know if I did anything to cause it but I was just standing there waiting in the shiny mod UI.
Server: Orion
IGN: Strideii

![2022-09-08_14 09 50](https://user-images.githubusercontent.com/78794976/189032549-4ef51269-2a3f-4180-a2cc-5e752fe6f1f9.png)
![2022-09-08_14 09 53](https://user-images.githubusercontent.com/78794976/189032554-928fdd2d-a4a9-4f65-9e8c-435adf83bfee.png)

**Comment by MissElyri** [comment]
Ras refunded; Closing
