### ISSUE TITLE
Under the map at /spawn.

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1829]
I don't think it's intended but I fell from the /warp crates area of the map and I've landed on the floor and are able to move around the bottom of the map. 

![2022-09-08_14 18 24](https://user-images.githubusercontent.com/78794976/189033418-19fc90dd-a354-4929-96d0-aa3b526c4b12.png)
![2022-09-08_14 18 29](https://user-images.githubusercontent.com/78794976/189033421-580e08d6-1c52-49af-b8e1-1a02a6146afd.png)
![2022-09-08_14 21 37](https://user-images.githubusercontent.com/78794976/189033652-ec1eb163-8833-4190-ac1d-d71ab4d2f776.png)

**Comment by CenizaRey** [comment]
Nah you’re meant to land there if you fall, it’s not like those who wind up down there can do any harm. Intended feature!
