### ISSUE TITLE
[Feature] strike form bug

### ISSUE THREAD

**Issue by CarsonLee2001** [ObliqueNetwork/Terra#1830]
I caught a strike form Vulpix yesterday and evolved her to strike form Ninetales today, and tried to use a form modifier to see can she change to Alolan form, but then I decided not to change it and clicked cancel. After that my strike Ninetales become a normal Ninetales, so is it a bug or something? I don't have any screen capture, I only help her take a ingame photo before she evolved.
Server: Orion
IGN: Carson_Lee_
![image](https://user-images.githubusercontent.com/105753352/189156793-70151c13-8e12-4bda-b122-f034e24e58a6.png)
![image](https://user-images.githubusercontent.com/105753352/189156849-cb24d683-7c8e-43fe-a246-39ad19db3f4b.png)

**Comment by Malphir** [comment]
I had this exact same thing happen to me previously and can confirm this is an issue.

**Comment by Rasgnarok** [comment]
@CarsonLee2001 Can you ping in support (Discord) when you are next online so an admin can reset your form? I've forwarded the issue to Val, the developer.

**Comment by HackuJacku** [comment]
This bug will be fixed after the next reboot. Thank you for reporting it :)
