### ISSUE TITLE
Legendary boss drop air

### ISSUE THREAD

**Issue by Kryla** [ObliqueNetwork/Terra#1831]
**Describe the bug**
Yesterday, or 2 days ago, on sept 7th, i battled a legendary boss houndoom and got air as one of the drops, same thing happened a week ago with Liam__, he battled a legendary boss golbat.

**Username:**
Kryla

**Server name (all applicable):**
Titan

**Comment by Oisin-Hearne** [comment]
This was fixed in a previous pixelmon version
