### ISSUE TITLE
[Custom Legendary Requirements] Time mismatch on Magearna Spawn

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1832]
Arcording to the custom spawns on the wiki Magearna has been changed to a night time legendary spawn. In game /wiki does not reflect this change. While wiki is known to sometimes misbehave other altered pokemon spawn times are reflected properly on the /wiki, leading me to believe the issue resides elsewhere.

1. Check: https://github.com/NebulaMC-GG/Bugs-and-Issues/wiki/Custom-Spawn-Conditions
![SrKSPANNEW](https://user-images.githubusercontent.com/17133410/189306589-3e240705-9b08-41f8-a86d-ca81c9a34e65.png)

2. run the `/wiki Magearna time` in game
![mag](https://user-images.githubusercontent.com/17133410/189307337-86fa6af1-a722-4e71-8895-fd876b1876c6.png)

for comparison Rotom:
Default:
![chrome_rDa1RyoPEn](https://user-images.githubusercontent.com/17133410/189307864-bb760066-ab4d-4dfe-9e85-08c8f7a69185.png)
Change:
![chrome_6gveuCp6nH](https://user-images.githubusercontent.com/17133410/189307872-451fe154-f4ee-4d05-ba5d-4f072a33baab.png)
![rotom](https://user-images.githubusercontent.com/17133410/189308114-8f2d1414-0710-440e-8f82-4498bc633f6f.png)

Expected behavior: for /wiki to display the time as Night 
Server: All

**Comment by CenizaRey** [comment]
This ticket solved a wiki typo, thanks! Closing.
