### ISSUE TITLE
use of 2 balls when 1 is used

### ISSUE THREAD

**Issue by killercreechan** [ObliqueNetwork/Terra#1834]
**Describe the bug**
i just noticed in a fight i was using 2 level balls when i was throwing 1 

**To Reproduce**
unknown how it happened

**Expected behavior**
to see if it was just me or if its everyone

**Screenshots**
will link a video showing

**Username:**
killercreechan

**Server name (all applicable):**
Titan

https://user-images.githubusercontent.com/112803874/189475151-b198e108-ae2d-4c46-acd6-5381ece8b1b8.mp4

**Comment by killercreechan** [comment]
i went to a different battle afterwords and used one ball? i was fighting a beldum when it occurred

**Comment by CenizaRey** [comment]
This issue hasn't re-emerged, and I can't seem to reproduce it. Closing for now
