### ISSUE TITLE
[Pixelmon] Cloning Machine Visual Bug

### ISSUE THREAD

**Issue by Wolfman02** [ObliqueNetwork/Terra#1836]
**Describe the bug**
When a cloning machine is placed, all nearby chests suffer a visual bug.

**To Reproduce**
1. Place a cloning machine near chests.
2. The visual bug should be replicated with this single step

**Expected behavior**
The chests seem to be transparent on the top and reveal a black abys. They also overlap with one another when observed form an angle. 

**Screenshots**
![2022-09-11_23 00 53](https://user-images.githubusercontent.com/111099361/189567056-c0f02d50-88d5-41fa-81da-c44d85a1339e.png)

![2022-09-11_23 01 03](https://user-images.githubusercontent.com/111099361/189567096-f6d56c81-ffdf-4bb5-9838-8744cab37ffd.png)

**Username:**
Time_Laps
Atlas

**Comment by Wolfman02** [comment]
![2022-09-11_23 16 08](https://user-images.githubusercontent.com/111099361/189567523-e45c4712-c0e1-48ed-bf2a-80b0aee65df1.png)
Just tested a shulker shell and the results are similar. The chest seems to be translucent and allows the chests to overlap them. I was not able to see what it looked like form an open perspective.

**Comment by Khrisstias** [comment]
What a goofy bug. Thank you so much for the report! Will forward to the mod's tracker!

**Comment by Khrisstias** [comment]
https://pixelmonmod.com/tracker.php?p=2&t=19119
