### ISSUE TITLE
Mystery Error

### ISSUE THREAD

**Issue by innqmorato** [ObliqueNetwork/Terra#1837]
Just went to my platform in giant tree taiga hills, and the whole area is claimed by an admin, coords and area photo down there
![2022-09-13_09 28 51](https://user-images.githubusercontent.com/109287888/189844682-24363297-5713-423d-a9b5-2588346d0d71.png)

**Comment by Vavalur** [comment]
![image](https://user-images.githubusercontent.com/107285589/190208720-a9aee8cf-0083-4aff-9037-607be156dc29.png)
large area claimed by admin on Orion
-1344 78 -1881

**Comment by Khrisstias** [comment]
It appears to have been resolved. Feel free to make a new ticket if this issue arises again.
