### ISSUE TITLE
Desert Lava Super Rod Fishing doesn't yield items(and only 2/3 pokemon) [Feature] Bug explanation

### ISSUE THREAD

**Issue by RyanDHackett** [ObliqueNetwork/Terra#1838]
**Describe the bug**
After about 100 casts with a super rod(about 75% of the durability of a rod), fishing in the desert for omega shards, only Magcargo(all "!" were this) and Torkoal(all "!!" were this) were found. No items(ground gem, fire stone, smooth rock, fire stone shard should all be obtainable at relatively high rates) and no "!!!"s at all, meaning no omega shards. There is also supposed to be magmar in the pokemon pool..
I suspect that item fishing from lava is somehow disabled through config.

**To Reproduce**
1. Go to Lava in "Desert" biome
2. Fish 50+ times with a Super Rod
3. *Crys in slugs and tortoises*

**Expected behavior**
-Magcargo, torkoal and magmar available
-Gems, stones, and shards available
-Omega shards available

**Screenshots**
No buggy visuals. Just mechanical.

**Username:**
Cindermaji
**Server name (all applicable):**
Orion

**Logs:**
Some log lines from the fishing:
https://pastebin.com/N2cQddwp

**Additional context**
I may not have casted enough times to truly find a "!!!", but the "!" and "!!"s should be things other than pokemon.
Pixelmon fishing rods are also not supposed to lose durability, according to a mod who was online.

**Comment by CenizaRey** [comment]
Fixed, closing
