### ISSUE TITLE
Mystery Platform Error

### ISSUE THREAD

**Issue by namelessMirror** [ObliqueNetwork/Terra#1839]
**Describe the bug**
I'm suddenly receiving a "You don't have an admin's permission to build" error on a platform I recently built.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/113485987/190038179-5b1a435b-eaf6-464b-a706-a0c78589da69.PNG)

**Username:**
Abstracttheworld

**Server name (all applicable):**
Orion

**Logs:**
[debug.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9561827/debug.log)

**Comment by Khrisstias** [comment]
It appears to have been resolved. Feel free to make a new ticket if this issue arises again.
