### ISSUE TITLE
/givepixelsprite command not working correctly 

### ISSUE THREAD

**Issue by Crimlatheloli** [ObliqueNetwork/Terra#1840]
the /givepixelsprite command seems to work on Pokémon spec parameters; list here:https://pixelmonmod.com/wiki/Pokemon_spec but when using any parameters other than shiny or egg (oddly enough) the given photo doesn't give the correct form

**Comment by HackuJacku** [comment]
@Crimlatheloli which specs are you using please? I've tested this and it works perfectly fine with form and palettes.

**Comment by Crimlatheloli** [comment]
so for some reason despite them being listed as form indisces they are regarded as palettes instead of forms

**Comment by Crimlatheloli** [comment]
so it does work you just have to use palette:(etc) instead of form:(etc)

**Comment by HackuJacku** [comment]
Form indices are no longer a thing, they were removed in 1.16 (you need to use the name - e.g: galarian, alolan, etc). 

Palettes are a "texture" version such as Strike, Ashen, etc.

Forms are stat/model changes such as Galarian and Alolan.

**Comment by Crimlatheloli** [comment]
ahh ok might wanna put the how to do it in the rank description of it so people don't get confused
