### ISSUE TITLE
Cosmetic Modifier Kit issue

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#1841]
I got a Cosmetic Modifier Kit from a solar crate, but only gaves me 1 of the 3 items that should gave me. In the message appear that i should recieved 3 but in my inventory i only had one, so i don't know which happened with the other 2. 

The item that I recieved was a gender modifier, the form modifier got it from other solar key (that is confirmed in the same message).
My IGN is miguipkv and the server is Atlas, in case of a refund. 

![1](https://user-images.githubusercontent.com/108286828/190094288-831fc587-0197-4faa-9eb2-5a1777d8ac56.png)
![2](https://user-images.githubusercontent.com/108286828/190094303-7c1a50f1-1bc0-4d84-b94c-c42cea28b251.png)

**Comment by MissElyri** [comment]
Coming on now to refund.

**Comment by HackuJacku** [comment]
This bug will be fixed after the next reboot. Thank you for reporting it :)
