### ISSUE TITLE
Trainer battles not working properly in adventure map!

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1842]
**Describe the bug**
So, in the new adventure map, every trainer that is NOT a boss has a menu pop up and struggles to fight you.

**To Reproduce**
1. Go to a trainer
2. Throw pokeball
3. Confirm battle rules
4. Select team
5. They will not select team hence you cannot fight them.

**Expected behavior**
They should fight you! Of course!

**Screenshots**
I got you!

**Username:**
BUGJUUICER/BUG-JUICER#0940

**Server name (all applicable):**
Orion

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_
//
I don't think a log is applicable here sadly.
![image](https://user-images.githubusercontent.com/42111124/190271354-26eca4ce-5e26-4d61-8e3b-d97ec4ef5c0c.png)

![image](https://user-images.githubusercontent.com/42111124/190271392-bd31a932-6386-42e1-a3e7-183d824ab7d5.png)

![image](https://user-images.githubusercontent.com/42111124/190271430-772bbf09-db5e-4d9f-a659-e629a3eeb1f6.png)

**Comment by CenizaRey** [comment]
This doesn't appear to reproduce on Titan, at least requires more testing! Will look into this further.

**Comment by KittyKatzyn** [comment]
Confirmed - tried battling "Sailor Boss Diavolo" at -183, -270, 66 in Nyr in Titan and Orion.  

Other tickets include "Marlee" at -199, -124, "Ellen" at -219, -186, and "Austin" at  -157, -157.

1) Press R to throw pokemon at his.
2) Battle Rules GUI pops up, press "OK".
3) Select my 1 (only) Pokemon, Charizard. Press "Confirm".
4) Charizard comes out as if in battle, but I am stuck on "waiting for other player to select a team".
5) Server console produces error: https://gist.github.com/KittyKatzyn/351dbeab482e1662df0e9c4d70c01144
6) /gamemode creative and give myself an NPC Editor.
7) Looking at the pokemon of this trainer, they don't have any moves, and therefore cannot battle.

Issue needs to be migrated!

**Comment by KittyKatzyn** [comment]
Forwarded to Internal!  Will update here when fixed!

**Comment by CenizaRey** [comment]
Fixed! Thanks for the report! Closing
