### ISSUE TITLE
Shopkeep in mushroom-esque area not working

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1843]
**Describe the bug**
She just doesn't interact/talk back at all. You can right click all you want.

**To Reproduce**
1. Go to X 857 / Y 81 / Z 570
2. Talk to the shopkeep with pink hair
3. She does not shop or keep!

**Expected behavior**
Should open a menu with shopkeep-things. Sellables.

**Screenshots**
:D I got you!

**Username:**
BUGJUUICER/BUG-JUICER#0940

**Server name (all applicable):**
Orion
![image](https://user-images.githubusercontent.com/42111124/190272262-2b6f77c2-67ff-4972-b078-cbdd1a170f2e.png)
![image](https://user-images.githubusercontent.com/42111124/190272295-6adcb1fc-1e23-4e30-be74-a55f7c006332.png)

**Comment by Chunkkss** [comment]
Known issue, Being fixed as adventure map gets updated!

Thanks for the report
