### ISSUE TITLE
Gym Leader Pokemon Fainted Before Battle

### ISSUE THREAD

**Issue by chrisdurocher** [ObliqueNetwork/Terra#1845]
Atlas server
IGN: MrH0li0
Challenger: Azazels696

Accepted the players challenge, chose my 6 mons, hit confirm. This brings me to team preview where leads are chosen, and one of the mons (pincurchin) was already fainted.

![Screen Shot 2022-09-14 at 8 55 28 PM](https://user-images.githubusercontent.com/100480889/190289068-199c79f9-ff34-4afc-bfc2-79264803ba60.png)

**Comment by chrisdurocher** [comment]
just took a battle where all 6 gym leader mons were fainted and it basically froze the challenger and just put the 6 fainted mons in my party which is now locked as well.

**Comment by chrisdurocher** [comment]
![Screen Shot 2022-09-16 at 4 13 52 PM](https://user-images.githubusercontent.com/100480889/190726761-e827814e-2532-4159-8263-72569ec5fee1.png)

This is where i ended up after choosing my 6 mons, never took me to the screen where you pick your lead.

**Comment by chrisdurocher** [comment]
I am team locked on atlas and orion from this happening on both servers.

**Comment by chrisdurocher** [comment]
After logging off for a few hours, came back and team was still locked. Someone then challenged the gym and the battle worked just fine and my team went back to normal after the battle.

**Comment by chrisdurocher** [comment]
The pattern that I am seeing is as follows:

After being offline for several hours, I get on the server and the first battle I take has no fainted pokemon. However any battle afterwards seems to carry over the fainted pokemon from the previous battle.

Also, I've had instances where the pokemon doesnt faint, but just sending it out to battle could result in it being fainted in the next gym challenge.

**Comment by Tac3403** [comment]
Adding to this: I had 1 mon faint in my last defending gym battle. Then, when I challenged the gym, my OWN pokemon in slot 1 was fainted!

**Comment by chrisdurocher** [comment]
Had a pokemon put to sleep in battle and i switched it out so it never woke up.

Accepted another challenge right after and the same mon was still asleep.

so it seems the problem could be that the effects from the last battle arent being reset and that could be the issue.

**Comment by HackuJacku** [comment]
This has now been fixed, thank you for reporting it :)
