### ISSUE TITLE
burning jealousy is not able to be added on to pokemon using the move tutor 

### ISSUE THREAD

**Issue by redjeff1** [ObliqueNetwork/Terra#1846]
**Describe the bug**
The move is not working for the two pokemon I tested from the agni move tutor

**Screenshots**
![image](https://user-images.githubusercontent.com/48700761/190292029-f21a4af2-5403-42d6-a114-daf445c86703.png)
![image](https://user-images.githubusercontent.com/48700761/190292073-2b0a7d40-3331-4045-8834-8f879ab02f3c.png)

**Username:REDJEFF**

**Server name (all applicable):atlas**

**Comment by CenizaRey** [comment]
This is a bug with Pixelmon, and should hopefully be fixed in the coming update. Thanks for the report!
