### ISSUE TITLE
move tutors not letting mons learn moves despite having proper payment on hand

### ISSUE THREAD

**Issue by Crimlatheloli** [ObliqueNetwork/Terra#1847]
when going to multiple diffrent move tutors they despite my having 10 heartscales wouldent let me learn a move that cost like 8 or 5 heart scales

**Comment by Khrisstias** [comment]
This also happens on Orion

**Comment by chrisdurocher** [comment]
yup was just about to make a ticket for this

**Comment by CenizaRey** [comment]
Sadly, through testing on SP, I've discovered this is an issue with tutors in the mod itself. They will only teach the moves they randomly spawn with, and not any moves that are added to their listing. Unfortunately we can do nothing but wait for them to be fixed.

**Comment by Khrisstias** [comment]
https://pixelmonmod.com/tracker.php?p=2&t=19017 This was reported and forwarded to the devs. Ty for the report!!
