### ISSUE TITLE
pwarp being able to be set in vanha

### ISSUE THREAD

**Issue by Crimlatheloli** [ObliqueNetwork/Terra#1848]
pwarps being able to be set is somthing very bad as someone could just set up a pwarp to a legend quest start or a checkpoint if they have proper money

**Comment by CenizaRey** [comment]
Considering legend quest starting locations will be listed in the wiki, and that there are no "checkpoints" as such other than linear point-to-point objectives that there's no use teleporting to, I don't particularly view this as an issue. Thanks for the report!
