### ISSUE TITLE
Da magik trees (Some missing tree blocks on the adventure map.)

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1850]
Hi, So I've been on a mission around the map and I've come across some magical trees, There some blocks missing I assume maybe from the transfer to live servers or something, It got lost idk. But here or some pictures and the coords are on the journey map on the right side. :D
![2022-09-15_15 55 42](https://user-images.githubusercontent.com/78794976/190327225-45ad204f-9232-4720-affc-ac3c8723ff17.png)
![2022-09-15_15 58 23](https://user-images.githubusercontent.com/78794976/190327228-467a86a0-8185-416b-97eb-06ae8e382cf0.png)

**Comment by Khrisstias** [comment]
It appears to have been resolved. Feel free to make a new ticket if this issue arises again.
