### ISSUE TITLE
[Fishing] Loot from fished Pokémon not dropping

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1851]
**Describe the bug**
Was fishing and getting loot drops normally from killing mons and then suddenly they stopped dropping altogether. Last thing that dropped was some slime balls from a Shellos, and I didn't receive them. I could still get loot drops from non-fished mons while this was occurring. Relogging did not fix this issue. As a note, many of the fished mons killed I know to have 100% drop rate on various items, so it wasn't just a string of bad luck. A server restart did resolve the issue.

**To Reproduce**
I honestly have no idea how it occurred in the first place and thus no idea how to replicate it.

**Expected behavior**
I expected loot drops to continue as they should.

**Username:**
Dracten

**Server name (all applicable):**
Titan

**Comment by Malphir** [comment]
Upon further investigation, it seems this occurs inside claims that are flagged to prevent mons from spawning. I had forgotten I had flagged it while building. The issue does remain however, that while you can fish mons in a flagged space, they will not drop loot. Mons that enter the flagged claim from outside still drop loot normally.

**Comment by StrideMate** [comment]
Hi! This is a old ticket and it is a hard one to replicate without knowing a exact cause to how it happened, I've tested this in the corresponding server it was reported, The claim was flagged with Pokemon spawning off and I fished inside the claim with 3 Pokemon, Each 3 of those Pokemon dropped their respective loot! If this ever occurs in the future, Please do reopen or make a new ticket! Closing!
