### ISSUE TITLE
[Ranks] Origin one-time reward and kit issue.

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#1853]
Hi, I reach Origin today, and I knew some issues could happen with the one-time reward, due to similar  experiences with the previous ones. I cleaned my inventory to know everything that i get from that wasn't mixed with other stuff, and some are missed and others are wrong. I will share SS as a prove, due to being a one-time reward from the most difficult dexrank, i don't wanna miss anything, as well as help to fix this and don't repeat the same issue for the next Origin players.

This is the ss before to claim the reward. My inventory was clean:
![2022-09-15_15 29 21](https://user-images.githubusercontent.com/108286828/190418756-0f01f4de-a5d3-47df-b320-46a30cde83bc.png)
After claim the reward:

![2022-09-15_15 29 28](https://user-images.githubusercontent.com/108286828/190419472-2a26f257-e46e-4a87-9af9-4a6d5d703288.png)

Now I will share the msg with the items received: 
![2022-09-15_15 30 40](https://user-images.githubusercontent.com/108286828/190419776-56227c69-4db4-4ef6-8e72-8c720c541b2b.png)
![2022-09-15_15 30 43](https://user-images.githubusercontent.com/108286828/190419806-ff1d5fa1-f658-48a3-84f9-9c571b38fda1.png)
![2022-09-15_15 30 45](https://user-images.githubusercontent.com/108286828/190419838-25f31335-3c1f-49c1-a982-55c38617dd16.png)

And this is my inventory after check everything was okey:

![2022-09-15_15 48 04](https://user-images.githubusercontent.com/108286828/190420890-a3faefe3-fa37-4cb8-ab92-10a10f721b3c.png)

This is an actual pic with the rewards that should give me this rank:
![image](https://user-images.githubusercontent.com/108286828/190421492-799ba8fb-ed9f-49c1-b459-e461f7b42ff1.png)

For don't make this toooo long (due to the pics), i will continue in a comment with the items that i received, and which are missing or wrong.

**Comment by EzelBerbier** [comment]
After checking all the items received and the ones that appear in the Oirigin one-time reward and checking the chat msg, this are only the one missed: 

- 512 claim blocks 
- 1 Hidden Abiloty Modifier 

My username is: miguipkv
Sever: Atlas

**Comment by EzelBerbier** [comment]
I found this new issue now, Origin kit appear blocked for some reason, so u can't claim it.

![image](https://user-images.githubusercontent.com/108286828/190431944-6c2f9e29-76c9-4018-a8da-5c5a59c3601e.png)

**Comment by KittyKatzyn** [comment]
Sorry for the delay - The one-time rewards should be functioning by now, and I just linked origin kits to the Origin rank so they should be good to go, as well!

Sorry for the delay! Thanks for your patience!

**Comment by KittyKatzyn** [comment]
Refunds given for both the modifier and the claim blocks, btw!
