### ISSUE TITLE
DynaMax isnt working on titan

### ISSUE THREAD

**Issue by DlNGY6** [ObliqueNetwork/Terra#1854]
DynaMax isnt working on titan 

so when you click the dynamax button it doesnt work

when you click the button your pokemon is supposed to get bigger and stronger

dingy6

Titan idk if the others also arent working

i dont think logs are needed for this

it still lets you click on the dynamax button but it just doesnt work

**Comment by KittyKatzyn** [comment]
Sorry for the delayed response, but this is a pixelmon bug which has been reported and forwarded to Internal, and should be fixed with the next update :)
