### ISSUE TITLE
Solar crate did not reward properly with ItemCache system

### ISSUE THREAD

**Issue by toofuriouz** [ObliqueNetwork/Terra#1855]
**Describe the bug**
coesmetic moldifiers only rewarded a growth moldifiers might have a issue with ItemCache system

**To Reproduce**
1. Go to crates
2. Open any  crate rewarding comestic moldifiers
3. See error

**Expected behavior**
should reward a growth, ball and size moldifiers

**Screenshots**
![image](https://user-images.githubusercontent.com/85075804/190526392-e2ab8a3f-4d44-405b-b6d8-83230c575606.png)
![image](https://user-images.githubusercontent.com/85075804/190526400-9eedff2f-5316-4e86-88e7-6beb9d37d5ea.png)
![image](https://user-images.githubusercontent.com/85075804/190526409-9be7d1ad-2cdf-4503-bb6d-0403bb1933c6.png)

**Username:**
**Server name (all applicable):**
IGN: TooFuriouZ
Server: Orion

**Additional context**
Would like refunds

**Comment by MissElyri** [comment]
Refunded!
