### ISSUE TITLE
Nature Mod Issue

### ISSUE THREAD

**Issue by CaptainTCovenant** [ObliqueNetwork/Terra#1856]
When using a Nature Mod, instead of listing the natures it lists UI ELEMENT.

**To Reproduce**
Right click nature mod
Select a pokemon
Hover over options

**Expected behavior**
All options will be grayed out and named UI ELEMENT

SSpamzzz - the Nature Mod owner

Known being on Orion, unsure on the others

![Screenshot_290](https://user-images.githubusercontent.com/92965754/190586675-b5cf16e8-fb90-4329-a7e2-d3e4398c9ae2.png)
![Screenshot_291](https://user-images.githubusercontent.com/92965754/190586677-c8a007b6-aedc-4f2e-b1ba-b477c9bb3c36.png)
.

**Comment by HackuJacku** [comment]
This issue as has now been fixed from the next reboot, thank you for reporting :)
