### ISSUE TITLE
One-time rewars from master rank 

### ISSUE THREAD

**Issue by Azazels696** [ObliqueNetwork/Terra#1857]
Hi 🙂 I reach my master rank and claim my one-time rewards but i dont recive the ability modifier but all the rest is okay 🙂 can have some help here please ? ^^ azazels696/atlas Tysm in advance :3

**Comment by MissElyri** [comment]
I have refunded and placed the ability modifier in your inventory! Sorry for the inconvenience!

**Comment by Azazels696** [comment]
Thank you so much and dont worry ^^ lil mistake happen sometime not ur
false :)
Le ven. 16 sept. 2022 à 9:13 a.m., Elyri ***@***.***> a
écrit :
