### ISSUE TITLE
Adventure Map Interactive Blocks not working

### ISSUE THREAD

**Issue by ThirstyMichael** [ObliqueNetwork/Terra#1858]
Players are unable to activate the use effect of certain blocks in the adventure map that you would be able to expect them to; While the players can use Stair sitting, Half Slab sitting, PCs, Healers, Enchanting Tables, and Enderchests, players are unable to interact with seemingly everything else. Including blocks such as normal chests I believe players used to be able to interact with before. The immediate issue is that this makes crafting in the adventure map impossible for 3x3 crafting. (also Anvils do not work despite Enchanting Tables functioning properly)
(comedically making crafting a pay2play feature in the tier 3 store rank in the adventure realm layer specifically) 
A similar error to this occurs when trying to interact with every *use* block.
![2022-09-16_09 09 52](https://user-images.githubusercontent.com/70663305/190648109-0c4a4264-231c-460f-88e8-4ab75ee14f34.png)

**Comment by KittyKatzyn** [comment]
Still an issue!  Needs to be migrated to Internal tracker!

**Comment by KittyKatzyn** [comment]
Forwarded to the Internal tracker! Will update here when fixed!

**Comment by CenizaRey** [comment]
Fixed, thanks for the report! Closing
