### ISSUE TITLE
Im not getting items from gym wins (titan)

### ISSUE THREAD

**Issue by Th3Boog** [ObliqueNetwork/Terra#1859]
I am not getting my gym badges for the first and second gym on titan and i havent gotten my ability modifier from the first gym either my in game name is Th3_Boog and the gym leaders i fought was nyuan for the first gym and dingy for the second

**Comment by fatyg5** [comment]
#1861 is a similar report, merging until I get confirmation issue is continued or fixed and will go from there.

**Comment by StrideMate** [comment]
In a effort to reduce old threads, I will be closing this for the time being! Please reopen the same ticket, Or make another ticket if this issue arises in the future! Thank you!
