### ISSUE TITLE
[Vanha Map Issues] An extensive compilation of issues with the Vanha map

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1860]
The following document is an ongoing list of issues found with the Vanha map. @Malphir on discord to request editor access if you have things to add or want to be assigned to a zone to find issues. You can also list any issues in the comments below, but please remember to provide coordinates for any issues.

If you are a builder fixing issues, please highlight any fixed issues instead of deleting them from the list.

https://docs.google.com/document/d/1UKXV6i_dRn3jTjEFJh2A-9-AEzsR5oraNv7hyUwzZNM/edit?usp=sharing

**Comment by Ooomalooo** [comment]
Thank you for compiling this list of issues regarding the Vanha map, it is greatly appreciated. The build team will be forwarded this list.

**Comment by Malphir** [comment]
Of course, just doing our part. As stated, additions will be ongoing for it as we have time.

**Comment by StrideMate** [comment]
These have all been fixed, I was apart of the team fixing them! :D I am going to close this as Malphir has retired sadly :( and we have solved all (Well I think some NPC ones not yet) the issues on the doc, We also have a copy saved in our build channel so if anyone is happy to update that on map updates you may DM me to get a link to the doc, Other than that closing!
