### ISSUE TITLE
pokemon sprite broken

### ISSUE THREAD

**Issue by killercreechan** [ObliqueNetwork/Terra#1863]
**Describe the bug**
i was looking in wondertrade and the sprite for cinderace is a broken texture

**Expected behavior**
for someone to look into it and fix it 

**Screenshots**
i will add a screenshot to show

**Username:**
killercreechan

**Server name (all applicable):**
titan but all may have it

![2022-09-17_19 46 06](https://user-images.githubusercontent.com/112803874/190879931-85e8433b-bd4f-4fae-ad34-d2206af6ae52.png)

**Comment by HackuJacku** [comment]
@killercreechan - when you hover over it, what Pokémon does it show as please?

**Comment by killercreechan** [comment]
![2022-09-17_19 55 46](https://user-images.githubusercontent.com/112803874/190879999-9912aa01-fc03-4c8c-89f8-75a32e49a7b8.png)

yes it does heres a screenshot showing

**Comment by KittyKatzyn** [comment]
This is a Pixelmon issue - there simply isn't a sprite for the online form, so I will forward this to their trackers.  :)  Thanks!

[public tracker link](https://pixelmonmod.com/tracker.php?p=2&t=19318)
