### ISSUE TITLE
Player Shops Signs Don't Return money for Buying yourself

### ISSUE THREAD

**Issue by Deathwolf14** [ObliqueNetwork/Terra#1864]
Ign: Deathwolf14_ (Nicked as Aurora)
Server: Orion (Believe this is across all, not tested)
I was Setting up my pwarp and market and have been testing the signs to make sure that it charges the right amount and give the right amount to the player and noticed that I wasn't receiving the money when I bought from myself. (Tested if It gave money if another player bought the item, it worked. 
I have no way to Confirm this, However I was roughly around at 647000~ Before doing this, I was dropped down to 547,252 afterwards (Tested afterwards with a player who bought a Mball for 12k, **So True Total is 559.252**)

**Comment by Deathnight7976** [comment]
This has either been fixed or was just a visual bug in which a ticket already exists for, Closing.
