### ISSUE TITLE
Invasion Boss Pokemon appearing outside of Adventure Map.

### ISSUE THREAD

**Issue by Cencor126** [ObliqueNetwork/Terra#1865]
During an invasion in Tesla, I heard a lightning strike outside my home on the Wilderness map. Turns out Boss Pokémon spawned outside.

![2022-09-17_21 21 59](https://user-images.githubusercontent.com/35191988/190885966-2cfbc9b3-5c5c-49a6-b75f-f18f2ff0676c.png)

**Comment by CenizaRey** [comment]
This was due to me force-starting an invasion and using the 'global' variable instead of 'normal' by accident

lo siento
