### ISSUE TITLE
[Emojis] :shrug: ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1867]
The ingame :shrug: emoji is missing an arm.

1. log on to the server
2. type `:shrug:`
3. look at output
4. missing an arm:
![Amputation](https://user-images.githubusercontent.com/17133410/190919832-91413db4-8a2d-4810-b894-8736a7355063.png)

Expectation: 
¯\\_(ツ)_/¯

All servers

**Comment by CenizaRey** [comment]
Should be fixed for next restart. Thanks for the report!
