### ISSUE TITLE
[Hub] Servers don't display player count

### ISSUE THREAD

**Issue by Vavalur** [ObliqueNetwork/Terra#1868]
**Describe the bug**
In the hub the holograms don't display the amount of players on the servers, just a "?"

**To Reproduce**
1. Login to the hub
2. Look at server holograms

**Expected behavior**
An actual player count to be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/107285589/190921545-aa06a458-f732-4cf1-928a-d664d6bcf6a6.png)

**Server name (all applicable):**
Hub

**Comment by Rasgnarok** [comment]
Now working, thank you!
