### ISSUE TITLE
Tyrogue always evolving into Hitmontop

### ISSUE THREAD

**Issue by Menno165** [ObliqueNetwork/Terra#1870]
**Describe the bug**
Tyrogue always evolving into Hitmontop, even if the attack or defense is higher than the other.
This has been tested on the beta server where it failed.
it was working fine on a singeplayer world.

**To Reproduce**
Get a lvl 19+ tyrogue that has either higher attack or higher defense and evolve it.

**Expected behavior**
When attack > defense it should evolve into Hitmonlee
When attack < defense it should evolve into Hitmonchan

**Username:**
Player who reported this:  Abstracttheworld

**Server name (all applicable):**
Reported on Orion.
Most likely the case on all since it happened on the beta as well.

**Comment by CenizaRey** [comment]
Fixed as of next restart, thanks for the report! Closing
