### ISSUE TITLE
[Feature] 100% removed from zygarde form mod

### ISSUE THREAD

**Issue by Jarokami** [ObliqueNetwork/Terra#1871]
Not sure if its a bug or a new feature but in 9.0.8 you could use the form mod to get Zygarde to complete form, however in the newest version 9.0.10 he is back to 50% and no option to change form. to my request of an explanation I was told to just buy 2 and get him legitimately but that's not possible since ultra space is turned off. after a few back and forth questions I was told to just wait to which I am fine with however  a form mod is now lost so if its a bug I thought id raise attention to it but if not, it is what it is.

(suggestion) keep in form mods till legitimately available through means of Zygarde cube, when I suggested this in server was met with someone telling me to just wait and that it would break the economy so it wont return. However I believe if there is no way to legitimately obtain him there is no economy for him, so until he is obtainable I believe it would be a good thing to keep in form mods

**Comment by HackuJacku** [comment]
Zygarde complete is a temporary form. Being able to use Form Modifiers to obtain this form was a bug and them remaining permanent was a bug. You can still obtain Zygarde-Complete form. I be removed them from Modifiers.

@MissElyri will handle refunding any Modifiers where required :)

**Comment by MissElyri** [comment]
These have already been refunded; Didn't realize it was also in tracker. Closing.
