### ISSUE TITLE
[Hunts/Bingo] Parsing error

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1872]
/Hunts and /bingo
show the pokemon species as "pixelmon.species" instead of "Species"

1. use the command `/hunts`
![hunts](https://user-images.githubusercontent.com/17133410/191347294-ff538060-de5d-4cf6-9de2-e695101c7aa8.png)
2. scroll over pixelsprite
3. read the species line
5. repeat for /bingo
![bingo](https://user-images.githubusercontent.com/17133410/191347345-c500c22b-9d55-4c47-ab99-1768aca5c746.png)

All servers

**Comment by Deathnight7976** [comment]
This issue also extends to the chat alert for hatching pokemon:
![hatch](https://user-images.githubusercontent.com/17133410/191382082-0c8ac7fe-7a58-4ebd-82d7-d6f12a2c0121.png)

**Comment by HackuJacku** [comment]
This is a PixelmonMod bug, @Khrisstias will forward it onto them :)

**Comment by Khrisstias** [comment]
It's a stinky MP only bug. Has been forwarded to the devs :)
