### ISSUE TITLE
Gym Rematches grant rewards again

### ISSUE THREAD

**Issue by Valjean42** [ObliqueNetwork/Terra#1873]
Gym Rematches are possible and grant the same rewards as first time beating the gym on wins
**To Reproduce**
1. Beat a gym
2. Challenge it again
3. Beat it again
4. You'll receive the rewards once for each time the gym is beat

**Expected behavior**
Either - No rematches are available OR Rematches grant lowered/no rewards.

**Username:**
Vallie42
**Server name (all applicable):**
All 3

**Additional context**
Asked in staff chat if current behavior was intended, dough told me it wasn't so I'm ticketin'
https://discord.com/channels/151095626916954113/161980232629354496/1021871704538103898

**Comment by Deathnight7976** [comment]
Gym rematches for gyms one has already completed are no longer an intended feature, nor possible anymore. Thus issue resolves itself closing.
