### ISSUE TITLE
titans store has a air for sale

### ISSUE THREAD

**Issue by killercreechan** [ObliqueNetwork/Terra#1875]
**Describe the bug**
i was looking in the market on titan and was looking at the furniture shop and saw under all the couches there was air for sale for 200

**Expected behavior**
to be removed from shop
 
**Username:**
killercreechan

**Server name (all applicable):**
titan maybe all servers

![2022-09-21_01 28 21](https://user-images.githubusercontent.com/112803874/191422276-e817a369-4ec4-4929-80da-f1fb47ca6998.png)

**Comment by KittyKatzyn** [comment]
This seems to no longer be an issue!  Thanks for the report!
