### ISSUE TITLE
[/kits|Curry] Dream and Master kit 

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1878]
Dream kit is meant to give 1x Wobbuffet Class curry however it gives 1x Koffing instead.
The same can be said about Master kit dropping 1x Charizard Class curry. 

1. redeem master kit from `/kits`
![MasterCurry](https://user-images.githubusercontent.com/17133410/191872470-e979b485-04d6-4f49-aa41-9a3059ad07f0.png)
3. With tooltips enabled hover over the curry dispensed
4. repeat with dream kit from `/kits`
![Dreamcurry](https://user-images.githubusercontent.com/17133410/191872492-528a779a-cc07-4fe7-9f30-96d1c66cfea6.png)
6. See error

Master kit to disperse Charizard Class and Dream Wobbuffet Class curries. 

Kit reference:
![MasterKit](https://user-images.githubusercontent.com/17133410/191872620-98c13d98-0e66-4f5e-9f3a-fa88d60896b8.png)

![DreamKit](https://user-images.githubusercontent.com/17133410/191872636-82090515-8e17-441f-8ef2-aa0f8812c350.png)

Deathnight7976

Orion, possibly all.

Also there appears Wobbuffet is misspelt in the `dexrewards` gui

**Comment by KittyKatzyn** [comment]
Hi there, DeathNight! o/

I can confirm that the curries given are not the right class!  I have looked into it, and with the help of one of the Pixelmon devs, figured out the correct item ID to give the right classes in the kits!  I have just changed both dream and master kits in Atlas, Orion, and Titan.

(I will also fix that typo real quick, thank you!)

Thanks for the report!
Katzyn
