### ISSUE TITLE
[Pokedrops] Nebula Custom Pokedrops

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1879]
According to the latest changelog referencing Cufant it is meant to drop silver ingots.

1. kill many cufants
2. get no silver
3. sadness

Cufants to drop silver ingots

![DiscordDrop](https://user-images.githubusercontent.com/17133410/191873697-0becb629-f571-4f25-8973-340afb07155f.png)
(I murdered 25+ all with similar drops ranging from 1-2 beefs.)
![Cufant](https://user-images.githubusercontent.com/17133410/191873798-14a36ce0-271b-4514-9e61-93b569585969.png)

Deathnight7976

Orion, likely all.

**Comment by CenizaRey** [comment]
When Pixelmon updated the way it handles pokedrops in a recent update, it reset all pokedrop files back to their defaults. This gave me the opportunity to review pokedrops. The latest changelog mentioning Cufant was prior to this change by the mod. On review, I decided Cufant shouldn’t be dropping silver. This is intended. Thanks for the report!
