### ISSUE TITLE
[Bingo] Goodof appearing on the bingo card (not sure if in hunts too).

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#1880]
I think this issue doesn't have too much explanation. I've been checking if appear on Hunts too, but didn't see it so i can't confirm if the same issue is there too, but i mention it just in case is true, to fix it as well.

![image](https://user-images.githubusercontent.com/108286828/191980263-c1e5c960-b462-4086-ae5e-a4ae982c300e.png)

**Comment by KittyKatzyn** [comment]
I have blacklisted His Majesty Godoof! 

_I hope he doesn't smite me for this..._

Thank you for your report!
