### ISSUE TITLE
Healer brakes lantern in highrift.

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1883]
So I had someone dm me in-game telling me that they broke the lantern in highrift, I tp'd and fixed it, However when people use the healer at the highrift pokecenter it activates the trapdoor causing the lantern on top to break. Maybe we change it to slabs of some sort?
![2022-09-24_18 34 35](https://user-images.githubusercontent.com/78794976/192089355-f6e4672f-2442-4974-b75b-5442d5615ee5.png)
![2022-09-24_18 34 37](https://user-images.githubusercontent.com/78794976/192089359-44f9d930-1e2b-4bdb-b277-cb1bb5977265.png)

**Comment by CenizaRey** [comment]
Fixed, closing
