### ISSUE TITLE
[Command] /filldex command

### ISSUE THREAD

**Issue by KittyKatzyn** [ObliqueNetwork/Terra#1884]
**Describe the bug**
/filldex is not currently an available command.

**To Reproduce**
1. "/filldex Katzyn 30" is not a valid command atm.

**Expected behavior**
According to the Pixelmon wiki, the command should set the designated player's dex to the percentage specified (30% in the case of the above example).

**Screenshots**
![image](https://user-images.githubusercontent.com/103725578/192092907-8492d470-9dd8-4525-be97-a195a1aa6010.png)

**Username:**
Katzyn
**Server name (all applicable):**
Orion
**Logs:**

**Additional context**
On the Pixelmon Support server, /filldex works to an extent - it fills the dex 100% regardless of the percentage specified (has already been reported internally).

**Comment by Rasgnarok** [comment]
Fixed, it needed an additional perm ission on arclight (minecraft.command.filldex).
