### ISSUE TITLE
Unable to mount your Pokemon in the Adventure map

### ISSUE THREAD

**Issue by CaptainTCovenant** [ObliqueNetwork/Terra#1885]
You are unable to ride your Pokemon on Titan and Orion servers while in the Adventure map. 
![Screenshot_305](https://user-images.githubusercontent.com/92965754/192096064-01249b65-d4e3-41f0-8988-32344b829d29.png)

While you are able to do so in Atlas.
![Screenshot_306](https://user-images.githubusercontent.com/92965754/192096106-bbf9f61f-2aa0-47e3-9f7e-c29cbc7726b1.png)

**Comment by Rasgnarok** [comment]
This should now be fixed, thanks!

**Comment by KittyKatzyn** [comment]
Hey darling, this doesn't seem to be fixed in Titan or Orion, and I can't wrap my head around it to fix it :) <3

**Comment by CenizaRey** [comment]
Fixed, closing
