### ISSUE TITLE
[Cosmetics] Bike Riding FPS tank

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1886]
Equipping cosmetics during or after using a bicycle causes FPS to tank to 2-6 fps. After interacting with the bicycle one will have to relaunch in order to use cosmetics and not experience severe fps lag.

1. Ride a bicycle, (Mach Bike)
2. Equip a Cosmetic during or after riding bike
3. Experience lag
4. Run away from bicycle
5. Equip Cosmetic 
6. Experience lag again. 
7. See Error

To be able to ride my bicycle with my psyduck hat in peace.

(My fps in this area is usually 150+)
![Drip](https://user-images.githubusercontent.com/17133410/192114158-c152814f-b9bf-449e-b5b3-e89d1dcfce3c.png)

Deathnight7976

Orion, likely all.

Also might worth noting that bags on bicycles disappear completely even after getting off while equipped (my hunch is they get offset into outer space by the bike, this issue still occurs with no backpack equipped however.) 

Secondly the position of hats do not cover the head while on a bicycle.

**Comment by Rasgnarok** [comment]
We should probably test this with head gear in SP as well, to confirm whether or not it's Pixelmon-side.

**Comment by KittyKatzyn** [comment]
This seems to no longer be an issue!  Closing!
