### ISSUE TITLE
[Invasions] Raid Den reset at 00:00

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1887]
An invasion occurred at `/warp Ione` and half way through the invasion the in game time hit 00:00 and the raid den swapped to a Shelder instead of a Xurkitree/

1. Trigger an Invasion near 00:00
2. Observe as the clock hits 00:00 the raid den deactivates/swaps raid mon.
3. see error

Raid den to be immune to the 00:00 Raid den deactivation/swap

Pre 00:00
![Xurk](https://user-images.githubusercontent.com/17133410/192122236-84bdfb76-0d94-4dee-a672-b698ec82ed22.jpg)

![2022-09-24_18 24 07](https://user-images.githubusercontent.com/17133410/192122179-9f21552b-1fd8-4c45-89a8-ec9aaf32a337.png)

Deathnight7976

Orion, Likely affects all.

It was most definetly a Xurkitree previously

**Comment by Khrisstias** [comment]
Going to close as raid dens are not part of invasions at the moment
