### ISSUE TITLE
Wishing pieces don't spawn 5 star raids

### ISSUE THREAD

**Issue by Blaius** [ObliqueNetwork/Terra#1892]
**Describe the bug**
Wishing pieces don't spawn 5 star raids

**To Reproduce**
1. Throw pieces in a den

**Expected behavior**
To get a 5 star raid before 100 pieces. Only ever been able to see 4 star raids and below.

**Username:**
Blaius

**Server name (all applicable):**
All

**Comment by KittyKatzyn** [comment]
Hi there, Blaius!  Sorry for the inconvenience!

I can confirm that using a Wishing Piece, you cannot currently summon a 5* raid.  

I will conduct further testing to see if this is strictly a Pixelmon bug, or a NebulaMC bug, and forward accordingly!

Thank you for your report!
Katzyn

**Comment by KittyKatzyn** [comment]
Forwarded to the Pixelmon Bug Tracker!
