### ISSUE TITLE
[Lang] Godoof's name broken lang in battle and with some commands.

### ISSUE THREAD

**Issue by KittyKatzyn** [ObliqueNetwork/Terra#1893]
**Describe the bug**
1) In battle, Godoof's name is "pixelmon.godoof".
2) When /pokegift'd, same as above.

**To Reproduce**
1. Throw Godoof into battle.
OR
1. /pokegift (player) (party slot #) 

**Expected behavior**
Should just say His name, say His name~

**Screenshots**
![image](https://user-images.githubusercontent.com/103725578/192231401-0622fe5c-abad-495f-8c14-5a33f5193957.png)

**Username:**
Katzyn
**Server name (all applicable):**
All.
**Logs:**
No logs.  

**Additional context**
Resource pack is up to date, lang file seems correct to my newbie eye.

**Comment by Malphir** [comment]
Added note, parsing issue on the typing in /wiki, as well as it's signature move. Also lists its only ability as both A1 and HA (Shedinja shares this particular issue).
![2022-09-27_13 03 29](https://user-images.githubusercontent.com/112078351/192625440-9c2f822e-6ab3-4cf5-83d7-68610251e637.png)
![2022-09-27_13 09 53](https://user-images.githubusercontent.com/112078351/192625718-73bd81a8-07d7-45f1-8b71-d4eeb4b137fa.png)

**Comment by Malphir** [comment]
Also only lists Nasty Plot and Swords Dance for TM/TR/HM despite it being able to learn Hyper Beam and Giga Impact as well, according to the Nebula wiki.
![2022-09-27_21 13 07](https://user-images.githubusercontent.com/112078351/192686074-ddf4b847-18d5-4343-9ef8-89409e020251.png)

**Comment by KittyKatzyn** [comment]
The above /wiki issues have been fixed since this ticket was made, but the attack and pokemon name lang issue persists; however it is a Pixelmon issue, which has been forwarded to their Internal tracker; as such, I will close this one!
