### ISSUE TITLE
[Cosmetics] Cosmetics rendering with incorrect or bugged models

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1894]
**Describe the Bug:**
There are a few cosmetics that have the wrong models for what they are, and also a few that have bugged models. Those affected will be named alongside their screenshots. For those I do not personally own, I will simply show a screen shot of them in the crate and describe the issue.

**Screenshots:**
Zapdos, Moltres and Articuno backpacks have a random missing texture black and purple section rendering on them.
![2022-09-26_14 15 46](https://user-images.githubusercontent.com/112078351/192384043-e14d32f5-e59c-4260-97da-369d6ae20086.png)
![2022-09-26_14 15 58](https://user-images.githubusercontent.com/112078351/192384049-0ccf8207-922e-4038-92ba-334a028b3271.png)
![2022-09-26_14 12 26](https://user-images.githubusercontent.com/112078351/192384056-6a69f657-e4ac-47b2-b014-e7e36698228f.png)

The Mew Hat has some z-plane fighting occurring with its textures.
![2022-09-26_14 13 13](https://user-images.githubusercontent.com/112078351/192384204-b2b327d9-bf87-43e0-9359-5bd5abfd684c.png)

The Green Wizard and Purple Earmuffs hats are rendering with the Black Trainer Cap instead of their respective models.
![2022-09-26_14 16 20](https://user-images.githubusercontent.com/112078351/192384417-096d2db0-96e0-4c71-9c9e-90a10b081a34.png)
![2022-09-26_14 16 33](https://user-images.githubusercontent.com/112078351/192384428-3faecab6-95b3-42a4-b324-b6fcc46e0398.png)
![2022-09-26_14 16 23](https://user-images.githubusercontent.com/112078351/192384434-2a3af7ff-feda-4d74-bebf-18a27e54ea71.png)

The Beanie and Red Beanie have identical models. Either one should be removed, or retextured.
![2022-09-26_14 17 21](https://user-images.githubusercontent.com/112078351/192384631-c2d6c62b-7df6-4216-a71f-a408e70bad37.png)
![2022-09-26_14 17 19](https://user-images.githubusercontent.com/112078351/192384639-695a36a8-1157-464f-bf76-e6967874d0bf.png)
![2022-09-26_14 26 36](https://user-images.githubusercontent.com/112078351/192384646-a57f635f-b9de-4466-9f0d-cbfc96dfb2f2.png)

**Username:**
Dracten

**Server name (all applicable):**
Titan (Check other servers)

**Comment by Chunkkss** [comment]
Cosmetics have all been updated and fixed.

Thanks for the report!
