### ISSUE TITLE
[AFK Messages] Incorrectly timed "You're no longer AFK!" message readout in chat

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1895]
**Describe the bug**
The AFK overlay clears when you move your mouse around to change your character's view. However, the "You're no longer AFK!" message doesn't read out in chat until your character actually moves around.

EDIT: The AFK chat message also appears prior to the AFK overlay appearing.

**To Reproduce**
1. Go AFK (notice that the AFK chat message appears earlier than the overlay)
2. Move your mouse and see overlay clear
3. Walk around and see chat message appear

**Expected behavior**
I expected both things to occur from the same action

**Screenshots**
As a side note, and I realized these were placeholder messages, there are a couple grammatical and punctuation issues in the chat AFK messagess.

![2022-09-26_14 48 05](https://user-images.githubusercontent.com/112078351/192388330-012eeb50-da9e-4681-9bf4-f75a723d7dcd.png)
You're now marked as AFK. Get fucked, no legendary spawns for you bitch! (I know this one will get changed but it makes me chuckle)

![2022-09-26_14 47 59](https://user-images.githubusercontent.com/112078351/192388311-72cd76ca-d2b4-4381-9300-01dde9c0271b.png)
You're no longer marked as AFK. You can now get legendary spawns!

**Comment by dvos1998** [comment]
They changed the message when you get AFK, but that has a typo ("no Legendary Pokemon will spawn on you. on you.") one "on you." to much
![image](https://user-images.githubusercontent.com/39247897/192533395-4cb9d0c2-5848-4fb4-a70b-37e41b5c739f.png)

**Comment by CenizaRey** [comment]
This is fixed as of next restart. Thanks for the report!
