### ISSUE TITLE
form mod transferring HA incorrectly

### ISSUE THREAD

**Issue by redjeff1** [ObliqueNetwork/Terra#1896]
**Describe the bug**
When using a form mod on a pokemon with a HA then the Hidden ability will stay the same instead of being changed to the hidden ability of the new form pokemon.

**Screenshots**
![image](https://user-images.githubusercontent.com/48700761/192619536-13b4b9da-9bf7-4e51-8913-7d0b20033ae1.png)
![image](https://user-images.githubusercontent.com/48700761/192619555-49af6c17-b551-4416-83d3-ff7c0b30a670.png)

**Username:REDJEFF**

**Server name (all applicable):Atlas**

**Comment by Deathnight7976** [comment]
Upon testing on Orion abilities now switch to legal abilities however the Hidden Ability becomes a non-hidden ability. Unsure whether that is intentional or not. Leaving open for now.

**Comment by KittyKatzyn** [comment]
This issue has been fixed in the most recent version of ModifierTokens, which is on Beta.  Will need to be pushed to live servers. Closing!
