### ISSUE TITLE
Playershops visual bug!

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1897]
Upon working if my chest shop was working, I had put my Arc chalice on sale for 1 million. I tried purchasing to see if the sign works and It's given me 1 million, I relogged the money went back to normal, I tried it again and the money went down 1 million, I relogged again and it was back to normal.

**Before:**
![2022-09-28_12 46 09](https://user-images.githubusercontent.com/78794976/192676505-608bec6a-1b37-4686-a7d8-26e95ba10860.png)

**After:**
![2022-09-28_12 44 43](https://user-images.githubusercontent.com/78794976/192676538-97af779b-b0f6-43eb-a364-630b4e5f957c.png)
![2022-09-28_12 42 08](https://user-images.githubusercontent.com/78794976/192676543-fa53d720-22f4-4ff6-a49f-fa012f7b5d7e.png)

That is what happened when I tried purchasing from myself, It fixes when you relog.
Thanks you!

**Comment by Deathnight7976** [comment]
This visual bug no longer seems to occur assuming fixed, Closing.
