### ISSUE TITLE
Over 50+ Luxrays at the luxray tree bug.

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1898]
So XxNipleTxX was going to the luxray tree to train his pokemans, When he tp'd there, There was atleast over 50 Luxrays spawned in already and it was absolute mayhem, I tp'd my FPS dropped to about 20fps in a second :( I've got some photos of the countless luxrays!

![2022-09-28_19 25 19](https://user-images.githubusercontent.com/78794976/192743502-563e24b7-6dd4-4820-aec5-82338fefde14.png)
![2022-09-28_19 28 33](https://user-images.githubusercontent.com/78794976/192743510-4a3782ab-1b73-4889-bdb8-172f86e040d3.png)
![2022-09-28_19 28 36](https://user-images.githubusercontent.com/78794976/192743515-bf0f6ca6-3e8c-4dbc-8d5d-acfbefd0ce8b.png)
![2022-09-28_19 28 39](https://user-images.githubusercontent.com/78794976/192743519-746d4c9f-c883-4eb0-b4c9-611f2a17d34c.png)
![2022-09-28_19 28 41](https://user-images.githubusercontent.com/78794976/192743523-034d8585-12c7-44cc-97c2-103be05892ab.png)

**Comment by KittyKatzyn** [comment]
After visiting each server's Luxray Tree, I am guessing this was either a one-off bug or something fixed it since this report was made.  Closing!
