### ISSUE TITLE
[GTS] Legendary Listings

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#1899]
**Describe the bug**
Legendaries listed in GTS have their Breedability listed as "TRUE"

**To Reproduce**
1. execute /gts
2. hover over a legendary

**Expected behavior**
For breedability listed as "FALSE"

**Screenshots**
![2022-09-28_15 58 39](https://user-images.githubusercontent.com/37944220/192887972-46ed296e-47f0-4599-aa0d-382b84a28c74.png)

**Username:** DraconiacLatias

**Server name (all applicable):** Orion

**Comment by KittyKatzyn** [comment]
Still an issue - unsure if GTS issue or Nebula issue; will find out when GTS has been updated (planned soon!).  Will leave open for now.

**Comment by KittyKatzyn** [comment]
Forwarded to Internal! Will update here when fixed!

**Comment by WisconsinWinters** [comment]
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/4a63d6d8-3522-4364-b77f-de774d69152f)
fixed.

**Comment by WisconsinWinters** [comment]
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/b3bbc416-cd17-45fd-8d83-40aa848ae84b)


fixed, the placeholdder for breedability is a seperate issue, but the wording should be clear enough.
