### ISSUE TITLE
Crashing Raid Starts

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1901]
Crashing during raids starting. Unsure what causes it. I have mods and texture packs that I'm unsure affect it but they might? Was told to report it anyhow. Let me know!

**To Reproduce**
--I have no clue.

**Username:** BUG-JUICER#0940 / BUGJUUICER

**Server name (all applicable):**
Orion

**Logs:**

[crash-2022-09-28_18.33.32-client.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9670307/crash-2022-09-28_18.33.32-client.txt)
[crash-2022-09-28_18.55.08-client.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9670308/crash-2022-09-28_18.55.08-client.txt)
[crash-2022-09-28_19.11.55-client.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9670309/crash-2022-09-28_19.11.55-client.txt)

**Extra:**
So I'm unsure what it is. For context I have multiple mods alongside Pixelmon that might be the issue? but I crash all the time so I'm unsure. I have multiple crash logs from other things, such as engaging in a fight with another mon, and other things.

**Comment by KittyKatzyn** [comment]
Possibly caused by the sound mod - waiting to see if Bug crashes any more :)

**Comment by KittyKatzyn** [comment]
Update - hasn't had any crashes since removing mod (SoundFilters-0.14_for_1.16.2.jar).

I'll test it with plain ole Pixelmon and pass it to their internal if I can reproduce the issue; otherwise we'll look into it here to see if it's conflicting with something on Neb's end :)

**Comment by Rasgnarok** [comment]
Very appreciated, thanks for the check-out, @KittyKatzyn !
