### ISSUE TITLE
Insufficient Permission Issue when trying to change /pwarp name.

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1902]
**Describe the bug**
Trying to change /pwarp name gives you a insufficient permission message.

**To Reproduce**
1. Type /pwarp
2. Go to manage my warps.
3. Right click to edit, Click "Rename warp"
4. Rename warp. However it says "Insufficient Permission"

**Expected behavior**
To be able to type Nagamichi Town Mall and the /pwarp name will change to said name.

**Screenshots**
![2022-09-30_11 13 28](https://user-images.githubusercontent.com/78794976/193168981-3caeb63d-15d5-4ab5-9c82-f394aff27e76.png)

**Username:**
Strideii
**Server name (all applicable):**
Orion

**Comment by KittyKatzyn** [comment]
@StrideMate and @Deathnight7976 do you still have this issue?  I tested on Orion and was able to make a pwarp and change the name with no issues.

**Comment by KittyKatzyn** [comment]
Seems to be fixed!  Closing!
