### ISSUE TITLE
[GTS] Friendship listed twice in mons stats.

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1903]
In GTS the friendship of a mon is listed twice. 

1. Use `/gts`
2. View Trades 
3. Scroll over any listed mon

![zVXWsEIjL1](https://user-images.githubusercontent.com/17133410/193173282-c2579af6-00ed-462b-9d91-c2b14966ab5c.png)

Friendship to only be listed once.

Deathnight7976

Orion, likely all.

**Comment by KittyKatzyn** [comment]
Can confirm!  Fixing :D Ty <3

**Comment by KittyKatzyn** [comment]
Issue fixed and tested on beta; pushing to servers.
