### ISSUE TITLE
Gym badges dissapear when i leave the server and come back

### ISSUE THREAD

**Issue by redjeff1** [ObliqueNetwork/Terra#1906]
**Describe the bug**
whenever I beat a gym and advance whenever I leave the server my previous gym badges do not stay.

**To Reproduce**
1. Beat gym
2. get gym badge
3. leave the server and come back
4. they are gone

**Expected behavior**
I only have the ground gym badge but I don't have the electric one nor the dark and ghost/fighting

**Screenshots**
![image](https://user-images.githubusercontent.com/48700761/193432833-ed5f814f-517b-45e5-8878-7fe176c5abcf.png)
![image](https://user-images.githubusercontent.com/48700761/193432840-488faa75-70e8-4c8e-932b-3243ca94ccad.png)

**Username:REDJEFF**

**Server name (all applicable):ATLAS**

**Additional context**
I've beat the first 4 gyms but every time I quit most/all disappear and have to be given back to me.

**Comment by Rasgnarok** [comment]
Is this issue still occuring? We've moved our database handling to attempt a fix for this issue in the last few days. Please let us know if the issue persists.

**Comment by redjeff1** [comment]
This glitch is still happening i have been given multiple gym badges but the only ones that I have is the electric and gound and have been given many other badges the dissapear

**Comment by KittyKatzyn** [comment]
Still an issue!  Needs to be migrated!
