### ISSUE TITLE
Swimming Mons still a LITTLE too fast (or certain ones?)

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1908]
**Description**
Milotic breaks the sound barrier.

**To Reproduce**
I have no clue but this creature was fighting for its live in a speed race.

**Expected behavior**
A decently slow, calmer, and more predictable swim cycle.

**Screenshots**
I'll do you one better! A video!
https://www.youtube.com/watch?v=XEwDOdFx9YM

**Username:**
BUG-JUICER#0940 / BUGJUUICER

**Server name (all applicable):**
Orion

**Comment by KittyKatzyn** [comment]
Assigning this to myself - will work on this tomorrow :)

**Comment by KittyKatzyn** [comment]
Having looked into this - you're right, milotic do ZOOM!

However, I also see that Pixelmon itself has decreased the swim speed for Milotic in the next update, so I'll go ahead and just let it fix itself!

Thanks for the report though - please do let us know if there's any others!
