### ISSUE TITLE
Shiny Ginormous pokemon in invasions?

### ISSUE THREAD

**Issue by bms716** [ObliqueNetwork/Terra#1910]
So to summarize this, in 2 different invasions, I found a wild shiny ginormous pokemon that each had 4x31 IVs. The first was a litwick and the 2nd is a mareep which is in the image below. Is this normal?
![image](https://user-images.githubusercontent.com/115069262/194011356-45f76c66-8e57-41ff-ac24-0d2f8553cdb4.png)

**Comment by KittyKatzyn** [comment]
Yep, this is normal :)  They're not breedable, and they're pretty rare, but they are intended!  Grats on your cute sheep <3
