### ISSUE TITLE
[Bug] World Border in Vanha missing.

### ISSUE THREAD

**Issue by Menno165** [ObliqueNetwork/Terra#1911]
**Describe the bug**
In Vanha for all 3 servers there is not a border around the edge where I checked, this causes to kill people who are in survival mode and went beyond.

**To Reproduce**
Steps to reproduce the behaviour:
1 Join any of the servers.
2 Go to the edge of the map (/tppos -1990 65 -1159 for quick way there)
3 Go beyond the -2000 (so towards -2010)
4 Die.

**Expected behavior**
I would expect a border blocking players from passing trough it.

**Username:**
Menno516 (Atred#1078)

**Server name (all applicable):**
All.

**Comment by WisconsinWinters** [comment]
fixed for next reboot.
