### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by MatureMicrobe4** [ObliqueNetwork/Terra#1912]
Idk if it’s a bug but I catched a shiny Aron and bronzer and there were lvl 23 27 I put them away in my pc and I took them out later then they turned into a lvl 93 and 76

![image](https://user-images.githubusercontent.com/115126215/194197976-f479df02-825f-4931-aec5-2195abd66b64.jpg)

**Comment by MatureMicrobe4** [comment]
Nvm it was a mistake it spawned at bedrock so it was a higher lvl I didn’t know sorry

**Comment by Malphir** [comment]
The lower your y-level the higher the level of the pokemon that spawn. (Discussed this particular issue and cleared up the misunderstanding with the player in-game, closing issue).
