### ISSUE TITLE
[GTS] Pokemon remain sent out when placed in gts

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1914]
The pokemon model doesnt despawn when the pokemon is listed in the `/gts`

1. Send pokemon out
2. list pokemon on `/gts`
![gts](https://user-images.githubusercontent.com/17133410/194351028-74b17e0b-a80b-461d-8b03-d1f3fd59cb86.png)
3. See error

When pokemon is listed on `/gts` for pokemon to vanish

Orion, likely all

**Comment by KittyKatzyn** [comment]
Can confirm!  Will see if I need to forward this on to Mister Daniel himself, or if we can fix it!

**Comment by Deathnight7976** [comment]
Issue appears to be resolved, when enter `/gts` all pokemon return to there balls at this time.
