### ISSUE TITLE
Some crates non-interactable

### ISSUE THREAD

**Issue by RyanDHackett** [ObliqueNetwork/Terra#1915]
**Describe the bug**
Solar crate cannot be interacted with

**To Reproduce**
Left or right click solar crate

**Expected behavior**
Crate opens gui

**Username:**
Cindermaji

**Server name (all applicable):**
Orion

**Additional context**
I talked to a mod. I think the plugin just needs a restart.

**Comment by Rasgnarok** [comment]
This should be fixed now, thanks!
