### ISSUE TITLE
[Feature] Bug explanatiGon

### ISSUE THREAD

**Issue by zTsuno** [ObliqueNetwork/Terra#1916]
Tesla Gym rewards say You should receive 18k, while I received 180k.
I do not have a screenshot for proof, only my balance. as you should know I am a broke boi.
![image](https://user-images.githubusercontent.com/106882836/194670944-300d716d-ae8b-416b-b024-2171afe31bbe.png)

**Comment by KittyKatzyn** [comment]
This has been fixed for all servers! <3
