### ISSUE TITLE
[Item] Pixelmon items & Tooltip

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1917]
When using [Item] and holding an item in hand it inputs that item into chat. If that item is from pixelmon it displays as [Air]. Secondly, when hovering over the inputted item in chat its meant to display any enchants, tooltips etc of the item, it does not. 

1. Hold pixelmon item in hand
2. Type `[item]` in chat
![air](https://user-images.githubusercontent.com/17133410/194685790-36e93d4f-3d87-4cf3-9360-fc2e28441596.png)
3. See error
4. Repeat with enchanted pickaxe or other item with tooltip
5. Hover over item
![notooltipdisplayed](https://user-images.githubusercontent.com/17133410/194685802-90d9143b-b677-478a-9bc6-6b70586b6f9d.png)
6. See error

For both Pixelmon items to be recognized and for hovering over the item in chat to display its respective tooltip. 

Orion, likely all.

In both attached images as it is not apparent I am hovering my cursor over the item in chat. Nothing is displayed.

**Comment by Deathnight7976** [comment]
Still displays pixelmon items as `[Air]` and fails to display tooltips when hovered over in chat.

**Comment by KittyKatzyn** [comment]
Forwarded to Internal!  Will update here when fixed!

**Comment by WisconsinWinters** [comment]
not usingi tem placeholder anymore, closing
