### ISSUE TITLE
[Berry Leaves] Eff 5 Hoes

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1918]
Eff 5 hoes instantly break vanilla tree leaves upon mining, this is not the case for pixelmon berry leaves.

1. Get an eff 5 Netherite Hoe
2. Locate a vanilla tree
3. Mine trees leaves
4. Compare againts berry leaves
5. See error

Instant leave harvesting via Eff 5 Hoes

Orion, likely all

**Comment by Khrisstias** [comment]
This has been reported to pixelmon https://pixelmonmod.com/tracker.php?mode=reply&p=2&t=19328 seems it only breaks at the speed mining it with your fist does. Thank you for the report!
