### ISSUE TITLE
Alolan blank TM not imprinting at 25 uses.

### ISSUE THREAD

**Issue by CaptainTCovenant** [ObliqueNetwork/Terra#1920]
When imprinting a move on Alolan blank tm, it requires more than the 25 needed for Galarian blank tm. 
Galarian blank imprints at 25 uses of a given move.
Server: Orion, unsure of others.

![Screenshot_324](https://user-images.githubusercontent.com/92965754/194735108-2a428bdd-0729-42cd-9f71-c20e6a8be529.png)

**Comment by Deathnight7976** [comment]
Issue still exists.

**Comment by WisconsinWinters** [comment]
this has been forwarded to internal, still need information as it comes in on what players are doing.
