### ISSUE TITLE
[Visual bug] Jolteon hat looks like eevee hat

### ISSUE THREAD

**Issue by dvos1998** [ObliqueNetwork/Terra#1921]
The jolteon hat looks like an eevee hat.

![image](https://user-images.githubusercontent.com/39247897/194777872-706dc51e-7da9-4ffb-be55-e470641738d6.png)
![image](https://user-images.githubusercontent.com/39247897/194777895-5937274a-3f24-4ed8-8591-8320f5fcfea5.png)

**Comment by KittyKatzyn** [comment]
I have fixed this - you should see a Jolteon hat after the next server restart :)
