### ISSUE TITLE
[Paletted Trade Evos] Recipient softlocks during trade-evo'ing a palette'd mon.

### ISSUE THREAD

**Issue by KittyKatzyn** [ObliqueNetwork/Terra#1922]
**Describe the bug**
Recipient softlocks during trade-evo'ing a palette'd mon.

I tested on other servers and in SP with /tradesim, and could not reproduce this issue, so I think it is Nebula-specific.

**To Reproduce**
1. /pokegive Onix p:crystal.  Give it a metal coat to hold.
2. Grab a friend.
3. Place the Onix in the trade machine and trade it to your friend.
4. It was a trap! Your friend is now stuck in limbo as his new Onix bugs him out.
5. The same happens for other trade evo mons with different palettes, such as alter porygon(s).
6. Trade evos work find for normal, unpaletted pokemon such as Kadabra.

**Expected behavior**
Crystal Onix should evolve cleanly into Crystal Steelix.

**Screenshots**

**Username:**
Katzyn

**Server name (all applicable):**
Orion, but I suspect all?

**Logs:**
Client Latest: Nothing of interest.
Client Debug: https://gist.github.com/KittyKatzyn/558c78d1fbb406ce18a562ef0d2f5431
Server Latest: https://gist.github.com/KittyKatzyn/9239dd4fa9910b9003cb02fab329bb75
Server Debug: https://gist.github.com/KittyKatzyn/efb8754f389d4f727849bc85b52c9192

**Additional context**

**Comment by Deathnight7976** [comment]
This bug no longer occurs as of latest update, Closing.
