### ISSUE TITLE
[Daycare] Missing boxes and Pokes.

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1923]
I only have 2/5 boxes unlocked in my daycare, the other boxes had pokemon in them and im unable to access those boxes as they are greyed out. Unknown if those pokemon still exist. 

Unknown

For all 5 of my boxes and ten pokes to be accessible 

![breeding](https://user-images.githubusercontent.com/17133410/194888684-4f60e82b-13ae-4940-b154-41bfa79420e5.png)

Deathnight7976

Orion

**Comment by Deathnight7976** [comment]
Upon further investigation it appears all master ranks across all 3 servers only have access to 2/5 Daycare boxes,

1. Get master rank
2. Open Daycare
3. See error

**Comment by Rasgnarok** [comment]
Fixed
