### ISSUE TITLE
battle sprites for new mega pokemon broken

### ISSUE THREAD

**Issue by killercreechan** [ObliqueNetwork/Terra#1924]
**Describe the bug**
i was testing the new mega evolutions and when i looked at the sprite in battle it was misingno

**To Reproduce**
mega evolve any pokemon to see the issue 

**Expected behavior**
to test and fix the sprites (no rush)

**Username:**
killercreechan

**Server name (all applicable):**
titan

![2022-10-10_16 13 13](https://user-images.githubusercontent.com/112803874/194945882-82b7228d-100d-4d5e-aaaf-82aa367ce8d9.png)

**Comment by CenizaRey** [comment]
I cannot reproduce this bug, closing until it re-emerges.
