### ISSUE TITLE
[/poketracker] Both Shiny and Legendary Bosses are tracked as if shiny/legend had spawned

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1925]
Both Shiny and Legendary Bosses are tracked as if shiny/legend had spawned

1. Spawn a Shiny Boss pokemon
2. use `/poketracker`
3. see error
4. Repeat steps 1 & 2 but with a Legendary poke boss

Ultimate Articuno boss:
![Shiny](https://user-images.githubusercontent.com/17133410/195141958-4d71e698-61d6-443a-a8b3-816a5fcbf102.png)
![leg](https://user-images.githubusercontent.com/17133410/195141977-636c26c5-6d54-428c-8da1-428960b7d21c.png)

For bosses not to be tracked as if they were naturally spawning shinies/legendaries.

Orion, Likely all

**Comment by Rasgnarok** [comment]
Fixed!
