### ISSUE TITLE
[Hunts] Oddish can be Selected for a Hunt Despite being a Spawner Pokemon

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#1926]
**Describe the bug**
Oddish can be chosen for a hunt despite having a spawner at /warp nyr

**To Reproduce**
1. Go to /warp Nyr
2. See that Oddish come from spawners

**Expected behavior**
Oddish never being selected for a hunt

**Screenshots**
![2022-10-11_17 37 14](https://user-images.githubusercontent.com/37944220/195211945-1b2e913c-c554-440f-b0dd-81613acc6f25.png)

**Username:** DraconiacLatias

**Server name (all applicable):** Orion, likely all

**Comment by Khrisstias** [comment]
Add Ponyta to the list.

**Comment by Deathnight7976** [comment]
Ledian too. 
![ledianHunt](https://user-images.githubusercontent.com/17133410/195650300-62ea4492-acb4-45d1-9295-68b0a0784f2f.png)

**Comment by Deathnight7976** [comment]
Nuzleaf:
![nuzhunt](https://user-images.githubusercontent.com/17133410/195696029-db65fdb3-4228-415d-b66f-6f3c0015b2e1.png)

**Comment by Deathnight7976** [comment]
Flaffy:
![FlaffHunt](https://user-images.githubusercontent.com/17133410/195711536-a1012b62-d837-4be6-8028-2ecc40105351.png)

**Comment by KittyKatzyn** [comment]
I will go through the spawner list and blacklist the mons today (pending any other issues cropping up).

**Comment by Khrisstias** [comment]
Sigilyph too

**Comment by Rasgnarok** [comment]
Fixed!
