### ISSUE TITLE
AFK Legend Problem

### ISSUE THREAD

**Issue by killercreechan** [ObliqueNetwork/Terra#1927]
**Describe the bug**
When i went afk long enough to have the legends stop spawning on me a pokemon moved me and made me no longer AFK.

**To Reproduce**

1. Stay still till you are afk
2. a wild pokemon move you

**Expected behavior**
For someone to look into it and see if it can be fixed or altered

**Username:**
Killercreechan

**Server name (all applicable):**
Titan probably all servers

**Comment by CenizaRey** [comment]
Did some testing, and confirmed that the legendary AFK detector goes by head movement, i.e. you have to look around for it to count you as non-afk. You likely looked at the pokemon as it pushed you, causing it to appear as though it took you out of AFK status. Thanks for the report! Closing
