### ISSUE TITLE
[Wondertrade] Poke Level Inconsistency 

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1928]
When using `/wt slot` the required level is >10, however, when using `/wt` and selecting a pokemon via the GUI the required level is  ≥10.

1. Get a level 10 pokemon
2. Attempt to `/wt slot` the mon
![chewtle](https://user-images.githubusercontent.com/17133410/195594436-b2cfe74b-f77d-4851-8b62-eeb4a9a3b052.png)
3. fail
4. Attempt to `/wt` and navigate the trade through the gui
![wt](https://user-images.githubusercontent.com/17133410/195594474-923d935f-ea21-4b41-83a5-05b528660b17.png)
![wt10](https://user-images.githubusercontent.com/17133410/195594513-0f6a05fd-ceb5-4c4f-9846-441fa32acab3.png)
5. Succeed, see error.

For the requirements both to be ≥10 ( my preference) or both to be >10. 

Orion, Likely all.

**Comment by Rasgnarok** [comment]
Fixed, thanks!

**Comment by Khrisstias** [comment]
This seemed to have re-broken

**Comment by Deathnight7976** [comment]
![broken](https://user-images.githubusercontent.com/17133410/201198097-a0e97c19-a229-47e4-bd48-a76f598b1d33.png)

**Comment by Deathnight7976** [comment]
GUI requires `x >= 10` meanwhile command requires `x > 10`

**Comment by WisconsinWinters** [comment]
fixed.
