### ISSUE TITLE
Ability coming soon?

### ISSUE THREAD

**Issue by bms716** [ObliqueNetwork/Terra#1929]
Essentially, this rotom I found doesn't have levitate? Not sure if it just isn't showing or what the deal is. I was told this is possibly a bug that other ghosts with 1 ability suffer with.
![image](https://user-images.githubusercontent.com/115069262/195658699-d062a2ba-4102-4ef6-8e7c-82c769e82d7d.png)

**Comment by Malphir** [comment]
This is a known bug that occurs when the game tries to assign an HA to a pokemon that doesn't have an HA. This issue has already been forwarded to the pixelmon team. Thank you for your report.

**Comment by KittyKatzyn** [comment]
Actually, I was just going to close this and leave it at that, but would you like us to change it to have a proper ability?  You won't be able to battle with it, as it is.

**Comment by KittyKatzyn** [comment]
Closing, as it's been a week with no response :)
