### ISSUE TITLE
[Bingo] Awarded "HA" Pokemon that can never have HA

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#1930]
**Describe the bug**
Yesterday when I completed bingo I was awarded a shiny unbreedable HA Pokémon, but it was a Honedge a Pokémon that does not have a HA. (i don't want a refund, just wanna make this issue known)

**Expected behavior**
To be given a pokemon with an actual HA

**Username:** DraconiacLatias

**Server name (all applicable):** Orion, could be an issue on all

**Comment by KittyKatzyn** [comment]
It's the same Pixelmon bug we keep talking about :)  

Also, you won't be able to battle with it (so don't sell it) - you sure you don't want a refund?

**Comment by Khrisstias** [comment]
lemme see if it really is bugged, as it still showed with "no guard"

**Comment by KittyKatzyn** [comment]
Oh, I see, if it was just given with the normal ability, that's good at least.  I can see if we can blacklist single-ability mons from being given as that reward.

**Comment by Khrisstias** [comment]
Yep! Can still fight with it!

**Comment by Khrisstias** [comment]
https://bulbapedia.bulbagarden.net/wiki/Category:Pok%C3%A9mon_without_Hidden_Abilities here's a list of all pokemon with no Hidden Ability that can be blacklisted

**Comment by KittyKatzyn** [comment]
I can't actually blacklist them, unfortunately, but I am wondering if once Pixelmon fixes the bug mentioned before, if this issue will be fixed as well, as it shouldn't be giving an "HA" pokemon if HA doesn't exist in that pokemon.

**Comment by Khrisstias** [comment]
we'll need to wait and see then

**Comment by KittyKatzyn** [comment]
You sure you don't want a refund?  :3

**Comment by Khrisstias** [comment]
I like my red sword pal! Will close this for now but if the HA fix doesn't work I will reopen
