### ISSUE TITLE
Certain Gym warps not functioning as intended

### ISSUE THREAD

**Issue by DaKingOfTheDinos** [ObliqueNetwork/Terra#1931]
**Describe the bug**
Certain gyms when they warp the leader and challenger, tp them to the coordinates of the gym in the overworld instead of the Vanha world
**To Reproduce**
1. Participate in gym challenges (I have seen it affected with both kuan-ti and Highrift gyms.)
**Expected behavior**
The player and challenger to be warped inside of the gym.

**Username:** Chis_sticks

**Server name (all applicable):**
All servers

**Comment by Rasgnarok** [comment]
Closing, fixed. Thank you!
