### ISSUE TITLE
[/poketracker] Shiny Tracker Still Displays Shiny Boss Portraits

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1935]
**Describe the bug**
Shiny bosses no longer display in the shiny tracker list, however their portrait still displays. The screenshot below depicts a shiny Wooloo boss portrait, but doesn't show it in the listing.

**Expected behavior**
The shiny boss to not show up at all in the tracker.

**Screenshots**
![2022-10-15_21 31 23](https://user-images.githubusercontent.com/112078351/196019184-f212b3b8-c0f6-4153-a8ad-e7d8d3b2cf41.png)

**Comment by PenginKami** [comment]
![2022-10-16_15 07 08](https://user-images.githubusercontent.com/96862959/196019134-8740bcbd-b7c7-4642-ae29-40cf03d1a44b.png)

Yeah, also are the portraits off centre for anyone else? 
This is also a picture showing the same thing happening on orion.

**Comment by Malphir** [comment]
The plugin designer tried to make it show only the head of the mon in the upper left corner... without realizing not all sprites have the head there... @PenginKami

**Comment by Malphir** [comment]
Added note, the shiny tracker no longer updates the listings at all on Titan.

**Comment by Rasgnarok** [comment]
Fixed by Kat a bit ago, closing.
