### ISSUE TITLE
Artmap A Bit Buggy with Item Frame Placements

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1936]
**Describe the bug**
When placing art map canvases on item frames above canvas pieces, it goes completely blank and is unrecoverable by normal player standards. Evsicles, the person who asked me to report this, is unable to get her artwork back. Strideii and I, BUGJUUICER, can confirm this.
(Ev#4997)
(JustStriide.#5784)
(BUG-JUICER#0940)

**To Reproduce**
1. Move art map from canvas to item frame.
2. When removing and putting it back, will randomly disappear artwork.
3. No other details sadly.

**Expected behavior**
Art to not die!

**Screenshots**
![image](https://user-images.githubusercontent.com/42111124/196024467-36b0d8c2-46fe-4fff-a2e9-475df8a13f3c.png)
Stride (I think?) and I can confirm that Zero definitely had a face before the bugs kicked in.

**Username:**
Evsicles, BUGJUUICER, Strideii

**Server name (all applicable):**
Orion

Can't report any logs here sadly but I can give a timestamp roughly:
3:40AM - 3:50AM EST

**Comment by skateboardkid97** [comment]
After server restart, Zero is completely fine and back to full health! It's just a strange visual glitch I think.

![image](https://user-images.githubusercontent.com/42111124/196025330-f8689658-e0bc-4442-ac18-e0ea398d8fc1.png)

**Comment by PenginKami** [comment]
Make sure you use the save item, then it's always recoverable in the /artmap menu!
