### ISSUE TITLE
Display Cases Broken

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1937]
**Describe the bug**
Fossil display cases do not close, drop or even drop the fossil in them when broken. It's very glitched right now.

**To Reproduce**
1. Put down a fossil display case.
2. Realize you can't close it.
3. Maybe put a fossil in, thinking it'll help,
4. It doesn't, and then you break it and then nothing drops at all.

**Expected behavior**
Fossil cases to close and drop what they have and also themselves.

**Screenshots**
I'll do you better! Video time baby!
https://youtu.be/690ylry0OvY

**Username:**
BUGJUUICER / BUG-JUICER#0940

Fossil room in Nagamichi's Museum located at:
x4178 / z7645 / y72

**Server name (all applicable):**
Orion

**Additional context**
my fossils are cold.....they need their glass blankets for their porcelain skin...... :[

**Comment by Khrisstias** [comment]
Hey! Thanks for the report! I have confirmed this is a bug. Will forward to the correct people.

**Comment by Khrisstias** [comment]
Oh! I forgot to ask, do you need any fossils refunded from this issue?

**Comment by skateboardkid97** [comment]
Oh! I'd like to have the fossils refunded if that's okay. I just deleted that one because it's the most common one I have.
I need:
x1 Skull Fossil
x2 Cover Fossil
x1 Root Fossil
This was mostly done on my part as testing but I'd like to have them back if possible. Thanks Khriss! :D

**Comment by Khrisstias** [comment]
Refunded!

**Comment by skateboardkid97** [comment]
Hi! So I was told to comment this here, another Pixelmon issue is that Side tables, Refrigerators, and any openable/closeable structures in-mod are not interactable at all. They're supposed to be, however when opened in game they're marked as claimed by administrator, even when administrators are trying to open them or are using bypass claim. Just wanted to note that! Thanks!

**Comment by Khrisstias** [comment]
> Hi! So I was told to comment this here, another Pixelmon issue is that Side tables, Refrigerators, and any openable/closeable structures in-mod are not interactable at all. They're supposed to be, however when opened in game they're marked as claimed by administrator, even when administrators are trying to open them or are using bypass claim. Just wanted to note that! Thanks!

I know for 100% certainty that refrigerators will not be fixed, as they are getting a new model via BlockBench. As for the other openables i am unsure of.
