### ISSUE TITLE
Shiny Poketracker Section

### ISSUE THREAD

**Issue by Yveltql** [ObliqueNetwork/Terra#1938]
I noticed earlier that the shiny section on the poketracker thing hasn't updated in about 16 hours as of writing this but I distinctly remember catching a shiny within the last hour or two which hasnt shown up on the list.

**Comment by Khrisstias** [comment]
Can confirm this. Just caught a shiny Chewtle but it only shows the portrait. Does not say if it caught, despawned, or defeated.

**Comment by Rasgnarok** [comment]
Seems to be working now, closing. I'll need more details in the future.
