### ISSUE TITLE
[Feature] Boss isn't appearing in boss tracker

### ISSUE THREAD

**Issue by PenginKami** [ObliqueNetwork/Terra#1939]
**Describe the bug**
The boss isn't listed in the boss tracker

**To Reproduce**
Find a Rare silicrobra boss I guess lol

**Expected behavior**
For it to appear in boss tracker in /poketracker.

**Screenshots**
![2022-10-17_09 43 17](https://user-images.githubusercontent.com/96862959/196064510-fd1ca569-8939-483f-9445-644807974611.png)

**Username:**
PenginKami

**Server name (all applicable):**
Titan

**Logs:**

**Additional context**

**Comment by Rasgnarok** [comment]
The sprite is sadly a bit too low on some of the pokemon, and the icon only moves slightly into view. I believe this is now fixed thanks to Katzyn, closing.
