### ISSUE TITLE
[Ione Invasion] The countdown didn't stop at 0 second

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#1940]
**Describe the bug**
The countdown didn't stop at 0 second, but at -4 seconds.

**Expected behavior**
The countdown should have ended at 0 second.

**Screenshot**
![ioneinvasioncountdown](https://user-images.githubusercontent.com/14977106/196310189-0802b5cb-d91c-4a26-8886-0eec5e566c27.png)

**Username:**
Mortenkein

**Server name (all applicable):**
Atlas

**Comment by Rasgnarok** [comment]
This is know, caused by a delay in the last pokemon fight to occur. Not a bug per se, but has been already flagged to the developer and deemed intended.
