### ISSUE TITLE
[Feature] Move Tutor isn't teaching grassy slide - arvandor

### ISSUE THREAD

**Issue by PenginKami** [ObliqueNetwork/Terra#1941]
**Describe the bug**
I click the move tutor with 5 heart scales, I click grassy slide, I click to remove sleep powder, and after its done it says "you can't pay the costs of learning this move!" 

**To Reproduce**
1. Go to arvandor pokecenter top floor
2. be in survival with 5 heart scales in your inventory
3. click on the move tutor with a tangrowth in your party
4. click grassy slide and replace a move
5. Despite having the resources, and it confirming prior to teaching that you can learn it and it costs 5 heart scales, it says you Can't Pay the resources

**Expected behavior**
For it to teach grassy slide and take my 5 heart scales

**Screenshots**
![2022-10-18_15 25 32](https://user-images.githubusercontent.com/96862959/196343428-29ac5e83-b375-4fe9-8b4a-28d9a1ea70
![2022-10-18_15 25 12](https://user-images.githubusercontent.com/96862959/196343437-fc3abc53-e86f-4a5b-9270-225dac553ddd.png)
6a.png)
![2022-10-18_15 25 17](https://user-images.githubusercontent.com/96862959/196343448-e75164be-10e4-4cac-9456-99b6b598f746.png)

**Username:**
PenginKami
**Server name (all applicable):**
Haven't checked any other then titan.
**Logs:**
I am lazy for logs, please tell me if they're necessary and I'll post them if you're having trouble finding the problem <3

**Additional context**

**Comment by CenizaRey** [comment]
The move tutor bug that was prevalent last version still exists, despite information to the contrary. We’ll let you know as soon as this is no longer the case!

**Comment by MissElyri** [comment]
Going to close this, as this is indeed a well known Pixlemon bug at this time. Thanks for the report!
