### ISSUE TITLE
Upgrade from Aria to Nova doesn't give Dark Grey /glow.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1942]
**Describe the Bug**
All in the title! When you upgrade to Nova in the Nebula shop, you get all your rewards except for the dark grey /glow.

**To Reproduce**
1. Buy Aria
2. Upgrade to Nova
3. See results

**Expected behavior**
You'd be getting the dark grey glow.

**Screenshots**
Will do!

**Username:**
BUGJUUICER / BUG-JUICER#0940

**Server name (all applicable):**
Orion (But happens in all probably)

![image](https://user-images.githubusercontent.com/42111124/196564181-f0c9e49f-4606-4745-83d6-5be07723278a.png)
![image](https://user-images.githubusercontent.com/42111124/196564187-f7067bde-adb5-42c1-b342-d3123866e6e8.png)

**Comment by MissElyri** [comment]
The command node for dark gray was missing from the Nova rank in general. I have added it, and added it's fix to all servers, but leaving open incase more testing needs to be done.

**Comment by MissElyri** [comment]
After some testing, fixes, and retesting, I have found that Jade was missing two colors for /glow, being Dark and Light Purple. Along with the fix to dark Gray, all colors of glow in every rank should now work properly on all servers! Thanks for the report.
