### ISSUE TITLE
Ban appeal (Banned on 11/2/2021 dd/mm/yyyy)

### ISSUE THREAD

**Issue by NoNoNoel** [ObliqueNetwork/Terra#1943]
Hey!

I've been wanting to play pixelmon again, but my account has been banned. This is likely because of the unclaimed base griefing my friend had been doing. I want to be clear about the fact that I was not playing anymore when she was doing these things. I hope I can get unbanned especially since it was more than 1.5 years ago. Hear from you soon!

**Comment by CenizaRey** [comment]
Hi! We no longer use the tracker for ban appeals. We use Google Forms now. Please fill out this link and we’ll get back to you!

https://forms.gle/DEztQ4nqAYJcYK6X8
