### ISSUE TITLE
[Daycare] Poke-Preview

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1944]
When putting two compatible Pokemon into a daycare to breed it will show a preview of the pokemon, This preview will show whether or not the Pokemon will be shiny prior to starting the breed. Secondly, the breeding history tab in your inventory will show shiny Pokemon icons for shiny Pokemon you have bred before they are even hatched. Unsure if this is a feature or a bug, however, Im leaning towards bug with at least the first part of the issue. I had not done any testing regarding if canceling and placing the mons in again causes a reroll on shiny chance as I had started the breed before I realized that the poke-icon was shiny. 

1. Place two compatible Pokemon in a daycare (Probably best to test on a server with insane shiny chances from breeding)
2. View the poke-icon before starting said breed. 
3. start said breed and collect the egg.
4. go into the daycare panel in your inventory prior to hatching egg
5. See shiny icon

For the icon not to show that a mon will be shiny prior to breeding the mon or hatching it.

![shinyhistory](https://user-images.githubusercontent.com/17133410/197029982-61c48f4d-bc0d-468b-a20c-fd5779f0046f.png)

As i had noted earlier in the ticket i had started the breed before realising the shiny icon was present but here is a non shiny version of the page where it occured:

![daycare](https://user-images.githubusercontent.com/17133410/197030126-5e305a5f-118f-4bb2-b87d-ee215ae12e01.png)

Deathnight7976

Orion, likely all.

**Comment by KittyKatzyn** [comment]
Thanks for the ticket Death - this is indeed a bug, and it is on Pixelmon's end, AND it has already been reported internally there :)  Closing!
