### ISSUE TITLE
[Pixelsprite Headwear] Textures fail to update when swapping between different palette pixelsprites.

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1945]
Textures fail to update when swapping between different palette pixelsprites. For exampe if I put a Charmander on my head and then put a shiny Charmander on my head it will display the non shiny one. However if I put a Charmander on my head then swap to a Mudkip then shiny Charmander itll display properly.

1. use `/givepixelsprite` to give yourself a shiny pokemon sprite and its unshiny version aswell as a different pixelsprite. 
2. put the normal pixelsprite on your head
 ![normal](https://user-images.githubusercontent.com/17133410/197316630-91c04057-f5a5-4ab2-a498-2bb98d02102b.png)
3. swap to the shiny variant pixelsprite
![shinybutbroken](https://user-images.githubusercontent.com/17133410/197316642-d645943e-010f-4918-94c8-9bd2b70921f9.png)
5. now repeat but instead swap to the alternative pixelsprite between normal and shiny pixelsprites
![normal](https://user-images.githubusercontent.com/17133410/197316705-4c5cf676-bb17-4a79-b2a4-3f4428084fa5.png)
![mudkip](https://user-images.githubusercontent.com/17133410/197316728-20ff20d7-cb06-477d-a487-a09e5970ef1b.png)
![shinyshiny](https://user-images.githubusercontent.com/17133410/197316719-6d2e75c8-4687-4618-8467-40a12969652d.png)

For the pixelsprite to update its texture without having to swap displayed mon prior.

Deathnight7976

Orion

This also occurs in 3rd person and others perspectives.

**Comment by KittyKatzyn** [comment]
This one is a Pixelmon bug and already forwarded to their internal tracker :)
