### ISSUE TITLE
I am having an issue with our custom textures

### ISSUE THREAD

**Issue by killercreechan** [ObliqueNetwork/Terra#1946]
**Describe the bug**
Our custom godoof and the vanhite, and cualan forms textures are broken just for me and not any others

**Expected behavior**
Help fixing the textures for the effected types

**Username:**
Killercreechan

**Server name (all applicable):**
Titan (just myself having the issue)

![2022-10-22_02 06 40](https://user-images.githubusercontent.com/112803874/197324235-2e4a2688-ccc2-41d4-8163-60344aff4f24.png)

![2022-10-22_02 11 16](https://user-images.githubusercontent.com/112803874/197324239-a48cfd35-b204-40a5-af5e-7e5ae3c617ba.png)

**Comment by killercreechan** [comment]
Only i am having this issue and i redownloaded the resource pack and re installed it so i have no clue what's going on

**Comment by CenizaRey** [comment]
Pretty sure you just need to restart your client after you apply a new resource pack and this issue will be solved. Let me know!

**Comment by CenizaRey** [comment]
Pretty sure you just need to restart your client after you apply a new resource pack and this issue will be solved. Let me know!
