### ISSUE TITLE
[Feature] Can craft Canvas back into empty map.

### ISSUE THREAD

**Issue by PenginKami** [ObliqueNetwork/Terra#1948]
**Describe the bug**
you can craft 8 canvas into 1 empty map, which is equivallent to voiding 7 empty maps and a ton of materials

**To Reproduce**
1. craft 8 canvas
2. turn 8 canvas into one empty map
3. regret your life choices as you turned 8 pog pieces of paper crafted USING empty maps into 1 boring empty map
4. 

**Expected behavior**
to not be possible

**Screenshots**
![2022-10-21_09 39 24](https://user-images.githubusercontent.com/96862959/197364180-fdad8fa4-10de-46f9-9062-aa89b374965f.png)
![2022-10-21_09 38 49](https://user-images.githubusercontent.com/96862959/197364182-746dd001-cf05-4242-94f2-0c0c084ef8f2.png)
![2022-10-21_09 39 12](https://user-images.githubusercontent.com/96862959/197364183-f9bb3db9-5453-49a8-8706-7fa30f626826.png)
![2022-10-21_09 39 24](https://user-images.githubusercontent.com/96862959/197364186-f6c40c5e-356d-4eb4-a97f-24ec0dfe6b40.png)

**Username:**
PenginKami
**Server name (all applicable):**
Orion is where it happened to me and I'd like a refund, and its probably possible on titan / atlas
**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**
I just want a refund... Ras said to do a ticket on github...

**Comment by PenginKami** [comment]
Deathnight helped me get the items back <3

**Comment by WisconsinWinters** [comment]
fixed.
