### ISSUE TITLE
[Staff-Commands] Hub

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1949]
Mods and i assume below do not have access to `/checkban player` while in the hub

1. Be `[Mod]`
2. connect to `/hub`
3. use command `/checkban player'

for /checkban to work and return the proper information

Deathnight7976

Hub

Other commands with such issues include `/cmi options chatspy (enable/disable)`

**Comment by Rasgnarok** [comment]
Fixed!
