### ISSUE TITLE
Bug: Right Clicking Gastrodon Crashes Game

### ISSUE THREAD

**Issue by MagnificentJynx** [ObliqueNetwork/Terra#1950]
**Describe the bug**
Essentially, my brother will throw out his gastrodon and right click it, in turn it crashes those around him completely, not just to the server selection. No it crashes minecraft as a whole
**To Reproduce**
1. Get a gastrodon (we assume, if it isnt just his)
2. Right Click on it
3. Get crashed, specifically for me at least it doesnt even pull up launcher again and you have to manually reopen the launcher

**Expected behavior**
After Right Clicking the Gastrodon, it should be a few seconds (around 2-3) before your minecraft starts lagging out, after those few seconds it brings to a "saving world" screen then Minecraft crashes as a whole

**Screenshots**
Do not have screenshots as there isnt much to screenshot

**Username:**
MagnificentJynx
my brother who used his Gastrodon is, Runmusxd and our friend pge was also affected in the initial 2 crashes before I got the crash details from launcher
**Server name (all applicable):**
Titan
**Logs:**
https://pastebin.com/6wRdVmT0

**Additional context**
We at first did not know what caused the crash, but through process of elimination found it to be the gastrodon, now the pokemon itself doesnt crash just when right clicked it does. We also tested it around 3 times to confirm it was what was causing the issue (4 as of writing this as I needed to recrash to get the report >.>)

**Comment by KittyKatzyn** [comment]
Fixed and closed :D
