### ISSUE TITLE
[UltraDexRank] Hatchery 3rd slot not available for ultra ranks, missing 3rd daycare permission

### ISSUE THREAD

**Issue by Franco-Orsi** [ObliqueNetwork/Terra#1951]
### Daycare 3rd Slot not working
Hi! So the bug is the next one, I've reached Ultra rank and I've relogged a lot of times, broke the hatcher and everything.
I was told I could unlock a 3rd daycare slot but it just doesn't work. 
Image 1: It seems unlocked but when I put the pokémon (image2) in it the X or ticket just doesn't appear and it doesn't let me use it. 
Images 2 and 3: Whenever I hover I get the "cancel" and "confirm" but when I press it it just doesn't work.

**To Reproduce**
1. Go to daycare
3. Click on 3rd slot
4. Try to use it
5. See error -> which is being unable to use it

**Expected behavior**
Being able to put the pokémon in it, use the gems to pay for it, get the timer and get to breed.

**Screenshots**

![image](https://user-images.githubusercontent.com/97135639/197480209-792d6f43-51fa-4cda-9afd-f20e3f3caaa6.png)
![image](https://user-images.githubusercontent.com/97135639/197480272-eafc07c1-f74d-418e-bf52-3bf4d9dfd85f.png)

Images 2 and 3:
![image](https://user-images.githubusercontent.com/97135639/197480525-781c9c25-ef4c-45b4-98ac-32f5b1d6e80c.png)
![image](https://user-images.githubusercontent.com/97135639/197480546-fbdb9047-15c3-46ef-b20b-e0faf1ad362d.png)

**Username: Luxuria_Rarity

**Server name (all applicable): Orion

**Logs:**
[2022-10-24-1.log.gz](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9850017/2022-10-24-1.log.gz)
[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9850018/latest.log)

**Additional context**
Props to DeathNight and BUGJUICER who helped me with this submit, luv you guys <3

**Comment by WisconsinWinters** [comment]
fixed
