### ISSUE TITLE
[Emoji/Embedded Links] Emojis will break links

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1953]
If a link contains an `/emoji` it will trigger and break any links:

1. Type a link with `o/` in it somewhere
2. send the message
3. see error

For the emojis not to overide embedded links.

![EmojiLink](https://user-images.githubusercontent.com/17133410/198249602-4fa8f00a-9ab1-4de6-9a39-0ce4b5bdd648.png)
The link used in the message above was `https://twitter.com/bromojumbo/status/1497769726952435716`

Deathnight7976
Orion, likely all

**Comment by CenizaRey** [comment]
The previous unicode 'o/' to trigger this emoji has been replaced with ': wave :' to avoid this issue in the future. Thanks for the report!
