### ISSUE TITLE
Cosmetic items are bugged

### ISSUE THREAD

**Issue by Tries97** [ObliqueNetwork/Terra#1954]
So i have a mew, mewtwo and jolteon hat. The mew and mewtwo ones are broken and my jolteon hat is an eevee hat... My backpack from zapdos seems broken as well. can someone help me? 
My IGN is: Tries97
Server: Titan

![unknown-15](https://user-images.githubusercontent.com/116970344/198844005-dfabab43-f392-46fe-878f-876d5342ae01.png)

**Comment by WisconsinWinters** [comment]
fixed
