### ISSUE TITLE
[CoreProtect] Infusers

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1955]
Infusers have no coreprotect container interaction blockdata

1. Put items inside an infuser
2. Take items out of an infuser
3. Inspect the infuser with core protect

For Infusers to have the same type of data  a chest would if items were added/removed.

Deathnight7976

Orion

**Comment by Deathnight7976** [comment]
Infusers still lack container logs.

**Comment by Khrisstias** [comment]
Can confirm this. Forwarded.

**Comment by WisconsinWinters** [comment]
coreprotect issue, unable to fix on our end
