### ISSUE TITLE
[UltraSpace] Bosses can float into the stratosphere and delete all rewards.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1956]
**Describe the bug**
When fighting a boss of any type, if you're stalling them out, especially Ultimate ones, they can float away into the top of US and completely despawn. Then when you kill them finally, they drop nothing.

**To Reproduce**
1. Find a boss in US
2. Stall it out and attack it til it's out of view/your camera only focuses on your Pokemon.
3. Kill it and realize no reward screen pops up.

**Expected behavior**
To give rewards!

**Username:**
BUG-JUICER#0940 / BUGJUUICER

**Server name (all applicable):**
Orion (Likely all)

**Comment by WisconsinWinters** [comment]
pokemon are now locked in place when in battle in ultra space, closing.
