### ISSUE TITLE
Leaving chunk early gets rid of pokemon when caught.

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1958]
This has been reported by 2 people now, I am unsure if it's a bug or not but here is the rundown.

One of the reports: https://discord.com/channels/151095626916954113/1037469971829227640/1037469971829227640

Basically these are pictures from someone else's issue, He caught a shiny ekans which obviously spawns in plains, In the screenshot he is under the ocean which I am assuming he left the chunk too early?
![2022-11-02_14 51 56](https://user-images.githubusercontent.com/78794976/199609075-0b04e9ed-c63d-435e-b082-338a97af9df7.png)
![2022-11-02_14 52 10](https://user-images.githubusercontent.com/78794976/199609019-2c5d2793-a44f-48fc-8c6a-4722636729d2.png)
![2022-11-02_14 53 36](https://user-images.githubusercontent.com/78794976/199608998-7ee49321-9ac8-4915-a761-e96f959e7b53.png)

Steps to reproduce: 
1. Shiny pokemon spawns
2. Throw pokeball at it
3. Wait until it goes left to right for times
4. Receive pokemon in party

Expected behaviour:
1. Receive the shiny pokemon in party or box

Server:
Orion (Most likely all)

**Comment by CenizaRey** [comment]
This isn't a bug, it's just how entity rendering works. An entity can't persist in an unloaded chunk, as that would cause immense amounts of lag even if it was feasible. Avoiding this issue is extremely easy, thankfully. Closing.
