### ISSUE TITLE
Kuan-Ti Advanced unchallengable

### ISSUE THREAD

**Issue by Sikening** [ObliqueNetwork/Terra#1959]
I have the agni and nogrod advanced gyms, but this is as far as I get in the gym menus. It won't let me click on Kuan-Ti, it just stays on the same screen.
![2022-10-30_18 48 18](https://user-images.githubusercontent.com/117047021/198905688-1dbbf540-59db-4b13-b65b-41b6ea5f1a73.png)

**Comment by Rasgnarok** [comment]
Not a suggestion, moving to the appropriate tracker.

**Comment by Rasgnarok** [comment]
I believe this is due to you missing the KuanTi badge on normal.

**Comment by Sikening** [comment]
Yes, sorry. I forgot to close it. Once I was given all of the normal badges as well as the advanced I had earned the issue was resolved.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by StrideMate** [comment]
This has been solved it seems, I am going to close it! If you have anything come up let us know! Thanks
