### ISSUE TITLE
[Bingo] Reward Pokemon does not have HA

### ISSUE THREAD

**Issue by kselda** [ObliqueNetwork/Terra#1961]
**Describe the bug**
Bingo Reward gave me a Cryogonal, which does not have a hidden ability. 

**To Reproduce**
1. Finish Bingo and receive rewards
2. In box, look for the reward Pokemon

**Expected behavior**
Bingo rewards are to include: 
1. Random Shiny Pokemon
2. Either a random shiny Pokemon or a random Pokemon with its HA. In both cases, Pokemon is to have at minimum 2 max IV's.

**Screenshots**
I was told that the stats were also an issue, so here is the Cryogonal's stats. 
![image](https://user-images.githubusercontent.com/61255672/200099498-136ecfb8-7b43-40df-b924-14dc9a8590a8.png)

**Username:**
Discord: Vanitas#0326

**Server name (all applicable):**
Kyagiri

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_
(This was days ago so I have no idea how to track old logs like that)

**Additional context**

**Comment by StrideMate** [comment]
Hi, You may DM me on discord (JustStriide.#5784) if you've never been refunded for this and I can sort it out for you! However Bingo has had a lot of updates since this happened, I believe it's been fixed since this incident! Apologies for the inconveniences, If anything else occurs you may reopen this or make another ticket, Thanks and Closing!
