### ISSUE TITLE
[Omen Rank Thingie] /Breed no longer working after most recent update. Same with /Hatch.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1962]
**Describe the bug**
Omens and all players are unable to use /breed. Even normal players, such as me, are unable to use /breed and even get a prompt saying 'you cannot use this command!', for Omens and everyone, it says the command simply does not exist. The same exists for /Hatch.

**To Reproduce**
1. Mod in Omen on yourself.
2. Use /breed 1 2
3. Use /hatch too.
4. Realize breeding is fucked

**Expected behavior**
For /breed to say something, like certain mons aren't breedable or not. Not that the command doesn't exist altogether.

**Username:**
BUGJUUICER/BUG-JUICER#0940

**Server name (all applicable):**
All servers don't have breed or hatch working, far as I'm aware.

**Comment by fatyg5** [comment]
Thank you for the report, I will investigate and update as I get new information.

**Comment by Mortenkein** [comment]
Both commands still don't work, at least on Atlas, even though they have been updated according to a recent changelog (24/11/2022 21:28).

**Comment by Chunkkss** [comment]
Closing due to command being changed and worked on.
