### ISSUE TITLE
[Legendary Spawning] Legendaries will magically up and disappear in flag disabled areas.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1963]
**Describe the bug**
When a legendary pokemon spawns on someone with "/claimflagdefinition pixelmon:user poke-spawn false" in their claim, the pokemon will remain in two states:
-Despawn immediately,
-Or be 'Active' for upwards of 2 hours without ever being seen.

If refunds are available also, there was a Hoopa on Evsicles and I at 3:10-ish AM, PST.
![image](https://user-images.githubusercontent.com/42111124/200114868-00cc457a-856d-472d-84db-63ae07530d4f.png)

This has happened to me with a Rayquaza and a Tapu Bulu. I was just unsure if it was a glitch or not so I didn't really report it previously. But I do realize now, every time this claim flag's in, it will attempt spawning a legendary on the person in the said claim, and then they will disappear without ever being seen.

**To Reproduce**
1. Make a claim of which has the "/claimflagdefinition pixelmon:user poke-spawn false" on.
2. Have a legendary spawn on you.
3. Tracker says despawned within minutes or active for hours.

**Expected behavior**
Legendaries to bypass this claim definition.

**Screenshots**
I have no screenshots to prove my Rayquaza or Bulu, but I do for the Hoopa above as we were in a normal desert and no one else at the time except for pawpe (monke) was. But he was in a desert lakes, and it said a normal desert.

**Username:**
BUGJUUICER, Evsicles, pawpe
BUG-JUICER#0940, Ev#4997, pawpe#0794

**Server name (all applicable):**
Has happened in Orion but I'm sure it's happened in every other server too.

**Additional context**
my hoopa dex snf snf ahu

**Comment by Deathnight7976** [comment]
Legendaries still attempt to spawn and announce in areas with pokespawning turned off via `/claimflagdefinition` rather than spawning elsewhere or on other players.

**Comment by WisconsinWinters** [comment]
gd is no longer used, closing
