### ISSUE TITLE
You get kicked off the server by hatching eggs

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#1964]
**Describe the bug**
You get kicked off the server by hatching eggs. It happened when I hatched 4 eggs: Aipom, Wooper, Scyther and Pincurchin. In the first slot, I had a Talonflame with the Flame Body ability.

**To Reproduce**
1. Breed two pokémon.
2. Move around until the egg hatches.

**Expected behavior**
Be able to hatch eggs without being kicked out of the server.

**Username:**
Mortenkein

**Server name (all applicable):**
Atlas, Titan

**Comment by Khrisstias** [comment]
It appears to have been resolved. Feel free to make a new ticket if this issue arises again.
