### ISSUE TITLE
[TMs/TRs] Shedinja cannot learn moves it can. Same with Hisuian Forms.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1966]
**Describe the bug**
I am not aware if this is already known about, but Hisuian forms cannot learn their previous counterparts' forms TMs and TRs when fully evolved and Hisuian. However I'm mostly reporting this because Shedinja is incapable of learning Baton pass and Swords dance, when it says it should be able to on main Pokemon websites.
TMs/TRs just don't seem to be fully checked out.

**To Reproduce**
1. Buy TMs/TRs from the funny merchant guy
2. Try using it on your beloved Shedinja/Hisuian Samurott
3. Cry

**Expected behavior**
For mons to be able to learn TMs that they can.

**Screenshots**
![image](https://user-images.githubusercontent.com/42111124/200148714-27901c8b-a56a-40fc-8519-c67bd6df9838.png)
![image](https://user-images.githubusercontent.com/42111124/200148728-fdd6156c-228e-48b5-96d9-1e9966b163f8.png)

(I don't have screenshots for the Hisuian Samurott as it was someone else's issue, just that Dewott could learn False Swipe by TM but Hisuian Samurott cannot.)

**Username:**
BUGJUUICER/BUG-JUICER#0940

**Server name (all applicable):**
Orion, likely all.

**Comment by CenizaRey** [comment]
Hi! This isn't actually a bug. Shedinja only learns these moves via transfer tutor, and not TM/TR. Additionally, Hisuian Samurott, like all Hisuian pokemon isn't compatible with any TMs/TRs. Its moves can only be taught via tutor. Thanks for the report! Closing.
