### ISSUE TITLE
[Bingo] Killing Megas of a bingo-mon (Mawile) counts as a bingo catch.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1968]
**Describe the bug**
When you kill a mega of, let's say, a Mawile, it crosses off that mon off of Bingo.

**To Reproduce**
1.Have Mawile on your bingo.
2. Kill a Mega Mawile.
3. See it's been crossed off of bingo, despite you never catching it.

**Expected behavior**
That when bingo means you catch mons for a reward, you catch mons...for a reward! If this is an intended feature, that's nice honestly. I'm just unsure if it even is.

**Screenshots**
I don't have any, sorry.

**Username:**
BUGJUUICER/BUG-JUICER#0940

**Server name (all applicable):**
Orion, likely all.

**Comment by KittyKatzyn** [comment]
Having tested this issue on Beta and Orion just now, I am unable to trigger this issue, so I am thinking something has fixed it in the past few months.  Sorry for the delay, but thanks for the ticket, Buggy!
