### ISSUE TITLE
[ChatColor/Emojis] Chatcolor and emojis are broken

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1970]
When typing in chat with a chatcolor enabled it will instead type the chatcolor variable and then your text behind it, for example typing with pink chatcolor(&d) would result in `dsample text` after typing `sample text` into chat.

Secondly typing emojis results in similar bugged chat as `:skull:` turns into `r7r`

1. Toggle a `/chatcolor` of your choosing
2. Type something into chat
3. See error
4. Repeat instead with an `/emoji` ex: `:skull:`

5. See error
![TmSdmBLiEl](https://user-images.githubusercontent.com/17133410/200638891-1d2bd972-456a-4a72-87a0-23068141ce0f.png)
For chat to format correctly to these emojis and chatcolors.

Deathnight7976

All servers

**Comment by CenizaRey** [comment]
Ascii Emojis are being removed altogether in the coming days to make way for the png emojis, so I'm not concerned with this. Thanks for the report, though! Closing for now.

**Comment by CenizaRey** [comment]
Also looking into the chatcolor problem as we speak, should be a simple fix
