### ISSUE TITLE
[DiscordChatLink] Quotation marks

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1971]
Things with quotation marks posted in game chat will not appear inside the discord channel

1. Open any servers discord link channel
2. Join the related server
3. Type in chat `"insert message"`
![IGC](https://user-images.githubusercontent.com/17133410/201266651-3f4c66df-bf83-477d-aada-b3e42d9631ce.png)
4. Check discord
![SC9sDIsXqz](https://user-images.githubusercontent.com/17133410/201266574-702613b5-8cc2-4210-a47b-5035480a0c1e.png)
5. See error

For the message to appear within discord

Deathnight7976
Orion, Likely all

Upon further inspection just the inclusion of a quotation mark anywhere within the chatline causes it not to record to the discord.

**Comment by Deathnight7976** [comment]
Still occurs

**Comment by chefburne** [comment]
This is no longer an issue, closing
