### ISSUE TITLE
When pressing tab, there is a list of emotes on orion.

### ISSUE THREAD

**Issue by Menno165** [ObliqueNetwork/Terra#1972]
**Describe the bug**
When you open the player list all the players online are shown, but besides that there is also a list of emotes next to them.

**To Reproduce**
1. Go to 'Orion'
2. Click on 'tab' or what keybind you have for the playerlist
3. See error

**Expected behavior**
Only the players are expected to show

**Screenshots**
![image](https://user-images.githubusercontent.com/84038836/201351855-61a90be2-d586-45a0-8263-c733e7e560a7.png)

**Username:**
Menno516

**Server name (all applicable):**
Orion (the screenshot given)
Beta (just some :haa: variants.)

**Comment by CenizaRey** [comment]
Fixed as of next reboot, closing
