### ISSUE TITLE
Limited Edition Keys in Vote crate still.

### ISSUE THREAD

**Issue by CaptainTCovenant** [ObliqueNetwork/Terra#1973]
You are still able to win Limited Edition Keys from Vote crates on all servers.

![Screenshot_397](https://user-images.githubusercontent.com/92965754/201444843-ec867d7a-dc2a-446f-8665-b155eb76f03c.png)
^ on Orion
![Screenshot_398](https://user-images.githubusercontent.com/92965754/201444865-a65bfcb3-f361-4fb9-a922-54f894b9fea1.png)
^ on Titan

**Comment by CenizaRey** [comment]
Not a bug, closing
