### ISSUE TITLE
Accented letters cannot be used in the in-game chat

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#1974]
**Describe the bug**
The server is unable to recognize accents since the addition of the server bridges. For example, when I type "pokémon", the server removes the "é", showing just "pokmon".

**To Reproduce**
1. Type any accented letter like é à û ç in the in-game chat.

**Expected behavior**
Be able to use accented letters.

**Username:**
Mortenkein

**Server name (all applicable):**
Atlas, but all servers I guess.

**Comment by Deathnight7976** [comment]
Accented letters do not link from discord to in game however, from server to discord functions.

**Comment by chefburne** [comment]
no longer an issue, closing
