### ISSUE TITLE
/repair all resets orbs

### ISSUE THREAD

**Issue by WisconsinWinters** [ObliqueNetwork/Terra#1975]
Using /repair all with a half-filled orb in your inventory will "repair" it along with all your other tools/armor, resetting it back to 375 kills needed.

**Comment by Deathnight7976** [comment]
Fix still causes orbs to lose progress.

**Comment by KittyKatzyn** [comment]
Forwarded to Internal!

**Comment by chefburne** [comment]
This has been solved, thanks for reporting
