### ISSUE TITLE
[Automnal Invasions] Boss Rarity

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1976]
During select Automnal Invasions bosses exclusively spawn in the uncommon rarity tier.

1. Start a random Automnal Invasion
2. Examine the rarity of the boss pokemons
3. If they are all uncommon, if not try another invasion (not every invasion is effected)

For a random assortment of boss rarities to spawn for juicy loots.

![2022-11-13_22 42 32](https://user-images.githubusercontent.com/17133410/201577706-2c6c08fd-15aa-4b30-b6c8-3a39fcd2f684.png)

Deathnight7976

Orion, likely all.

I'm not 100% positive this is a bug but i feel like something isnt right seeing as some invasions have all rarity bosses and others dont of the same raid theme.

This seems to effect multiple different raids at different locations ill attempt to list any i come across and edit the ticket with the town names as I see them. Also unsure if its the towns themselves or the select location of the raid as there seems to be 2 locations per town. 

1. Arvandor (near the ponyta spawner)

**Comment by EzelBerbier** [comment]
That happened in the last Atlas invasion too, in Agni this time, i think spawned 2 epic and few rare, but all the poke left was uncommon, and i only saw 1 special texture pokemon catchable spawned. In the Viral invasions i normally saw 2-3 spawned, and more ultimate-legendary bosses. Its kinda weird.

**Comment by Deathnight7976** [comment]
In this particular instance on Orion not a single boss pokemon other than uncommon was seen, normal rare pokemons did spawn however such as a rainbow skarmory and a shiny nidoking.

**Comment by EzelBerbier** [comment]
Thats weird, in the Atlas one only a valencian poliwhirl but nothing more, and most of the boss uncommon, and nothing really really god apart. Maybe was just a bad luck.

**Comment by StrideMate** [comment]
We can just let this ticket go for now, Until next Seasonal event where we have Seasonal raids and if the issue arises during that time we will forward the issue first thing it happens, If it happens then! Closing!
