### ISSUE TITLE
[Legendary Spawning] Victini Hasn't Spawned Once

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1977]
**Describe the bug**
So when they said they added Victini via spawning, I kinda suspected they did. But the lil guy hasn't spawned once between Atlas, Orion, and Titan.

**To Reproduce**
1. Go to Leaf Plat. in Savannah
2. Camp
3. Camp for weeks
4. See no Victini

**Expected behavior**
For Victini spawning to be enabled.

**Username:**
BUGJUUICER/BUG-JUICER#0940

**Server name (all applicable):**
Likely all. Orion.

**Comment by CenizaRey** [comment]
There was a bug with Victini spawning, this has been fixed as of next restart. Thanks for the report! Closing
