### ISSUE TITLE
[Poketracker] Loading & Despawned/Caught

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1979]
If a legendary spawns on you and you leave the area and unload the poke it'll update the tracker as `[Despawned]` (likely as the server no longer sees it) and then when it is reloaded the tracker will swap it back to `[Active]`. However once Caught the tracker will then revert back to `[Despawned]` rather than `[Caught]`. 

1. Have a legend spawn
2. Run away from a legend until the `/poketracker` says `[Despawned]`
3. Run back to where you left said legend
4. Check `/poketracker` and see `[Active]`
5. Catch legend
6. Check `/poketracker` and see `[Despawned]`
7. See error

For a caught legend to display as `[Caught]` and not `[Despawned]` even if the legend was unloaded

Deathnight7976

Orion, likely all

![Despawned](https://user-images.githubusercontent.com/17133410/201622013-6d7cf26f-0045-4697-b955-3970b7a19c11.png)

The Manaphy pictured above in the screenshot above was caught by myself and had been unloaded in the search for it resulting in said bug occurring.

**Comment by WisconsinWinters** [comment]
changed pokemon despawning mechanics to not despawn pokemon on chunk unload, closing.
