### ISSUE TITLE
[Poketracker] Ultra Beasts

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1981]
An Ultra Beast Celesteela spawned during an invasion at `/warp tesla` it failed to be tracked within `/poketracker`.

1. Spawn a Celesteela via Invasion
2. Use `/poketracker`
3. Check the Ultra Beast category
![CelesteelaTracker](https://user-images.githubusercontent.com/17133410/202424281-0c243c37-beff-4067-b066-c53f6bcdb6f4.png)

For all Ultra Beast spawns to be tracked accurately.

Deathnight7976

Orion, maybe all?

I don't think this is only limited to Celesteela as I've noticed some other ultra beasts in the past seemed to not update accurately however Celesteela is the only one I can 100% confirm failed to poketracker via `/poketracker`

**Comment by CenizaRey** [comment]
The Poketracker tracks Ultra Beasts that spawn naturally. Invasions are considered "forced spawn events", which means they don't count towards the tracker. Thanks for the report, though! Closing.
