### ISSUE TITLE
[/wiki] Custom Evolution missing from /wiki

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1982]
Crabrawlers custom evolution via Ice stone does not appear when using `/wiki Crabrawler evolution`

1. Enter the command `/wiki crawbrawler evolution` (They evolution bit in this command is case sensitive) 
2. Check Evolution requirements
![Crawbrawler](https://user-images.githubusercontent.com/17133410/202437803-789c611a-7136-48ba-9a22-455acd3d1181.png)
3. send out a Crabrawler
4. Use Ice Stone on Crabrawler
5. See error

For Crabrawlers custom changed evolution to show on the wiki. 

Deathnight7976

Orion, maybe all?

The custom evolutions do show on other mons when wiki'd it seems just crawbrawler is missing. However when looking at other custom evolutions I noticed that `/wiki Eevee evolution` is completely missing Glaceon's evolution (tho i imagine this is just cut off do to character limits??)

**Comment by Rasgnarok** [comment]
This one needs forwarding to Pixelmon's tracker, https://pixelmonmod.com/tracker.php?p=2

**Comment by KittyKatzyn** [comment]
I've gone through all of Nebula's custom evos (as far as I can tell) and Crabrawler-Crabomninable seems to be the only one affected.  I have made a change to the species file, so this issue should be fixed the next time the datapack is updated on the live servers :)

Thanks for the report, as always! Closing!
