### ISSUE TITLE
[Staff Permissions] Enderchests

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1983]
Staff members who lack `/enderchest` or `/ec` via donor rank for personal use do not have access to `/ec player` or `/enderchest player`. Attempting to open the players enderchest via `/invsee` and navigating via the GUI is also unsuccessful. 

1. Lack a donor rank or other rank that grants `/ec` or similar 
2. Attain the rank of `[Mod]`
3. Attempt to open a players enderchest via `/enderchest player` or similar 
4. Repeat via `/invsee` GUI
![Chatoutput](https://user-images.githubusercontent.com/17133410/202440373-1259e1d8-1419-48da-941e-2d7d5e992bbb.png)
5. See error

For staff members meant to have access to `/enderchest` to have such command available to them.

Deathnight7976

Titan, Atlas, likely all.

I believe the issue just stems from mods lacking basic `/enderchest` which prevents them from using it on other players aswell.

**Comment by CenizaRey** [comment]
Fixed, thanks for the report! Closing
