### ISSUE TITLE
Orion /gts sell issue

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#1987]
When using /gts sell, and selecting "sell hand" there is no +1,000 option to the price. 

Join Orion
Type /gts sell
Select sell hand
See error

![Screenshot_422](https://user-images.githubusercontent.com/67767916/203296561-a0936964-164c-4b10-82fd-f7aabeb3adbc.png)

**Comment by Deathnight7976** [comment]
Issue has been solved, closing.
