### ISSUE TITLE
Can't use /gts sell  to select items

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#1988]
You can use /gts sell to sell held items on Orion, but you cannot do so on Titan and Atlas.

**To Reproduce**

Join atlas/titan
hold an item and run /gts sell
see error 

**Expected behavior**
join orion after step 2
hold an item and run /gts sell

**Comment by StrideMate** [comment]
This is a older thread, This has since been fixed as I've ran tests in both servers reported. Thank you for the report though and if it occurs in the future, Please let us know! Closing!
