### ISSUE TITLE
[LUNAR Heads] Redeeming stacked heads removes your stacked ones, also.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1989]
**Describe the bug**
When you redeem a LUNAR set, if you have any extra heads stacked it'll delete them.

**To Reproduce**
1. Stack some heads
2. Redeem LUNAR set
3. Realize heads have disappeared

**Expected behavior**
To subtract heads rather than remove.

**Username:**
BUG-JUICER#0940 / BUGJUUICER

**Server name (all applicable):**
Orion, likely all.

**Comment by KittyKatzyn** [comment]
Forwarded to Internal! Will Update when fixed!

**Comment by WisconsinWinters** [comment]
invalid ticket as no longer used, closing
