### ISSUE TITLE
Poké Balls cannot be sold to shopkeeper NPCs

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#1991]
**Describe the bug**
You can't sell any Poké Ball to shopkeeper NPCs.

**To Reproduce**
1. Try to sell any Poké Ball to a shopkeeper NPC.

**Expected behavior**
Be able to sell Poké Balls to shopkeeper NPCs.

**Server name (all applicable):**
Atlas, but I guess all servers have the same bug.

**Comment by Chunkkss** [comment]
This was changed to encourage the buying / selling to other players in the server, creating a player run market.
