### ISSUE TITLE
[PixelHunts] You don't get a reward for completing a hunt

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#1992]
**Describe the bug**
I didn't get a reward for completing an Uncommon /hunt. Another player (Chilgt) didn't get a reward for completing an Ultimate /hunt. Also, the exclamation mark above the Epic /hunt is gone.

**To Reproduce**
1. Type /hunt
2. Catch any Pokémon on the list

**Expected behavior**
Be able to get a reward for completing a hunt.

**Server name (all applicable):**
Atlas, but I guess all servers have the same bug.

**Comment by Deathnight7976** [comment]
This appears to be fixed. Closing.
