### ISSUE TITLE
Bingo not rewarding, and other bugs

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#1993]
Doing /bingo, the UI is off centered, does not display the time left correctly, and does not show information of pokemon properly

**To Reproduce**
Join one of 3 servers
Run /bingo
see error
--------
finish bingo
see error (no rewards)

Player has reported these not working properly
![Screenshot_434](https://user-images.githubusercontent.com/67767916/203896065-c9fde0c8-a45e-4c1a-ade5-0aa664510402.png)

**Comment by Khrisstias** [comment]
This is fixed, thanks for the report!
