### ISSUE TITLE
[Shulkers & Balls] Balls may become random various ball types or glitch out and be usable despite not existing in inventory/inventory shulkers.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1994]
**Describe the bug**
It's a bit hard to explain, but when having no balls of a certain type, it may still read from your old inventory and allow you to use mballs and such without a price. Even if the balls were never there, they may all become pokeballs too, randomly. However their items do not change, it's just in the battle menu.

Putting them back in your inventory then back into the shulker supposedly fixes the issue.

**To Reproduce**
1. Have a ball shulker
2. Try using your balls
3. Realize most may be poke or random.

**Expected behavior**
Balls to be consistent.

**Screenshots**
It's just hard to explain and screenshot. You'd need to have to experience it yourself. Possible Pixelmon glitch?

**Username:**
BUGJUUICER/BUG-JUICER#0940

**Server name (all applicable):**
Orion, likely all.

**Comment by Azazels696** [comment]
Hi,for what i know you need to ''refresh'' your ball in your shulker by cary it on your inventory,after you can return these ball in your shulker. :) For my self i have carry i my ball in my shulker on me for a battle to make sure .:D

**Comment by Khrisstias** [comment]
What azazel said, this happened to me and i took the balls out and put them back in. Try this and let me know if it works

**Comment by Deathnight7976** [comment]
Please reopen if issue continues to persist otherwise closing.
