### ISSUE TITLE
Pokeballs crafts not working (Potentially all type of ball crafts.)

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#1995]
**Describe the bug**
When trying to craft Poke balls, it doesn't work. I tested it with bug and both of us were unable to craft Poke balls even though we had the correct materials.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Crafting table
2. Place Materials to craft in the correct way
3. Craft the Poke balls
4. Receive said amount of crafted Poke balls

**Expected behaviour**
To put the correct materials in the crafting table and craft the Poke balls.

**Screenshots**
![2022-11-25_21 45 35](https://user-images.githubusercontent.com/78794976/203968304-1f3d1307-d72e-4cd1-845d-f3ec9c4693d0.png)
![2022-11-25_21 45 38](https://user-images.githubusercontent.com/78794976/203968313-061cde91-73f4-4ab5-82df-ceeb8b9d06e9.png)
![2022-11-25_21 56 11](https://user-images.githubusercontent.com/78794976/203968500-e88010cf-0b02-4457-8aa7-9d04fc89fb3c.png)

**Username:** Strideii

**Server name (all applicable):** Orion (Maybe all)

**Comment by KittyKatzyn** [comment]
TY for the report, thankfully this issue was already confirmed and forwarded to the Pixelmon trackers :)

Closing!
