### ISSUE TITLE
/pokestats isnt working

### ISSUE THREAD

**Issue by ParanoeX** [ObliqueNetwork/Terra#1996]
Straight forward issue. /pokestats command isnt working.
I get an error message stating "An unexpected error occurred trying to execute that command".
Apparently the command isnt working for anyone else, either.
The command wasnt working before the newest update, so its not due to the new update :)

**Comment by KittyKatzyn** [comment]
Can confirm this as an issue - thanks for the report!  Unfortunately I have no idea how to fix this, so I'll just leave the isolated error message here: https://gist.github.com/KittyKatzyn/b726829dc09c0da5f609dbb39c79aaa1 and pass this along.  Thank you!

**Comment by WisconsinWinters** [comment]
disabled access to pokestats, errors forwarded to pixelmon
