### ISSUE TITLE
[Item crafting issue] Pokedisplay uses incorrect ingredients

### ISSUE THREAD

**Issue by Chilgt** [ObliqueNetwork/Terra#1997]
**Describe the bug**
The poke display item is meant to use 2 silver, a Poke ball, a lead, and 3 smooth stone slabs. In the server, the recipe is incorrect, as bedrock blocks are in place of the smooth stone slabs.

**To Reproduce**
1. Use JEI/look at the crafting recipe for the poke display.
2. Look at the wiki for the real recipe

**Expected behavior**
The crafting recipe should be correct and not require bedrock blocks.

**Screenshots**
![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 11_26_2022 3_18_16 PM](https://user-images.githubusercontent.com/119134421/204107606-8778433e-23b6-435c-8a5d-18bbd3c625db.png)

**Username: Chilgt**

**Server name (all applicable): All, I assume**

**Additional context**

**Comment by Khrisstias** [comment]
Hello! This is on purpose as pokedisplays are buggy and can cause crashes. Thanks for the report!
