### ISSUE TITLE
Bingo bork still after fix

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#1998]
Bingo still tracks incorrect remaining pokemon as well as funky UI

**To Reproduce**
Join a server
Run /bingo
See error

screenshot of Orion
![Screenshot_447](https://user-images.githubusercontent.com/67767916/204155940-62867f67-c1d3-4d5b-8ebb-228fcd30a923.png)

This is happening on all servers it appears

**Comment by fatyg5** [comment]
Speaking with the dev about this, hopefully a fix will be available soon.

**Comment by Khrisstias** [comment]
This should be fixed! Thank you for the report!
