### ISSUE TITLE
[Magikarp Boat] Poke Display obtainable through optional Equal boss in the Shiny Magikarp boat.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#2000]
**Describe the bug**
When you fight the Equal boss in the Shiny Magikarp boat, it gives you a Pokedisplay. Of which, I am aware right now is extremely buggy and could possibly crash the server or do other things. 

**To Reproduce**
1. Find a Golden Magikarp boat
2. Fight the Equal boss in there (The second one)
3. Get Poke Display
4. cry

**Expected behavior**
For this not to be available!

**Screenshots**
I have one if it's important. I'll keep it for now in my inventory but trash later when this is handled.
![image](https://user-images.githubusercontent.com/42111124/204347954-706a4e29-37a8-4f60-a2d4-900fa7934db2.png)
![image](https://user-images.githubusercontent.com/42111124/204347990-02d6de1d-986f-447c-9e35-5bf92df806f1.png)
(Bedrock to my knowledge is the classic placeholder of 'do not craft this' I assume.)

**Username:**
BUGJUUICER/BUG-JUICER#0940

**Server name (all applicable):**
Orion, likely all.

**Comment by Deathnight7976** [comment]
Still an issue

**Comment by KittyKatzyn** [comment]
Forwarded to Internal! Will update this when fixed!

**Comment by WisconsinWinters** [comment]
fixed, even if pokedisplays are obtained somehow, they cannot be interacted with or placed in the world.
