### ISSUE TITLE
[External Move] Forage

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2001]
Attempting to use the external move `Forage` does nothing.

1. Send out a pokemon
2. Check that the external move is set to forage (by default it is)
3. Use your external move hotkey

Foraging to forage

Deathnight7976
Orion, likely all

Idk if it matters but the attempt to forage was made in a swamp biome.

**Comment by Rasgnarok** [comment]
This is a 9.1.0 bug, pending a fix Pixelmon-side.
