### ISSUE TITLE
[Bingo] The comprehensive list

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2002]
Bingo is still very broken as of right now with missing rewards, broken parsing, and typos in the gui itself.

Loot:
Currently a bingo dishes out

- $4,000 Pokedollars
- 8 Copper hour glasses
- 20 Diamonds??
- No pokemon
- No legendary item.

What it should dish out:

- $31,500 Pokedollars ($2,500 Per Row, $2,000 Per Column, and $7,500 for a sheet)
- 14 Copper Hour Glasses (2 Per column)
- 4 Silver Hour Glasses (1 Per row)
- 2 Pokemon (1 Guaranteed shiny, One shiny OR HA pokemon (2+ivs))
- A Legendary item

When any pokemon is caught the server outputs a message that you completed a bingo slot and got %reward%! Despite no rewards for completing a singular slot.
![Discord_1QLuN8hsPr](https://user-images.githubusercontent.com/17133410/204457249-c8c80319-5b2b-476e-b013-551d41569592.png)

When entering the command `/bingo` It outputs that you have (12-1) remaining while excluding the unit (hours)
![Discord_nWbsUkcqZX](https://user-images.githubusercontent.com/17133410/204457266-20a59e38-090a-4cbf-ae5f-0f96d6f31f58.png)

The GUI mentions that a sheet contains 27 Pokemon to catch when the reality is that it contains 28 Pokemon (7*4)
![0SEBVnvZjy](https://user-images.githubusercontent.com/17133410/204457546-b6423cbc-fd6a-4c6d-abe0-9b71a7ef28fa.png)

When hovering over a pokemon the biomes, spawn-times, and catchrate all fail to display properly instead displaying there placeholders
![Discord_X4s9pk2keD](https://user-images.githubusercontent.com/17133410/204457688-0caa0c74-e3ee-47d0-a4d8-bfe4b7b69218.png)

1. Complete rows and columns of bingo
2. Fails to disperse all rewards
3. See error

For bingo to function like it did pre-9.10

Deathnight7976, BUGJUUICER (Testee)

Orion, likely all

**Comment by Rasgnarok** [comment]
Bingo will need to be disabled, we are currently waiting on an update to completely reconfigure it and prevent issues like the ones listed above.
