### ISSUE TITLE
Vote crate failing to give the new balls

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2003]
as title states, with the update to 9.1.0 the vote crate needs changes for the new balls. 
I am going to assume its all balls, but noticed it from someone not getting their Park ball. 

**To Reproduce**
Open crate - receive balls
See error

Orion server, however might be all.

**Comment by Deathnight7976** [comment]
I believe this has been fixed, if this occurs again please reopen.
