### ISSUE TITLE
Vote crate did not give a shiny when it should have

### ISSUE THREAD

**Issue by OriStillTheMain** [ObliqueNetwork/Terra#2004]
**Describe the bug**
 I won a "randomy shiny pokemon" from the Vote crate and the Pokemon Tsareena got sent to my PC, when i checked my PC to see Tsareena it was there but not shiny 

**To Reproduce**
Open Crate - Recieve random shiny pokemon

**Screenshots**
![shiny1](https://user-images.githubusercontent.com/119464645/204681199-0b33d348-82c0-4e04-9eba-0ea116c68971.PNG)
![tsareena](https://user-images.githubusercontent.com/119464645/204681219-cdbaf7db-8832-49aa-843e-6f82f12b60f7.PNG)

**Username:**
OriStillTheMain
**Server name (all applicable):**
Orion

**Comment by OriStillTheMain** [comment]
Has been resolved!
Apparently Tsareena does not have a shiny form

**Comment by CenizaRey** [comment]
Wait, what? That’s pretty crazy. Could you report your findings to the Pixelmon Mod tracker please? https://pixelmonmod.com/tracker.php

**Comment by KittyKatzyn** [comment]
> Wait, what? That’s pretty crazy. Could you report your findings to the Pixelmon Mod tracker please? https://pixelmonmod.com/tracker.php

I think this is actually due to our own datapack, not Pixelmon itself :)

**Comment by KittyKatzyn** [comment]
Sorry for the last response, but this was resolved previously, so I will close this!
