### ISSUE TITLE
Cosmetics Doubling when equipted

### ISSUE THREAD

**Issue by killercreechan** [ObliqueNetwork/Terra#2010]
**Describe the bug**
i noticed on other players that the cosmetics were doubling like one would be on there head like normal then there was a glitched one above there head 

**To Reproduce**
Equip any head cosmetic or any cosmetic and have someone look at you

**Expected behavior**
For someone to look into it and fix the visual bug

**Screenshots**
Will incude

**Username:**
Killercreechan

**Server name (all applicable):**
Titan Possibly all

![2022-12-02_22 07 53](https://user-images.githubusercontent.com/112803874/205432565-d12292cc-eb03-42ff-8443-4fdc48a672f3.png)

**Comment by CenizaRey** [comment]
This is a bug with Pixelmon 9.1.0, and should be forwarded to their tracker. Closing
