### ISSUE TITLE
Ultrabeasts being traded does not register a new dex entry. (Orion server)

### ISSUE THREAD

**Issue by Flaxencat6969** [ObliqueNetwork/Terra#2011]
Sorry if things are not as to protocol, it's my first time reporting a bug or anything. So to the issue at hand: 
Server: NebulaMC Pixelmon (Orion)
User: Flaxencat6969
Issue: We noticed while trading today, that trading Ultra Beasts did not register a dex entry. I was told that they previously did and that this must be a bug/issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Username:**

**Server name (all applicable):**

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by Deathnight7976** [comment]
This been fixed.
