### ISSUE TITLE
The Pokémon obtained from crates have only one move

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#2012]
**Describe the bug**
Since version 9.1.0 of Pixelmon, Pokémon obtained from crates have only one move, instead of four. The same problem occurs when the /skullcollections command is used.

Even in single player, I found a similar problem when I tested the /pokegive command (see the last 3 screenshots below). The _Form_ argument could be the cause of the issue.

**To Reproduce**
1. Use a key on a crate
2. Get a random Pokémon
3. In the inventory, right-click the Pokémon, then click on Moves

**Expected behavior**
Pokémon should have 4 moves, if they are not low level.

**Screenshots**
**Pokémon obtained with version 9.0.11 of Pixelmon:**

![01_AutumnalLudicolo](https://user-images.githubusercontent.com/14977106/206807318-f2bd3594-12cd-4aca-8533-a8e042a46b56.png) --> Autumnal Ludicolo
![03_AutumnalUrsuluna9011](https://user-images.githubusercontent.com/14977106/206807320-a21e9bb8-1d67-4d50-8b8e-a30a61af5695.png) --> Autumnal Ursuluna

**Pokémon obtained with version 9.1.0 of Pixelmon:**

![04_AutumnalUrsuluna910](https://user-images.githubusercontent.com/14977106/206807582-b056c507-b4d5-4b11-87cf-a33883f65871.png) --> Autumnal Ursuluna
![05_AutumnalLilligant](https://user-images.githubusercontent.com/14977106/206807583-47e1dad7-ff2f-4386-843d-ea9b629f6ef3.png) --> Autumnal Lilligant

![06_EclipseDarkrai](https://user-images.githubusercontent.com/14977106/206807585-8fc38b71-c6e5-4571-bba6-07a38b35a1c3.png) --> Eclipse Darkrai

**[Single player] Command used: /pokegive Mortenkein ninetales level:50**

![07_Ninetales](https://user-images.githubusercontent.com/14977106/206808172-acb7e7a4-9ecb-45e6-8e05-6154e61c3012.png)

**[Single player] Command used: /pokegive Mortenkein ninetales level:50 form:alolan**

![08_AlolanNinetales](https://user-images.githubusercontent.com/14977106/206808195-d2dc5b49-1b83-44cd-9a2b-49a38afa1776.png)

**[Single player] Command used: /pokegive Mortenkein ninetales level:50 form:alolan palette:shiny**

![09_ShinyAlolanNinetales](https://user-images.githubusercontent.com/14977106/206808214-d8e73c16-df88-4f0a-b790-ccf8bd2f8128.png)

**Server name (all applicable):**
Atlas, probably all servers

**Comment by Rasgnarok** [comment]
This is a Pixelmon bug as of 9.1.0, will be fixed soon by Pixelmon. In the meantime, you should be able to use the Relearner (which is now free) to recuperate the lost moves.
