### ISSUE TITLE
Wild Vanhite Falinks only have the Protect move, regardless of their level

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#2013]
**Describe the bug**
Since version 9.1.0 of Pixelmon, wild Vanhite Falinks only have the Protect move, regardless of their level.

**To Reproduce**
1. Find a wild Vanhite Falinks
2. Catch it

**Expected behavior**
This Pokémon should always have 4 moves.

**Server name (all applicable):**
Atlas, probably all servers

**Comment by CenizaRey** [comment]
This is a Pixelmon bug, and their team is aware of it. There’s unfortunately nothing to be done on our end, however the move relearner will restore any lost moves. I’ll ask our admins to remove the heart scale cost temporarily. Thanks for the report!
