### ISSUE TITLE
Unable to enter nether portal that was built in my own claim.

### ISSUE THREAD

**Issue by Flaxencat6969** [ObliqueNetwork/Terra#2014]
BUG:
I created a claim surrounding a haunted-looking tower in the dark forest. Once claimed, i created a nether portal inside the tower, but am unable to enter. A message pops up saying that I cannot enter because I am not trusted for this claim.

STEPS:
1. Create claim around haunted tower (Variant 2?)
2. Create nether portal inside claim
3. Attempt to enter nether from portal.
4. ERROR: Cannot enter portal because trust level is not sufficient for said claim.

EXPECTATION:
I expected to be granted access to the nether from the portal since it lies within my claim, as is the case with all my other claims.

USER:
Flaxencat6969

SERVER:
Orion

![2022-12-10_15 19 15](https://user-images.githubusercontent.com/120101055/206873836-9718a109-b9d5-4abd-82ad-2f0b75ff7aa1.png)

**Comment by Rasgnarok** [comment]
Can I have the coordinates to your claim?

**Comment by Flaxencat6969** [comment]
Hey, sorry for the delay, just got home. 
x: -21005 z: -7581
I was speaking with a mod ingame and they think the issue may be that someone on the other end of the portal could potentially have a claim. Still, the coords are submitted for your review. Thank you.

**Comment by WisconsinWinters** [comment]
closing as GD is no longer used.
