### ISSUE TITLE
Move Tutor move swapped/gone

### ISSUE THREAD

**Issue by TheBlur21** [ObliqueNetwork/Terra#2015]
hello, my ign is TheBlur21 recently i taught my Charizard thunder punch by the move tutor in tesla i play on the server titan but the next day after teaching my Charizard the move the first time I sent it into battle the move was gone and replaced with air slash, i didn't even teach it air slash so it was very odd but a kind mod informed me to report the bug after helping me by helping me get the move thunder punch back.

**Comment by CenizaRey** [comment]
This is a Pixelmon bug and is known on their end, we can sadly do nothing but wait for it to be fixed in an upcoming Pixelmon version. Closing
