### ISSUE TITLE
headbutt doesnt work

### ISSUE THREAD

**Issue by Dandastardly11** [ObliqueNetwork/Terra#2016]
**Describe the bug**

**To Reproduce**

**Expected behavior**
headbutt should make a pokemon appear or sum (stride told me to make this report)

**Screenshots**

**Username:** Dandastardly11

**Server name (all applicable):** atlas

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by Rasgnarok** [comment]
This is a 9.1.0 bug, it should be addressed soon by Pixelmon
