### ISSUE TITLE
Tsareena tag bugged

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2017]
The Autumnal Tsareena does not have the tag (Autumnal Form) like the other palettes. 

![image](https://user-images.githubusercontent.com/108286828/207982186-9c9ac2cf-e80e-4235-a3f2-be4209d161ff.png)
![image](https://user-images.githubusercontent.com/108286828/207982213-62124b62-e2e4-48c5-be86-29c2d2365980.png)

**Comment by KittyKatzyn** [comment]
Thanks for this ticket!  This issue has been fixed!
