### ISSUE TITLE
Pokemon still naturally spawning in the gym areas.

### ISSUE THREAD

**Issue by Menno165** [ObliqueNetwork/Terra#2018]
A while back I remember that Faty was trying to stop pokemons from spawning in the gyms.
I recently (few minutes back from this post) took a battle in Orion for electric-normal. Nearly at the end we had about 15 (give or take) wild pokemon spawned in.

I do not know if this is also the case in the other gyms and servers.
I will check on that later, but for now I had to go.

Expected behavior was that there would be no pokemon spawning inside the gym areas.

If needed, my discord:
Atred#1078

**Comment by WisconsinWinters** [comment]
disabled pokemon spawning in vahna aside from spawners, closing.
