### ISSUE TITLE
Wrong crate name and a typo

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#2019]
**Describe the bug**
When you win a **G Head** from the Limited Edition crate, this message appears in the chat: [NebulaMC] [ThanksgivingCrate] Player won a 1x _**U Head**_ from the Thanksgiving Crate.

![WrongCrateName](https://user-images.githubusercontent.com/14977106/208280438-ad509458-b796-443a-9916-6f5171552b18.png)

**Server name:**
Altas

**Comment by CenizaRey** [comment]
Fixed, thanks for the report! Closing
