### ISSUE TITLE
Item Frame Bug Repeat

### ISSUE THREAD

**Issue by Flaxencat6969** [ObliqueNetwork/Terra#2020]
Flaxencat6969
Orion

Alright, so it happened again. I was placing letter blocks into item frames to label my shop areas and instead of placing a letter block, it placed my backpack and ate it. Gone. Poof. Now, I've already placed about 20-25 letter blocks so far without an issue and suddenly, for whatever reason, it swapped a letter block for my backpack again. Not sure why, but apparently it prefers to swap items going into the frames with off-hand items. This time there was no lag or disconnection issues. Odd indeed.

**To Reproduce**
1. Go to: Anywhere with Item Frames
2. Click on: The item frame to place items inside (be sure there is an item in your off-hand slot. Mine happened to be Alakazaam Cosmetics Backpack).
3. If not right away, placed items should suddenly swap out with off-hand items then disappear.

**Expected behavior**
I only expected my item blocks to be placed inside the item frames, not my off-hand item.

**Screenshots**
Item Disappeared, so it's difficult to show a ss of it being gone. I could attach coordinates but the is the second time this has happeend in an entirely different location.

**Username:**
Flaxencat6969

**Server name (all applicable):**
Orion

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by Chunkkss** [comment]
I attempted this around 50 times, with a hat and with a backpack cosmetic. Could not recreate this glitch.

If this happens again, let us know. Sorry for the inconvenience.
