### ISSUE TITLE
[Poketracker] Innacurate status displayed on legendary pokemons.

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2022]
All legendary pokemons whether they are caught or despawned show up on the tracker as despawned.

1. Have legendary spawn
2. Have legendary caught
3. Check `/poketracker`

For the poketracker to accurately track the status of legendary pokemon.

![Discord_AHn3gZkd1v](https://user-images.githubusercontent.com/17133410/208317006-304de742-b933-4a38-a892-94eda54ace46.png)
Clearer pictures cause last one is fuzzy
![Discord_4DjDaLniHa](https://user-images.githubusercontent.com/17133410/208317069-338f0c6d-f9cd-4b1c-b76b-ace1a25862fe.png)
![ShareX_1jg0vc838T](https://user-images.githubusercontent.com/17133410/208317071-97159c55-7d6a-4fb3-b616-27d4c656227f.png)

Orion, likely all.

This bug was forwarded from the support channel on discord.

**Comment by Rasgnarok** [comment]
Closing, no longer valid.
