### ISSUE TITLE
Hat's Causing lag when putting them on.

### ISSUE THREAD

**Issue by Ammuvt** [ObliqueNetwork/Terra#2024]
I've noticed that the hats causes lag spikes and crashes should someone put one on. It's mostly the scute hat, a rainbow flower crown. It could be the bike and hats causing that issue but I'm not sure.

**Comment by Khrisstias** [comment]
https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/1886 has already been reported previously. Thanks for the report c:
