### ISSUE TITLE
[Pokeloot] Overworld newly genned pokeloots one time use.

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2027]
Pokeloots generated in newer chunks are once again disappearing after the first player claims the loot.

1. Find a newly generated pokeloot (likely 16000+blocks out)
2. Claim said pokeloot
3. See error

Overworld pokeloots to remain after being claimed.

Orion, possibly all.

**Comment by CenizaRey** [comment]
There’s nothing we can do about this now they’ve been generated, unfortunately. Thanks for the report! Closing.
