### ISSUE TITLE
Misleading Bingo prompt and missing prompt in chat box

### ISSUE THREAD

**Issue by Centuron** [ObliqueNetwork/Terra#2028]
There are just two small bugs I've noticed with bingo.
When bingo resets It says you have 24 hours to complete Bingo instead of 12.
When you complete Bingo it does not announce that you received the random shiny, but it does put it in your PC
I guess there might be a third bug, but unsure if it's intended with the new bingo system, but it no longer announces the exact time you have left to complete bingo.  It will always just show you how many hours you have left.

**To Reproduce**
For Bug 1
1. Wait for Bingo to Reset
2. See Error: "You have 24 hours to complete your bingo"

Bug 2

1. Complete Bingo
2. See Error: Does not announce the acquisition of random shiny despite it going into PC

Bug 3 (unsure if bug)
1. Let bingo reset or type /bingo wgule working on bingo.
2. See you have X hours left to complete bingo.

**Expected behavior**
For Bug 1, I expect to see "You have 12 hours to complete your bingo"
For Bug 2, I expect to see a prompt for me receiving a shiny.
For Bug 3, if it is a bug, I expect to see the the exact time you have left for completing your bingo instead of the closest hour rounded up, like prior bingos used to.

**Screenshots**

Centuron
Titan

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**
![2022-12-20_05 21 09](https://user-images.githubusercontent.com/113794806/208921348-867a529e-d9a1-44a0-8f71-e10c132fe68e.png)
![2022-12-20_22 00 29](https://user-images.githubusercontent.com/113794806/208921352-96262a10-1602-4fae-bd37-7a43c914f13c.png)
![2022-12-21_08 12 44](https://user-images.githubusercontent.com/113794806/208921356-fec60410-9795-43ae-84d2-0cd81e8fc345.png)

**Comment by CenizaRey** [comment]
Fixed bugs 1 and 2, 3 is intended! Thanks for the report! Closing.
