### ISSUE TITLE
Omen rank players don't have the permission to use the /breeding and /breakegg commands

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#2030]
I can't use the new commands (/breeding and /breakegg):

![permissionnewcommands](https://user-images.githubusercontent.com/14977106/209153949-7f928b69-a380-4b39-bc58-8236f7494f3c.png)

**Server name (all applicable):**
Atlas, probably all servers

**Comment by CenizaRey** [comment]
Fixed, thanks for the report! Closing
