### ISSUE TITLE
[Dexrewards] Missing Pokemon tab

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2031]
The `/dexrewards` missing pokemon tab is not functional.

1. Use `/dexrewards`
2. Select the missing pokemon in the GUI
3. See error

For the missing pokemon tab to appear.

Orion, likely all.

**Comment by Deathnight7976** [comment]
Still broken

**Comment by KittyKatzyn** [comment]
Nebula is currently using a very outdated version, and the most recent version of BDR (v 3.2.1) fixes this issue.  Will update this mod to fix this issue.

Forwarded to Internal!  Will update this when fixed!

**Comment by lankyboy01** [comment]
This issue was fixed, thanks for the report!
