### ISSUE TITLE
[Bingo] Bad maths

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2032]
In the bingo GUI it displays you need to catch 27 pokemon, however the actual number is 28 (4*7).

1. Type `/bingo`
![BingoGUI](https://user-images.githubusercontent.com/17133410/209228459-96dd2712-9bf3-4589-a7f2-5821b9e21f14.png)
2. Read the GUI
3. Count how many mons one must catch
![Bingo4x7](https://user-images.githubusercontent.com/17133410/209228490-d885277c-a8f6-41de-aee1-f0e2c0e4e73c.png)
4. Compare to GUI 
5. See error

For bingo to display the accurate number of pokemon needed to be caught.

Orion, likely all.

**Comment by CenizaRey** [comment]
Fixed! Thanks for the report. I will be laughing at Envyful for his awful default configs later
