### ISSUE TITLE
Vanhite Sprite pokes missing in the 1.4.0 version of the Texture Pack

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2033]
I thint this does not need any further explanation, the sprites of the Vanhite pokes are all missing (not the model). There is a screenshoot as an example.

![image](https://user-images.githubusercontent.com/108286828/209259919-17402245-1585-46a6-bcc7-8c71b189a292.png)

**Comment by CenizaRey** [comment]
This is an issue with your resource pack. Restarting the client fixes this. Closing
