### ISSUE TITLE
[Bingo] Catch a pokémon of the bingo does not count on Atlas

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2034]
When u catch a pokémon that it's from the Bingo, won't appear a message saying u catched a pokémon of the bingo, and there is any  green tick (✔) in the Bingo, so it's impossible to complete the bingo.

**To Reproduce**
1. Find the pokémon you need for Bingo.
2. Catch it.
3. Check ./Bingo.
4. The pokémon sprite it's still there, with any green tick that replace it.

I asked in Titan and Orion players, and they confirmed me that it's only a Atlas issue, because seems working normally in the others. 

Here a few screenshoots that shows the bug.

![image](https://user-images.githubusercontent.com/108286828/209261466-5afb6785-a8d0-4d01-8976-beeee2a9cf81.png)
![image](https://user-images.githubusercontent.com/108286828/209261517-61c50011-4401-4858-b49a-ca15ff7771d8.png)

**Comment by Khrisstias** [comment]
I have tested this myself and have confirmed. Drifloon was on my card but when i caught it, no checkmark appeared.

**Comment by CenizaRey** [comment]
Fixed! Thanks for the report!
