### ISSUE TITLE
[Bingo] Random 3iv HA Pokemon gave Pokemon without an HA.

### ISSUE THREAD

**Issue by Shika-The-Deer** [ObliqueNetwork/Terra#2035]
I completed the bingo and it gave me the random 3iv HA mon reward and it gave me an Archen, which does not have a hidden ability and can only have Defeatist.
(This was refunded already by Khriss but they told me to make a ticket.)
![image](https://user-images.githubusercontent.com/34965947/209265815-4e2d3193-442a-461b-ace7-51c3f46ced6b.png)
![image](https://user-images.githubusercontent.com/34965947/209265839-6a769f76-4870-4d4d-99c6-46e48016738d.png)
![image](https://user-images.githubusercontent.com/34965947/209265871-b1e45d09-7234-44f1-9d3a-07d1adb29aa5.png)

**Comment by KittyKatzyn** [comment]
Thank you for the ticket! This issue was fixed about a week ago, by giving Archen "Wimp Out" as it's Hidden Ability! As such, I'll close this issue, as it shouldn't happen again :)  Thanks!
