### ISSUE TITLE
[Tags] Can apply the same tag twice

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#2037]
**Describe the bug**
You can apply a tag twice. Say you have the "Normal" tag and you get another one, you can apply it again, wasting the tag.

**To Reproduce**
1. Win two of the same tag
2. Apply both

**Expected behavior**
Being unable to apply the tag again

**Username:** DraconiacLatias

**Server name (all applicable):** Orion, likely all

**Comment by CenizaRey** [comment]
This is impossible with the plugin we are using to handle physical tag items. I wish it was possible tho :( closing
