### ISSUE TITLE
[GTS] Missing GUI Button

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2040]
When using /gts sell then selecting an item, the +1000 option is just gone.

1. Equip an item into your hand
2. Enter the command `/gts sell`
3. Select the Sell Hand option
![GUI](https://user-images.githubusercontent.com/17133410/209457336-4a75dc6b-8b06-4dec-a931-0f534977d996.png)

For the +1,000 window pane to exist in the gui menu.

Orion, Likely all

**Comment by fatyg5** [comment]
Confirmed not an issue anymore. Thanks for the report.

**Comment by fatyg5** [comment]
I lied.

**Comment by fatyg5** [comment]
Fixed, for future reference, someone named the item stained_glass_pane and forgot the lime_ causing it to not load. There is no "stained_glass_pane". Pushing fix to all servers.
