### ISSUE TITLE
Legendary Spawn Bug

### ISSUE THREAD

**Issue by innqmorato** [ObliqueNetwork/Terra#2042]
My pc was on all night for some gatcha games, and i didnt remember to close pixelmon, so it was open and  i was still inside orion server for like 8h of being afk. Essentially a Cobalion spawned on me during that time, i will give logs if needed, also a virizion spawned during the night and as i was in the biome it could've been on me but idk. Im pretty sure by the way that the not afk spawning is broken atm. I'm adding the whole logs of the night in order that staff can check from it the afk mark and the spawn, dont know if it's needed.

Innqmorato, Orion.

[2022-12-25-2.log.gz](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/10299752/2022-12-25-2.log.gz)
(if this file doesnt open, change its extension in .rar)

**Comment by Chunkkss** [comment]
AFK Legend spawning is an unintended feature, I apologize.

There will not be a refund for this.

**Comment by Chunkkss** [comment]
Reopening, legends spawning on AFK players is unintended. Will be looked into. 

Sorry about the confusion.

**Comment by Rasgnarok** [comment]
Closing, fixed as of next restart.
