### ISSUE TITLE
Losing Pokemon from Pc

### ISSUE THREAD

**Issue by xPsychowolf07** [ObliqueNetwork/Terra#2045]
ive been losing pokemon from my pc someone should fix this bug before other people also use their loved pokes cause my Cryogonal shiny lvl100 aint happy about that

**Comment by fatyg5** [comment]
Can you explain how this happened? I am unable to do anything without any guidance on the cause

**Comment by Chunkkss** [comment]
Closing due to no response. If this happens again, or you're able to give us an explanation on how this could've happened, please let us know!
