### ISSUE TITLE
There are no EV training spawners at /spawn and the End portal has a visual bug on Atlas

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#2046]
Unless it's intentional, there are no more EV training spawners at /spawn on **Atlas**. Also, the End portal has a visual bug:

![endportalspawn](https://user-images.githubusercontent.com/14977106/210377032-c0a56723-a78a-4b3d-b555-a4a846d28286.png)

**Comment by CenizaRey** [comment]
Fixed, thanks for the report!
