### ISSUE TITLE
Stuck in Battle

### ISSUE THREAD

**Issue by Moonception** [ObliqueNetwork/Terra#2047]
I was trying to catch a remoraid underwater while on my mantine. I engaged with the remoraid using my Haxaraous but the screen started flickering. I wasn't able to make any moves, and I was unable to end the battle because the chat kept opening and closing without me touching anything. I was finally able to disconnect when I relogged it seemed to fix the issue.

**Comment by CenizaRey** [comment]
This is a Pixelmon battle bug, and happens occasionally. It isn’t the fault of Nebula, and as such, we can unfortunately do nothing about it. Thanks for the report and sorry for the inconvenience.
