### ISSUE TITLE
Ability modifier didnt work

### ISSUE THREAD

**Issue by SilvxrSora** [ObliqueNetwork/Terra#2048]
used an ability modifier on a mon and the ability didn't change.
 
Tried one more time to reproduce the same result but wasnt able to.

 modifier got refunded.

**Comment by CenizaRey** [comment]
What was the pokemon? What was its original ability? What were you trying to change the ability into?

**Comment by SilvxrSora** [comment]
The poke was impidimp, the original ability was Frisk, and I was trying to change it to Prankster

**Comment by Chunkkss** [comment]
Tested this issue, could not recreate. If this happens again let us know. Sounds like a one-off glitch though!
