### ISSUE TITLE
Poketracker miss placing legendary pokemon bosses

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2049]
**Describe the bug**
As title says, when a legendary pokemon spawns as a boss it shows up in legend spawn list instead of boss spawn list. Happened on Orion but I imagine its like this on all servers.

**To Reproduce**
Have a wild Legendary pokemon boss spawn on you
check /poketracker
see error

![Screenshot_6](https://user-images.githubusercontent.com/67767916/211134033-5e35f2e1-cb11-43ae-ab45-b2d1d6a8f5c6.png)

^ Ultimate Type Null boss

**Comment by CenizaRey** [comment]
Should be fixed now, thanks for the report! Closing
