### ISSUE TITLE
Claim list TP enabled

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2050]
**Describe the bug**
TITAN ONLY - you can TP to claims you make from /claimslist, this was suppose to be disabled. Seems to have been re-enabled on Titan server.

**To Reproduce**
Claim land
Run /claimslist
Select said claim
Click teleport
Pick a corner
See error

![Screenshot_7](https://user-images.githubusercontent.com/67767916/211137240-f2f18b17-d78a-4f06-bd06-5365ed5aac12.png)
^ Titan server. It is disabled on Atlas and Orion

**Comment by CenizaRey** [comment]
Should be fixed, thanks for the report! Closing
