### ISSUE TITLE
[Poketracker] Leggy Tracking Broke

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2052]
A legendary pokemon spawned and the tracker failed to track said legendary pokemon.

1. Wait for leggy to spawn
![Mew](https://user-images.githubusercontent.com/17133410/211168282-7cecccbb-b8c6-4506-912f-1a69de9531f1.png)
2. Then use command `/poketracker`
![Poketracker](https://user-images.githubusercontent.com/17133410/211168291-2fc85ac3-0e09-4672-855b-6dd87c50121e.png)
3. See error

For legendaries to track on poketracker

Orion, possibly all?

Log (CST), Orion
``[07Jan2023 13:49:24.818] [main/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Pixelmon] Mew has spawned in a Modified Jungle biome!``

**Comment by CenizaRey** [comment]
Should be fixed, thanks! Closing
