### ISSUE TITLE
Breeding and Breakegg command.

### ISSUE THREAD

**Issue by zTsuno** [ObliqueNetwork/Terra#2053]
**Describe the bug**
The bug seems to believe my Pokémon are unbreedable or at least, that's what I'm going by.

**To Reproduce**
1. Go to 'Use /breeding will bring up a UI to select two Pokémon of your party to breed. But after picking your Pokémon and clicking confirm, the UI disappears, and no egg will appear.
Also, when using /breakegg, It also brings up a UI to select a egg to hatch, but when clicking the egg, it tells me that it is a unknown command.'
2. Use:  '/breeding and select your two pokemon, or use /breakegg and select the egg'
3. See error

**Expected behavior**
To produce an egg when using /breeding and to hatch an egg when using /breakegg.

**Screenshots**
![image](https://user-images.githubusercontent.com/106882836/211209690-83b368ca-062e-42ce-8d0a-256b28b0d905.png)
![image](https://user-images.githubusercontent.com/106882836/211209700-869938af-0702-489f-ae1b-bc1411c20ce2.png)
![image](https://user-images.githubusercontent.com/106882836/211209732-690f74bf-8576-4b9d-be2a-fe4f772a7209.png)
![image](https://user-images.githubusercontent.com/106882836/211209747-3631ff02-8a9c-4c5c-8533-fc364545d3b9.png)
![image](https://user-images.githubusercontent.com/106882836/211209784-1040a287-6ee6-4054-b7ff-93cb3b31ebcf.png)

**Username:** MsKirishima

**Server name (all applicable):** ALL

**Comment by WisconsinWinters** [comment]
seems to be fixed, just used breakegg UI as intended, and breed is permanently disabled.
