### ISSUE TITLE
[GTS] /gts sell items giving random timing - ATLAS

### ISSUE THREAD

**Issue by coldpiplup** [ObliqueNetwork/Terra#2054]
**Describe the bug**
ATLAS SERVER. This applies only to items being listed, not Pokemon. Whenever you type /gts sell command, not matter what the value you put for the amount of seconds, it randomizes the timing. You can put 999999999999 and it comes out 8 minutes or 50 minutes.

**To Reproduce**
1. Put item in hand
2. type /gts sell 1 10000 99999 (any price and time works)
3. Open /gts
4. See random time remaining

**Expected behavior**
Expected the seconds to match what you type.

**Username:**
ColdPiplup (Helper)

**Server name (all applicable):**
Atlas

**Comment by Deathnight7976** [comment]
It appears this issue has changed a bit but still exists and is now network wide, When using the command `/gts sell 1 50000 999999` or `/gts sell 1 50000 999999999999` it defaults to ~13h 53m completely ignoring any time inputs.

**Comment by KittyKatzyn** [comment]
Having looked at the EnvyWare Discord, this seems to be a known issue. We're currently on an outdated version, but the current most recent version doesn't offer timing to be set by the seller at all, so it may be a good idea to wait until this is fixed before updating the mod for our server.

Forwarded to Internal!  Will update when fixed!

**Comment by WisconsinWinters** [comment]
fixed, closing
