### ISSUE TITLE
Nebula MC online store Rank Kit discrepancies from in game kits 

### ISSUE THREAD

**Issue by iamcjmxv** [ObliqueNetwork/Terra#2058]
There are a few discrepancies between the Omen kit description online and the rewards listed in game in /kits. 

_The list online is as follows_

1x Solar Crate key! ($2.50 value)
1x Megastone Crate Key! ($2.50 value)
**3x Master Ball** - PokéBalls with a 100% catch rare!
1x Perilious Soup - resets the EVs of a Pokémon to 0!
1x Colourful Shake - increases friendship of a Pokémon!
3x Ultra Rare Sodas - levels up your Pokémon by 4 levels!
3x Strong Hidden Ability Lure - increases the spawn rate of Hidden Ability Pokémon by 1.73x!
7x XL EXP Candies - levels up your Pokémon by 30,000 exp!

**Expected behavior?** 
There are all typos in the ingame. 
_The list in game is as follows_

1x Megastone Crate Key ($2.50 value)
**2x Master Ball** -  PokéBalls with a 100% catch rare!       -------------------     Should be 3?
1x Perilious Soup
1x Colourful Shake
                                                                                        
3x Strong Hidden Ability Lure 
5x XL EXP Candies                                                                 -------------------    Should be 7?

![image](https://user-images.githubusercontent.com/60482171/211242318-aacdd76f-d1a0-49a4-9f5e-d6b926905b43.png)

![image](https://user-images.githubusercontent.com/60482171/211242164-1e76418f-c878-4705-abac-7cff33761376.png)

**Conj_1**

**Orion at the minimum, I don't have omen on the other two:**

**Comment by KittyKatzyn** [comment]
Thank you for the report! Fixed these issues, as well as a couple of others on the store and in game!  :) Closing!
