### ISSUE TITLE
i cant /home

### ISSUE THREAD

**Issue by lovecatz173** [ObliqueNetwork/Terra#2059]
every time i do /home or click on my home in /homes it says i dont have a bed and wont let me teleport

![2023-01-09_12 20 55](https://user-images.githubusercontent.com/122307880/211381490-15082668-99b6-4560-8825-327b9a788a24.png)

lovecatz173

orion

**Comment by lovecatz173** [comment]
i deleted my home and set it again and it works, hopefully it doesnt do this again when i leave and come back

**Comment by CenizaRey** [comment]
Will investigate this further. Thanks for the report! Closing
