### ISSUE TITLE
[Gym Tags] I have beaten the first two gyms and claimed the challenger tag but cannot use it

### ISSUE THREAD

**Issue by F4Mx** [ObliqueNetwork/Terra#2062]
**Describe the bug**
I have beaten the first two gyms and claimed the tag. I should have access to the Challenger tag but whenever i use it i get a "You don't have permission to use this tag"
**To Reproduce**

1. Go to 'Tags'
2. Click on 'Challenger'
3. No Access.

**Screenshots**
![image](https://user-images.githubusercontent.com/122241208/211658701-18fe15eb-6016-4f4e-90a5-3bc071350599.png)
Idk what proof i can give but here is a screenshot of me being able to challenge the 3rd gym which you have to beat the first and second gym to be able to do
![image](https://user-images.githubusercontent.com/122241208/211659036-06b21d53-be30-4d2c-b279-f5c393b34264.png)
Screenshot of error message that i get
**Username:**
F4M
**Server name (all applicable):**
Orion

**Comment by CenizaRey** [comment]
I cannot reproduce this bug under any conditions, this may have just been a fluke. If you provide your server and IGN I can refund you this tag!
