### ISSUE TITLE
[Bingo] Reseted after a server crash

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2063]
Bingo card get reseted after a server crash if u didn't catch any of the pokémons in the bingo

1. Get a new bingo
2. Check the bingo cards
3. Don't catch any pokémon
4. Wait for a server crash
5. Join the server after the crash
6. Bingo message saying the Bingo was reseted
7. Check the bingo card

**Expected behavior**
The bingo card should maintance even if u didn't catch any pokémon.

Happened me recently, my bingo card got reseted for time, getting a new one, the server crashed after few minutes and my bingo card got reseted after the crash, getting a worst bingo with 2 unowns (the actual bingo killer), when the previous one wasn't than painful. This is the log with all the info in case is needed.
[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/10395749/latest.log)

**Comment by CenizaRey** [comment]
It isn't possible to transfer this kind of data over a server crash, sadly. Closing
