### ISSUE TITLE
[TheGauntlet] /warp TheGauntlet - Orion

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2064]
The warp, "The Gauntlet" is missing 99% of its blocks, the admins+ boss challenges all sit on the barrier floor below spawn. 

1. Turn on `/god` or `/fly`
2. Use `/warp TheGauntlet`
3. See error.

For the Gauntlet Island not to be missing a huge chunk due to world edit.

![2023-01-13_02 48 00](https://user-images.githubusercontent.com/17133410/212278144-009e6e04-c6c3-44dc-a460-4394f1039529.png)

![2023-01-13_02 48 15](https://user-images.githubusercontent.com/17133410/212278155-b2097082-7c73-4530-bcf5-7c0578b186f5.png)

Orion.

The remnants only seem to exist on Orion, I'm guessing that either atlas/titan never had "The Gauntlet" or it was meant to be removed entirely?

**Comment by CenizaRey** [comment]
I broke it by accident but it was never really a project we planned on continuing anyway. The remnants of it will be destroyed shortly. Thanks for the report!
