### ISSUE TITLE
Omen rank players no longer have unlimited homes

### ISSUE THREAD

**Issue by Mortenkein** [ObliqueNetwork/Terra#2065]
**Describe the bug**
Omen rank players cannot set more than 112 homes (previously 9999).

**To Reproduce**
1. Set 112 homes
2. Try to set a new home

**Expected behavior**
Be able to set 9999 homes, as before.

**Screenshots**
![nounlimitedhomes1](https://user-images.githubusercontent.com/14977106/212318811-93229537-d54a-452c-a6e9-45d660accc60.png)
![nounlimitedhomes2](https://user-images.githubusercontent.com/14977106/212318814-c289111c-bf6a-45ed-bb4b-3a8d62a86759.png)

**Edit:**
The sethome limit is now lower, after the automatic server restart:

![nounlimitedhomes3](https://user-images.githubusercontent.com/14977106/212339188-3e75eaa6-26ed-4e7f-8b83-b9988806ee18.png)

**Username:**
Mortenkein

**Server name (all applicable):**
Atlas, probably all servers

**Comment by CenizaRey** [comment]
We discovered that allowing players to set unlimited homes was causing a severe amount of server lag as the storage was throttling the network. We had no choice but to limit the homes to just over 100. It wasn't a decision taken lightly, but we feel that the current limit is more than enough for any person. Sorry for the inconvenience, and thanks for the report - but we will not be returning to unlimited homes for the Omen rank.
