### ISSUE TITLE
Core Protect issue

### ISSUE THREAD

**Issue by iamcjmxv** [ObliqueNetwork/Terra#2066]
Issue with Core Protect

**To Reproduce**
If you place a lava bucket down you cannot use any inspect or lookup or near command it shows no data for lava. 

**Expected behavior**
There should be a way to see who placed down lava on someone else's claim or near it. 

**Conj_1**

**All servers**

**Comment by Chunkkss** [comment]
./co lookup time: radius: action:CLICK should be the solution. It doesn't seem to log clicks however probably because this would flood logs with an insane amount of pages.
