### ISSUE TITLE
[Server] Render Distance to short

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2067]
When you appear in a biome, and pokémon start to spawn, you can only see few of them, if u walk a bit they disappear and appear others, and if u come back to your own steps, they are still there (so they didn't despawn), confirming is a render distance of entities. It's not a user issue because before go to bed the render distance was okey and I was able to see pokes in a far distance, and Im using Optifine with the Entity Distance option at max (500%). Seems to happen in all the servers.
![image](https://user-images.githubusercontent.com/108286828/212536446-222cd1c4-f792-405e-b664-d470f7210e24.png)

**To Reproduce**
1. Join a server
2. Go to a clear area to check the bug better
3. See only a few pokémons near to u (same in the Journey Map)
4. Walk enough distance for them to disappear, not to despawn
5. Come back, they are still there bu u wasn't able to see them
6. The new pokes u saw when i was walking, if u go back they will stay there
7. See the error

**Expected behavior**
You should be able to see pokémons in a far distance, same in the Journey Map, like happened not long ago

A screenshoot of my base, where u can saw 2-3 pokémons. Confirmed that is a common issue in all the servers for staff members when I asked.

![image](https://user-images.githubusercontent.com/108286828/212536636-a2be2bdb-cd8d-44a2-a120-d7f6db727d4e.png)

**Comment by Khrisstias** [comment]
https://imgur.com/a/fho4Sd1 made a video to better show what's going on

**Comment by Khrisstias** [comment]
Going to close as render distance was bumped up.
