### ISSUE TITLE
[NPC Trainer] Miner trainer outside of Agni is buggered

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#2068]
**Describe the bug**
Unable to challenge the NPC, checked it's settings and nothing seems wrong. Unsure how to fix.

**To Reproduce**
1. Throw a pokemon at this NPC trainer

**Expected behavior**
Able to battle the NPC

**Screenshots**
![2023-01-15_12 49 55](https://user-images.githubusercontent.com/37944220/212563933-21a450ea-a003-49f3-b02a-fa2dd3d70bdb.png)

**Username:**DraconiacLatias

**Server name (all applicable):**Orion

**Comment by KittyKatzyn** [comment]
This NPC seems fixed now! Closing!
