### ISSUE TITLE
[ResourcePack] Cualan Shellos has no fall back

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#2069]
**Describe the bug**
If someone does not have the resource pack, Shellos will have a missing texture instead of being a normal shellos (the primals properly fall back)

**To Reproduce**
1. Turn off resource pack
2. Send out a cualan shellos

**Expected behavior**
The shellos looking like the east or west form without the pack

**Screenshots**
![2023-01-15_14 11 51](https://user-images.githubusercontent.com/37944220/212564793-aa859f04-c3e2-46dd-85c9-324909bc97d4.png)

**Username:** DraconiacLatias

**Server name (all applicable):** Orion

**Comment by KittyKatzyn** [comment]
Thanks for the ticket, Khriss! Can confirm the issue, and will be fixed! I thought this was worse than it was, but thankfully I was wrong lol!

**Comment by KittyKatzyn** [comment]
With a lot of testing, editing, and removing redundant files, this issue has been fixed! However, the changes won't take place until the servers have the new datapack AND users have the new resource pack.
