### ISSUE TITLE
[Discord] Discord text channels no longer link to in game chat

### ISSUE THREAD

**Issue by Dovukin** [ObliqueNetwork/Terra#2070]
**Describe the bug**
The NebulaMC discord text channels such as #orion no longer link the message from the discord to the in game chat of the specific server

**To Reproduce**
1. Go to the NebulaMC discord server 
2. Be online in one of the servers (titan , orion , atlas)
3. Message in the respective text channel example #orion 
4. See no message in the ingame chat

**Expected behavior**
The discord message from the text channel should appear in the ingame chat

**Screenshots**
![Screenshot (25)](https://user-images.githubusercontent.com/122803986/212703730-6c2db4b8-fed9-4776-a309-96f773ca0367.png)
![Screenshot (26)](https://user-images.githubusercontent.com/122803986/212703754-0d7f4179-1f06-45ad-8374-5b646a5ff94b.png)

**Username:**
Dovukin

**Server name (all applicable):**
The bug is for all 3 servers

Additionally i believe the added cross chat is what caused this as before it was working normally

**Comment by Rasgnarok** [comment]
https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/2061

**Comment by chefburne** [comment]
no longer an issue, closing
