### ISSUE TITLE
Wondertrade command confirming with different slots

### ISSUE THREAD

**Issue by Chunkkss** [ObliqueNetwork/Terra#2071]
Wondertrade command will confirm with a different slot than you originally wondertraded with, therefor if you make a slight mistake you will wondertrade the wrong pokemon.

Tested with Centuron

/wt 5

asks for confirmation

/wt 6

will wondertrade the 6th pokemon in your party with no further confirmation

**Comment by KittyKatzyn** [comment]
Fixed by updating the mod!  Updated mod live on all servers!  Yay!

Closing! <3
