### ISSUE TITLE
having a name that is also a tag tricks the plugin

### ISSUE THREAD

**Issue by darknegadude** [ObliqueNetwork/Terra#2072]
If a player has a nickname that is the same as a tag, hovering over the tag acts as if you are hovering over the name of the person whose nickname matches the tag, clicking on the tag prompts the player to pm the player whose name matches the tag

1. have a nickname that matches a tag 
2. hover over the tag on another player
3. See error

**Expected behavior**
the tag shouldn't be treated like a name when hovered over or clicked on

**Screenshots**

![2023-01-16_22 04 58](https://user-images.githubusercontent.com/49503839/212815054-27c7dc82-85b0-4493-9ae4-a06be00f369f.png)

**Username:**
Darknegadude

**Server name (all applicable):**
Only tested on Atlas, but probably network wide

**Comment by chefburne** [comment]
No longer an issue, closing
