### ISSUE TITLE
Rotom forms unobtainable by the usual way.

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2074]
**Describe the bug**
You are unable to change Rotom forms by throwing it out at a machine. Tested in singleplayer and it works as intended, however does nothing in the server. Tested with two different rotoms, in a claim and outside of a claim. Tried a Fan, Fridge and Washing machine.
-unsure if we had another way to obtain them, but could not find information on that in discord-
**To Reproduce**
Place a fan
Throw base form Rotom at the fan
See error

**Expected behavior**
Rotom should have turned into Rotom-fan and learned a new move. 

This persists on all servers.

**Comment by Rasgnarok** [comment]
We can write some alternative way of obtaining these.

**Comment by KittyKatzyn** [comment]
Forwarded to Internal! Will update here when implemented!
