### ISSUE TITLE
No Access to /redeem gui or /redeem cosmetics in game

### ISSUE THREAD

**Issue by Chunkkss** [ObliqueNetwork/Terra#2075]
Should be an omen command to unlock all the eeveelution scarves, but I don't have permissions to use the command.

![image](https://user-images.githubusercontent.com/107234416/213097736-bc50d520-61bb-4dc4-b3f2-51d5c6cbf7f9.png)

**Comment by Deathnight7976** [comment]
It appears this is no longer a gui brought up via command but instead is brought up by pressing `Escape` then selecting the `Pixelmon` button and the cosmetics should be available there.
![ApplicationFrameHost_xyx6HsIwBq](https://user-images.githubusercontent.com/17133410/221762031-8ce312cc-290c-4cb1-9fae-55333ccd77d5.png)
