### ISSUE TITLE
[Hunts] Fuecoco, Quaxly and Sprigatito evolutions in the Hunts

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2076]
With the addition of the evo lines of Fuecoco, Quaxly and Sprigatito, they can be found as a possible Hunt:
![image](https://user-images.githubusercontent.com/108286828/213164111-85afaf74-5f01-4686-a5de-343b3f771bdd.png)
But there is an issue, they don't have a spawn configured
![image](https://user-images.githubusercontent.com/108286828/213164206-8de163db-af19-4258-91d1-725fea8015dd.png)
![image](https://user-images.githubusercontent.com/108286828/213164355-4c452bb3-152e-4e74-b2de-2f23103fc318.png)
![image](https://user-images.githubusercontent.com/108286828/213164432-715d890f-2707-4f40-887a-626100c733b7.png)
And because they can't be found in the wild, those hunts are impossible to make. 

Happen the same with the second evo lines: Quaxwell, Crocalor and Floragato.

**Comment by CenizaRey** [comment]
Fixed! Thanks for the report! Closing
