### ISSUE TITLE
[DiscordChatLink] Staff chat

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2078]
The link from the discord to in game staff chat has broken. Messages sent from the discord will not appear in game, however, messages sent from in game appear in the discord.

1. Hop on a server
2. Type something in the appropriate staffchat channel
3. Tab into server

![countingIG](https://user-images.githubusercontent.com/17133410/213235679-20f0e4fc-3896-4aaf-bd02-e80c186866d7.png)
![Abms4pWY0u](https://user-images.githubusercontent.com/17133410/213236174-161ed1ac-b826-4fe7-ae9e-227cf49a3b8a.png)

For messages sent within the discord to appear within minecraft.

Orion, likely all. & Discord.

**Comment by Chunkkss** [comment]
This has been fixed!
