### ISSUE TITLE
all vote link button not working

### ISSUE THREAD

**Issue by redjeff1** [ObliqueNetwork/Terra#2079]
if you go into the vote menu and try to press the all vote links button nothing shows up, the button is pressable but nothing will show up in chat.

**Screenshots**
![image](https://user-images.githubusercontent.com/48700761/213260709-a42cd1aa-e0c0-4088-a947-92b75d873e04.png)

**Username:**
REDJEFF
**Server name (all applicable):**
atlas

**Additional context**
it hasn't worked since forever :sadge:

**Comment by KittyKatzyn** [comment]
Forwarded to Internal! Will update this when fixed!

**Comment by chefburne** [comment]
now works, thanks for reporting
