### ISSUE TITLE
[Spawn] Admin Claims

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2080]
The `/spawn` region on all three servers is contained within an admin claim, however on the far west edge the admin claim stops before reaching the edge barrier block wall. There is a 12 block gap which is entirely unclaimed.

As a temporary fix I've added these sections to my player claim until someone can expand the admin claim. 

Deathnight7976

Far west side, Cords: -155 1 91
All.

**Comment by Chunkkss** [comment]
Adjusted barriers to be in, filling until admin claim. Doesn't affect anything in spawn.

Fixed.
