### ISSUE TITLE
[Bingo] The book does not show the info anymore

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2081]
Before the 9.1.1 and 9.1.2 the book in the ./Bingo command gaves u the info about what is bingo and which rewards gives u, but after the update that info does not appear anymore.

![image](https://user-images.githubusercontent.com/108286828/213757353-f0761f57-b247-4da3-9954-59da5b521647.png)

**Comment by Chunkkss** [comment]
Bingo has a new menu, this is no longer an issue using /bingo!
