### ISSUE TITLE
/buyclaimblocks doesn't work

### ISSUE THREAD

**Issue by TheBatman52** [ObliqueNetwork/Terra#2083]
Whenever I use /buyclaimblocks it just says "you cannot exceed 1,000 claim blocks" even when i got the money

![2023-01-21_18 44 54](https://user-images.githubusercontent.com/123264272/213880860-f4770457-34fd-456b-9035-569062554462.png)
![2023-01-21_18 44 58](https://user-images.githubusercontent.com/123264272/213880867-b1048353-ee8c-41c7-8308-baea0d71642c.png)

TheBatman52 on Titan

**Comment by Khrisstias** [comment]
there is a buying limit on claim blocks. this is to prevent players from claiming entire biomes to themselves

**Comment by TheBatman52** [comment]
> there is a buying limit on claim blocks. 

I know that but why can't i buy even a single one like in the picture?
