### ISSUE TITLE
[/Hunts] Gen 9 Evolution - Floragato

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2084]
Despite changelog reporting that Gen 9 starters and there evos will no longer appear in hunts post server restart, A Floragato has appeared in the mythical tier hunt.

1. Use `/hunts`
2. Get a rare Gen9 in Hunts
![Gen9Evolution](https://user-images.githubusercontent.com/17133410/214153257-d5d998c5-21ce-426c-9280-9e771d1b8a11.png)
3. See Error

For no Gen 9's to appear in `/hunts`

Orion, maybe all?

**Comment by Centuron** [comment]
Can confirm in Titan as well

**Comment by Deathnight7976** [comment]
Fixed as of next restart.
