### ISSUE TITLE
[Event Shop] /eventshop not distributing keys

### ISSUE THREAD

**Issue by chefburnt** [ObliqueNetwork/Terra#2086]
When you go to /eventshop, click "Crate Keys", and select a key, you will not receive the key. Though the event tokens will be taken from your balance.

1. Join Atlas, Orion, or Titan
2. Have at least 300 event tokens
3. Go to /eventshop
4. Attempt to buy one of the keys, see the error.

Upon buying a crate key from /eventshop, you would expect the key to be given to you.

![image](https://user-images.githubusercontent.com/123426993/214195116-23febfd5-94e7-4325-b4eb-8bfbd551e7d4.png)
![Image2](https://user-images.githubusercontent.com/123426993/214195129-f1674abf-c97e-4aaa-b2a0-e83b6d04bf63.png)

Tested by REDJEFF and Chunkkss (from support channel), seems to be all 3 servers.

Chunkkss logs from the /eventshop menu as well as the purchasing of the key:

[errorlog.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/10485647/errorlog.txt)

**Comment by KittyKatzyn** [comment]
Sorry for the inconvenice!  This issue has been fixed!  Thank you!
