### ISSUE TITLE
Megastone crate keys still in the reward pool

### ISSUE THREAD

**Issue by Dovukin** [ObliqueNetwork/Terra#2088]
**Describe the bug**
Megastone crate keys are still being given out in reward pools such as the /hunts and the solar crate keys

**To Reproduce**
Firstly you may try mythical hunts or solar crate keys
Alternatively you can just look at the rewards for mythical hunts and solar crates
Both display and give out megastone crate keys

**Expected behavior**
The megastone crate keys shouldnt be in those reward pools as they are disabled 

**Screenshots**
![2023-01-24_13 18 41](https://user-images.githubusercontent.com/122803986/214278686-ce3d80cb-e605-44e8-945a-c991ae687639.png)
![2023-01-24_13 18 59](https://user-images.githubusercontent.com/122803986/214278698-6c7e04d8-e225-4b2c-8a10-c821690f2682.png)

**Username:**
Dovukin
**Server name (all applicable):**
All servers

**Comment by Dovukin** [comment]
It would seem this also applies to some monthly kits such as rune and omen which also should be adressed

**Comment by Chunkkss** [comment]
This has been fixed. 

Thank you for the report.
