### ISSUE TITLE
Some /marry chat is broadcasted across the other two servers

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2089]
**Describe the bug**
When you use /marry chat(toggled or not) with chatlink on, your messages are sent such as in the screenshots. 
Unsure why but it appears to only happen to one of the two married peoples, I assume it is whoever sent /marry (user).

**To Reproduce**
1. Marry someone
2. Type in marry chat saying something random for a test
3. See responses in chat

**Server name (all applicable):**
All servers
![Screenshot_96](https://user-images.githubusercontent.com/67767916/214388833-571d2e1d-d678-4f9e-941c-f9e881a60b23.png)
![Screenshot_97](https://user-images.githubusercontent.com/67767916/214388841-bb17d2f0-1eda-47e3-bd2c-1d8a987d81ad.png)

**Comment by Rasgnarok** [comment]
Closing, fixed for the next restart.
