### ISSUE TITLE
Raid Den activation bug

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2090]
**Describe the bug**
Since the 9.1.1 and 9.1.2 pixelmon updates, raid dens do not activate on their own - unless the den is in claimed land.
Not sure why this would be the case, but after seeing a raid den activate at my claimed base, decided to test in ultra space as well(since thats where most players go for raids now) and confirmed they do spawn in claimed land *only*. 

**To Reproduce**
1. Claim raid den(s), the more the easier to test.
2. Wait or /set time
3. See error
4. Visit Ultra space 
5. Repeat step 2
6. Fly around and see no activated dens

**Servers**
> This applies to all servers
![Screenshot_98](https://user-images.githubusercontent.com/67767916/214404621-e25ba737-0e14-4e51-a797-370e709dd660.png)
![Screenshot_99](https://user-images.githubusercontent.com/67767916/214404633-a1c04431-4dd3-4ddd-98a9-fd924eb665b7.png)

**Comment by Rasgnarok** [comment]
This is related to issue with Pixelmon raid dens and activation, pending next update. We'll have to reevaluate then. I suspect GD is basically resetting and tracking the den activation counter (F3), and therefore preventing them from freezing as is currently the bug.
