### ISSUE TITLE
[Cosmetic] Lion Head Hat and Magikarp Hat have the same model

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2091]
When you win a Lion Head Hat from a Cosmetic Crate, the model that appear is the one from the Lion Head Hat, but when it drops into your inventory, turns into a Magikarp Hat, but with the name of the Lion Head Hat.

**To Reproduce**
1. Win or buy a Cosmetic Crate Key
2. Go to ./warp Crates
3. Use the Cosmetic Crate Key in the Cosmetic Crate
4. Win the Lion Head Hat
5. Check your inventory
6. Now it's a Magikarp Hat

**Expected behavior**
The Lion Head Hat should have the model of the Lion Head Hat, not the model of the Magikarp Hat.

![image](https://user-images.githubusercontent.com/108286828/214478238-9f8090bf-3968-4ee2-aecd-ee66077d48a8.png)

**Comment by KittyKatzyn** [comment]
Fixed!  Thanks for the ticket :) Closing~
