### ISSUE TITLE
[Event Shop] Random Legend Issue

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#2092]
**Describe the bug**
When purchasing "Random Legendary Pokemon" from the event shop, it gave me a rampardos. (was already refunded by Death)

**To Reproduce**
1. Execute /eventsshop
2. Purchase "Random Legendary Pokemon"

**Expected behavior**
To receive a random legend

**Screenshots**
![2023-01-25_15 44 44](https://user-images.githubusercontent.com/37944220/214699700-be2c5fa0-0bb0-48f9-bf15-a09ce8c0a4f6.png)

**Username:** DraconiacLatias

**Server name (all applicable):** Orion

**Comment by KittyKatzyn** [comment]
Fixed!  Thanks for the ticket <3 Closing~
