### ISSUE TITLE
Cross server chatlink no longer works

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2096]
**Describe the bug**
As title says, the cross server chat is no longer working in game. Tested it with Centuron in atlas and me in Orion/titan, no messages were received. Ran /chatlink toggle to see if it was left on, but it was enabled.

**To Reproduce**

1. Go to Any of the 3 servers, and have another test dummy on a different server
2. Try to talk to them
3. See error
![Screenshot_109](https://user-images.githubusercontent.com/67767916/215222915-3fddbb2e-86be-4a89-a0f8-4d0b3553a85a.png)

**Comment by Chunkkss** [comment]
Has been fixed since yesterday. Thanks for the report!
