### ISSUE TITLE
Bulbasaur bug

### ISSUE THREAD

**Issue by Lifeinsurance4533** [ObliqueNetwork/Terra#2098]
On multiple occasions i would see a bulbasaur on the minimap and walk towards it, once i get close it turns into another mon. Just recently one turned into Meowth and another turned into Magikarp.

**Comment by CenizaRey** [comment]
This is a rendering issue. When Pixelmon knows that a space is to be taken up by a pokemon, but it doesn’t yet know what that pokemon is - or that pokemon has yet to be determined, the default fallback is Bulbasaur. It’s the same reason the statue chisel defaults to Bulbasaur when you use it, or when there’s an occasional visual glitch in your party and some mons turn into Bulbasaur briefly. Unfortunately, there’s nothing to be done about it
