### ISSUE TITLE
Form Mod Gui Makes Pokemon Lose HA

### ISSUE THREAD

**Issue by Centuron** [ObliqueNetwork/Terra#2100]
**Describe the bug**
So this bug seems consistent with the Alolan Pokemon at the very least, I've tested it with Sandshrew and Vulpix.
If you have a pokemon that can change form in your party and open up the Form Mod GUI, it makes that Pokemon lose its HA, regardless of if you end up using the mod or not.  I don't think it matters which form of the Pokemon it is, since it was tested on Alolan Sandshrew and Kontonian Vulpix.
When you open up the GUI, it already changes the abilities of the Pokemon in there.
This also does seem to just be Pokemon that can change form, since I also had a HA Pangoro and Beldum, and they retained their HA after looking at the Form Mod GUI

**To Reproduce**

1. Have a Pokemon that can change forms, in your party such as Alolan Sandshrew that has an HA
2. Right click with Form Mod in hand to open GUI
3. Look at Pokemon and see which Pokemon can change forms and their current abilities.
4. Look at the Pokemon, in this case Alolan Sandshrew, and notice that it no longer has HA.
5. Check party out of GUI to confirm changes, and see the Pokemon has indeed lost its HA

**Expected behavior**
To be able to use Form Mod GUI with with Pokemon losing its HA, without using Form Mod

**Screenshots**
![Asand1](https://user-images.githubusercontent.com/113794806/215739349-549a8179-043f-448f-abfb-9da26af1e703.png)
![Asand2](https://user-images.githubusercontent.com/113794806/215739351-f968d561-4a79-44e2-b80c-120ed05d84a9.png)
![Kvul1](https://user-images.githubusercontent.com/113794806/215739353-374db9ba-9e57-41c3-922b-5715b3d36a29.png)
![Kvul2](https://user-images.githubusercontent.com/113794806/215739354-3d01bb12-2dba-4d83-bd43-0020ab2d92f8.png)

**Username:**
Centuron

**Server name (all applicable):**
Titan, unsure of others

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by Deathnight7976** [comment]
This has been fixed on Orion, However remains an issue on both Titan/Atlas

**Comment by chrisdurocher** [comment]
I just had this same issue on Atlas. Chi fixed the mons for me.

**Comment by KittyKatzyn** [comment]
This issue has been fixed with an update to our ModifierTokens mod, which is now live (and will be active after server restarts) on all live servers!

Thank you for the report! Closing.
