### ISSUE TITLE
[Cosmic Crate] 3x cosmetic modifier kit

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2101]
If your inventory is too full to receive all the rewards it will fill your inventory and then doesnt queue the missing reward

1. Open a cosmic key w/ a nearly full inventory (in this circumstance the player had 5 open slots)
2. Win 3x cosmetic modifier kit
3. Check inventory for rewards
4. Empty inventory spaces to allow more to come (they queue properly)

For your inventory to fill as much as possible then for remaining items to end up in queue for when inventory space is made.

Titan, Likely all.

I did not personally encounter this issue, instead it was reported to me by a player who wanted there missing rewards.

**Comment by Rasgnarok** [comment]
Closing, no longer valid.
