### ISSUE TITLE
weight broke ingame v wiki

### ISSUE THREAD

**Issue by koy0561** [ObliqueNetwork/Terra#2102]
![image](https://user-images.githubusercontent.com/111909101/216023161-363a729c-c0ff-412f-a019-e93912d93d27.png)
![image](https://user-images.githubusercontent.com/111909101/216023180-a8114dc3-7f29-4e0a-8312-f227e005655a.png)

**Comment by Oisin-Hearne** [comment]
![image](https://user-images.githubusercontent.com/48627086/216147445-d7d5d441-9ea5-42d6-888e-1e7953e31f92.png)
This has been fixed! Thanks for the report, and good eye on spotting that.
