### ISSUE TITLE
[Store/Nova] /kit Nova gives the incorrect balls

### ISSUE THREAD

**Issue by chefburnt** [ObliqueNetwork/Terra#2103]
**Bug**
Despite having 16x Ultra Balls listed as a /nova kit reward on the store: https://store.nebulamc.gg/category/ranks, you actually receive 16x Poke Balls. 

**Steps to reproduce the behavior:**
1. Have Nova rank as your highest store rank, so you have access to /kit nova.
2. Use /kit nova in-game, see error. 

As it says you get Ultra Balls, you would expect to get Ultra Balls.

**Screenshots**
(Reposted from a user in Support, was unable to get sufficient screenshots of said bug. Apologies.)

![image](https://user-images.githubusercontent.com/123426993/216468955-f8bcbdb5-80da-452a-9b8d-fb519f47d6da.png)

![image](https://user-images.githubusercontent.com/123426993/216470711-b312bfe5-2dfc-4e03-a57b-be8ff7b1cf5c.png)

**Username:** Pond_Pond_ (IGN of user that experienced the problem, from Support on discord.)

**Server**: Issue was on Orion, though could be on Titan/Atlas as well. Was unable to test.

**Comment by CenizaRey** [comment]
Fixed, thanks for the report! Closing
