### ISSUE TITLE
[Inventory Desync] Renamed items

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2104]
When shift clicking items within ones inventory doing so to a renamed item (whether via anvil or /rename) causes it to glitch out and not move visually despite being in the correct slot. While shift clicking non-renamed items works flawlessly. This often results in players storing/trashing/dropping items they believe to be worthless junk but instead be a desync'ed shulker/valuable item.

1. Use an anvil or `/rename` an item in your inventory
2. Shift click it into another inventory space, can be a chest or just another slot of your inventory
3. Compare to a normal un-renamed item

For items to fluidly transfer when using inventory keybinds such as shift click etc.

Deathnight7976

Orion, ALL.

**Comment by Rasgnarok** [comment]
There's not much we can do here, it's packet desync between the client and the server - clients with worse ping will have this happen most often. Best we can do is make sure our server is as performant as possible.
