### ISSUE TITLE
[PokeTracker] Active/Despawned Shiny bug

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#2105]
**Describe the bug**
When catching a shiny that appears on /poketracker it will say it despawned. However sending it back out while it is still on the tracker list it will say (active) again

**To Reproduce**
1. Catch a shiny that is on the tracker
2. Send it back out
3. See that /poketracker has it back as active again

**Expected behavior**
Not having the tracker say the shiny is active.

**Screenshots**
![2023-02-04_12 57 30](https://user-images.githubusercontent.com/37944220/216785080-22e03119-9111-4f2d-9f3c-12a797df4223.png)
![2023-02-04_12 57 44](https://user-images.githubusercontent.com/37944220/216785084-16ef8100-5e6f-4a06-9f47-45e0dab491ba.png)

**Username:** DraconiacLatias

**Server name (all applicable):** Orion

**Comment by KittyKatzyn** [comment]
Forwarded to both our Internal tracker and EnvyWare Discord! Will update here when fixed!

**Comment by KittyKatzyn** [comment]
This should be fixed upon server restart :D
