### ISSUE TITLE
[Sign Shops] Berry Wood signs

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2106]
The sign shop plugin thing does not recognize berry wood signs as signs. It does not allow you to link a container to a berry wood sign to create a sign shop.

1. Make a berry wood sign shop
2. Attempt to link container w/ items to said shop
3. See error

To be able to use all the pretty wood signs as shops much like the vanilla signs.

Orion, All

**Comment by CenizaRey** [comment]
Unfortunately, due to SignShop's use of Enum Materials, we cannot make Pixelmon Signs operational in this regard. Thanks for the report! Closing
