### ISSUE TITLE
Primal Arceus Not Flying

### ISSUE THREAD

**Issue by innqmorato** [ObliqueNetwork/Terra#2109]
Primal Arceus got some problems :
1. Not Flying
2. Turns into normal form when Calamitas Ultimus gets used
3. Calamitas Ultimus doesn't seem to hit bosses
Uploading screen of my Arceus that turned normal from primal form still having Calamitas Ultimus
![image](https://user-images.githubusercontent.com/109287888/218317312-2a1c9933-385a-483f-b037-6c9e8dc95ae2.png)

**Comment by KittyKatzyn** [comment]
This should be fixed by a recent species file update :) Closing!
