### ISSUE TITLE
[StaffChat] An error has occured while running this command.

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2110]
If your connection is interrupted while you have `/sc` toggled on, when you rejoin you will be unable to see staff chat messages as well as unable to toggle `/sc`. Attempting to do so will result in "An error has occured while running this command." in chat.

1. Toggle on staffchat
2. Wait for some shitty java.bullshit dc
![java bs](https://user-images.githubusercontent.com/17133410/218295456-d82bdd2a-35d4-403c-ab6b-0f18f9110796.png)
3. Rejoin server
4. Use '/sc'
![erroroccured](https://user-images.githubusercontent.com/17133410/218295465-c705a61e-55fe-48ff-9b8f-9f68e1477009.png)
5. See error.

Network wide.

After having this occur 20 or so times i finally recognized the pattern of getting dc'ed with `/sc` on and then on relog having broken staffchat. **Relaunching the client does fix this issue until it occurs again.**

**Comment by CptTCovenant** [comment]
**Update:** It does not matter if /sc is toggled, it breaks from the same connection lost error regardless. Happens couple times a week to me.

**Comment by Centuron** [comment]
it happens a bunch to me as well and i do not toggle /sc

**Comment by Rasgnarok** [comment]
Closing, no longer valid.
