### ISSUE TITLE
Zygarde [Bug

### ISSUE THREAD

**Issue by DarkSayian** [ObliqueNetwork/Terra#2111]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Username:**

**Server name (all applicable):**

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by innqmorato** [comment]
needs to be closed as ticketed on discord's #support.

**Comment by CenizaRey** [comment]
It needs to stay open as a support ticket is an individual issue, and Github tickets remind us that the bug exists.

**Comment by Chunkkss** [comment]
Will be testing shrines and confirming if this was a one off, or continuous bug.

**Comment by Rasgnarok** [comment]
Guess we will never know if this was tested, needs retesting (I guess the shrine doesnt work??)

**Comment by WisconsinWinters** [comment]
just tested and spawned both forms fine, closing.
