### ISSUE TITLE
[Bug] Tidal Bell Spawning Lugia at Night Crashes Server (Orion)

### ISSUE THREAD

**Issue by acrandall11** [ObliqueNetwork/Terra#2114]
**Describe the bug**
When Lugia is supposed to be spawned at night from the Tidal Bell the entire server crashes.

**To Reproduce**
1. Place Tidal bell on bottom of tile. (Tile was a claimed tile in seen bug)
2. Wait or Activate Tidal Bell at Sunrise.
3. Wait for Night when Lugia should spawn.
4. Server Crashes.
This was specifically Orion.

**Expected behavior**

**Screenshots**

**Username:**

**Server name (all applicable):**

**Logs:**
[gistfile1.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/10742428/gistfile1.txt)

**Additional context**
This was Orion.  This was next on a Claimed Block.  This repeated at least 3 times before I tried in Single Player mode and could not replicate at the behest of Katzyn.

**Comment by acrandall11** [comment]
I can't even mine the bell to stop it.

**Comment by KittyKatzyn** [comment]
Since time has passed and we haven't been able to reproduce this issue, I think it's safe to say it was a weird one-off bug?  Gonna close for now :)
