### ISSUE TITLE
Battling Orthworms Bugs Out

### ISSUE THREAD

**Issue by Centuron** [ObliqueNetwork/Terra#2115]
**Describe the bug**
When you enter battle with Orthworm, sometimes you cannot attack, nor throw balls.  After 3 attempts or so, you get booted from battle.

**To Reproduce**
1. Enter battle with wild Orthworm
2. Attempt to make an attack or throw a ball, does not work
3. After 2-3 attempts, get kicked from battle

**Expected behavior**
I would expect to be able to battle or catch the Orthworm without getting kicked from battle

**Screenshots**
![2023-02-15_09 22 33](https://user-images.githubusercontent.com/113794806/219055792-0f1f50dc-526f-4148-95c4-57aa410d309d.png)

Centuron

Titan, am also hearing reports from both other servers

**Logs:**
Pixelmon Version 9.1.3
Battle data 2023-02-15T08:46:25.738879Z

Team #0 Player Kryla
	{EVSpeed:135s,StatsDefense:162s,IVAttack:31b,Growth:3b,Moveset:[{MoveID:"Dazzling Gleam",MovePP:15b,MovePPLevel:3b},{MoveID:"Psybeam",MovePP:32b,MovePPLevel:3b},{MoveID:"Draining Kiss",MovePP:16b,MovePPLevel:3b},{MoveID:"Psychic",MovePP:16b,MovePPLevel:3b}],PersistentData:{},Gender:1b,ribbon_display2:{receiver:'{"text":""}',received:1673986713319L,type:"destiny"},originalTrainerUUID:[I;-1412471660,1964068474,-1517073477,614621733],GigantamaxFactor:0b,Friendship:255s,eggCycles:-1,EVAttack:213s,StatsSpecialAttack:301s,IVSpDef:31b,CaughtBall:"premier_ball",IVHP:31b,EVHP:38s,ndex:282,palette:"shiny",UUID:[I;685562419,696928943,-1173154239,750486302],StatsSpecialDefense:267s,Nickname:"Lady G",Nature:14b,Ability:"Trace",StatsHP:286s,IVDefense:31b,Health:286,HeldItemStack:{id:"pixelmon:gardevoirite",Count:1b},originalTrainer:"AdmiralCrunch",SpecFlags:["unbreedable"],DoesLevel:1b,EVDefense:58s,DynamaxLevel:10,Variant:"",StatsSpeed:251s,EVSpecialAttack:62s,StatsAttack:219s,IVSpeed:31b,Level:100,IVSpAtt:31b,NBT_VERSION:2b,EVSpecialDefense:4s,EXP:607,RelrnMoves:[],ribbons2:[{receiver:'{"text":""}',received:1673986713319L,type:"destiny"}]}
	{MoveSkillCooldown:[{MoveSkillCooldownCurrent:1676231011078L,MoveSkillCooldownTarget:1676231036078L,MoveSkillCooldownId:"forage"}],EVSpeed:166s,StatsDefense:176s,IVAttack:0b,Growth:2b,Moveset:[{MoveID:"Close Combat",MovePP:8b,MovePPLevel:3b},{MoveID:"False Swipe",MovePP:63b,MovePPLevel:3b},{MoveID:"Slash",MovePP:20b},{MoveID:"Psycho Cut",MovePP:24b,MovePPLevel:1b}],PersistentData:{},Gender:0b,originalTrainerUUID:[I;-1211768855,1609253614,-1598754607,256404931],GigantamaxFactor:0b,Friendship:250s,eggCycles:-1,EVAttack:98s,StatsSpecialAttack:176s,IVSpDef:21b,CaughtBall:"poke_ball",IVHP:10b,EVHP:38s,ndex:475,palette:"shiny",UUID:[I;2011224367,924336630,-1971533654,-2052205264],StatsSpecialDefense:237s,Nature:8b,Ability:"Steadfast",StatsHP:265s,IVDefense:14b,Health:265,HeldItemStack:{id:"pixelmon:leftovers",Count:1b},originalTrainer:"Ceniza_",SpecFlags:[],DoesLevel:1b,EVDefense:109s,DynamaxLevel:0,Variant:"",StatsSpeed:230s,EVSpecialAttack:66s,StatsAttack:306s,IVSpeed:24b,Level:100,IVSpAtt:25b,NBT_VERSION:2b,EVSpecialDefense:33s,EXP:569,RelrnMoves:[],ribbons2:[]}
	{MoveSkillCooldown:[{MoveSkillCooldownCurrent:1669135870852L,MoveSkillCooldownTarget:1669135895852L,MoveSkillCooldownId:"forage"}],EVSpeed:91s,StatsDefense:213s,IVAttack:24b,Growth:4b,Moveset:[{MoveID:"Outrage",MovePP:16b,MovePPLevel:3b},{MoveID:"Hyper Voice",MovePP:10b},{MoveID:"Dragon Ascent",MovePP:8b,MovePPLevel:3b},{MoveID:"Hurricane",MovePP:12b,MovePPLevel:1b}],PersistentData:{},Gender:2b,originalTrainerUUID:[I;-1747669859,-1269741032,-1345315310,1262789900],GigantamaxFactor:0b,Friendship:249s,eggCycles:-1,EVAttack:139s,StatsSpecialAttack:355s,IVSpDef:31b,CaughtBall:"master_ball",IVHP:31b,EVHP:61s,ndex:384,palette:"shiny",UUID:[I;-1548857115,1516129045,-1824063532,-1983157165],StatsSpecialDefense:230s,Nature:14b,Ability:"AirLock",StatsHP:366s,IVDefense:31b,Health:366,HeldItemStack:{id:"pixelmon:leftovers",Count:1b},originalTrainer:"Kryla",SpecFlags:["unbreedable"],DoesLevel:1b,EVDefense:85s,DynamaxLevel:10,Variant:"",StatsSpeed:250s,EVSpecialAttack:76s,StatsAttack:363s,IVSpeed:11b,Level:100,IVSpAtt:31b,NBT_VERSION:2b,EVSpecialDefense:58s,EXP:356,RelrnMoves:[],ribbons2:[]}
	{MoveSkillCooldown:[{MoveSkillCooldownCurrent:1672386948077L,MoveSkillCooldownTarget:1672387848077L,MoveSkillCooldownId:"open_wormhole"},{MoveSkillCooldownCurrent:1669135884953L,MoveSkillCooldownTarget:1669135909953L,MoveSkillCooldownId:"forage"}],EVSpeed:86s,StatsDefense:276s,IVAttack:31b,Growth:3b,Moveset:[{MoveID:"Earth Power",MovePP:10b},{MoveID:"Hyper Beam",MovePP:6b,MovePPLevel:1b},{MoveID:"Judgment",MovePP:16b,MovePPLevel:3b},{MoveID:"Future Sight",MovePP:10b}],PersistentData:{},Gender:2b,originalTrainerUUID:[I;-1747669859,-1269741032,-1345315310,1262789900],GigantamaxFactor:0b,Friendship:153s,eggCycles:-1,EVAttack:59s,StatsSpecialAttack:274s,IVSpDef:0b,CaughtBall:"master_ball",IVHP:31b,EVHP:72s,ndex:493,palette:"none",UUID:[I;-1533950480,1581010420,-2116381021,812173873],StatsSpecialDefense:266s,Nickname:"Bontoose",Nature:14b,Ability:"Multitype",StatsHP:399s,IVDefense:31b,Health:399,HeldItemStack:{id:"pixelmon:spooky_plate",Count:1b},originalTrainer:"Kryla",SpecFlags:[],DoesLevel:1b,EVDefense:126s,DynamaxLevel:10,Variant:"ghost",StatsSpeed:325s,EVSpecialAttack:82s,StatsAttack:290s,IVSpeed:30b,Level:100,IVSpAtt:9b,NBT_VERSION:2b,EVSpecialDefense:85s,EXP:0,RelrnMoves:[],ribbons2:[]}
	{MoveSkillCooldown:[{MoveSkillCooldownCurrent:1673696306911L,MoveSkillCooldownTarget:1673697206911L,MoveSkillCooldownId:"open_wormhole"}],EVSpeed:85s,StatsDefense:267s,IVAttack:6b,Growth:2b,Moveset:[{MoveID:"Prismatic Laser",MovePP:10b,MovePPLevel:3b},{MoveID:"Confusion",MovePP:23b},{MoveID:"Photon Geyser",MovePP:8b,MovePPLevel:3b},{MoveID:"Power Gem",MovePP:31b,MovePPLevel:3b}],PersistentData:{},Gender:2b,ribbon_display2:{receiver:'{"text":""}',received:1673986713329L,type:"lunchtime"},originalTrainerUUID:[I;-409134158,916866775,-1477846960,1693142217],GigantamaxFactor:0b,Friendship:254s,eggCycles:-1,EVAttack:147s,StatsSpecialAttack:285s,IVSpDef:18b,CaughtBall:"park_ball",IVHP:22b,EVHP:17s,ndex:800,palette:"shiny",UUID:[I;-187912768,-186236395,-1437240112,358894843],StatsSpecialDefense:209s,Nature:7b,Ability:"PrismArmor",StatsHP:330s,IVDefense:31b,Health:330,HeldItemStack:{id:"pixelmon:leftovers",Count:1b},originalTrainer:"Liam__",SpecFlags:[],DoesLevel:1b,EVDefense:118s,DynamaxLevel:10,Variant:"",StatsSpeed:215s,EVSpecialAttack:109s,StatsAttack:287s,IVSpeed:31b,Level:100,IVSpAtt:31b,NBT_VERSION:2b,EVSpecialDefense:34s,EXP:895,RelrnMoves:[],ribbons2:[{receiver:'{"text":""}',received:1673986713329L,type:"lunchtime"}]}
	{MoveSkillCooldown:[{MoveSkillCooldownCurrent:1657917759785L,MoveSkillCooldownTarget:1657917784785L,MoveSkillCooldownId:"forage"}],EVSpeed:87s,StatsDefense:203s,IVAttack:23b,Growth:6b,Moveset:[{MoveID:"Wood Hammer",MovePP:24b,MovePPLevel:3b},{MoveID:"Play Rough",MovePP:16b,MovePPLevel:3b},{MoveID:"Shadow Claw",MovePP:15b},{MoveID:"Charm",MovePP:20b}],PersistentData:{},Gender:0b,originalTrainerUUID:[I;-1747669859,-1269741032,-1345315310,1262789900],GigantamaxFactor:0b,Friendship:105s,eggCycles:-1,EVAttack:141s,StatsSpecialAttack:127s,IVSpDef:7b,CaughtBall:"great_ball",IVHP:22b,EVHP:36s,ndex:778,palette:"shiny",UUID:[I;-6952962,197346892,-1377730248,778976548],StatsSpecialDefense:231s,Nickname:"MiMi",Nature:14b,Ability:"Disguise",StatsHP:251s,IVDefense:27b,Health:251,HeldItemStack:{id:"pixelmon:mimikium_z",Count:1b},originalTrainer:"Kryla",SpecFlags:[],DoesLevel:1b,EVDefense:137s,DynamaxLevel:10,Variant:"disguised",StatsSpeed:272s,EVSpecialAttack:70s,StatsAttack:243s,IVSpeed:30b,Level:100,IVSpAtt:5b,NBT_VERSION:2b,EVSpecialDefense:39s,EXP:20,RelrnMoves:[],ribbons2:[]}
Team #1 WildPokemon Orthworm
	{EVSpeed:0s,StatsDefense:182s,IVAttack:19b,Growth:5b,Moveset:[{MoveID:"Iron Defense",MovePP:15b},{MoveID:"Iron Tail",MovePP:15b},{MoveID:"Earthquake",MovePP:10b},{MoveID:"Shed Tail",MovePP:10b}],PersistentData:{},Gender:0b,GigantamaxFactor:0b,Friendship:50s,eggCycles:-1,EVAttack:0s,StatsSpecialAttack:80s,IVSpDef:28b,CaughtBall:"poke_ball",IVHP:27b,EVHP:0s,ndex:968,palette:"none",UUID:[I;1945373495,689655450,-1589100531,-714520295],StatsSpecialDefense:72s,Nature:12b,Ability:"EarthEater",StatsHP:156s,IVDefense:3b,Health:156,SpecFlags:[],DoesLevel:1b,EVDefense:0s,DynamaxLevel:0,Variant:"",StatsSpeed:87s,EVSpecialAttack:0s,StatsAttack:108s,IVSpeed:20b,Level:55,IVSpAtt:17b,NBT_VERSION:2b,EVSpecialDefense:0s,EXP:0,RelrnMoves:[],ribbons2:[]}

Turn #0
Caught error in battle. Continuing...
null
com.pixelmonmod.pixelmon.battles.attacks.Attack.doesPersist(Attack.java:1312)
com.pixelmonmod.pixelmon.battles.controller.participants.PixelmonWrapper.selectAIAction(PixelmonWrapper.java:639)
com.pixelmonmod.pixelmon.battles.controller.participants.BattleParticipant.selectAction(BattleParticipant.java:314)
com.pixelmonmod.pixelmon.battles.controller.BattleController.update(BattleController.java:453)
com.pixelmonmod.pixelmon.battles.BattleRegistry.updateBattles(BattleRegistry.java:248)
com.pixelmonmod.pixelmon.battles.BattleTickHandler.tickStart(BattleTickHandler.java:13)
net.minecraftforge.eventbus.ASMEventHandler_260_BattleTickHandler_tickStart_WorldTickEvent.invoke(.dynamic)
net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:86)
net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:857)
net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291)
net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787)
net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917)
net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
java.base/java.lang.Thread.run(Thread.java:829)

**Additional context**
The logs above were the ones that Katz asked for me to add in.

This is also not a consistent bug either, because it only happens about 50% of the time, while i was testing it.

People have also been saying that this is more common when encountering females, but I think that's because females seem to be spawning more, it is happening with both genders.

You can catch them outside of battle with out issues.

It also seems to only happen with wild ones, since I caught one of the ones that was kicking me from battle and battled someone with it, encountering no issues.

There are no issues in single player.

I think another issue that may be a Pixelmon bug, is that none of them seem to be dropping any loot.

**Comment by KittyKatzyn** [comment]
Confirmed to be a Pixelmon bug, and should be fixed for next update!
