### ISSUE TITLE
[Voteparty] Fails to disperse key

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2117]
Vote party hit on Orion and no keys were given out to any player.

1. Vote via `/vote`
2. hit the `/vp` Goal
3. Get no keys

for all players who voted and are online to get a key. (limited keys rn, solar during normal ""seasons"")

Orion

A discord support ticket was made showing all users who were online during the voteparty.

**Comment by KittyKatzyn** [comment]
A fix for this has been tested on beta, and pushed to the live servers!  Config was reloaded on all servers, so it should be good to go!  Thanks Death!
