### ISSUE TITLE
[Resourcepack] Tripwire hooks

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2119]
Default tripwire hooks are missing a texture.

1. Use servers custom resourcepack
2. Get `minecraft:tripwire_hook`
3. See error

For regular tripwire hooks to have textures.

![Tripwirehook](https://user-images.githubusercontent.com/17133410/219515750-4acb8216-414c-47d5-8b0f-73390e4094ce.png)

Pretty sure this has something to do with new keys being tripwire hooks.

**Comment by KittyKatzyn** [comment]
Forwarded! Will update here when fixed!

**Comment by WisconsinWinters** [comment]
fixed with newer respacks
