### ISSUE TITLE
Whismur Spawner at Kuan-Ti Missing

### ISSUE THREAD

**Issue by Centuron** [ObliqueNetwork/Terra#2120]
**Describe the bug**
A player went to Kuan-Ti to hunt for Whismur and went to the spawner listed at the location in the github.
Upon arrival there were no whismurs.  I went and checked in spectator mode and there was no spawner visable, not indicator showing there was one like other spawners such as Natu and Zangoose.

**To Reproduce**
1. Go to Whismur spawner in Kuan-Ti 
2. No Whismurs spawn

**Expected behavior**
I expect Whismurs to spawn at the location listed on the github

**Screenshots**
![2023-02-16_20 36 01](https://user-images.githubusercontent.com/113794806/219531756-e2c2cee6-111b-4cb9-9eaf-767e8e7bcd9d.png)
![2023-02-16_20 36 04](https://user-images.githubusercontent.com/113794806/219531757-86510e67-d7ce-4df0-8b1f-b63446a444dd.png)

Centuron

All 3 Servers

**Comment by CenizaRey** [comment]
Fixed, thanks for the report! Closing
