### ISSUE TITLE
[Battle towers] Statuses not healing between tower floors

### ISSUE THREAD

**Issue by CLAAAAY** [ObliqueNetwork/Terra#2121]
**Describe the bug**
Battling in the battle tower, got hit by toxic from the enemy bronzong into my slowbro on the first fight. On the second fight, my slowbro was still poisoned upon switching in, even though the HP and PP were healed
**To Reproduce**
Slowbro got toxiced by bronzong in the battle tower and did not get healed of the status between the first and second fight. It did get healed of HP and PP though.

**Expected behavior**
Expected to be fully healed between fights.

**Username:**
claaaay#9171
**Server name (all applicable):**
claaaay (this happened on Titan)

**Additional context**
Could just be an issue with status specific, could be an issue with the regenerator ability, I was healed of HP and PP between fights but not the toxic.

**Comment by lankyboy01** [comment]
Forwarding this to the dev, thanks for the report!

**Comment by Rasgnarok** [comment]
Was this fixed?

**Comment by WisconsinWinters** [comment]
works, tested with toxic orb and was fully healed.
