### ISSUE TITLE
Kicked from Battle Tower

### ISSUE THREAD

**Issue by chrisdurocher** [ObliqueNetwork/Terra#2122]
**Describe the bug**
After defeating the second trainer in battle tower, I was given prize of 5k and kicked from battle tower. Could not challenge again due to cooldown. (roughly 5pm EST)

**To Reproduce**
1. Challenge Battle Tower
2. Defeat second trainer
3. Did not advance me to next trainer

**Expected behavior**
Should have moved me on to challenge the third trainer

MrH0li0 on Atlas

**Additional context**

**Comment by chrisdurocher** [comment]
Attempted again and this time got kicked after defeating the third trainer.

**Comment by Khrisstias** [comment]
Do you recall the team of the third trainer?

**Comment by Rasgnarok** [comment]
This should now be fixed, thank you for the report!

**Comment by chrisdurocher** [comment]
I just tried again and got kicked after defeating the second trainer again.
Right around 8:00pm EST on atlas.

Was a Dark type team with an Umbreon that had dig but thats for a separate ticket lololol jkjk
