### ISSUE TITLE
Mega Evolution not working in battle tower

### ISSUE THREAD

**Issue by chrisdurocher** [ObliqueNetwork/Terra#2124]
**Describe the bug**
When in battle against a trainer in the battle tower, selecting mega evolution on mawile then selecting the move results in the pokemon using the move but not mega evolving. The following turn, mega evolution is once again able to be selected, but will not result in mega evolution occuring.

**To Reproduce**
1. while in battle, select mega evolution and choose move
2. pokemon uses move but does not mega evolve

**Expected behavior**
pokemon should mega evolve before using the selected move

MrH0li0 on Atlas

**Additional context**

**Comment by WisconsinWinters** [comment]
fixed
