### ISSUE TITLE
/warp Elite4 missing from Titan

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2126]
**Describe the bug**
Someone on Titan brought up that /warp Elite4 was not a thing, meanwhile it works on Atlas and Orion

**To Reproduce**
Go to Titan
Try to warp to Elite4
See error
Go to Orion/Atlas
Repeat

**Comment by KittyKatzyn** [comment]
Forwarded to Internal!  Will update here when fixed!

**Comment by CenizaRey** [comment]
Fixed, thanks for the report! Closing
