### ISSUE TITLE
Battle Tower [MegaThread]

### ISSUE THREAD

**Issue by Chunkkss** [ObliqueNetwork/Terra#2127]
Please describe all your issues with battle tower here, so we can go through all of them and have any issues fixed. 

Thank you.

**Comment by Dovukin** [comment]
A player on atlas (Siphen21) used zygarde which caused a battle error and tped them improperly , sent to a random arena and broke out as it isnt claimed , further testing needed to see if zygarde causes the error in the other servers . I believe the zygarde battle error might be a pixelmon issue but perhaps the arenas could be claimed just in case

**Comment by chrisdurocher** [comment]
MrH0li0
Atlas

I beat the first trainer and just got stuck in the battle tower.

Also the custom forms and megas all need to be fixed on the pastes. Their nicknames state what they should be but the pokemon themselves are incorrect.

**Comment by AftonsHell** [comment]
I can’t Mega evolve and sometimes my mons just randomly die for no reason

**Comment by Rasgnarok** [comment]
Invalid teams were fixed on the 27th of Feb at 1PM EST, please make a new thread for any new issues.
