### ISSUE TITLE
[Missing Permission Node] /thru - Atlas

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2129]
Executives are missing the permission node required to use `/thru` on Atlas and only atlas.

1. Be an Executive
2. Try to `/thru`
3. See error
![Permnode](https://user-images.githubusercontent.com/17133410/221291844-00ab0797-0f98-4afa-8735-fca2198a60dd.png)

For executives to have access to the command, both TMods and Mods have access but its missing for Executives.

Atlas

**Comment by Deathnight7976** [comment]
Solved.

**Comment by MissElyri** [comment]
This has been fixed on Atlas and most recently Titan; Orion was fine. Closing. :)
