### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by TheAzureKnight7** [ObliqueNetwork/Terra#2130]
I delevelled my Hisuian Decidueye from 37 to 27 and used candies to get it to 30 so it would learn bulk up but instead it learned aura sphere.

**To Reproduce**
1. Get Hisuian Decidueye
2. Delevel it below 30
3. Use rare candies to get level 30
4. Decidueye will learn aura sphere and not bulk up

**Expected behavior**
Hisuian Decidueye is meant to learn bulk up at level 30, not aura sphere. You can find this info on both the pixelmon wiki and the game itself.

**Screenshots**
Do not have

**Username:**
TheAzureKnight
**Server name (all applicable):**
Titan - NebulaMC
**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**
I have been unable to teach Decidueye bulk up via tms, via levelling, and there is no move tutor and it's really annoying considering in solo worlds it learns bulk up just fine but specifically on this server it seems unable to learn the move. I think this may be a bug with bulk up in general but Im just some 16 year old so Im prolly wrong.

**Comment by KittyKatzyn** [comment]
The base issue was fixed, and the de-leveler refunded!  Sorry for all the confusion, it was a very odd issue, but everything should be good now!  Thank you for your patience!

Closing!
