### ISSUE TITLE
Discord's #network-chat only appears on titan

### ISSUE THREAD

**Issue by Dovukin** [ObliqueNetwork/Terra#2131]
**Describe the bug**
The link between the discord #network-chat only shows messages of the discord to titan and not orion and atlas

**To Reproduce**
1. Go to either orion or atlas
2. Send a message in the #network-chat
3. See the error

**Expected behavior**
#network-chat messages from the discord should appear on all servers

**Screenshots**
![Screenshot (47)](https://user-images.githubusercontent.com/122803986/221952347-ce372779-bbab-4d1d-bdb8-72253309ca80.png)
![2023-02-28_20 54 59](https://user-images.githubusercontent.com/122803986/221952385-72830435-390c-4448-811a-1967655fe501.png)

**Username:**
Dovukin
**Server name (all applicable):**
Orion and Atlas

**Comment by KittyKatzyn** [comment]
Forwarded to the Internal tracker!  Will update here when fixed!

**Comment by Rasgnarok** [comment]
Fixed ages ago, forgot to close.
