### ISSUE TITLE
[Battle Tower] Unable to progress

### ISSUE THREAD

**Issue by chrisdurocher** [ObliqueNetwork/Terra#2132]
After defeating the first trainer, the battle ends, no reward is given and instead of progressing to the next trainer I just end up inside the battle tower.

MrH0li0, Atlas, 10:54pm

**To Reproduce**
1. Challenge battle tower
2. defeat first trainer
3. see error

**Expected behavior**
I imagine it's meant to automatically challenge the next trainer until all are beaten.

**Comment by lankyboy01** [comment]
This error should now be fixed. If the error pertains, feel free to open another ticket. Thanks for the report!
