### ISSUE TITLE
Lost my shulker box containing all my poke balls

### ISSUE THREAD

**Issue by ZackPowers07** [ObliqueNetwork/Terra#2135]
IGN: Zack_Powers_07 Server: Titan
I used the /back command when I was inside a gym but it put me back at my spawn bed but my friend TheAzureKnight saw my shulker box on the ground where I was last standing before I tped to gym but when he picked it up, it disappeared and now I lost all of my pokeballs. Unfortunately, Me nor my friend did not have medal on so I do not have any video proof to show but I'm hoping there is some kind of log or way to check my inventory in the past. If this is not refundable/restorable I understand since I did not have any clipping application on so there is no way to prove this event ever happened. If there is more info that I need to share the fastest way to get my attention is to ping/dm my Zack Powers 07#7312

**Comment by Chunkkss** [comment]
Resolved.
