### ISSUE TITLE
while trading for new clue scrolls, if a pokemon evolves it bugs out into a screen you cannot clear

### ISSUE THREAD

**Issue by koy0561** [ObliqueNetwork/Terra#2139]
![2023-03-10_18 21 21](https://user-images.githubusercontent.com/111909101/224452798-4c9de5f6-e2ea-4d0a-8d83-b10a35c783c7.png)

**Comment by Rasgnarok** [comment]
Forwarded, thank you

**Comment by Rasgnarok** [comment]
Fixed
