### ISSUE TITLE
[Scrolls] Use move 200 times.

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2140]
When using a move to complete a scroll instead of counting 1 move use as 1 it counts as 3.

Upon further testing it appears its counting turns recharging as turns in which you used the move, as well as an additional +1 the first time you use the move in combat.

1. Get a legendary `/scroll` (Use Hyper Beam 200 times)'
2. Grab yourself a mon with Hyperbeam (In my case its a dragonite with hyperbeam in moveslot 4)
3. Attack pokemon with hyperbeam (Aggron) 
4. Check scroll
5. See error
![Legendary scroll](https://user-images.githubusercontent.com/17133410/224470978-02985b36-be2a-45ab-b43c-a1b3f7a36b6e.png)

For the scroll to increment by the amount of times a move is used and not 3x that.

Orion, likely all.

Additional notes is it does not count when using the move on a mon the move doesn't effect despite you having used the move, Which probably makes sense balance wise as it prevents cheese however I believe this should likely be more transparent within the scroll. (Using hyperbeam on a haunter for example.)

**Comment by chefburne** [comment]
No longer an issue, closing
