### ISSUE TITLE
[ClueScroll] Using splash doesnt count towards splash task

### ISSUE THREAD

**Issue by Dovukin** [ObliqueNetwork/Terra#2142]
**Describe the bug**
The last task of a common scroll was to use splash 3 times but no matter how much i used it , it never counter assumedly cus splash doesnt deal any damage

**To Reproduce**
1. get a common scroll
2. get the task to use splash
3. use splash
4. see issue

**Expected behavior**
using splash should count towards the scroll

**Username:**
Dovukin
**Server name (all applicable):**
Orion

**Comment by CenizaRey** [comment]
This is a known issue, and our dev is working on a fix now! Will update here with news

**Comment by Rasgnarok** [comment]
Closed, ticket is no longer in effect.
