### ISSUE TITLE
Legendary Pokemon Dex by Trading

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2144]
**Describe the bug**
Unknown why, Legendary Pokemon seem to be giving dex when not your OT. Tested on Orion and Atlas.

**To Reproduce**
1. Join Orion
2. Get /pokegift'd a Legend you do not have in your Dex e.i Darkrai
3. Check PokeDex

![Screenshot_74](https://user-images.githubusercontent.com/67767916/224521334-d8d10ae3-8de6-4e01-86e9-690efe300f47.png)
![Screenshot_75](https://user-images.githubusercontent.com/67767916/224521336-fabc5025-41ff-4b1f-805a-e76cdf832d33.png)

**Comment by Rasgnarok** [comment]
Fixed as of the new reset
