### ISSUE TITLE
Ras's Cryogonal does not spawn.

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2145]
I can't be detailed about the bug, because i can't know what it ss affecting the cryogonal to spawn, but seems is not doing it. Some players on Atlas (and other from other servers) after talk about it, we ended up thinking this pokemon is not spawning properly. Most of us we've been trying to hunt it since yesterday, wasting a lot of hours waiting for a rain/storm, that happen every 3 hours if im not wrong, using strong ice lure and resetting the are the whole 30mins to maximize the changes to spawn it. 

In other hand, the other ultra rare ras's palettes were easier to get, so we are stucked in the limited scroll for the cryogonal, that does not spawn in any case. 

I got a confirmation by Cen that they does not have the same rarity of UB (0.1), i don't know which exact number of rarity, but even having 0.5 (ditto's rarity), 1.0 or like the starters (5.0 or 10.0), would be easier to get using strong lures. Would take u time, but not like this knowing different players are hunting at the same time with the same luck, at least few of them should have it at this point.

**To Reproduce**
1. Go to a Ice Spike biome.
2. Wait till it start to rain or storm
3. Equip a strong ice lure to increase the spawn chances
4. Reset the area as max as u can, checking the area between resets to don't miss anything till the rain/storm stop
5. Any Ras's cryogonal spawned. 
6. Repeated it every storm/rain. Same result

As far as I know this happen in Atlas and Orion, no one of Titan confirmed it, but if it's happen in two servers, it's probably the same for the third one.

**Comment by CenizaRey** [comment]
Others have had this pokemon spawn on them, there are no issues with its spawning. Thanks for the report! Closing
