### ISSUE TITLE
scroll bug

### ISSUE THREAD

**Issue by Kryla** [ObliqueNetwork/Terra#2147]
ign Kryla
server Titan

I was trying to do a legendary scroll and my task was ''capture 1 dialga'' , i got  a red chain and the adamant orb and paid to spawn. i caught it, but the scroll was stuck on capture 1 dialga and didnt count. 
another scroll had a ras' sylveon , same thing happened, didnt count when i caught it.

At this moment when i write it is solved. seems the another scroll was bugging it, the one with capturing pokemons.

[2023-03-11-2.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/10951304/2023-03-11-2.log)
[2023-03-12-1.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/10951305/2023-03-12-1.log)

**Comment by KittyKatzyn** [comment]
Thanks for the update, will close this now :)
