### ISSUE TITLE
Global boosters arent global 

### ISSUE THREAD

**Issue by Dovukin** [ObliqueNetwork/Terra#2148]
**Describe the bug**
The global boosters (at least the exp boost from battles) isnt global and only applies to the user

**To Reproduce**
1. Get a global exp booster from scrolls or however
2.Activate it 
3.Kill a mon in a spawner to see how much exp you get
4. Have another person do the same
5. See error

**Expected behavior**
The booster should activate for all players online in your server

**Screenshots**

**Username:**
Dovukin
**Server name (all applicable):**
Orion

**Comment by Deathnight7976** [comment]
After testing it appears the booster is infact global however due to only being a 1.25x exp multiplier is easy to miss.
