### ISSUE TITLE
No shiny from uncommon scroll

### ISSUE THREAD

**Issue by Dovukin** [ObliqueNetwork/Terra#2149]
**Describe the bug**
One of the rewards for the uncommon scroll is a random shiny mon , yet if its a mon with multiple colours like vivilion or flobebe itll only come as non shiny

**To Reproduce**
1. Complete a shiny scroll and get the shiny random mon
2. Get one such mon
3. See issue

**Expected behavior**
The mons should be shiny 

**Username:**
Dovukin
**Server name (all applicable):**
Orion

**Comment by chefburne** [comment]
This is no longer an issue, closing
