### ISSUE TITLE
Cant receive the 60m battle exp booster

### ISSUE THREAD

**Issue by Dovukin** [ObliqueNetwork/Terra#2151]
**Describe the bug**
Upon completing the rare scroll one of the rewards is a 60m battle exp mod which you cant get , ive lost 6 to this now along with another player who has experienced this too on atlas

**To Reproduce**
1.Complete a rare scroll
2.Get the 60m battle exp booster reward
3.Claim it 
4. See issue

**Expected behavior**
Should get the 60m battle exp boost

**Screenshots**
![2023-03-14_01 11 29](https://user-images.githubusercontent.com/122803986/225024639-bdc64cf3-4819-4846-b4b3-82979c86125f.png)
![2023-03-14_01 11 31](https://user-images.githubusercontent.com/122803986/225024668-76f21158-c0b9-428e-954b-37264ed36cdf.png)

**Username:**
Dovukin
**Server name (all applicable):**
Orion,Atlas

**Additional context**
The other player was Ezel on atlas

**Comment by Deathnight7976** [comment]
This has been fixed.
