### ISSUE TITLE
[Autumnal Gardevoir] Some special palettes 

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2153]
Currently there exists special palettes of a Autumnal Gardevoir obtainable via pallete mod on an autumnal formed gardevior. They are very buggy and broken looking.

1. Give yourself 2 Autumnal Gardevoirs `/pokegive <user> Gardevior form:Autumnal`
2. Give yourself 2 Palette mods `/modifiertokens grant Deathnight7976 palette 2 true`
3. Use both palette mods and swap each gardevoirs pallete to both strike and valentine
4. Send out said gardevoirs
5. See error
![2023-03-14_15 45 11](https://user-images.githubusercontent.com/17133410/225133191-3aef970a-2d9e-4a5a-af4c-d3c73f1f2274.png)

For these broken textured gardevoirs to be unobtainable

**Comment by CenizaRey** [comment]
This is because the Autumnal Gardevoir has an entirely separate model, and is therefore incompatible with the base model's palettes. It is disabled for the average player for this exact reason. Thanks for the report! Closing
