### ISSUE TITLE
[ClueScrolls] "Vanhite" Solrock - Hatch x Vanhite forms

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2154]
The epic clue scroll has the task "Hatch 5 Vanhite Form Pokemon" which requires you to hatch vanhite form pokemon, Despite solrock being listed as "Vanhite form" when hovering over it in your party it does not count towards this task. I believe this is due to the fact that its form is actually `"Pixelmon.solrock.form.supernova"`. 

1. Get a epic scroll with the task "Hatch 5 Vanhite Form Pokemon" via `/scrolls`
2. Get one Vanhite/Supernova solrock `/pokegive <player> Solrock form:supernova`
3. Get one Ditto `/pokegive <player> ditto`
4. Give yourself 1 everstone and place it on the solrock `/give <player>  pixelmon:ever_stone`
5. Give yourself 1 Golden Hourglass `/give <player> pixelmon:gold_hourglass`
6. Use `/rdc` or open daycare block
7. Place both the solrock and ditto into the same box
8. Drag golden hourglass onto box
9. Collect egg
10. Hatch egg via running around with the mon in your party
11. Check scroll
12. See error

For either Vanhite solrock not to be listed as vanhite form or qualify for the hatch x vanhite forms task

![solrockformchoice](https://user-images.githubusercontent.com/17133410/225490475-6d93d417-f3fd-4692-82f0-74e80c063b67.png)
![Solrockparty](https://user-images.githubusercontent.com/17133410/225490494-83b04a85-9d3d-45e5-a9ea-2af8650aeb15.png)

Network wide

**Comment by WisconsinWinters** [comment]
closing with scrolls port to new system
