### ISSUE TITLE
Negative Claim Blocks

### ISSUE THREAD

**Issue by Wetstew** [ObliqueNetwork/Terra#2155]
I brought it up on [Discord](https://discord.com/channels/151095626916954113/1083225006026260581) a week ago and I got reimbursed.

I'm not sure exactly what caused this.  I got my last dex reward a week before and didn't notice my claim block count being affected.

Within the past couple weeks before I noticed this I trimmed down my /claimlist and labeled what I kept in order to claim a large berry farm I dug out.  I did use the command to restrict Pokemon spawn within the berry farm.

I've noticed off and on while digging with my chat would occasionally (once a week or so) be spammed with something along the lines of "this claimed area is too small", but I never noticed my claim block count being affected by this.

I was using an efficiency 4 Diamond Shovel while under Haste 2, so maybe the speed I was digging while getting that error caused something to calculate wrong?  I didn't notice the problem until the day I posted the support ticket.

**Comment by Deathnight7976** [comment]
Resolved.
