### ISSUE TITLE
Random ultra beast and Legendary rewards from scrolls being bugged

### ISSUE THREAD

**Issue by TimmyTwoShoe** [ObliqueNetwork/Terra#2156]
**Describe the bug**

When using both vouchers received from scrolls, they seemed to just be random pokemon instead 
**To Reproduce**
Try using either voucher given from completing the scrolls 

It should give just a random pokemon and not legend or UB

**Username:**
Timmy_Two_Shoes
**Server name (all applicable):**
Titan
**Logs:**
https://cdn.discordapp.com/attachments/1085969931146887309/1085969931851534387/latest.log

**Comment by KittyKatzyn** [comment]
The rewards for scrolls have been changed recently, and this issue should now be fixed :)  Please let us know if you have any other issues! Thank you for the report!
