### ISSUE TITLE
Cracked Geode in Limited Crate

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2158]
**Describe the bug**
When placing the Cracked Geode, it says "The gems inside shine with great rewards!" But does not drop/reward anything. 
No Pokemon, or Money given to player, as well as no item.

**To Reproduce**
1. Obtain Cracked Geode
2. Place Cracked Geode somewhere in the wilderness
3. Get  "The gems inside shine with great rewards!"

Server: all
![Screenshot_94](https://user-images.githubusercontent.com/67767916/226087998-2cfdb1f2-4f37-4a3b-ad67-b8f9e505febc.png)
![Screenshot_95](https://user-images.githubusercontent.com/67767916/226087999-48747dde-7e92-4957-99c5-a1b6d0d872c5.png)

**Comment by KittyKatzyn** [comment]
The server logs do show items are given, but this is not communicated to the player, though there was one typo in a modifier command, which caused one type of mod to not be given properly.

Both the typo AND the lack of communication have been fixed now, so players will know what they receive from the geodes :)

If you are still missing a reward from this, please make a support ticket on the discord with the specifics, such as the rewards you DID get, so we can refund that for you :)  TY!
