### ISSUE TITLE
No teleport back when dropping off Spawn

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [ObliqueNetwork/Terra#2159]
Currently dropping from the edge of /spawn doesn't teleport you back.
![2023-03-18_17 01 56](https://user-images.githubusercontent.com/58639155/226117220-25ead1a6-3023-48ad-9f56-41f6031543f0.png)

**Comment by KittyKatzyn** [comment]
Confirmed!  Forwarding to Internal! Will Update here when fixed!

**Comment by WisconsinWinters** [comment]
closing with the spawn overhaul, not really possible anymore.
