### ISSUE TITLE
[Leaderboards] Placement wiping daily

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2160]
For a majority of the leaderboards on Orion the stats are wiped daily? Yesterday players had scores had highers stats then when i came to check today and the Happiny one is entirely empty despite me breeding 20 yday.

1. Check the `/warp leaderboards` rankings
2. wait till it resets (I assume its on restart but havent been around to actually verify)
3. See error

For the leaderboards only to reset weekly when rewards are distributed

It appears mon exp isnt reseting and i cant tell if shinies caught has reset but every other leaderboard has reset its stats when not intended.

Orion & Titan unable to verify atlas.

I breed the happiny 20 times on Orion

**Comment by Rasgnarok** [comment]
Fixed.
