### ISSUE TITLE
[Leaderboards] Reward Distribution

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2162]
Upon hitting 0 earlier this morning the leaderboards only dispersed cosmetic keys to online players. Players who were offline and had top 3 placement received no rewards even upon logging in. Secondly, I believe the rewards are intended to be more than just cosmetic keys however unsure if players are meant to receive all listed rewards or only a select few from those in `/lbrewards`

1. Get a top 3 placement on the `/warp leaderboards`
2. wait for time to expire
3. See rewards
4. Repeat step 1 & 2 but be offline during expiration of leaderboard
5. Log in
6. See lack of any rewards
7. See error

For offline players to receive the rewards while offline or upon next join.

Screenshots of the leaderboards that expired:
![playerexp](https://user-images.githubusercontent.com/17133410/227642177-67cca5f3-b89e-46a7-b504-bc124139eea5.png)
![catchshiny](https://user-images.githubusercontent.com/17133410/227642195-be2040df-fcfc-4aac-9df7-a47bf0a36aac.png)
![TrainersDefeated](https://user-images.githubusercontent.com/17133410/227642222-aa737eec-6d19-4201-a4a1-4032d6c1c735.png)

Deathnight7976

Orion

I believe it was intended to extend all of these leaderboards however these 3 expired before the extension took place. As you can see in my inventory is the rewards from the `PlayerExp` Leaderboard which i was online for. However I left prior to the `CatchShinies` Leaderboard and received no rewards for it.

Current status of the 3 boards:
![Playerxp2](https://user-images.githubusercontent.com/17133410/227642916-4df779b3-5e18-48db-9c8f-a1b0887217eb.png)
![catchshiny2](https://user-images.githubusercontent.com/17133410/227642941-5a31550f-7695-437c-b025-d855439acdf9.png)
![trainers2](https://user-images.githubusercontent.com/17133410/227642971-df596b9e-2da4-441b-94de-2307c3f000d1.png)

You may notice an inflated number in the current catch shinies leaderboard but that will be a separate ticket.

**Comment by KittyKatzyn** [comment]
Forwarded!

**Comment by Rasgnarok** [comment]
Closed, ticket is no longer in effect.
