### ISSUE TITLE
[Leaderboards] Inflated Shiny Capture #

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2163]
A player has caught 4 shinies since the `Catch Shiny` leaderboard reset however the leaderboard displays them having caught 2628 shinies.

1. I have no clue how to reproduce this issue.

For the leaderboard to count correctly

![catchshiny2](https://user-images.githubusercontent.com/17133410/227643517-4efbf064-5e49-4ba7-aaa6-314c3c013d95.png)

Orion

**Comment by Rasgnarok** [comment]
Closed, ticket is no longer in effect.
