### ISSUE TITLE
After being banned you are not made aware

### ISSUE THREAD

**Issue by Centuron** [ObliqueNetwork/Terra#2166]
**Describe the bug**
Once a player is banned they are still able to join the hub and then try to join a server.  However once they try to join a server, they are stuck with the negotiating screen, so players will not know they have been banned, nor the reason or get an appeal link.

**To Reproduce**
1. Get banned
2. Join the Nebula Server
3. Enter hub, then try to join one of the 3 servers
4. Get Stuck on Negotiating screen

**Expected behavior**
I would excpect banned players to not be able to even join the hub and get a message showing why they were banned

**Screenshots**

Centuron

Orion and Titan, I'm assuming Atlas as well

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by chefburne** [comment]
no longer an issue, closing
