### ISSUE TITLE
[Shrines] Bird orbs and GTS

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2171]
Purchasing a full orb from gts will cause it to not be detected as a full orb via the shrine plugin.

1. Get full bird orb (static)
2. Sell it on gts
3. Buy it from gts
4. Try to summon bird (zapdos)
5. See error

For orbs purchased via GTS to be able to summon legendary birds as normal.

Orion, Likely all.

**Comment by chefburne** [comment]
no longer an issue, closing
