### ISSUE TITLE
Claim Block Bank somehow carrying over to other server(s)

### ISSUE THREAD

**Issue by Flaxencat6969** [ObliqueNetwork/Terra#2172]
I am normally an Onion player, where as an Omen already have max'd out claim blocks (76k+). Came to Atlas to help with vote party and found a cozy little nook as a new player and decided to claim it. Turns out I have the same amount of claim block bank as I do on my home server.

Expectations:
I only expected to have roughly 500 claim blocks to use as a new player on Atlas.

![2023-04-18_06 27 07](https://user-images.githubusercontent.com/120101055/232751925-77ead894-674f-41e1-a992-ba860f4c9df2.png)

IGN: JesterFox
Orion

**Comment by Rasgnarok** [comment]
Closing ticket, pre-reset issue.
