### ISSUE TITLE
Bingo reward system

### ISSUE THREAD

**Issue by spiritozz** [ObliqueNetwork/Terra#2173]
After completing bingo today I received 2 shiny pokemon and GS ball. That makes for 3 rewards instead of 1 shiny and 1 legendary item from the pool. All of the rewards came at the same time that I completed the bingo so I am sure they all were from bingo.
Don't know if this has been happening to others and don't know yet if its 1 of a kind bug yet
Server: Atlas 
IGN: Spiritozz

**Comment by WisconsinWinters** [comment]
closing with the bingo overhaul
