### ISSUE TITLE
[Modifier Tokens] Item Deletion

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2174]
When in a modifier token menu and you pick up any item that item deletes.

1. Give yourself a modifier token `/modifiertokens grant <player> <modifiertype> 1 true`
2. Enter the modifier tokens menu (Right click)
3. Have someone drop items on you
4. Leave menu
5. Check inventory
6. See error

For items picked up while in token modifier menu not to delete.

Network

**Comment by chefburne** [comment]
no longer an issue, closing
