### ISSUE TITLE
Scrolls not filling out properly

### ISSUE THREAD

**Issue by TheKeyblade** [ObliqueNetwork/Terra#2179]
**Describe the bug**

**To Reproduce**
1. Have Scroll in inventory
2. Kill Mega Pokemon
3. Doesn't count towards scroll

**Expected behavior**
 - Scroll fills out once Mega dies.
**Screenshots**

**Username:**
Aeiriecakes
**Server name (all applicable):**
Aeris

**Comment by chefburne** [comment]
no longer an issue, closing
