### ISSUE TITLE
Acro and Mach Bikes bug in claims

### ISSUE THREAD

**Issue by ShapooK** [ObliqueNetwork/Terra#2180]
**Describe the bug**
Mach and Acro bikes can be destroyed and stolen in trusted claims by a person that is not trusted. 

**To Reproduce**
1. Go to a claimed area of yours 
2. Place down Acro and Mach bike
3. Have someone untrusted break them 

**Screenshots**

![](https://cdn.discordapp.com/attachments/1083947408590905415/1112213338462634034/Screenshot_195.png)
Person in sc not trusted in one of my claims and could easily destroy my bikes and steal them 

**Username:**
ShapooK
**Server name (all applicable):**
Titan, but most likely all.

**Comment by WisconsinWinters** [comment]
closing as GD is no longer used
