### ISSUE TITLE
/Warp Houndoompit closed off area

### ISSUE THREAD

**Issue by Aerinyan** [ObliqueNetwork/Terra#2183]
**Describe the bug**
Wide closed off area in /warp Houndoompit where pokemon spawns can be clogged with players no way of reaching said area without /fly. 

**To Reproduce**
1. Go to /warp Houndoompit.
2. Go towards houndoom spawner area.
3. See hole towards closed off area.
4. See error.

**Expected behavior**
Ether fill in closed off area or make it so players can have an accessible in/out by adding blocks as steps at the hole in the wall entrance.

**Screenshots**

![Screenshot 2023-06-04 193127](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/22c7dd7e-0f65-4f9d-8035-d3323561b6e1)
![Screenshot 2023-06-04 193115](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/26fe2622-9b4c-431b-80ee-ac7ce0440270)

**Username:**
Aeiriecakes

**Comment by Deathnight7976** [comment]
Space has been filled in, issues should be resolved.
