### ISSUE TITLE
Bingo still gives tidal/clear bell

### ISSUE THREAD

**Issue by EricNgo0923** [ObliqueNetwork/Terra#2185]
The finished bingo still gives the bells that were supposed to be disabled

Username:ChibiMegumin

![bell](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/73042015/5005fd60-0978-46b1-9d90-8654071d3503)

**Comment by Khrisstias** [comment]
This has been fixed, thank you for the ticket
