### ISSUE TITLE
Gliscor and H-Arcanine don't have the correct HAs.

### ISSUE THREAD

**Issue by CallMeHobby** [ObliqueNetwork/Terra#2186]
This bug occurs when a pokemon with a hidden ability evolves, its evolution no longer has the hidden ability. For example, in my case, it happened with my gligar (hidden ability is immunity) and my Hisuian growlithe (hidden ability is rock head). After evolution, Gliscor should have the ability Poison Heal - Arcanine should keep rock head. For some reason, they both lose the HA after evolution. 

If you spawn in either of the above pokemon and evolve them in the server, they both lose the HA. However, if I go into singleplayer, after evolution both pokemon have the correct HA. I was previously told its a bug with pixelmon, but its not. Both have the correct hidden ability after evolving in singleplayer.

Username: CallMehobby
Server: Nebula (Orion)

**Comment by KittyKatzyn** [comment]
~~This is a Pixelmon bug, and has already been reported for them to fix. Edit - has already been fixed.~~

Edit edit - okay so it's not that they're losing their HA, it's that their files contain the wrong HA, which is Nebula-specific.  We can fix that, sorry for misunderstanding due to the title.

**Comment by KittyKatzyn** [comment]
The gliscor bug IS the Pixelmon bug - Nebula's file is correct.  That one will be fixed by Pixelmon.

H-Arcanine has been fixed on our end.  The fix won't be live on the servers until the next time we update the servers to use the updated datapack, though.

Thanks!
