### ISSUE TITLE
[Battletower] Gui Outdated

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2188]
The battle tower gui shows pre nerf values

1. Do /battletower
2. Read gui
3. see $5,000 a floor and $140,000 total

For it to display $1,250 a floor and $42,500 total

![Discord_CCnkOoy94a](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/17133410/a6be6090-cccf-4860-9c74-8b1e7750b47e)
![battletowergui](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/17133410/5723f4bb-cfbe-4d03-a30d-43805ab88fd7)

Orion, likely all

**Comment by ElementalMP** [comment]
Updated config to reflect changes on all servers and verified changes.

- Closing ticket as resolved.

Thanks for the detailed report!
