### ISSUE TITLE
[Ultra Beast Spawning] Xurkitree's biomes aren't updated.

### ISSUE THREAD

**Issue by volkamenia** [ObliqueNetwork/Terra#2192]
**Describe the bug**
Xurkitree's spawning biomes are stated to have been updated to Ultra Plant in the changelog, but are still displaying as various forests at night during storms in /wiki

**To Reproduce**
1. Go to /wiki Xurkitree
2. Click on Spawning
3. Scroll down if necessary

**Expected behavior**
Correct the spawning conditions for Xurkitree

**Screenshots**

https://i.gyazo.com/1e225b0977b3a1e17d391b4120cfd6ef.png

**Username:**

Grandeflora

**Server name (all applicable):**

Orion

**Logs:**

idk if we need these for this particular issue but let me know

**Additional context**

N/A

**Comment by Deathnight7976** [comment]
Should be resolved, /wiki is now displaying them spawning in the correct biome.
