### ISSUE TITLE
Random Legendary Pokemon Crate Reward bug

### ISSUE THREAD

**Issue by Aerinyan** [ObliqueNetwork/Terra#2193]
**Describe the bug**
When winning a crate reward of 'Random Legendary Pokemon', the pokemon given is a random non legendary pokemon instead. It also does not announce in chat that the player has won a random legendary pokemon.

**To Reproduce**
1. Use crate key (Solar Crate Key in this particular one)
2. Win "Random Legendary Pokemon Reward"
3. Receive random non legendary pokemon

**Expected behavior**
Find and fix issue as to why it gives out random non legendary pokemon instead of intended random legendary pokemon.

**Screenshots**
![Screenshot_161](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/cf56e36f-b8cd-409b-8c00-7c77c8598152)
![Screenshot_2023-06-09_180517](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/7d25f88a-62d1-41f3-bdd0-6a1361bc791a)

**Username:**
Zhao_Zilong

**Server name (all applicable):**
Titan (likely all servers)

**Logs:**

[2023-06-09-1.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/11710704/2023-06-09-1.log)
Timezone: UTC +1

**Additional context**
To be assigned to Elemental

**Comment by ElementalMP** [comment]
Just trying to match log to log here, can you please advise your timezone?
Cheers

**Comment by Aerinyan** [comment]
Timezone: UTC + 1 for the log file

**Comment by chefburne** [comment]
Pokémon specs now match the listed information in crates, closing
