### ISSUE TITLE
Remote daycare "/rdc" not working

### ISSUE THREAD

**Issue by ShapooK** [ObliqueNetwork/Terra#2195]
**Describe the bug**
After the new pixelmon update, the command /rdc does not work anymore. (Command pulled up the daycare)

**To Reproduce**
1. Do /rdc
2. Nothing happens, after a few minutes
3. See error

**Expected behavior**
Would bring up the daycare without using the block anywhere

**Username:**
ShapooK

**Server name (all applicable):**
Titan but probably All

**Comment by Rasgnarok** [comment]
Fixed.
