### ISSUE TITLE
reasource pack - Geode and primal pokemon are showing up in normal pallet instead of their respective pallets

### ISSUE THREAD

**Issue by WolfzDagger** [ObliqueNetwork/Terra#2197]
**Describe the bug**
The reasources of Primal pokemon and geode pokemon are not working, they say that they are that pallet but shop up in normal pallet/

**To Reproduce**
1. look at any geode or primal pokemon...
2. they will show up us a normal pallet pokemon.

**Expected behavior**
 
i was expexting them to still have their custom skins 

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/136806022/78fcbc7c-d3c7-4c82-bc70-1229041f38ca)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/136806022/ab9f84f2-d425-4336-97a6-b02c84b09ed8)
![Inked2023-06-16_11 13 26](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/136806022/32eb4aac-2ee2-43f6-a7cc-03fdc61057b9)

**Username:**
WolfzDagger

**Server name (all applicable):**

all servers

**Comment by WolfzDagger** [comment]
Server restart fixed the issue

**Comment by CenizaRey** [comment]
No changes were carried out with the geode/primal palettes between server resets. What actually happened is the assets weren’t loading properly on your client. A simple relog fixes this most times!
