### ISSUE TITLE
[Crates] Amount of Masterballs you get from Solar crate are less than displayed

### ISSUE THREAD

**Issue by TheKeyblade** [ObliqueNetwork/Terra#2198]
**Describe the bug**
Masterballs displayed are lesser than the amount you get

**To Reproduce**
1. Go to /warp crates
2. Click on Solar Crate
3. Hover over 5 masterballs

**Expected behavior**
Expected to show 3 masterballs 

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/133035392/94384b46-282c-49ad-b856-89dd22a6d908)
**Username:**TheKeyblade

**Server name (all applicable):** All

**Comment by chefburne** [comment]
GUI now reflects correct amount, closing
