### ISSUE TITLE
[Glazed Terracotta] Only Orion can rotate Glazed Terracotta

### ISSUE THREAD

**Issue by FarDiamond** [ObliqueNetwork/Terra#2199]
**Describe the bug**
When placed, glazed terracotta of any type can be rotated with crouch + right click in Orion (even inside others' claims!) and cannot be recreated in Atlas or Titan

**To Reproduce**
1. Go to Orion
2. Place down or go to placed glazed terracotta
3. With an empty hand, crouch + right click
4. See glazed terracotta rotate
5. Go to Atlas or Titan
6. Repeat steps 2 + 3
7. See error 

**Expected behavior**
The ability to rotate glazed terracotta in all servers, but not within claims (or alternatively unable to rotate entirely)

**Username:**
 FarDiamond3049
**Server name (all applicable):**
 Orion and Titan/Atlas

**Comment by chefburne** [comment]
terracotta rotate mechanics are consistent across servers now, thanks for the report!
