### ISSUE TITLE
Not receiving a reward from Asteroids

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2201]
Describe the bug
I got the 3 asteroids from the limited edition crate upon opening my last asteroid i did not receive the item it said i got. I got a maximum iv mod that i recieved but it also said i got a shiny modifier which i didnt recieve even though i had nothing in my inventory

**To Reproduce**
1.Get 3 asteroids
2.Open all the asteroids at the same time
3.award not recieved
4.see error

**Expected behavior**
should recieve all the rewards 

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/137843758/2ffe2956-331b-42fb-88c8-1bba911f9cd9)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/137843758/ad19d847-fbea-47ac-8c09-b20bebeda871)

**Username:**
itsAmaze
**Server name (all applicable):**
all
**Logs:**
[debug.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/11876364/debug.log)

[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/11876365/latest.log)

**Comment by chefburne** [comment]
no longer relevant, closing
