### ISSUE TITLE
Command /breakegg doesnt work in 6 slot

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2202]
**Describe the bug**
If you try to use this command on an egg in the 6 slot, it acts as if there is nothing there. You are dealt the "Error there is no pokemon in that slot" message.
**To Reproduce**
1. Not sure if it has anything to do with using /breeding before hand or not but have an egg in the 6 slot and use /breakegg 6

**Expected behavior**
The egg in the 6 slot would hatch

**Screenshots**
![Screenshot (480)](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/95523378/53b4d040-4a9c-411a-82ec-834eb1dbc18e)

**Username:**
_Peyton_7
**Server name (all applicable):**
Peyton on all servers

**Comment by chefburne** [comment]
no longer an issue, closing
