### ISSUE TITLE
[Feature] Can open chests in claims

### ISSUE THREAD

**Issue by FarDiamond** [ObliqueNetwork/Terra#2203]
**Describe the bug**
Some chests can be opened on specific spots of the chests within claims, specifically on /pw Jokers_Mew_Platform 4 large chests can be opened by right clicking slightly do the left of the white middle part of the chest.

**To Reproduce**
1. Go to /pw Jokers_Mew_Platform (on Titan)
2. Click left from the middle white part of the chests (thinking as a grid from left to right, top to down) 3,3 7,1 8,2 and 8,3
3. Chest opens

**Expected behavior**
A claim should protect all the chests on the wall from being opened

**Username:**
Far
**Server name (all applicable):**
Titan

**Comment by Rasgnarok** [comment]
Closing ticket, pre-reset issue.
