### ISSUE TITLE
[Donor Command] /repair works on Ras' Golden Lens and Lures

### ISSUE THREAD

**Issue by volkamenia** [ObliqueNetwork/Terra#2204]
**Describe the bug**
Running /repair or /repair all will repair Ras' Golden Lens and Lures in your hand/inventory. 

**To Reproduce**
1. Hold a Lure or Ras' Golden Lens that's been used at least once.
2. Type /repair
3. See error

**Expected behavior**

**Screenshots**

**Username:** Grandeflora

**Server name (all applicable):** Orion

**Logs:**
Let me know if needed.

**Additional context**
Not sure if this is a bug or a feature, so I thought I'd report it!

**Comment by chefburne** [comment]
this has been solved, thank you for reporting!
