### ISSUE TITLE
Receive Non-Legendary from a Legendary voucher

### ISSUE THREAD

**Issue by StrideMate** [ObliqueNetwork/Terra#2205]
**Describe the bug**
Upon completing a scroll, Moon received a Legendary voucher in which Moon used and received a Meinfoo.

**To Reproduce**
1. Complete the scroll
2. Receive a voucher
3. Use the legendary voucher
4. Receive a Non-Legendary

**Expected behavior**
When using the voucher given from the scroll, Should receive a Legendary pokemon.

**Screenshots**
![2023-07-08_08 36 44](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/78794976/b80c9084-2a3f-4138-b8eb-72c9f6e1e36d)
![2023-07-08_08 36 23](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/78794976/2d14b062-3f8e-4175-b972-1a7de713709a)
![2023-07-08_08 30 55](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/78794976/79ed4e0f-e23f-4295-8077-a11d103700d9)

**Username:**
Mooneverdark

**Server name (all applicable):**
Orion (Possible all)

**Logs:**
This is moon's log from the Ticket on discord
[techniclauncher_2023-07-08.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/11991078/techniclauncher_2023-07-08.log)

**Comment by chefburne** [comment]
No longer an issue, thank you for reporting
