### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by SheGhoull** [ObliqueNetwork/Terra#2206]
**Describe the bug**
This is only in command/ channel /sc (/staffchat on discord). some staff members are not getting all of the members profile pictures in the chat. if you click on the bots, it shows an error message. (see screenshots attached)
**To Reproduce**

**Expected behavior**
n/a

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139086349/f1f12ed2-ebd8-4f5a-8188-ba72472936d2)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139086349/a042f801-bb1b-4c54-b2dd-72b10bd2b74d)

**Username:**
SheGhoull
**Server name (all applicable):**

**Logs:**
n/a

**Additional context**
this has been happening for a few days now. (4 or less at the time of this posting). some players pfp do show but it is completely random. if a players bot pfp shows one hour it may not be in the next hour.

**Comment by Khrisstias** [comment]
This is no longer an issue, closing
