### ISSUE TITLE
Donor Commands not working

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2207]
**Describe the bug**
For my instance i have omen and most of the commands work. However some commands dont work such as /head /mobhead and /craft and /nick 

**To Reproduce**
1.Have a donor rank
2.Run the commands in game 

**Expected behavior**
Gives an error and says that i do not have permission for those commands or says unknown command

**Screenshots**
![2023-07-14_18 10 18](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/137843758/87cc1d1d-36ad-44a9-b647-a51557c60c61)
in order i did /head then /mobhead then /craft then /nick for the nick command when i use the command it lets me use the command but it doesnt actually change my nick in game and instead will keep my original ign

**Username:**
itsAmaze
**Server name (all applicable):**
atlas
**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by iamcjmxv** [comment]
/sit does not work either... totally of great importance :)))

**Comment by WisconsinWinters** [comment]
/flyspeed for flying does not work for Omens.

assuming this has been moved to /speed under the essentials command system

**Comment by Aerinyan** [comment]
/glow is also an unkown command.
/nickname exists but the nicknames set do not stick

**Comment by Rasgnarok** [comment]
/flyspeed and /sit are now fixed, will need to look into the rest of them

**Comment by WisconsinWinters** [comment]
glow implemented, nickname fixed last I tested.
