### ISSUE TITLE
[Feature] Donor Claim blocks

### ISSUE THREAD

**Issue by iamcjmxv** [ObliqueNetwork/Terra#2208]
**Describe the bug**
Claim blocks are not default setting to X amount for donor rank Omen, Unsure about other donor ranks. 

This was said in changelog " This means old Store purchases should have kept their baseline rank claim block count."
This may be an only me issue. 

**To Reproduce**
1. Run /claim
2. Claim menu pops up with set amount of claimblocks at 1024
3. Thats bad hehe

**Expected behavior**
Should have 15k I beleive? 

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/60482171/64687d0e-0f3d-4716-9bed-93354e459344)

**Username:**
_Conj 

**Server name (all applicable):**
At least Orion

**Additional context**
Some commands are messed up, but there is an existing ticket for that by itsAmaze
https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/2207

**Comment by KittyKatzyn** [comment]
Could you please test this once more and let us know if this issue has resolved for you?  Thank you!

**Comment by KittyKatzyn** [comment]
This has been fixed!  Thank you for your report <3
