### ISSUE TITLE
[Rank Permissions] Missing Marshadow Grey name color

### ISSUE THREAD

**Issue by Dracorexion** [ObliqueNetwork/Terra#2213]
**Describe the bug**
I have omen rank and when I used /namecolor, I noticed Marshadow Grey was locked, despite being unlocked at Aria rank

**Username:**
Dracorexion
**Server name (all applicable):**
Atlas

![2023-07-14_23 53 45](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134461703/e3011151-ca1f-44fd-bfba-f623b2caf1bd)

**Comment by KittyKatzyn** [comment]
Confirmed, and thanks for the report!

Issue is fixed now :D
