### ISSUE TITLE
Elevators not reaching as far

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2214]
**Describe the bug**
Seems since reset Elevators dont reach as far as they did before. I made a schematic of a prior build so i could rebuild it after reset but now the elevators dont reach. Im not sure how far they reached before the reset but they only reach 8 Blocks as of now.

**To Reproduce**
Steps to reproduce the behavior: Not sure if necessary
1. Place 2 elevator blocks with 8+blocks within them and you wont be able to use it

**Expected behavior**
I expected it to be able to at least reach 10 which was my build before reset

**Username:**
_Peyton_7

**Server name (all applicable):**
Peyton / _Peyton_7

**Comment by KittyKatzyn** [comment]
Confirmed!

I have changed this back to what it was before the reset - 32 blocks, instead of Pixelmon's basic 10.  Fix will be live on all servers after the next server resets.  

Thank you!
