### ISSUE TITLE
[Gyms] Battle crashing after fainting Challenger's pokemon

### ISSUE THREAD

**Issue by Tac3403** [ObliqueNetwork/Terra#2215]
**Describe the bug**
in agni, if you accept a challenge and defeat an opponent pokemon at anytime, it would crash and immediately end the battle
**To Reproduce**
1. have agni normal challenger
2. select pokemon and start battle
3. faint an opponents pokemon
4. crash happens here 

**Expected behavior**
challenger can send out next pokemon 

**Server name (all applicable):**
Orion, untested on others 

**Logs:**
did /battlelog, but im not seeing them uploaded to discord..? battles were between Tac_3403 and WillyWayBack on orion around 1 pm Central time

**Additional context**
had the player faint gym leaders Pokémon, did not crash the battle. I did not have them switch, that is untested.

**Comment by KittyKatzyn** [comment]
Forwarded!  Thank you.

**Comment by Rasgnarok** [comment]
Fixed!
