### ISSUE TITLE
[Vanish] Command doesn't work

### ISSUE THREAD

**Issue by MariSylveon** [ObliqueNetwork/Terra#2216]
When the command is done it says its enabled but however I remain visible, When Elemental used `/vanish` there was particles 

1. enter `/vanish`
2.  View your character 
3.  See Error

Vanish to make you invisible and without particles

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139662822/df210afd-6175-4ac9-a023-c49c42c8faac)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139662822/b65aaf77-449b-4b0a-8e3f-2da862433756)

Orion, likely all

**Comment by WisconsinWinters** [comment]
unable to fix, this is essentials issue and will need a custom solution or another plugin on our end.
