### ISSUE TITLE
[Voting] One of the sites is possibly not registering on the server and a few of the links are messed up

### ISSUE THREAD

**Issue by Dracorexion** [ObliqueNetwork/Terra#2218]
**Describe the bug**

Voting Sites that didn't give me any reward:
https://minecraft.buzz/server/7781 (might already be fixed, can't test cause I already voted on it today)
When clicking the ender pearl to pull up all 8 sites, the Elite Minecraft link takes you to Best Minecraft link and the Best Minecraft link takes you to Pixelmonservers.

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134461703/a8f892d5-95ba-4787-8223-2364c50989fe)

**Comment by Aerinyan** [comment]
This only happens when you click the 5th and 6th links via "Vote All" list. But if you click on individual links in /vote, you get redirected to the correct vote sites.

**Comment by Rasgnarok** [comment]
Fixed
