### ISSUE TITLE
[PlayerWarp] Most of the PlayerWarps

### ISSUE THREAD

**Issue by Ultamategamer26** [ObliqueNetwork/Terra#2219]
A lot of the PlayerWarps are old and still active which will teleport to the wrong location that has nothing to do with the PlayerWarp. It also doesn't allow you to see the player warps in the PlayerWarp GUI.

**Comment by KittyKatzyn** [comment]
Hi there!

I do believe this issue should be fixed now, yes?

There is still an issue on Orion that is prevents the warp lists from being viewed, but that issue is in another ticket and has been foprwarded to Internal.
