### ISSUE TITLE
[GTS] /gts sell makes all Pokemon untradable

### ISSUE THREAD

**Issue by raviolugh** [ObliqueNetwork/Terra#2220]
**Describe the bug**
When I do /gts sell, it does not allow me to sell any of the naturally caught pokemon I have gotten and makes them untradable. 
**To Reproduce**
1. /gts sell
2. See that pokemon are untradable

**Username:**
raviolugh
**Server name (all applicable):**
Atlas
![github](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139720449/9d428ff3-fb2f-4c3e-a8f0-e288c41000bd)

**Comment by KittyKatzyn** [comment]
Confirmed! Forwarding to Internal. Thanks for your report!

**Comment by KittyKatzyn** [comment]
This issue has been fixed, and the fix will be live on each server upon server reset.
