### ISSUE TITLE
Legendary Plushies 

### ISSUE THREAD

**Issue by Aerinyan** [ObliqueNetwork/Terra#2222]
**Describe the bug**
Legendary Plushies reverting into base Bulbasaur plushies when retrieved after placing down and will delete itself if placed down as Bulbasaur plushies. 

**To Reproduce**
1. Place down legendary plushy.
2. Retrieve Plushy.
3. See error.

**Expected behavior**
Let legendary plushy not turn into bulbasaurs when retrieved and retain their legendary.

**Server name (all applicable):**
All

**Comment by KittyKatzyn** [comment]
This has been confirmed and forwarded to Internal, thank you!

**Comment by chefburne** [comment]
no longer an issue, closing
