### ISSUE TITLE
Nether only spawns underground spawns

### ISSUE THREAD

**Issue by Blanobo** [ObliqueNetwork/Terra#2223]
Currently, in the Nether the only pokemon that spawn naturally are the underground spawns. Golbat, Zubat, Geodude, Swoobat, Nacli etc. Nothing that spawn above ground like Salandit, Bisharp, Houndour, Magmar, or turtornator seem to be able to spawn. 

**To Reproduce**
1. Go to the Nether
2. Standing still for 30s and see that only underground spawns, spawn. 
(Went to the nether on all 3 servers, same issue only underground spawns.)

**Screenshots**

![2023-07-17_16 48 42](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/133820465/96e7db8f-368d-49be-9d6d-45751fc7664e)

![2023-07-17_16 48 14](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/133820465/732486c1-a337-4b56-9aea-7ed905bf3406)

**Username:**
 Blano

**Server name (all applicable):**
 Orion (My Server) 
 Atlas 
 Titan

**Comment by KittyKatzyn** [comment]
This is a Pixelmon bug; should hopefully be fixed with the next Pixelmon update.

**Comment by Rasgnarok** [comment]
Needs an update as Pixelmon likely fixed it in their datapack, and then it broke again, and now it should work once more? Might be also in betterspawner conf, TBA and must be tested in beta

**Comment by Rasgnarok** [comment]
Updated, confirmed this happens on vanilla Pixelmon in singleplayer. Pushed back the issue to the Pixelmon Team, pending a fix from them.
