### ISSUE TITLE
Beast Rank Tag

### ISSUE THREAD

**Issue by Aerinyan** [ObliqueNetwork/Terra#2225]
**Describe the bug**
Beast Rank tag showing as "Luxury" but with the correct colours for beast rank.

**To Reproduce**
1. Equip Beast Rank from /tags
2. Type in chat
3. See error

**Expected behavior**
Correctly show "Beast" as a tag for beast rank.

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/76e1fe9b-02b4-4d82-85da-9d66587b5806)

**Server name (all applicable):**
Atlas (Most likely All)

**Comment by Aerinyan** [comment]
![Screenshot 2023-07-18 093247](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/0b0a994a-f2f7-4a87-a493-23722a05e80c)

same issue with Dream Rank

**Comment by Rasgnarok** [comment]
Fixed
