### ISSUE TITLE
[Datapack] NPC Berry shop JSON has duplicate berries, resulting in the player purchasing more items than intended.

### ISSUE THREAD

**Issue by KittyKatzyn** [ObliqueNetwork/Terra#2227]
**Describe the bug**
NPC Berry shop JSON has duplicate berry, resulting in the player purchasing more items than intended.

**To Reproduce**
1. Go to the Berry Shop at the market.
2. Purchase any of the following berries: kee maranga yago touga pumkin ginema eggant drash.
3. Realise you ended up buying 2x as much as intended. Money paid reflects this.

I gave myself $100.00 on Titan, where I have $0. I went to the berry NPC and bought a single drash berry for $50.  My money then went to $0, and I now have two berries in my inventory.

**Expected behavior**
Players should recieve and pay for the amount they want.

**Screenshots**
N/a

**Username:**
Katzyn

**Server name (all applicable):**
Confirmed on all servers.

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_
N/a
**Additional context**
N/a

**Comment by CenizaRey** [comment]
Fixed as of next restart, thanks for the report! Closing
