### ISSUE TITLE
Pwarp price bug on atlas

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2229]
**Describe the bug**
On atlas it costs 5k to make a pwarp but on orion and titan it costs 20k to make a pwarp

**To Reproduce**
join atlas server and make a pwarp

**Expected behavior**
will charge the user 5k to make a pwarp but if you play on titan or orion it will charge 20k

**Username:**
itsAmaze
**Server name (all applicable):**
Atlas

**Comment by FrozenEggs8** [comment]
To add to this, you're only able to create 1 pwarp on Atlas now. Used to be able to create 3 before reset.

**Comment by chefburne** [comment]
resolved, closing
