### ISSUE TITLE
Player speed bugged after using /flyspeed

### ISSUE THREAD

**Issue by coldpiplup** [ObliqueNetwork/Terra#2230]
Walk speed appears to be perma slowed after messing with /flyspeed

**To Reproduce**
1. type /flyspeed 10
2. walk around
3. you're slow nerd

**Expected behavior**
It shouldn't affect movespeed of walking but it does. 

Username: ColdPiplup (happening to many Omen ranks right now though)

All pixelmon servers

Need logs? I don't think so but LMK if you do.

**Comment by Rasgnarok** [comment]
Fixed
