### ISSUE TITLE
Claims appearing out of nowhere

### ISSUE THREAD

**Issue by Squidammo** [ObliqueNetwork/Terra#2232]
I've been told by players they would get claimed areas out of nowhere without using a golden shovel or a /claim command.
 Now, I don't know at all how to reproduce this, but this is a thing that exists and maybe we should investigate more around the claiming plugin. Players have lost claims for no reason and maybe this could be related.

**Comment by Rasgnarok** [comment]
Closed, ticket is no longer in effect.
