### ISSUE TITLE
Omen /repair issues

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2233]
**Describe the bug**
While running repairing my hammer, I wanted to see how long the cooldown was, which lead to there being no cooldown on /repair.
Additionally, there is no access to /repair all.

**To Reproduce**
1. Join Orion/Titan/Atlas
2. Hold a damaged tool and run /repair
3. Try using /repair on another tool shortly after

![Screenshot_164](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/67767916/3e4c1027-54da-45a9-bb81-50673db6c37a)

**Comment by chefburne** [comment]
Repair commands now work as intended
