### ISSUE TITLE
[Senior Mod] EssentialsX /give can not target pixelmon items, prefer minecraft's /give

### ISSUE THREAD

**Issue by WisconsinWinters** [ObliqueNetwork/Terra#2235]
Using EssentialX's /give command does not appear to be able to target pixelmon modded items such as pixelmon:s_exp_candy

Attempting to do /give with the EssentialsX version wont return a valid item, nor does looking up any modded items appear to bring anything back.

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/b2dff73d-ad93-4118-894c-fa67b2fa533a)

**Comment by Rasgnarok** [comment]
This should now be fixed as of the next restart (already live)
