### ISSUE TITLE
Back command does not work correctly with Marry TP command

### ISSUE THREAD

**Issue by Ascix** [ObliqueNetwork/Terra#2239]
**Describe the bug**
If you use the back command after the marry tp command, it will bring you to two areas before.

**To Reproduce**
1. Current area is place 1
2. Teleport somewhere else (place 2)
3. Use /marry tp command
4. It will bring you back to place 1

**Expected behavior**
I should have returned to place 2

**Username:**
Audacideez

**Server name (all applicable):**
Titan

**Comment by WisconsinWinters** [comment]
this is an issue with them being two seperate plugins, won't be able to fix on our end unless we create a /marry back
