### ISSUE TITLE
Poké Displays can transfer Vault Pokémon

### ISSUE THREAD

**Issue by colgatetoofpaste** [ObliqueNetwork/Terra#2241]
**Describe the bug**
If a Pokémon that you vaulted is placed inside of a Poké Display, another player can destroy the Poké Display and obtain the Pokémon inside, "trading" the Pokémon.

**Expected behavior**
From what I understood, Pokémon are supposed to return to their owner when removed from a display.

**Username:** reported by DoubleGlitter26

**Server name (all applicable):** All

**Comment by Rasgnarok** [comment]
Fixed, item is now banned.
