### ISSUE TITLE
[Signshop] Signshops unlinked after server restart [Nether]

### ISSUE THREAD

**Issue by NoobJeffy** [ObliqueNetwork/Terra#2242]
**Describe the bug**
Signshop at Nether will unlink at every restart or server crash.

**To Reproduce**
1. Build Signshop at Nether but not overworld
2. wait for server restart or server crash
3. Signshop unlinked.

**Expected behavior**
Every Signshop at nether will unlink chest

**Username:**
NoobJeffy

**Server name (all applicable):**
Atlas

**Comment by WisconsinWinters** [comment]
closing as many signshops are now invalidated after reset and a fresh database is up.
