### ISSUE TITLE
Breeding Tax Not Taxing

### ISSUE THREAD

**Issue by coldpiplup** [ObliqueNetwork/Terra#2244]
**Describe the bug**
Breeding 75% or higher IV pokemon does not tax properly. Maybe it's just me but I've only been taxed a few times.

**To Reproduce**
Steps to reproduce the behavior (FOR ME SPECIFICALLY)
1. Open daycare
2. Put in two hidden ability dratinis
3. Click the check and pay a dragon gem
4. Yay no tax

**Expected behavior**
Tax as described in the announcement

**Username:**
ColdPiplup

**Server name (all applicable):**
Atlas

**Logs:**
Bruh there's nothing but settings in that folder IDK D:

**Comment by Rasgnarok** [comment]
Fixed
