### ISSUE TITLE
/ignore still showing the ignored players messages

### ISSUE THREAD

**Issue by Oryso** [ObliqueNetwork/Terra#2245]
**Describe the bug**
Putting someone on your /ignore list doesn't stop you from seeing their messages.

**To Reproduce**
1. /ignore someone
2. Still see their chat

**Expected behavior**
Not able to see their chat.

**Screenshots**
![2023-07-24_23 09 32](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/8157c265-4192-4091-876d-e4bb26d19317)
![2023-07-24_23 45 49](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/162d7c02-a403-4cb6-9e79-8b96cf8319af)
![2023-07-25_00 51 56](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/1a21d4b4-f5c6-4e2d-aebe-00ded7d754c8)

**Username:**
Oryso

**Server name (all applicable):**
Orion

**Logs:**
Not sure if needed, if so let me know.

**Comment by Rasgnarok** [comment]
Use [P] to hide messages from a player while in the same server as them

**Comment by WisconsinWinters** [comment]
fowarded this to tracker to see if a global /ignore is possible, but workarounds with [P] menu are needed for now
