### ISSUE TITLE
Movement pads prevent you from being AFK, intended?

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2248]
In the past, movement pads did not remove you from being AFK while on it so we allowed the use of egg hatching machines - which is just a circle loop of movement pads so the player gets egg steps while on it. Currently the movement pads prevent players from being marked as AFK. Is it intended to do that?

To replicate: 
1. TP to someones egg hatcher
2. Get on the movement pads, while on run /afk (or wait 5+ mins)
3. See error.

**Comment by WisconsinWinters** [comment]
seems like an interaction issue with pixelmon and anti-afk, disabled movement plates.
