### ISSUE TITLE
Bugged Copper Hourglass

### ISSUE THREAD

**Issue by Aerinyan** [ObliqueNetwork/Terra#2249]
**Describe the bug**
The copper hourglass is supposed to skip a gem requirement needed for breeding. But when trying to do so, despite dragging and clicking it does not use the hourglass to skip the requirement. 

**To Reproduce**
1. Open daycare.
2. Place two breedable pokemon into daycare. 
3. Click check mark.
4. Drag and click copper hourglass into the box with the gem requirement.
5. See error.

**Expected behavior**
Allow skipping of gem requirement with copper hourglass.

**Screenshots**

![Screenshot 2023-07-29 225937](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/a03adfb7-8034-4b71-b6ba-a202966ab2c3)

https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/0a5599ac-d9ae-4900-96f9-401abb4d13fe

**Username:**
Aeiriecakes

**Server name (all applicable):**
Orion (most likely all)

**Additional context**
another orion player has mentioned this in a ticket, as well as players in other servers.

**Comment by WisconsinWinters** [comment]
fixed
