### ISSUE TITLE
[Leaderboard] rank and score reversion

### ISSUE THREAD

**Issue by NoobJeffy** [ObliqueNetwork/Terra#2250]
**Describe the bug**
Rank and score reversion

**Screenshots**
12hrs ago
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/56636470/e8dae461-fb5e-4d81-9a89-32c162da74e6)
and now
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/56636470/19eae84f-93e4-4b2d-a152-b6bdfe808713)

**Username:** NoobJeffy

**Server name (all applicable):** Atlas

**Logs:**
I don't think it need a log, but i will provide if needed

**Comment by Rasgnarok** [comment]
Closed, ticket is no longer in effect.
