### ISSUE TITLE
[Rank permissions] Rune, Omen, Legacy do not have access to /logmessages or  /logmessages choosegroups

### ISSUE THREAD

**Issue by raviolugh** [ObliqueNetwork/Terra#2251]
**Describe the bug**
Before the reset, Rune, Omen, and Legacy ranks had access to create custom join/leave login messages. Now none of these ranks have this permission. 
**To Reproduce**
Be a legacy, rune, omen rank, and do /logmessages, /logmessages choosegroups, /login messages, see unknown command. 
**Expected behavior**
It's expected to be able to create a custom leave/join login message as it was prior to the reset and I was told the permissions were not changed for these ranks. 
**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139720449/9ddb6c90-fb99-40e0-ab47-31e9e786caf7) (/logmessages, /logmessages choosegroups)

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139720449/f282c6e1-d8ac-4612-a871-ce2fe5b03ede)
(/loginmessages)
**Server name (all applicable):**
All servers

**Comment by Rasgnarok** [comment]
The command is now `/loginmessage` or `/leavemessage`, the plugin has changed but the function is the same. I've now made `/logmessage(s)` an alias of `/loginmessage` by default.
