### ISSUE TITLE
/warn failing to show to players without a staff role.

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2252]
When using /warn on a staff, it gives the following pop up (first screenshot) - while warning a player without a staff rank gives no pop up (screenshot two and three). 

**To Reproduce**
1. Run /warn on a staff
2. have them send screenshot, see correct output.
3. Run /warn on a non staff
4. Have them send a screenshot, see error.

**Expected behavior**
/warn *should* print what is seen in the first screenshot, to anyone who got /warn'd

![Screenshot_190](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/67767916/df8f10f1-a298-4cbd-b448-58fb392330a5)
![Screenshot_191](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/67767916/32971694-2f0c-4cb5-b01f-c2dcd3a91bdb)
![Screenshot_192](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/67767916/3a302670-096b-4582-b6f1-ffe464b1ccf9)

**Comment by WisconsinWinters** [comment]
fixed
