### ISSUE TITLE
Visual bug of tax

### ISSUE THREAD

**Issue by ManBaguette** [ObliqueNetwork/Terra#2253]
**Describe the bug**
Shows the wrong amount you must pay for breeding.

**To Reproduce**
1. Do the usual and put your pokemon in the day care
2. Look at the price you'll have to pay
3. Look at the requirements to commence breeding

**Expected behavior**
Show the same amount

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/141190982/772e6eb5-a382-4376-a7a6-809f75d7dddd)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/141190982/f529740f-4e3e-4e11-815b-d1d8e6e45660)

**Username:**
ManFeguette

**Server name (all applicable):**
Titan

**Logs:**
Don't think logs are needed for this

**Additional context**
You'll be paying the price in the first screenshot ($2000) which should be the normal price

**Comment by WisconsinWinters** [comment]
fixed
