### ISSUE TITLE
Incorrect poaching breedable status

### ISSUE THREAD

**Issue by ManBaguette** [ObliqueNetwork/Terra#2254]
**Describe the bug**
It says "Breedable: TRUE" even though I've made it unbreedable. Even when the pokemon is breedable it says "FALSE"

**To Reproduce**
1. Go to /poaching
2. Click on "Any Level 1 Pokémon"
3. Hover over the pokemon you want to sell
4. Look at breeding status
5. See error

**Expected behavior**
the opposite breeding status

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/141190982/a59813aa-e795-41cf-aac0-2046f651003e)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/141190982/c0388248-583e-4bdf-9030-bc03be58604a)

**Username:**
FeguetteMan

**Server name (all applicable):**
Titan

**Logs:**
No need

**Additional context**
The male is the unbreedable and female is breedable.

**Comment by CenizaRey** [comment]
Fixed! Thanks for the report, closing
