### ISSUE TITLE
Votestreaks still able to be accessed through /vote GUI despite being disabled

### ISSUE THREAD

**Issue by WisconsinWinters** [ObliqueNetwork/Terra#2255]
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/afae1b40-b10e-4081-9979-8b1c1cb2b71a)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/c1ac9612-30b9-4df9-949f-7df284c11b13)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/d8509616-e92f-4468-9a90-159122868f9e)

**Comment by Rasgnarok** [comment]
Vote Streaks is now enabled, closing
