### ISSUE TITLE
Can only make 1 Pwarp (atlas)

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2256]
**Describe the bug**
Can only create 1 Pwarp on atlas versus being able to make 3

**To Reproduce**
1. Play on atlas
2. Make a pwarp
3.Make a second pwarp
4.Gets error message

**Expected behavior**
when trying to make a second pwarp it says that we can only make one pwarp

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/137843758/c19ebd80-4eb5-44a6-bb90-4fe8d87a5ce6)

**Username:**
itsAmaze
**Server name (all applicable):**
Atlas

**Comment by Rasgnarok** [comment]
Fixed
