### ISSUE TITLE
Paintings can be placed in any claim including admin claims

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2257]
For instance, in spawn and the end main island paintings can be placed regardless of trust access. same can be said for items frames. I'm not sure how many other items/blocks but i'm checking.

**To Reproduce**
Simply just go to any claim and place a painting. You can place it but cannot break it

**Expected behavior**
Players should not be able to affect other claims they are not trusted in.

**Username:**
_Peyton_7

**Server name (all applicable):**
Peyton

**Comment by chefburne** [comment]
This is no longer an issue, thank you for reporting
