### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by Blanobo** [ObliqueNetwork/Terra#2258]
**Describe the bug**
Pokemon are losing HA when being evolved. 

**To Reproduce**

1. Evolve a pokemon that requires and item or stone to evolve.
2. Lose the HA :(

**Expected behavior**

When evolving a pokemon via an evolution stone or item the pokemon will lose their Hidden Ability (tested on HA Clefable and Gligar lost HA on evo, HA Litten and Trapinch stayed on evo) 

**Screenshots**

![2023-08-08_03 43 47](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/133820465/d6bca8ba-defc-4f45-86d7-257864290008)

![2023-08-08_03 44 17](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/133820465/2ce15679-0988-4950-9a21-0b5c46ecb992)

![2023-08-08_03 44 43](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/133820465/51d2855f-2989-428c-8a85-1ce31bc292e2)

**Username:**
Blano

**Server name (all applicable):**
Orion
(maybe on all servers? I don't know)

**Comment by Khrisstias** [comment]
Sadly this is a pixelmon bug: https://pixelmonmod.com/tracker.php?p=2&t=20520 so we can't do much other than manually edit the pokemon's ability to the right one
