### ISSUE TITLE
[Feature] Ball Modifiers 

### ISSUE THREAD

**Issue by Tairano420** [ObliqueNetwork/Terra#2260]
**Describe the bug**
Ball modifiers do not work after recent update, once you select a mon it is meant to display what ball you want to change it to but it shows nothing

**To Reproduce**
1. Use a ball modifier
2. Select pokemon
3. Nothing pops up

**Expected behavior**
Select mon and then be shown all the different types of balls to be changed to.

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/87144451/f6745a54-f27c-485a-99c0-f332f8650d68)

**Username:**
NoobJeffy
**Server name (all applicable):**
Atlas

**Comment by chefburne** [comment]
This has been fixed, thank you for reporting
