### ISSUE TITLE
Custom Pokemon's Abilities being wrong on evo

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2261]
**Describe the bug**
Custom Pokemon Dont seem to keep their abilitys upon evolving whether it be HA or not. In this particular instance, Ekans with shed skin Evolved into Adnocana with intimidate when it should have been levitate. What I believe is happening is that Ekans has Shed skin which is an ability Adnocana doesnt have so it picks at random which regular ability it will then take.

**To Reproduce**
Evolve custom pokemon and check their ability afterwards

**Expected behavior**
Should Evolve to the proper corresponding ability pertaining to the certain custom mon

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/95523378/8db9b601-f0a8-4271-82cd-971eed6f3a30)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/95523378/c236a88f-0ab9-4439-a88d-051b05d783e1)

**Username:**
_Peyton_7

**Server name (all applicable):**
Peyton

**Comment by CenizaRey** [comment]
Good theory, but that’s not what’s happening. Easy fix though, thanks for the report!
