### ISSUE TITLE
[Custom Balls] Wrong names

### ISSUE THREAD

**Issue by TheKeyblade** [ObliqueNetwork/Terra#2262]
**Describe the bug**
When you obtain the custom balls (Ex: Shiny ball) the item names look like they're broken

**To Reproduce**
1. Obtain a Custom Ball
2. Hover over them
3. Shiny balls item name is "item.pixelmon.shiny_ball"

**Expected behavior**
Item name should be just Shiny Ball

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/133035392/2197ab6f-ebd6-4c68-b31c-a26296ae67cd)

**Username:**
TheKeyblade
**Server name (all applicable):**
All

**Additional context**
I think all the other balls on Beta have similar issues as well

**Comment by CenizaRey** [comment]
Known bug, fixed in next resource pack update. Thanks for the report! Closing.
