### ISSUE TITLE
[Battle Tower] Teleporting into empty rooms

### ISSUE THREAD

**Issue by colgatetoofpaste** [ObliqueNetwork/Terra#2263]
**Describe the bug**
Whenever you try to initiate Battle Tower, you get placed into an empty room with no NPC in sight.

**To Reproduce**
1. Do /battletower
2. Click on the key

**Expected behavior**
Generally, you get teleported into the room, and fight the floor's NPC.

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/49378349/ab4383b3-6662-4605-8af3-9aeecbfc52b6)

**Username:** colgatetoofpaste

**Server name (all applicable):** Orion, Titan, Atlas

**Logs:**
[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/12347057/latest.log)

**Comment by Khrisstias** [comment]
Thank you for the ticket, I made an internal ticket on the gitlab already so i will link this one to the internal ticket.
