### ISSUE TITLE
the command /Nexus won't let me click on any of the icons

### ISSUE THREAD

**Issue by GhostlyComets** [ObliqueNetwork/Terra#2265]
I haven't played Pixelmon for a few months, since before the reset. Some new things have appeared, such as the command /nexus. I decided to try it out because I wanted to look through all of the commands, but none of the icons are letting me click on them except the one titled "links." I'm not sure if I need to download anything. I do have the updated resource pack installed!

To reproduce:
1. Type the command /nexus
2. Click on literally any of the icons except the one titled "links."
3. It'll say, at least for me, "Unknown Command. Type /help for help."

**Expected behavior**
I expected to be able to see, specifically, the commands of the server. I initially wanted to turn off cross-server chatting since I always get confused about it, but forgot the command.

**Screenshots**
file:///C:/Users/Aaron/Downloads/2023-08-16_00.00.41.png

**Username:**
GhostlyComets

**Server name (all applicable):**
Titan

**Logs:**
No logs for this, I don't think.

**Comment by chefburne** [comment]
closing as https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/2325 details the same issue
