### ISSUE TITLE
Bypass /wt confirmation

### ISSUE THREAD

**Issue by Squidammo** [ObliqueNetwork/Terra#2266]
We can bypass /wt confirmation by:

1. trying to /wt a lvl 1 pokemon
2. trying to /wt another pokemon in the same slot an hour later (or 10 hours later even)

Solution: maybe should add a confirmation reset after 5 minutes

**Comment by Rasgnarok** [comment]
This needs replicating before moving this ticket to https://github.com/EnvyWare/WonderTrade-Forge/issues

**Comment by WisconsinWinters** [comment]
unable to replicate, after resetting cooldown and wondertrading slot 1

**Comment by Squidammo** [comment]
the exact steps were:
/wt anything on the first slot
Wait (no matter how long)
switch your slot with a new pokemon
/wt this new pokemon on this same slot

This should bypass the confirmation but I doubt this is still an issue as this post was made almost a year ago

**Comment by WisconsinWinters** [comment]
as I manually reset my cooldown, and still had to confirm, I am considering this fixed.

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/33f5ee4c-9431-408a-9a6c-934070693cf5)
