### ISSUE TITLE
[Move Tutor] Enamorus has incorrect Tutor learnset

### ISSUE THREAD

**Issue by colgatetoofpaste** [ObliqueNetwork/Terra#2267]
According to the Pixelmon Wiki, and as verifiable on a singleplayer world, Enamorus should be able to learn Earth Power and Mystical Fire from a Move Tutor. However, if you attempt to do so while on Nebula, the moves become unlearnable.

Screenshots are all in this zip folder: [move_tutor_issue.zip](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/12373761/move_tutor_issue.zip)
Two screenshots display the move tutor in singleplayer, with the two different Enamorus forms. 
Three screenshots show each of Earth Power, Mystical Fire, and Iron Defense selected on the Nebula server at various move tutors, with only Iron Defense being learnable.
The remaining screenshot shows the player's inventory with 10 Heart Scales, more than enough to be able to obtain one of the moves.

**Username:** colgatetoofpaste, but discovered by IeuanCat

**Server name (all applicable):** occurred on Orion; untested on Titan and Atlas

**Comment by Khrisstias** [comment]
I have fixed this, it is now pending restart on all servers
