### ISSUE TITLE
Certain JUMP! forms not being able to be fished up.

### ISSUE THREAD

**Issue by Oryso** [ObliqueNetwork/Terra#2268]
**Describe the bug**
I will start out by saying there are many different JUMP! forms for certain pokemon.

32 JUMP! Magikarp
12 JUMP! Shellos
8 JUMP! Clobbopus
9 JUMP! Spheal
8 JUMP! Slugma (and their corresponding magmar palettes)

 Currently the entirety of clobbo, spheal, and slugma are not able to be fished up with any kind of rod. (I've spent multiple hours looking pre-reset, especially for slugma which I've probably spent close to 8 hours on) And even if you palette mod the slugma forms, evolving a magby with them in party also won't add the slugma texture to the magmar as its supposed to. (I did make a ticket about this specific issue before I believe)

 The shellos forms ARE able to be fished up, however they're incredibly rare. This is fine in my opinion because that just makes fishing them up all the more rewarding, but if you were to make a stickerbook section for them I'd put it into a seperate section besides the Karp one.

 Now for the Karps. Out of all 32 forms, both me and Blano have already spent hours fishing for them and have found some issues with 6 of them. 2 of the 6, "White Forehead" and "White Mask" have different names on the wiki than what the palette in game says, which is "Orange Forehead" and "Orange Mask". This itself isn't too big of an issue as long as people are aware they're the same thing.

 The other 4 however, "Orange Two-Tone", "Pink Two-Tone", "Blue Raindrops", and "Violet Raindrops", are either not able to be fished up, or are incredibly rarer than they're supposed to be. The wiki for JUMP! forms says that the percentage of getting an Orange Two-Tone from a So-So appraised Old Rod is 11.63%. Blano spent at least 30 minutes fishing with just a So-So rod and got multiple of every other form, but no Orange Two-Tone, even though the Two-Tone in wiki states that its the most common one.

**To Reproduce**
1. Get an appraised fishing rod
2. Go to a body of water, or lava for slugma
3. Fish
4. Not fishing up the palettes mentioned above

**Expected behavior**
Able to fish up every JUMP palette as intended.

**Username:**
Oryso

**Server name (all applicable):**
Orion (Probably all)

**Additional context**
Here's the link to the wiki page if you need/want it
https://pixelmonmod.com/wiki/Jump

Also if you need anymore info about it, just let me know. I'm not the best at explaining things.

**Comment by Khrisstias** [comment]
This is a confirmed pixelmon bug

**Comment by chefburne** [comment]
These have been added through our datapack, closing
