### ISSUE TITLE
[NPC Gyms] Issue with Gym Leaders being offline still persists

### ISSUE THREAD

**Issue by colgatetoofpaste** [ObliqueNetwork/Terra#2269]
**Describe the bug**
NPC Gyms still do not work if there are no Gym Leaders online, except for the first gym.

**To Reproduce**
1. Type /gyms
2. Click on the next gym in progression (this assumes you've beaten gym 1)
3. Note the "there are no gym leaders online!"

**Expected behavior**
The Gym Leaders being online should not affect NPC gyms, and yet it does.

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/49378349/e49d027a-cd6f-44c1-9588-e2bd7f309c8b)
This is after defeating gym 1.

**Username:** colgatetoofpaste

**Server name (all applicable):** Applies to Orion, but may apply to Titan and Atlas

**Comment by chefburne** [comment]
no longer an issue, closing
