### ISSUE TITLE
omen kits

### ISSUE THREAD

**Issue by koy0561** [ObliqueNetwork/Terra#2270]
cannot preview omen quarterly 
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/111909101/b4401ade-9a46-49b9-a649-c700126d8795)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/111909101/eb107cee-4c84-4c38-ae7d-c2323772e400)

**Comment by CenizaRey** [comment]
The reason for this is because there's no actual "items" to give. Claiming the Omen Quarterly Kit runs commands, it doesn't straight up give items. Regardless, the "right click to preview" option has been removed from this kit. Thanks for the report! Closing
