### ISSUE TITLE
[Raid Dens] Extra Wishing Piece consumed when thrown into a den

### ISSUE THREAD

**Issue by colgatetoofpaste** [ObliqueNetwork/Terra#2272]
**Describe the bug**
When a Wishing Piece is thrown into a Raid Den to activate it (as in, item dropped by hand onto the den), if the player is holding at least one extra Wishing Piece, another will be consumed (for a total of 2 Wishing Pieces)

**To Reproduce**
1. Grab at least two Wishing Pieces
2. Go to an inactive Raid Den
3. Throw in a Wishing Piece
4. Notice the extra Wishing Piece removed from the inventory

**Expected behavior**
Doing this should only consume the first Wishing Piece, not one in the player's hand.

**Video evidence**
https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/49378349/9b64cf7c-4e2b-419c-9179-49fc2f56d17c

**Username:** colgatetoofpaste

**Server name (all applicable):** Video taken on Orion, but first noted on Atlas

**Logs:**
[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/12425958/latest.log)

**Additional context**
This bug does NOT occur in singleplayer--I tested it and only a single Wishing Piece was consumed.

**Comment by Rasgnarok** [comment]
This was a Pixelmon bug that has now since been fixed, a quite annoying one at that.
https://pixelmonmod.com/tracker.php?p=2&t=21085
