### ISSUE TITLE
Players get gym battle rewards when /endbattle is used

### ISSUE THREAD

**Issue by Schmlif24** [ObliqueNetwork/Terra#2273]
Occasionally, when /endbattle is used in the case of a bug or the challenger not following rules, the challenger will still get the rewards as if they beat the gym but will not have the badge in /gyms badgecase.

I've tried to reproduce this with no success. Whether it be myself or the other player using /endbattle. So I'm sorry I can't provide anything here.

**Expected behavior**
The battle should end with no winner, the challenger should not get the associated badge in their badgecase, and no rewards should be given.

Schmlif224

All servers

**Logs:**
this is all I have at the moment but it does display that Eparrot recieved the challenger tag and money after /endbattle was used in the nogrod gym.
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/140265090/325e175f-7697-47aa-8919-48a6ec0fce52)

**Comment by Schmlif24** [comment]
Here's the full log of the above image if this helps any more
[2023-08-25-1.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/12442535/2023-08-25-1.log)

**Comment by chefburne** [comment]
this has been solved, thanks for reporting
