### ISSUE TITLE
[/wiki moves] Plugin not working

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2274]
**Describe the bug**
On any server trying to view moves on /wiki nothing happens

**To Reproduce**
1. /wiki (pokemon of choice) and select moves

**Expected behavior**
It should then pop up a list of all the learnable/teachable moves for that particular pokemon

**Username:**
_Peyton_7

**Server name (all applicable):**
Peyton

**Comment by Rasgnarok** [comment]
This is actually a Pixelmon bug, forwarding here: https://pixelmonmod.com/tracker.php?p=2
