### ISSUE TITLE
Move options on /wiki doesnt work

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2276]
**Describe the bug**
When using the ingame wiki the option that is suppose to display all the moves that pokemon can learn does not work. If i click on the moves option it does not display anything similarly if i do /wiki pokemon moves this also does not work

**To Reproduce**
1. /wiki any pokemon
2. click on moves
3. see error

**Expected behavior**
upon clicking the moves option or using it within the /wiki command it is suppose to display all the moves that pokemon can learn from levelup and tms 

**Screenshots**

**Username:**
itsAmaze
**Server name (all applicable):**
All

**Comment by Rasgnarok** [comment]
This is a Pixelmon bug, please report to the tracker: https://pixelmonmod.com/tracker.php?p=2
