### ISSUE TITLE
[Feature] Rayquaza Changes from Viral to Regular When Mega Evoing in Battle Tower

### ISSUE THREAD

**Issue by Ultamategamer26** [ObliqueNetwork/Terra#2277]
**Describe the bug**
A player had a Viral Rayquaza and battled in the battle tower. They hit mega evolve and after the battle the Rayquaza went back to regular, no Viral form.

**To Reproduce**
1. Get Viral Rayquaza
2. Battle in Battle Tower
3. Mega Evolve Rayquaza
4. See Rayquaza is now regular

**Expected behavior**
It isn't supposed to go back to regular form, and should stay as Viral form.

**Screenshots**
No screenshota

**Username:**
Ultamate

**Server name (all applicable):**
Titan

**Comment by Rasgnarok** [comment]
This is actually a Pixelmon bug, custom datapack forms with 'special interactions' (such as Dragon Ascent) will revert previous forms in their transition to the 'special' form (eg, the mega form). It needs resolving on their side: https://pixelmonmod.com/tracker.php?p=2
