### ISSUE TITLE
[LeaderBoards] Player EXP gets Reset for Ultamate after server restart in morning

### ISSUE THREAD

**Issue by Ultamategamer26** [ObliqueNetwork/Terra#2278]
**Describe the bug**
Ultamate's exp for the Player EXP leaderboard gets reset to N/A after each server restart in the morning. I get the EXP from either coal mining, or furnace smelting.

**To Reproduce**
1. I get EXP through mining coal and smelting, and get 1st on Leaderboard
2. I Log Off
3. Server gets Restarted
4. I Log on and see I am in last place with a score of N/A

**Expected behavior**
I am supposed to remain with my EXP score after server restart

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/46078010/89fdeed2-4d83-447c-8525-4f74e35c8d0c)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/46078010/244dfde0-5cd9-4f2e-acba-1ccc16217694)

**Username:**
Ultamate

**Server name (all applicable):**
Atlas

**Logs:**
[techniclauncher_2023-09-02.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/12518095/techniclauncher_2023-09-02.log)

**Comment by Rasgnarok** [comment]
LBs have been disabled for upcoming Clan LBs.
