### ISSUE TITLE
Omen command issues 

### ISSUE THREAD

**Issue by Quadehar97** [ObliqueNetwork/Terra#2279]
Atlas 
Ign: Quadehar97 

I just went through the list of Omen commands to see what ones worked and I put a red dot next to the ones that don't.

![Screenshot_20230905_195742_Samsung Internet](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/67765177/9e47605f-e201-4b71-b312-715a93e03451)
![Screenshot_20230905_195751_Samsung Internet](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/67765177/71397668-091a-406f-8ac4-13ac6113a35b)
![Screenshot_20230905_195800_Samsung Internet](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/67765177/36299b41-bba7-4c97-8a4a-45bb85bd6eaa)
![Screenshot_20230905_195833_Samsung Internet](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/67765177/785c0519-eef9-4451-87ef-8066eefda5f5)

**Comment by Azazels696** [comment]
the -Breakegg- command work for me...use it every day ..try with num slot like ..: /breakegg 3
 <3

**Comment by WisconsinWinters** [comment]
I've fixed /craft for all of the Omens on live.

However, the rest of the commands such as /head and /mobhead will need to be re-implemented as a custom plugin on our end, as those were under a different command system that we are no longer using.

**Comment by Rasgnarok** [comment]
I'll investigate /glow, /head, /textcolor and /mobhead, but some of them like /launch and /ride are simply not possible anymore. As for /se, we had to remove it because people kept abusing it in other people's sign shop stores. Similar story for no-cooldown /rtp, some people spammed it 30-50 times a minute, which meant the server actually lagged out thanks to them.

As for the /redeem gui screen, it is still working, the menu's just moved to [ESC]'s Pixelmon menu cosmetic screen.

**Comment by WisconsinWinters** [comment]
> I'll investigate /glow, /head, /textcolor and /mobhead, but some of them like /launch and /ride are simply not possible anymore. As for /se, we had to remove it because people kept abusing it in other people's sign shop stores. Similar story for no-cooldown /rtp, some people spammed it 30-50 times a minute, which meant the server actually lagged out thanks to them.
> 
> As for the /redeem gui screen, it is still working, the menu's just moved to [ESC]'s Pixelmon menu cosmetic screen.

/head has been replaced with essentials /skull.

**Comment by WisconsinWinters** [comment]
I've figured out that /head is now functionally /hat, and fixed /skull to be able to spawn in other players heads as intended.
