### ISSUE TITLE
[Raid Dens] Throwing wishing pieces sometimes deletes items

### ISSUE THREAD

**Issue by Uschalabamba** [ObliqueNetwork/Terra#2280]
**Describe the bug**
A semi consistent bug where throwing a wishing piece into an empty raid den deletes items from your inventory. This seems to be restricted to items in your hotbar and only happens upon dropping the wishing piece with Q, not when right clicking. Out of 11 pieces, items got deleted 4 times. An additional wishing piece was consumed twice, and another hotbar item was deleted the other times (each in different hotbar slots). While not consistent, it seems to happen fairly regularly.

Reproduce:

1: throw a wishing piece into an empty raid den
2: After the raid has spawned, see if any items got deleted
(sadly not very consistent)

I can confidently say that Items didnt accidentally drop from the initial Q press since sometimes items in different hotbar slots got deleted.

All tests from me were conducted in an ultra forest in 2 different dens. There didnt seem to be a link to the raids star level or specific pokemon.

Username: Uschalabamba

Tests were conducted on Orion.

Log file:
[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/12541471/latest.log)

**Comment by Uschalabamba** [comment]
As requested here are the videos of the bug in action.
Here is the one where another item gets removed:

https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/58392021/63a70e7a-cb71-4249-a5c8-d109715124d3

And here the one where another wishing piece gets consumed:

https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/58392021/25fa9ec3-7d34-4bfc-bc92-75f1aec18618

Note that this is not because of a second accidental Q press, since the item gets immediatly removed, and there is no drop animation.

I did not previously know they were consistent with this "setup" but they seem to be now, at least for me. I can recreate each scenario with 100% accuracy.

**Comment by Rasgnarok** [comment]
This was a Pixelmon bug that has now since been fixed, a quite annoying one at that. 
https://pixelmonmod.com/tracker.php?p=2&t=21085
