### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by Schmlif24** [ObliqueNetwork/Terra#2282]
Altaria's hidden ability is shown in /wiki as 'Shroud Body' instead of Cloud Nine

**To Reproduce**
1. do /wiki Altaria
2. Abilites list displays Natural Cure and 'Shroud Body'

**Expected behavior**
the hidden ability should be cloud nine instead of shroud body

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/140265090/68f7379b-e1bd-4862-81d5-4cc25d609354)

Schmlif224

Titan

**Comment by Rasgnarok** [comment]
This should be fixed now.
