### ISSUE TITLE
[Feature] Basculegion has the wrong first ability

### ISSUE THREAD

**Issue by Ascix** [ObliqueNetwork/Terra#2283]
**Describe the bug**
Basculegion is shown to have Rattled, when it should have Swift Swim.

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/65693329/a5756d08-d434-4a1f-9aa7-004acd98ee48)

**Username:**
Audacideez

**Server name (all applicable):**
Titan

**Comment by chefburne** [comment]
closing as https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/2321 details the same issue
