### ISSUE TITLE
Gym Rules don't display on /nexus

### ISSUE THREAD

**Issue by Schmlif24** [ObliqueNetwork/Terra#2284]
Gym Rules don't display when selected on /nexus

**To Reproduce**
1. use /nexus in game
2. select Gym Rules
3. Stated "Unknown command. Type /help for help"

**Expected behavior**
should provide an in game list of gym rules or a link to the gym rules github page at https://github.com/NebulaMC-GG/Bugs-and-Issues/wiki/Gym-Rules

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/140265090/87055a86-3f8f-4916-95ef-4794500b850c)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/140265090/aefa054b-9e3a-42ff-9b30-c282d7ae9079)

Schmlif224

Titan

**Comment by chefburne** [comment]
closing as https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/2325 details similar issue
