### ISSUE TITLE
Adventure and Wilderness portal in spawn don't work

### ISSUE THREAD

**Issue by Mellozilla** [ObliqueNetwork/Terra#2285]
**Describe the bug**
The adventure and wilderness portals in spawn do not work. they take you to the nether

**To Reproduce**
1. Go to spawn and walk through either the adventure map portal or wilderness portal and enter

**Expected behavior**
All nether portals in spawn that are linked to either the wilderness or the adventure map lead me to the nether

**Screenshots**

**Username:**AFadedColor

**Server name (all applicable):**Atlas-Orion-Titan

[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/12580023/latest.log)

**Comment by Rasgnarok** [comment]
Needs re-testing, I've fixed this numerous times

**Comment by Mellozilla** [comment]
this works as intended now ^^
