### ISSUE TITLE
UI blinking on and off

### ISSUE THREAD

**Issue by Hawkyshadows** [ObliqueNetwork/Terra#2287]
**Describe the bug**
The game was glitching in and out of the battle menu

**To Reproduce**
I'm not sure if it can be reproduced but I was leveling up two pigeottos for a scroll at the time one of them was pink

**Expected behavior**
The screen should start blinking in and out of battle screen disconnecting and rejoining fixed the problem

https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/111762972/73951859-3089-4695-a5e8-a0e8978ace91

**Screenshots**
I have a video

**Username:**
Hawkyshadows
**Server name (all applicable):**
Atlas
**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by chefburne** [comment]
Closing as no one has been able to reproduce
