### ISSUE TITLE
chat alert for personal boosters misspelled

### ISSUE THREAD

**Issue by Mellozilla** [ObliqueNetwork/Terra#2289]
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/116930379/6727754e-7401-4cb0-9a9f-e918f0ad472c)
the "you can only have one personal booster at a time" chat alert has improper grammar in it, the word can is misspelled.

**Comment by chefburne** [comment]
This has been fixed, thanks for reporting!
