### ISSUE TITLE
Staff leave and join alerts 

### ISSUE THREAD

**Issue by Mellozilla** [ObliqueNetwork/Terra#2290]
the join and leave logs are only showing up for staff, not the actual players. unless the server crashes then we see them leave. thats the only time though
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/116930379/d4c1a048-5932-4408-b5d2-5a261ce6572a)
these logs for example^ we can only see players tagged as staff leave and join. the only time we see players leave and join is if the server gets shutdown/crashes

**Comment by Rasgnarok** [comment]
Needs re-testing to see if issue persists

**Comment by danorris709** [comment]
These join and leave messages are not intended for normal players. These are part of the staff chat. Not a bug.
