### ISSUE TITLE
Gym Pokemon leveling up

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2292]
**Describe the bug**
When doing gym battles the gym pokemon start to level up when they are not suppose to 

**To Reproduce**
1. Battle a gym leader
2. see error
3. 
**Expected behavior**
The gym pokemons should not level up or get xp 

**Username:**
itsAmaze
**Server name (all applicable):**
All Servers

**Comment by chefburne** [comment]
closing as https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/2317 details the same issue
