### ISSUE TITLE
[/trust] Cannot trust players who aren't online

### ISSUE THREAD

**Issue by FarDiamond** [ObliqueNetwork/Terra#2293]
**Describe the bug**
You can only /trust players who are online (in titan and orion)

**To Reproduce**
1. Go to Titan or Orion
2. Make claim
3. /trust [online player]
4. See them trusted
5. /trust [offline player]
6. "Player [offline player] is not found."
7. See error

**Expected behavior**
You should be able to trust people who are offline

**Username:**
FarDiamond3049
**Server name (all applicable):**
Titan, Orion
**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by WisconsinWinters** [comment]
this is a griefdefender issue, something we can't fix
