### ISSUE TITLE
Charizard Name Color Shows Wrong Color

### ISSUE THREAD

**Issue by Oryso** [ObliqueNetwork/Terra#2295]
**Describe the bug**
After beating the charizard world boss, I tested the name color and instead of being the charizard colors it has the same colors as mewtwo's.

**To Reproduce**
1. Equip Charizard name color
2. Type in chat
3. See wrong color

**Expected behavior**
Have the name color be the correct charizard colors.

**Screenshots**
![2023-09-27_22 22 16](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/dfc1fd90-ab82-4e3a-b80e-a18aeb4fcc1a)

![2023-09-27_22 22 19](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/47b07c59-0e2b-4ba7-a547-468ce6c36f22)

**Username:**
Oryso (Also see it happening with Azezel11)

**Server name (all applicable):**
Orion

**Additional context**
The tag seems to be working just fine.

**Comment by chefburne** [comment]
Resolved, thank you for reporting
