### ISSUE TITLE
/party command display bug

### ISSUE THREAD

**Issue by Asiryft** [ObliqueNetwork/Terra#2296]
When using the /party command, it will show unbreedable mons as breedable

To reproduce
1. Grab an unbreedable mon
2. Do /party and check its breed status

Should see it list the mon as breedable, even though it isn't

Asiryft

Titan, Orion, Atlas

Several players across all 3 servers have been having this issue

**Comment by Rasgnarok** [comment]
Needs re-testing to see if issue persists

**Comment by WisconsinWinters** [comment]
forwarded to internal tracker
