### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by Malitae** [ObliqueNetwork/Terra#2297]
**Describe the bug**
Pokemon party slot 6 is having issues with a variety of commands.
Known issue commands are: adding to sticker book, /breakegg, etc

**To Reproduce**
1. Have pokemon in party slot 6 that matches the correct requirements for sticker book
2. Attempt to register pokemon
3. Will receive error that you are not the OT of the pokemon and it won't register

**Expected behavior**
Pokemon should register.

**Screenshots**

**Username:**
Malitae

**Server name (all applicable):**
Titan, Atlas, Orion 

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**
I haven't been able to try other commands but this seemed a general issue with the box itself not the command.

**Comment by chefburne** [comment]
closing as issue is resolved
