### ISSUE TITLE
[/flyspeed] Doesn't actually change the flying speed

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2298]
**Describe the bug**
When server reset neither /walkspeed nor /flyspeed worked. /walkspeed got changed and is fixed however /flyspeed doesn't change the actual flight speed. It shows up in chat that you are changing your speed but any speed change past /flyspeed 1 doesn't speed you up.

**To Reproduce**
1. Use the /flyspeed command and test the difference between flyspeed 1 and flyspeed 2 on against a certain distance. I tested it myself and got the same time from start to finish.

**Expected behavior**
/flyspeed 2 is meant to increase the speed at which you fly

_Peyton_7
Peyton

**Comment by WisconsinWinters** [comment]
I have a fix queued that'll let you go about 25% faster over normal flying speed with /flyspeed 10. The command works just a bit differently with EssentialsX, and flyspeed in this case will scale with the limits we have set in our configs.
