### ISSUE TITLE
[Name Color] Arceus namecolor reward shows as darkrai namecolor

### ISSUE THREAD

**Issue by FarDiamond** [ObliqueNetwork/Terra#2300]
**Describe the bug**
After beating the Arceus world boss, I tested the name color and instead of being the Arceus colors it has the same colors as darkrai's.

**To Reproduce**

1. Equip Arceus name color
2. - Type in chat
3. - See wrong color

**Expected behavior**
Have the name color be the correct Arceus colors.

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134177870/57720c53-7747-4b9c-a978-147c1996446c)

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134177870/8d95db66-b725-4e46-8b60-275c0b462b40)

**Username:**
FarDiamond3049 (nicknamed FarDiamond)

**Server name (all applicable):**
Titan

**Comment by chefburne** [comment]
Fixed, thank you for reporting
