### ISSUE TITLE
LB Rewards Listed

### ISSUE THREAD

**Issue by Aerinyan** [ObliqueNetwork/Terra#2301]
**Describe the bug**
The IV Booster listed in /lbrewards is a 30m iv booster but they are supposed to be 5m boosters only.

**To Reproduce**
1. run /lbrewards
2. hover on any block to view rewards
3. See error

**Expected behavior**
Edit hover to reflect 5m IV Booster reward instead of 30m

**Screenshots**

Hover:
![Screenshot 2023-10-03 135948](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/f43d7368-ade5-4eed-854f-7a0295b5b209)

Reward:
![Screenshot 2023-10-03 140739](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/81caa049-a96f-4768-9fb2-f538b58fbfda)

**Server name (all applicable):**
All

**Comment by Rasgnarok** [comment]
LBs have been disabled for incoming Clan LBs, closing.
