### ISSUE TITLE
Pokecolor bug dissapearing color

### ISSUE THREAD

**Issue by ShapooK** [ObliqueNetwork/Terra#2302]
**Describe the bug**
Doing /pokecolor on a pokemon and then relog removes the pokecolor on said pokemon.
**To Reproduce**
1. do /pokecolor (slot) &1hi 
2. Throw pokemon out, See color of said pokemon 
3. Relog, throw pokemon out, see only name stayed and has color
4. See Error

**Expected behavior**
The color should stay when player relogs 

**Screenshots**

**Username:**
ShapooK

**Server name (all applicable):** 
Titan
Most likely all

**First pic is when pokecolor was added to the mon, the second pic was when i relogged and threw out the mon**

![pokecolor1](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35164973/d0a89990-6ce1-4b51-9302-fdc9f256cfa9)
![pokecolor2](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35164973/c9503039-af10-4737-800f-7d2a6125acfd)

**Comment by Rasgnarok** [comment]
Needs re-testing to see if issue persists

**Comment by WisconsinWinters** [comment]
forwarded to pixelmon
