### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by iamcjmxv** [ObliqueNetwork/Terra#2303]
**Describe the bug**
/ss and /socialspy on disables socialspy no matter what

**To Reproduce**
1. run /ss or /scoialspy on
2. look at chat

**Expected behavior**
Should enable social spy not disable it 

**Username:**
_Conj 

**Server name (all applicable):**
All

**Comment by chefburne** [comment]
This has been fixed, closing
