### ISSUE TITLE
V-Create cannot be learned

### ISSUE THREAD

**Issue by bucketcow** [ObliqueNetwork/Terra#2306]
V-Create, a move that should be able to be tutor transferred for Rayquaza, is absent from the list of moves in the transfer tutor.

**To Reproduce**
Use a Rayquaza at a transfer tutor, or any of the move tutors in the villages in /warps. I visited all of them, none of which had V-Create.

**Expected behavior**
In the Pixelmon wiki, it states that V-Create should be obtainable from transfer tutors.

**Screenshots**
![image_2023-10-06_044328287](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/147104548/f38c5c31-be72-4aac-82a6-9ee453d96d10)

**Username:Bucketcow**

**Server name (Orion):**

**Additional context**
![Screenshot 2023-10-06 044119](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/147104548/c93e4f81-ca26-4b64-88cf-77c9752420fd)

**Comment by Rasgnarok** [comment]
Added V-Create to `/spawn`'s Transfer Tutor for the cost of 5 Heart Scales.
