### ISSUE TITLE
Cosmic Crate Ditto

### ISSUE THREAD

**Issue by Aerinyan** [ObliqueNetwork/Terra#2307]
**Describe the bug**
Store list's chance to win a 6iv HA Unbreedable Ditto but should be 31ivs HP HA Unbreedable Ditto which is reflected in cosmic crate preview in game.

**To Reproduce**
1. Go to store
2. Click on Cosmic Crate Keys
3. Read items that can be won from crate

**Expected behavior**
Change listed Ditto reward in store to sync up with in game and actual reward.

**Screenshots**

![Screenshot 2023-10-06 163214](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/d4d054cd-c620-4206-90ff-38d0bdb0128a)

![Screenshot 2023-10-06 164629](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/0fe7cab9-4134-457b-b15b-c69724d97352)

**Server name (all applicable):**
All

**Comment by CenizaRey** [comment]
Fixed, thanks for the report! Closing
