### ISSUE TITLE
[/invsee] Items getting despawned

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2308]
**Describe the bug**
Sometimes when taking items from someone else's inventory with /invsee the item you're taking and placing into your own inventory glitches and jumps to a different slot and despawns whatever you had in that slot. For instance, I was taking a lure from someone and placing it into the sixth slot in my hotbar but it jumped to the first slot  which help my netherite pickaxe which was now gone. It doesn't happen every time.

**To Reproduce**
1. /invsee someone
2. Drag and drop an Item from their inventory into your own over and over

**Expected behavior**
The Item you place in your inventory goes into the slot you chose and doesn't despawn your items

_Peyton_7

Peyton

**Comment by Rasgnarok** [comment]
Needs re-testing to see if issue persists

**Comment by WisconsinWinters** [comment]
this is a known issue with EssentialsX, and they recommend a different solution when it comes to editing inventories. 

https://github.com/EssentialsX/Essentials/issues/3065
