### ISSUE TITLE
[/ignore] doesn't work (edited title to new issue)

### ISSUE THREAD

**Issue by FarDiamond** [ObliqueNetwork/Terra#2309]
**Describe the bug**
./ignore ignores people. But trying to ignore someone on a different server gives "Error: Player not found" and if you go to the server their own to /ignore and go back to your own; you can still see them like nothing happened

**To Reproduce**
1. /ignore [player on different server]
2. See "Error: Player not found"
3. /server [their server]
4. /ignore [player]
5. /server [original server]
6. See error (them still talking)

**Expected behavior*
./ignore should work across servers

**Screenshots**

**Username:**
FarDiamond3049 (nicknamed Far)

**Server name (all applicable):**
Titan (tried ignoring someone on Orion)

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by FarDiamond** [comment]
today i learned that /ignore doesn't work at all; just tried to /ignore someone in the same server for the first time today

**Comment by FarDiamond** [comment]
just learned /ignore doesn't work at all; tried to /ignore someone in the same server for the first time

**Comment by Rasgnarok** [comment]
Needs re-testing to see if issue persists

**Comment by WisconsinWinters** [comment]
It's still persisting. i've made an internal ticket suggesting a global ignore be added if possible
