### ISSUE TITLE
10k reward silent-announcement from Vote Crate.

### ISSUE THREAD

**Issue by Vongthao4** [ObliqueNetwork/Terra#2311]
**Describe the bug**
Got a vote key and used it on vote crate. Could be formatting error? The amount could be trivial for players.

**To Reproduce**
1. Get a vote key.
2. Open a vote crate.
3. Land on the 10k money *I assume it was 10k*.

**Expected behavior**
Chat to silent-announce "[NebulaMC] Ban_Vong has won 10k Coins from the Vote Crate!"

**Screenshots**
![Bug](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/147103910/58140854-e877-4073-ae7d-def4d44363ef)

**Username:**
Ban_Vong

**Server name (all applicable):**
Orion

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by chefburne** [comment]
This has been fixed, thank you for reporting!
