### ISSUE TITLE
Bypass Afk

### ISSUE THREAD

**Issue by MoonEverDark** [ObliqueNetwork/Terra#2312]
You can bypass afk by being in the daycare with finished eggs or breeding pair.
Tested with no eggs or breeding pair and does activate afk.

MoonEverDark

Orion

**Comment by WisconsinWinters** [comment]
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/e21b48b0-d7e1-478d-a45c-28bf0bae7d22)

I'm not able to reproduce this, anything else you have been doing?

**Comment by Rasgnarok** [comment]
Needs re-testing

**Comment by WisconsinWinters** [comment]
still not able to reproduce afterr re-testing, closing
