### ISSUE TITLE
Move Tutor in Nogrod does not let Celesteela learn Meteor Beam

### ISSUE THREAD

**Issue by raviolugh** [ObliqueNetwork/Terra#2314]
**Describe the bug**
The Move Tutor in Nogrod does not let Celesteela learn Meteor Beam despite having the heart scales required. 
**To Reproduce**
1. Go to -660.808, 107.06250, -683.348 (in Nogrod)
2. Have a celesteela in your party
3. Right click the move tutor
4. See error that you cannot learn Meteor Beam

**Screenshots**

**Username:**
raviolugh
**Server name (all applicable):**
Orion

![move tutor meteor beam](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139720449/f1616c81-5d92-4822-bfef-9a4c5ed7cee6)

**Comment by Rasgnarok** [comment]
Seems to be working now, closing.
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/18584380/a98525dd-9d05-4f78-828d-dd565bb17978)
