### ISSUE TITLE
Type with /breeding

### ISSUE THREAD

**Issue by Malitae** [ObliqueNetwork/Terra#2315]
**Describe the bug**
Just a typo with /breeding. 'bread' should be 'bred'

[14/10/2023 15:04:58 PM] [main/INFO] [CHAT] (!) Successfully bread Egg

**To Reproduce**
1. 2 breedable pokemon in party
2. /breeding clicking on the pokemon
3. successful breed with say 'Successfully bread Egg'

**Expected behavior**
'Successfully bread Egg'

**Screenshots**

**Username:**
Malitae
**Server name (all applicable):**
Likely all / tested Orion
**Logs:**
[14/10/2023 15:04:58 PM] [main/INFO] [CHAT] (!) Successfully bread Egg

**Additional context**

**Comment by PJLesure** [comment]
Fixed, thank you!
