### ISSUE TITLE
Two Vote Sites aren't working

### ISSUE THREAD

**Issue by Hawkyshadows** [ObliqueNetwork/Terra#2316]
**Describe the bug**
The first and 5th vote link do not work anymore

**To Reproduce**

Click the links

**Expected behavior**
They won't load

**Screenshots**
![IMG_5743](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/111762972/fbc6dfdc-cb16-40b1-9e8c-2915b785aed0)
![IMG_5744](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/111762972/204aa2e8-7bca-4c29-b89b-0ea3ac802490)

Hawkyshadows

All Servers

**Additional context**
The fifth link hasn't worked for a while, the entire site was apparently deleted, I had mentioned it not working before to an admin but the first link not working is a recent development as it worked fine yesterday

**Comment by WisconsinWinters** [comment]
removed the non-working voting links, closing
