### ISSUE TITLE
[Gyms] Pokemon gaining exp/levelling up

### ISSUE THREAD

**Issue by chrisdurocher** [ObliqueNetwork/Terra#2317]
Gym Pokemon on all three servers are gaining exp. and levelling up during battles.

This is not meant to be the case, Gym Pokemon are meant to stay at the level they have been given on the PokePaste.

Not sure what other info if any is needed, feel free to dm me on discord with any questions.

Discord: chrisdurocher

**Comment by Rasgnarok** [comment]
Forwarded to private Envyware Gym Github
