### ISSUE TITLE
[Shrines] Celebi caught in beast ball will not be Alien palette.

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2318]
**Describe the bug**
When catching Celebi in a beast ball, it would normally be caught as an alien palette Celebi which is not the case from the shrines plugin. 

**To Reproduce**
1. Summon Celebi'
2. Catch in a Beast Ball
3. See Error

**Expected behavior**
Caught celebi should be alien palette.

**Server name (all applicable):**
All servers

**Comment by PJLesure** [comment]
Pixelmon bug, reported to Pixelmon tracker.

**Comment by chefburne** [comment]
Fixed by Pixelmon, closing
