### ISSUE TITLE
Ancient Greninja form loss

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2319]
**Describe the bug**
Killing a pokemon in battle with Ancient Greninja will cause it to turn into ash greninja due to its ability, removing its ancient form.
**To Reproduce**
1. Give self Ancient Greninja
2. Enter battle and kill a Pokemon
3. See error

**Expected behavior**
You should see that Ancient Greninja turns into a normal Greninja after battle.

**Comment by Rasgnarok** [comment]
Fixed, next datapack update removes Battle Bond from being a valid ability with Ancient Form Greninja. All existing Ancient Greninja will need to be updated to match manually.
