### ISSUE TITLE
[Trade Scrolls] Some scroll steps do not work in claimflagged areas

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2320]
**Describe the bug**
Trying to do "Trade away X Pokemon" or any other trade scrolls do not work in a claim that is /claimflagdefinition pixelmon:user poke-spawn false. 

**To Reproduce**
1. Try to complete a trade scroll step on a trade machine in a claimed area with said claimflag

**Expected behavior**
The step should complete naturally but does not

**_Peyton_7**
**Peyton/FunPolice**

**Comment by Rasgnarok** [comment]
Needs re-testing, this should now work now that I've enforced poke-spawn

**Comment by WisconsinWinters** [comment]
closing as GD is no longer used.
