### ISSUE TITLE
Basculegion not having Swift Swim

### ISSUE THREAD

**Issue by ShapooK** [ObliqueNetwork/Terra#2321]
**Describe the bug**
Basculegion not having the "Swift swim" Ability, every where i seen it has every ability including swift swim, but in pixelmon it has every ability except "Swift Swim"  (Pixelmon wiki also shows that it does not have it) 

**To Reproduce**
1. /wiki Basculegion
2. See abilities, Only has "Rattled, Adaptability, Mold Breaker (HA)
3. Go to Bulbapedia, Serebii or any other site, Shows every single ability 

**Expected behavior**
Basculegion should have the "Swift swim" Ability if all other abilities are in the game except for swift swim 

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35164973/187cb3c4-2015-419b-8f4e-53ce9f95c7c5)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35164973/a0f33145-fc33-49bc-9ba9-80fb8cdde030)

**Username:**
ShapooK
**Server name (all applicable):**
Titan (All, tested)

**Comment by chefburne** [comment]
As of next update Basculegion will have Swift Swim as an ability, thank you for reporting
