### ISSUE TITLE
[Battle Tower] Kicked after win

### ISSUE THREAD

**Issue by chrisdurocher** [ObliqueNetwork/Terra#2322]
The Battle Tower still appears to be having it's issues with kicking challengers after a win, when it should progress them to the next level.

Have had players telling me about it happening to them recently. I've got a video recorded by a player of what it looks like when this bug occurs. I'll attach that video here. (Edit: Video is too big to attach despite being only about 10 seconds long, I'll hold on to it incase anyone would like it e-mailed to them)

Tested it for myself and had the same experience of getting kicked after a win with the same visual of falling through the world after beating last pokemon. I'll also attach my log file in case that is of any use:

This occurs right at 12:31pm EST. Here is a snippet from exactly when i experienced getting kicked, you can see it pushes me out of being afk once i get teleported back to spawn after being kicked from the battle tower.

[B#822] 2023/10/22 12:31:53 [INFO]  [12:31:53] [main/INFO] [minecraft/NewChatGui]: [CHAT] [NebulaMC Towers] Good Job, You beat the Ground Floor! You Won $1,250
[B#822] 2023/10/22 12:31:53 [INFO]  [12:31:53] [main/INFO] [minecraft/NewChatGui]: [CHAT] Server successfully added 1250.0 PokéDollars to your balance!
[B#822] 2023/10/22 12:31:55 [INFO]  [12:31:55] [main/INFO] [minecraft/NewChatGui]: [CHAT] You are no longer AFK.

Full Log:

[techniclauncher_2023-10-22 copy.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/13063969/techniclauncher_2023-10-22.copy.log)

**Comment by chrisdurocher** [comment]
New Battle Tower related bugs post update to 9.1.8

1. Randomly during a battle, the battle will end and send you to the next trainer as if you won the battle when this did not in fact happen.

2. Mega evolving has a high chance of just kicking the challenger from battle tower, teleporting them back to spawn as if they were defeated.

**Comment by Rasgnarok** [comment]
Needs re-testing

**Comment by Shika-The-Deer** [comment]
I can confirm this still happens on Orion. After defeating the Ground floor of the Battle Tower you are teleported to spawn as if you had lost the challenge, happened to both Oryso and I.

**Comment by WisconsinWinters** [comment]
should be fixed now, found some invalid  teaams in battletower. reopen ticket if issue happens again
