### ISSUE TITLE
[PlayerWarps] - Using an "unobtainable" item as the item name you set from menu will make it impossible to see, requiring manual editing via commands to fix.

### ISSUE THREAD

**Issue by WisconsinWinters** [ObliqueNetwork/Terra#2323]
**Describe the bug**
After creating a playerwarp, you are able to set an item through the GUI in your playerwarp menu. The plugin will let you choose an unobtainable item like "lava", and make it invisible from the playerwarps menu. You are able to still teleport to the playerwarp via commands, but will not see it in your playerwarp GUI.

**To Reproduce**
1. Create a playerwarp with /pw create <name>
2. Edit the playerwarp via GUI with /pw -> Manage My Warps -> Right-click on your warp

**Expected behavior**
The plugin shouldn't let you use unobtainable blocks such as the literal lava/water blocks.

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/1d690dfe-1daf-4abd-a073-7decf2ccef39)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/633c6a72-1e56-4538-a179-6566daac9b50)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/4b6c29ac-c8c7-492c-920e-b98d237452ae)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/9df9cc89-7674-406b-b4e3-a7e579d2a6f4)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/9b05e4eb-c57c-4a5c-b2a4-7fa5cfb8c711)

**Username:**
WisconsinWinters

**Server name (all applicable):**
All

**Additional context**
Could be forwarded to playerwarps plugin dev. You can work around this by simply doing /pwarp <your playerwarp> item <new item name>

**Comment by chefburne** [comment]
Lava/water can no longer be selected pending restart, thank you for reporting
