### ISSUE TITLE
[Scroll Rewards] Halloween Scroll Shiny Reward Form

### ISSUE THREAD

**Issue by josmit48** [ObliqueNetwork/Terra#2324]
Describe the bug
I received a normal shiny Marowak instead of the shiny Alolan Marowak from the Halloween scroll. I believe it said you have a random ghost type shiny pokemon.

To Reproduce

Randomly receive a shiny pokemon that is supposed to be Alolan (but will come out as normal formed) from a Halloween scroll.

Screenshots
![buug](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/57877708/8665ca78-b9c6-417a-b96e-054eb76f37e1)

Username:
Temperestre

Server name (all applicable):
All?

Additional context

**Comment by chefburne** [comment]
solved for next halloween, thank you for reporting
