### ISSUE TITLE
Nexus needs updating

### ISSUE THREAD

**Issue by raviolugh** [ObliqueNetwork/Terra#2325]
**Describe the bug**
When doing /nexus, most of the links are invalid.
**To Reproduce**
1. Go to /nexus
2. Click on all the categories

**Expected behavior**
It's expected to give corresponding links to the categories provided, ie. "FAQ" instead of "unknown command". 
**Screenshots**

**Username:**
raviolugh
**Server name (all applicable):**
atlas
![NEXUS](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139720449/5301cd12-6fc3-4f00-9280-eb3f7d88368d)
![nexus 2](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/139720449/ada40f4a-2743-4c4b-b019-f3174ee6c4e0)

**Additional context**

**Comment by Rasgnarok** [comment]
Needs re-testing, I need to know which buttons broke?

**Comment by WisconsinWinters** [comment]
replaced with /menu

fixed.
