### ISSUE TITLE
Rune command to fly

### ISSUE THREAD

**Issue by Kamorasthemad** [ObliqueNetwork/Terra#2326]
**Describe the bug**
Rune rank has the command to use /unlockfly when used it unlocks the ability to fly but the moment I tp to someplace the flying stops, you cant double tap space to start flying again and the command to unlock it goes on cooldown.

**To Reproduce**
1.type/unlockfly
2. Begin flying
3. tp somewhere else and flying stops

**Expected behavior**
flying should unlock and be interrupted for the 2 hours reactivable by double tapping spacebar 

**Username:**
Kamorasthemad
**Server name (all applicable):**
Atlas
**Logs:**
[techniclauncher_2023-10-24.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/13126294/techniclauncher_2023-10-24.log)

**Additional context**
adjust the command so it doesnt say you've unlocked the /fly command, when you use /unlockfly command, and allow it to be re enabled by double tapping space.

**Comment by WisconsinWinters** [comment]
Forwarded to internal tracker

**Comment by chefburne** [comment]
duplicate ticket, closing
