### ISSUE TITLE
Mobs not dropping loot

### ISSUE THREAD

**Issue by khoskins2** [ObliqueNetwork/Terra#2328]
**Describe the bug**
When killing pokemon, some do not drop loot including bosses.

**To Reproduce**
1. Log in
2. Find boss or pokemon
3. Kill pokemon
4. Receive no loot

**Expected behavior**
Loot should be dropped

**Server name (all applicable):**
Titan

**Comment by WisconsinWinters** [comment]
Unable to reproduce, please re-open a new ticket if issue persists.
