### ISSUE TITLE
Bisharp cannot evolve due to the datapack the server has for it.

### ISSUE THREAD

**Issue by Sylith23** [ObliqueNetwork/Terra#2329]
Bisharp evolves into Kingambit using a leaders crest, on here it cannot due to the "geode" bisharp datapack I assume

**To Reproduce**
1. Click on bisharp with Leaders crests
2. Its now holding it.
3. Rethink life choices.
4. Its still a bisharp.

FrootPvP

Titan

**Comment by CenizaRey** [comment]
It is due to the datapack, but has nothing to do with Geode Bisharp. It will be fixed next restart!
