### ISSUE TITLE
WorldBoss Battles bug

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2330]
**Describe the bug**
When trying to enter a world boss battle it lets you enter the battle then instantly kicks you out of the battle

**To Reproduce**
1. Wait for a world boss
2. do /boss battle
3. enter battle
4. see results
5. 
**Expected behavior**
It should allow the player to enter the battle and fight the boss instead of kicking the player out

**Username:**
itsAmaze

**Server name (all applicable):**
ALL

**Comment by PJLesure** [comment]
This has been moved to our internal tracker, thanks Amazee

**Comment by chefburne** [comment]
no longer an issue, closing
