### ISSUE TITLE
Visual pokemon dupe

### ISSUE THREAD

**Issue by MoonEverDark** [ObliqueNetwork/Terra#2331]
**Describe the bug**
When I evolved Fractooth into Frostodon the Factooth stayed in my party. Even after putting them both in my pc and relogging it didn't remove the copied Fractooth. I thought maybe I had 2, and it let me evolve the Fractooth again. After placing both back in pc I relogged and again both were still there. I pokegifted one to JesterFox to see if both would send but only one sent. Every time he threw out the one I sent it showed that mine was also out. I took a screen capture video (unable to upload here as file is too big, but will upload privately to youtube and share link in screenshot section) as this bug is really strange.

**To Reproduce**
Unsure how to reproduce it, have tried evolving other pokemon but hasn't happened again

**Expected behavior**
Haven't encountered something like this so only thing I expected was for my pokemon to evolve.

**Screenshots**

![2023-10-29_09 00 40](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/123283563/712f600e-99e0-4d1f-a0b6-0d4bea12d3b7)

https://youtu.be/e5IcOsK60sE

**Username:**
MoonEverDark
**Server name (all applicable):**
Orion
**Logs:**

[techniclauncher_2023-10-28.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/13198135/techniclauncher_2023-10-28.log)

**Additional context**
I still have them both currently, am unsure if I delete one if both will delete, didn't want to do that just in case it can be viewed in game by staff. I will delete if requested, just unsure what to do with them.

**Comment by lolanonymous** [comment]
Can you reproduce this in singleplayer?

**Comment by Rasgnarok** [comment]
@WisconsinWinters Honestly not sure what we can do about this one, it sounds like a party desync?

**Comment by WisconsinWinters** [comment]
haven't heard or seen this occur in a while, going to close and will re-open if it occurs again
