### ISSUE TITLE
Lugh is unbattleable and the boss version does not give a limited key

### ISSUE THREAD

**Issue by Sylith23** [ObliqueNetwork/Terra#2332]
After facing lugh during the quest and clicking "Run" he becomes unable to be rechallenged. Clicking on the statue or anything in the room does nothing.  

The legendary boss lugh does not give a limited key.

FrootPvP

Titan
![2023-10-29_18 04 32](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/77018011/f79efede-b030-4ee1-94b7-5cea12c0d53a)

**Comment by chefburne** [comment]
no longer relevant, closing
