### ISSUE TITLE
[NPC Gyms] Highrift causing server crash

### ISSUE THREAD

**Issue by chrisdurocher** [ObliqueNetwork/Terra#2333]
Battling Highrift NPC Gym causing server crash.

I have managed to create the exact same circumstances twice now to cause this:

1. Lead Koraidon w/ choice band Flare Blitz to one-shot the gym's lead Corviknight
2. NPC will send in Scizor and use Bullet Punch
3. Battle chat will read "Scizor used Bullet Punch" but before effects of Bullet Punch can take place, I get stuck on "waiting..."
4. After about 30 seconds of waiting, server crashes.

I've added a video link here where i used a completely different strategy and the same bug occurs, just later (turn 13 Corviknight uses Defog).

https://www.dropbox.com/scl/fi/djtumfpip2gw33o69gnuo/Screen-Recording-2023-11-01-at-11.43.21-AM.mov?rlkey=uxsndjahwygqjzh3r3ottqjay&dl=0

Also took this screenshot of the beta servers console, which occured immediately after I sent the challenge to the NPC gym

<img width="791" alt="Screenshot 2023-11-01 at 11 58 30 AM" src="https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/100480889/4f096496-1af4-403a-bee5-312f1acb8033">

**Issue cannot be reproduce if the player uses Bullet Punch on Scizor in a normal battle.**

**Comment by chefburne** [comment]
Fixed by Pixelmon, closing
