### ISSUE TITLE
"Underground" spawns are spawning above ground

### ISSUE THREAD

**Issue by Oryso** [ObliqueNetwork/Terra#2334]
**Describe the bug**
The pokemon that have spawning conditions as 'underground' are spawning in every biome above ground, usually taking up at least half the spawns.

**To Reproduce**
1. Go anywhere in overworld
2. Wait
3. Have 'Underground' spawns start spawning

**Expected behavior**
Have them only spawn underground as they should be.

**Screenshots**
![2023-11-15_02 18 16](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/60732022-a837-49f2-89f0-c14b11cdc0f5)
![2023-11-16_02 49 27](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/0b964565-e8f9-4613-818e-61d7872c22e9)

**Username:**
Oryso
**Server name (all applicable):**
Orion

**Additional context**
I didn't check Atlas, but I went to Titan for a little bit and didn't see this issue there.

**Comment by CenizaRey** [comment]
I'm quite sure it's just drilbur

**Comment by Oryso** [comment]
Drilbur is for sure the most common, but there are plenty more. Geodude, Whismur, Bunnelby, Roggenrola, Nacli just to name a few. 
![2023-11-16_19 19 45 edit](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/a7398a8e-9eab-4016-b6a5-5a952db67641)
![2023-11-16_19 20 44 edit](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/8b3468d5-d73e-4b17-8e31-1593fa8c0b6c)

**Comment by CenizaRey** [comment]
None of these pokemon have custom spawning files on NebulaMC, which means they're not underground spawns, this is how they are by default!

**Comment by Oryso** [comment]
Still hasn't been fully fixed yet. Geodude, Graveler, Drilbur, Excadrill, Roggenrola, Lunatone, Bunnelby, Whismur, Loudred all should not be able to spawn in this biome above ground.
![2023-11-19_21 58 13](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/648dec8c-459f-4524-99a4-3349b5da6389)
![2023-11-19_21 59 35](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/4c0a8e72-41f4-4c33-b966-442f4f6dcba1)
![2023-11-19_22 01 11](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/b1f72718-7fc3-46cc-aaf0-0f05ea5ee5a3)

**Comment by CenizaRey** [comment]
Yes, Ory, I know it hasn’t been fixed yet, that’s why I haven’t closed the ticket

**Comment by Oryso** [comment]
I know but Ras told me to update it

**Comment by CenizaRey** [comment]
She said to make sure the ticket exists, not to bump it if it did
