### ISSUE TITLE
Dynamax not working 

### ISSUE THREAD

**Issue by Fadida3** [ObliqueNetwork/Terra#2335]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Username:** Fadida3

**Server name (all applicable):** Orion 

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**
Since yesterday I can’t use Dynamax for some reason I wear the ring and everything it’s shows me the icon to Dynamax but when I try to dynamax and click Dynamax move nothing happens the Pokémon not Dynamaxing they just stay like they are

**Comment by WisconsinWinters** [comment]
Can you add some detail please?

Does it not work in battle when you attempt it, or under certain conditions?

**Comment by Fadida3** [comment]
> Can you add some detail please?
> 
> Does it not work in battle when you attempt it, or under certain conditions?

Hi yes it’s not working in battle when I attempt it not in battle against wild Pokémon raids boss Pokémon’s nothing

**Comment by chefburne** [comment]
Dynamax now works, thank you for reporting!
