### ISSUE TITLE
Rune /unlockfly command gets disabled when switching dimensions

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2336]
**Describe the bug**
When you do /unlockfly with rune rank to fly and go to a different dimensions like the nether the command gets disabled and they are unable to reenable the fly command even when 2 hours have not passed.

**To Reproduce**
1. get rune rank
2. use the /unlockfly command
3. Go to the nether
4. go back to the overworld
5. do /unlockfly
6. see error

**Expected behavior**
the user should be able to fly between dimensions and not have the command disabled when they are trying to go to another dimension

**Username:**
Crimla_the_smol

**Server name (all applicable):**
ALL

**Comment by WisconsinWinters** [comment]
Forwarded to internal tracker for our devs, thanks for report!

**Comment by chefburne** [comment]
Fly will no longer disable when switching dimensions, thank you for reporting!
