### ISSUE TITLE
[Suggestion] Increase /GTS limit on # of items sold from 3 to 5

### ISSUE THREAD

**Issue by Cencor126** [ObliqueNetwork/Terra#2337]
Was told to make a ticket for reviewing here about my post on the Discord.

"More a personal preference than anything. I've noticed Orion rarely fills up a page on the /gts, and those who do use it are regular users, often selling breeds or mods.

If we can increase the limit from 3 items/pokes to 5, I think that'll be perfect.

I know we can make our own shops, but /gts is amazing for those who haven't established a large assortment of items/pokemon to sell, or just want to make a quick buck."

Username: Cencor
Server: Orion (if that makes any difference)

**Comment by CenizaRey** [comment]
Approved, set up for next restart!
