### ISSUE TITLE
[Breeding] Slimeon Breeding Ability Glitch

### ISSUE THREAD

**Issue by josmit48** [ObliqueNetwork/Terra#2339]
**Describe the bug**
Slimeon had its ability changed and Hawky's slimeon was 

**To Reproduce**
1. Get a female Slimeon that had its ability "Gooey" that changed to HA
2. Breed it (female or not I think)
3. Hatch the egg from it
4. Put it on gts to see visual bug as Run Away (HA) or adaptability (HA)

**Expected behavior**
A visual bug as Run Away (HA) or adaptability (HA) will appear on GTS or in /wt list

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/57877708/53d56e6d-89e6-445f-93b9-12d4f312f1d0)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/57877708/5e9ea614-5b6f-4391-9882-5023362d77a0)

**Username:** Temperestre

Server: Atlas (All servers possibly)

**Logs:**

https://pastebin.com/LwFENh1X
Hatched an[06Dec2023 07:46:43.709] [main/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Your Egg hatched into a baby Eevee!
Putting the hatched eevees on gts: ![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/57877708/3dbd95be-abb7-4515-8355-65d8a041e6fd)

**Additional context**
This might also happen rarely with a male slimeon as parent. I haven't hatched a real HA eevee yet. Am I supposed to? After 7 of these eggs reproduced, I haven't received one real HA eevee. P.S: I used a gender mod on the slimeon to make it female (if that affects anything)

**Comment by josmit48** [comment]
After 7 of these eggs reproduced, I haven't received one real HA eevee.

**Comment by CptTCovenant** [comment]
Confirmed in game, parents were both another OT so it never will pass down HA.

However the visual glitch for it passing down (HA) next to any ability is still there.

**Comment by Rasgnarok** [comment]
This is likely the old bug with modifiers, it's been now since fixed for all NEW modifier actions, but old Pokemon that were affected by this bug (roughly December) need to be modified manually with the wand, @CptTCovenant

**Comment by Rasgnarok** [comment]
Closing, OP inactive.
