### ISSUE TITLE
[Rank Description] Rune and Jade Rank

### ISSUE THREAD

**Issue by ThaBoogyMAN** [ObliqueNetwork/Terra#2340]
Both Jade and Rune have the description : 
"Access to nickname yourself, with Minecraft color, formatting and hex color codes! (/nick)
Note: The hex code (e.g: '#ffaa00') needs to be encoded in { } braces (e.g: '{#ffaa00}')."
This is no longer accurate or valid according to CPT

**Comment by chefburne** [comment]
Rank descriptions have been updated by Ras. Thanks for reporting!
