### ISSUE TITLE
Leaderboard bot not printing 

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2341]
**Describe the bug**
The bot on discord is not printing out the top 3 placers for the leaderboard

**To Reproduce**
1. Place top 3 in the leaderboard
2. Check discord #leaderboard channel
3. see error

**Expected behavior**
It should print out the top 3 placers for the leaderboard

**Username:**
itsAmaze
**Server name (all applicable):**
discord

**Comment by Rasgnarok** [comment]
LBs are set to be replaced by Clan LBs, closing this as will be soon unecessary!
