### ISSUE TITLE
[Chat Bug] /gymbans List - Titan

### ISSUE THREAD

**Issue by ThaBoogyMAN** [ObliqueNetwork/Terra#2342]
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/153828761/64c94d81-fe25-4383-8f79-4692d9817359)

Only for Titan
/gymbans 
The ban List for gym mons with print in chat when the command is run, but it is not clickable and doesnt let you view the link
It does work on Orion and Atlas.

**Comment by chefburne** [comment]
Fixed, thanks for reporting
