### ISSUE TITLE
Mimikyu Floette & Minior Do not become shiny after being caught in a shiny ball

### ISSUE THREAD

**Issue by itsAmaze** [ObliqueNetwork/Terra#2343]
**Describe the bug**
When you catch a mimikyu floette or minior in a shiny ball they do not become shiny

**To Reproduce**
1. Get a shiny ball
2. Catch a mimikyu floette or minior in the shiny ball
3. see error

**Expected behavior**
The caught mon is suppose to be shiny 

**Screenshots**
![2023-12-18_23 21 07](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/137843758/ed9fa059-9f11-4d9c-b9ec-eb7bcfd04314)

**Username:**
itsAmaze
**Server name (all applicable):**
ALL

**Comment by WisconsinWinters** [comment]
I can't reproduce it with mimikyu, but I can reproduce it with Floette and Minior.

I believe this is due to the fact that minior and floette have multiple "shiny" versions. Forwarded to internal tracker.

**Comment by Ultamate2** [comment]
Same thing occurs with Vivillon due to the numerous palettes

**Comment by Rasgnarok** [comment]
This is actually a Pixelmon bug, it's well-known and there's no real fix right now. It's because they don't have a shiny palette due to the form methodology.
