### ISSUE TITLE
Braviary Flying bug

### ISSUE THREAD

**Issue by EpicArman1** [ObliqueNetwork/Terra#2344]
Describe the bug
Braviary does not fly even though it is a flying mount

To Reproduce
1. mount Braviary
2. spacebar/fly button
3. Braviary does a tiny hop

Expected behavior
Braviary will just land back down to floor after his small bounce and will be unable to jump again

EpicArman

All Servers

**Comment by WisconsinWinters** [comment]
i've queued a fix for this to our datapack. thanks for report!

**Comment by WisconsinWinters** [comment]
Fix pushed to live after next restart as of this post.
