### ISSUE TITLE
Enamorus spawning at the wrong time of day

### ISSUE THREAD

**Issue by Oryso** [ObliqueNetwork/Terra#2345]
**Describe the bug**
An enamorus spawned at night (around 15:00) in a sunflower plains even though it should only be a dawn/dusk spawn (18:30-0:00, 10:00-11:30).

**To Reproduce**
Not entirely sure how to reproduce a legend spawn so no idea

**Expected behavior**
Expected for enamorus to spawn during dawn/dusk, and not night as only cosmog spawns in sunflower plains at night.

**Screenshots**
![2024-01-04_03 04 07](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/9905876a-fdd5-404d-be99-feb2b6e1c3dd)

These 2 are just so you can see the time that it spawned:

![2024-01-04_03 18 48](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/3df81a8e-b5f3-497d-a338-e9a97d8dd855)
![2024-01-04_03 18 50](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/2e159217-cf4e-4437-a6b2-e2442c9f476c)

**Username:**
Oryso
**Server name (all applicable):**
Orion

**Additional context**
It also happened with a Throh that spawned during night when it should be a morning only spawn, so not sure how many pokemon this is effecting. Also not sure if its an actual bug or like a one time thing due to some kind of lag, even though I personally wasn't lagging.

**Comment by Rasgnarok** [comment]
We have a fix queued for tomorrow, hopefully this resolves. Please open a new ticket if issue persists after 26/02/2024.
