### ISSUE TITLE
Some of the info are Old and Misleading. And also throwing potential ideas.

### ISSUE THREAD

**Issue by WxllyDox** [ObliqueNetwork/Terra#2346]
Going through the Information for some of the sections of the Github, I found some information that seems to be outdated. Hopefully I can guide you with where the errors are and that you don't tell me to spin a sign outside the shop for the rest of my life. Not only that but it will be better if the arrangement of the villages are place in chronological order (Nyr, Agni, Nogrod, Kuan-Ti and so on) It help with knowing where you are currently and you dont have to scroll all the way down just to get info for your first playthrough of the story.

Unique NPC's
The first problem that I have seen is that the information here is wrong, There isn't a spiral staircase or having to pay a Mind Badge to the Move Relearner. The Move Relearner is located to the right of /warp training

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/2b6b0dca-5100-4dd0-9a29-fa25ed3b17da)

Nyr's General Pokemart Stock
The information here is plain has most of the vendors are located at /warp Market.  It will be more helpful that way instead of people running around Nyr. Not only that but the /warp crate is at the opposite side of where the market is actually located. Just putting the information that /warp market will send you there seems to be a better choice.

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/64c82a34-72f7-47f2-9524-9c8cf1cb16c0)

Instead of going through all of the pages and repeat the same progress all of the Move Tutors in the villages says that you will be charge with HS (Heart Scales). Which is untrue, here's some of the screenshots I took. All of them shows a price for it.
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/eea73503-578f-4ac1-beaf-dfd632dd7684)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/c226bf54-8170-4972-bfeb-29b6ee2b89b2)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/6f090836-84bf-4c5a-bcd3-a74ef28026e8)

Another Issues that I have already brought up but forgot to mention further, some of the Gym description do not show the proper level requirement to challenge the gym. Also including that some of the rewards here are not the same on the Pixelmon Server.  (P.S you might want to also check if the National Dex Rewards are also correct.)
Example of both issues:

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/46f2c55c-32b9-406d-938a-1c0bf97a0d06)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/f167f5dc-f2eb-4d42-87f5-bf6c082a828d)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/a3bab635-c33f-48d9-aa85-fc71a11a60de)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/226c3e26-eec7-4603-8dc9-598f4f5db5fa)

This is the ones that I have seen not updated. For now, all I have time for to look into. When I have more time, I will look for more errors or outdated information that needs readjusting.

Thank you for your time

Helper WxllyDox

**Comment by WisconsinWinters** [comment]
I've forwarded this to our internal planning pages. Thanks for report.
