### ISSUE TITLE
[Claims] Claimflagdefinition "poke-spawn" disables trade-evolutions and trade-objectives on scrolls

### ISSUE THREAD

**Issue by Uschalabamba** [ObliqueNetwork/Terra#2347]
Using a trading machine inside of a claim where the claimflagdefinition "poke-spawn" is set to false, makes trading-objectives of scrolls and trade-evolutions not work. Trade-objectives of scrolls don't count, and trade-evolutions don't trigger.

1. Place a trading machine inside of a claim
2. set the claimflagdefinition "poke-spawn" to "false"
3. Use the trading machine with either a trading-objective scroll or a Pokémon with a triggerable trade-evolution
4. complete the trade

Expected behavior:
The scroll objective counts or the trade-evolution triggers

Actual behavior
Nothing happens

Username: Uschalabamba

Server Name: Orion

Logs:

[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/13850506/latest.log)

**Comment by Uschalabamba** [comment]
I just found out that is also impacts the /tradesim command in the same way as detailed above.

**Comment by Rasgnarok** [comment]
This is probably not something we can fix, Pixelmon/Forge can't detect Spigot-based (aka GD) flags. We will likely have this fixed by moving to Clans, as you won't be able to stop spawning of Pokemon in Clans.
