### ISSUE TITLE
Mawile's ability stuck after battle

### ISSUE THREAD

**Issue by lexjo** [ObliqueNetwork/Terra#2349]
Following a gym challenge my mawile's ability stayed as huge power despite changing back to normal mawile from mega mawile, this should have reverted back to intimidate.
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/17412315/608dd640-adce-4be2-9a6c-bed1f64aa177)

**Comment by Rasgnarok** [comment]
Has this been fixed/addressed? Can we reproduce the bug? We need more information, perhaps the admins can test this one too @WisconsinWinters

**Comment by lexjo** [comment]
The ability on the mon was fixed by cpt but i'm not sure how to reliably reproduce the bug

**Comment by WisconsinWinters** [comment]
i tried this earlier and wasn't able to reproduce in gyms

**Comment by Rasgnarok** [comment]
Could not be reproduced, closing.
