### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by Ultamate2** [ObliqueNetwork/Terra#2351]
**VoteParty on Atlas not triggering for some People that voted**

**To Reproduce**
use /vote
vote until your streak goes up
wait for vote party
Don't get anything from vote party

**What is Supposed to Happen**
They are supposed to get the rewards from the vote party

![amaze vote party issue](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/154950890/dc2b87bb-bf3b-4497-91fb-f806f4748da4)

**Username: Ultamate**

**Server: Atlas**

**Logs:**
[latest (6).log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/13894793/latest.6.log)

**Additional context**
I am not entirely sure how to reproduce the issue but it has occurred multiple times for people on Atlas

**Comment by Rasgnarok** [comment]
VPs reward people that vote in the last 24h, so that's definitely odd. We can move this to internal and wait to see if we get more information, @WisconsinWinters

**Comment by WisconsinWinters** [comment]
I have a ticket on this for some of the errors on the live servers, proxy seems to sometimes be getting the vote, but is not forwarding properly to the live servers.
