### ISSUE TITLE
[/sit and /nickname] Both commands show as having no permissions

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2354]
**Describe the bug**
Upon trying to use either /sit or /nick /nickname I receive the notification in chat that I have no perms however I am omen and SrMod
**To Reproduce**
1. Run any of the commands and observe the error

**Expected behavior**
/sit should sit the player and /nick should change the desired players nickname
**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/95523378/ede8164a-fb73-495d-a2af-c3f1b1ddb955)

**Username:FunPolice**

**Server name: _Peyton_7 (all applicable):**

**Comment by WisconsinWinters** [comment]
updated permissions, fixed.
