### ISSUE TITLE
Vote party forced legendary spawn didnt work

### ISSUE THREAD

**Issue by Vahypr** [ObliqueNetwork/Terra#2355]
A legendary didn't force spawn after reaching vote party goal

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/156500522/e7c57757-7f4d-443e-9970-a024b7236f77)

Server is Titan

[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/13927208/latest.log)

**Comment by WisconsinWinters** [comment]
queued improvements to this so it doesnt fail on an attempt
