### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by Vahypr** [ObliqueNetwork/Terra#2356]
Trading darkrai then it lost both dexlives

After a player traded his darkrai he got in a legendary scroll it lost both dex lives after receiving it back.

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/156500522/e1800aba-bd7e-43a9-988d-3dff36f6b24b)

Vahypr
(Prosc1utt0) Player having this issue)
Atlas
 I have uploaded your attachments for you: 
- https://paste.helpch.at/obubupatok

**Comment by Rasgnarok** [comment]
This needs reproducing by our admins, see if the issue persists @WisconsinWinters

**Comment by WisconsinWinters** [comment]
i have an issue up for this on our internal tracker
