### ISSUE TITLE
[Vp legend] Legend insta despawned and no message in chat

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2358]
**Describe the bug**
Vp legend was force spawned but no message was in chat and after checking poketracker legend was despawned after 3 seconds.

**Expected behavior**
Vp legend should appear in chat and the legend should maintain active this is after the most recent changelog and Vp legend spawn fix

**FunPolice:**

**_Peyton_7 (all applicable):**

**Comment by WisconsinWinters** [comment]
i believe this is caused by the legend spawning on someone's claim that has pokespawning disabled but so far i haven't been able to track down what is causing it.

**Comment by Rasgnarok** [comment]
Replaced all VP force-spawns with a random player reward of a random Legendary.
