### ISSUE TITLE
[Bug] Daycare unable to accept type gems.

### ISSUE THREAD

**Issue by Cencor126** [ObliqueNetwork/Terra#2359]
**Describe the bug**
I was told people are aware of this bug, but I figured I might as well post a bug report just in case.

After taking in 3 eggs and breeding pairs from a previous breeding session, I was unable to proceed past the stage where type gems were requested.

2 breeding pairs were grass types, stuck requesting for 1x grass gem for ea. No $ payment made.
a single pair of Scorbunnies on the other hand, did not visually show the egg icon, nor the type gem request (but hovering over it did). No $ payment made.

Placement in the daycare (by pair and by parent position) did not seem to change the results.

**Expected behavior**
Daycare accepts type gems after pressing the tick, before asking $ for tax (in my case).

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35191988/3eac4486-b679-4173-96de-146676675d86)

Username: Cencor
Server: Orion

**Comment by chrisdurocher** [comment]
Yeah I'm having this same issue, heres what happens:

1. click day care
2. put in breeding pair
3. click check
4. (error occurs here) skips prompt for breeding tax, asks for gems, but will not take gems
5. (bonus step) if you relog it will allow you to insert gems and proceed to breed the pair.

There does appear to be an additional bug where one of the daycare slots may go invisible and not accept gems and therefore will not breed.

**Comment by josmit48** [comment]
Username: Temperestre 
Ras said they fixed this when servers restarted.

**Comment by WisconsinWinters** [comment]
fixed.
