### ISSUE TITLE
Shiny Balls don’t count for scroll’s shiny clue 

### ISSUE THREAD

**Issue by undefeatablemon** [ObliqueNetwork/Terra#2360]
I tried to use a shiny ball to meet the conditions for an epic scroll clue (catch 2 shinies) but it didn’t count for it. Initially I made a suggestion that it should count but was told to report it as a bug so here I am xp.

**Comment by Rasgnarok** [comment]
It's definitely a bug, we can move this to our internal tracker to update Scrolls
