### ISSUE TITLE
Mega boss stone drop issue

### ISSUE THREAD

**Issue by lexjo** [ObliqueNetwork/Terra#2361]
Earlier today (approx 8pm GMT) after beating a wild mega-houndoom boss, the Houndoominite that showed in the drops screen became a Sea Incense when added to my inventory.

**Comment by Rasgnarok** [comment]
Need confirmation this is still happening, aka - can an admin reproduce the issue?

**Comment by Rasgnarok** [comment]
Closing, ticket is outdated and no longer reproducible.
