### ISSUE TITLE
[Move Tutor] Eelektross cant learn some move tutor moves that it should be able to learn.

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2362]
**Describe the bug**
Eelektross should be able to learn some move tutor moves like knock off or fire punch but was unable to when trying to on the agni and kuan-ti move tutors
**To Reproduce**
1. Go to the mart in agni or the "PC" building in kuan-ti
2. Click on the move tutor
3. With an eelektros, attempt to get either moves

**Expected behavior**
Should be able to learn them

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/95523378/7dffdfc7-9854-46b3-9a6d-b26b279746b0)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/95523378/189dbfac-91ed-4e6d-aa37-524698970900)

**FunPolice:**

**_Peyton_7 (all applicable):**

**Comment by Rasgnarok** [comment]
Same here, we can just edit our datapack to match and also report the missing moves to Pixelmon @WisconsinWinters

**Comment by Rasgnarok** [comment]
Added Knock Off and Fire Punch as Transfer moves, but it seems it was already there as a Tutor Move... the bug remains to be found.
