### ISSUE TITLE
[Transfer Tutor] Eevee Can't Learn Sing

### ISSUE THREAD

**Issue by Ultamate2** [ObliqueNetwork/Terra#2363]
**Despite Being Listed on Pixelmon Wiki and Pokemon Wiki, Eevee Cannot Learn Sing Via Transfer Tutor**

**To Reproduce**
1. Get an Eevee
2. Go to /warp Training
3. Select the Eevee in the Move Tutor
4. Cannot get Sing

**Expected behavior**
The Transfer Tutor is supposed to have the move Sing for Eevee

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/154950890/89df1705-1517-4a18-80e7-71da550e4552)

**Username: Ultamate**

**Server name: All**

**Additional context**
Some other event moves are not on the transfer tutor for certain pokemon

**Comment by Rasgnarok** [comment]
This is a datapack issue, we can start adding Event Moves but it'll need datapack updates @WisconsinWinters ... perhaps if the Gym Admins can make a list for us of all big event moves, we can do one big update, or at least add Sing to Eevee

**Comment by Rasgnarok** [comment]
Fix will be up for next restart through the Transfer Tutor.
