### ISSUE TITLE
Drowning bug [Feature] Bug explanation

### ISSUE THREAD

**Issue by Tybomb12** [ObliqueNetwork/Terra#2364]
Well i am curently in the ocean and im not loosing and of the bubbles at all im not sure if this is s bug or my game is lagging just thought you guys shoukd no about it.

**Expected behavior**
to drown and take damage 

**Screenshots**

*Narcia_**

**Server name titan

**Comment by WisconsinWinters** [comment]
can't reproduce this, do you ahve any videos or ranks that might be giving you god?

**Comment by Rasgnarok** [comment]
Could not be reproduced, closing.
