### ISSUE TITLE
[Feature] Zygarde in 100% form not turning shiny via shiny ball

### ISSUE THREAD

**Issue by FarDiamond** [ObliqueNetwork/Terra#2365]
**Describe the bug**
Zygarde if caught in 100% or complete form doesn't turn shiny if caught in shiny ball

**To Reproduce**
1. Go to zygarde shrine in /warp shrines
2. Buy 10% zygarde _50% of the time it has power construct_
3. Take it down below 50% to activate power constrict
4. Catch in Shiny ball
5. See Error (not shiny)

**Expected behavior**
shiny ball should make all mons caught in it shiny

**Screenshots**
https://cdn.discordapp.com/attachments/1199154290707660900/1199154322836033687/image.png?ex=65c1827d&is=65af0d7d&hm=5b65a4982865d8d7df3bed313948374da2f66eaac009eb24e0886506ca997c95&
**Username:**
FarDiamond3049
**Server name (all applicable):**
Titan
**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by Rasgnarok** [comment]
This needs reproducing by an admin and moved to our internal tracker, @WisconsinWinters

**Comment by WisconsinWinters** [comment]
reproduced and forwarded to internal tracker
