### ISSUE TITLE
[/boss battle] switching Pokemon after death makes the player stuck on "Waiting..."

### ISSUE THREAD

**Issue by Uschalabamba** [ObliqueNetwork/Terra#2366]
When participating in the new boss battle, after one of your Pokemon is defeated, you are prompted to switch to another Pokemon as usual. Upon selecting another Pokemon, the battle will be stuck on "Waiting...".

1. type /boss battle
2. make your Pokemon die to the boss
3. Upon being prompted to select another Pokemon, do exactly that.
4. Get stuck on "Waiting..."

**Expected behavior**
The Pokemon gets switched out normally.

Username: Uschalabamba

Server name: Orion

Logs are have been added:
[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/14027212/latest.log)

Additional Infos: When the boss is defeated by other players, the battle ends and you still get rewards. This will take a hot minute though.

**Comment by Rasgnarok** [comment]
Does this always happen or is this a one off? If so, I need a full party log.

**Comment by Rasgnarok** [comment]
Closing, feature was overhauled. If issue persists, please open a new ticket.
