### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by WxllyDox** [ObliqueNetwork/Terra#2367]
Was fighting the World Boss on Titan and discovered that swapping out to a different pokemon when your first one died cause whatever you swapped to, to faint after battle.

All you have to do is wait for a World Boss to happen (Or start one)
1. You fight the boss with one of your pokemons, you hit them onces.
2. You let your first pokemon die
3. Swap to someone else and kill the World Boss
4. When the battle finishes both your first and second pokemon will have fainted

Unfortunately, I was forgot to take screenshots, but will be willing to try and replicate the bug inside of the Beta Server.

Username: WxllyDox
Server: Titan

[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/14027526/latest.log)

If you are having hard time to replicate it on Beta Server, I suggest you try it on Titan. I willing to help if my information is lacking or not descriptive enough for someone to understand the problem.

**Comment by Rasgnarok** [comment]
Need confirmation this is still happening, aka - can an admin reproduce the issue?

**Comment by WisconsinWinters** [comment]
reproduced and forwarded to tracker
