### ISSUE TITLE
Wrong Battlepass Challenge Completion

### ISSUE THREAD

**Issue by Oryso** [ObliqueNetwork/Terra#2368]
**Describe the bug**
For the 2nd week challenges of the BP, if you try to complete the "Like sitting ducks" challenge (defeat 3 trainers), it will instead make progress on the "He's so metal" challenge (catch 3 steelix) instead.

**To Reproduce**
1. Kill a trainer
2. Open BP
3. See steelix challenge progress instead of trainer defeats

**Expected behavior**
Expected for the correct challenge to be completed

**Screenshots**
![2024-01-26_02 28 32](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/015fbf28-e4cf-4cc6-86b5-f00dea298d04)
![2024-01-26_02 28 34](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/99ac04ed-c567-49eb-88b9-d9cb0b12919e)

**Username:**
Oryso

**Server name (all applicable):**
Orion and Atlas, probably Titan too

**Additional context**

**Comment by Rasgnarok** [comment]
I believe this is now fixed.
