### ISSUE TITLE
[World Boss Bug] Cannot use Hisuian Zoroark on Giratina World Boss

### ISSUE THREAD

**Issue by Ultamate2** [ObliqueNetwork/Terra#2369]
**Describe the bug**
When going into a world boss with Hisuian Zoroark against Giratina World Boss it just cancels the battle

**To Reproduce**
1. Have Hisuian Zoroark as first slot
2. Use /boss battle command
3. Doesn't take you to fighting screen
4. Says 0 damage done to boss

**Expected behavior**
It is supposed to allow Hisuian Zoroark to battle Giratina and not get instantly kicked out

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/154950890/6fe096ee-4f58-4041-be78-582a36758771)
https://medal.tv/games/minecraft/clips/1S5lUj9MSenmqO/d1337NGwzAs4?invite=cr-MSxMTmUsNDc4NjA0MTIs
(Evidence)

**Username:KrimsonKat**

**Server name: All**

**Additional context**
Doesn't show battle screen

**Comment by WisconsinWinters** [comment]
forwarded to devs
