### ISSUE TITLE
Ultra Fishing Shards Spawning Wrong Rarity

### ISSUE THREAD

**Issue by WxllyDox** [ObliqueNetwork/Terra#2370]
Here's a step by step explanation on how I stumbled upon it. I decided to try and use my shards to get a BB Greninja to spawn in a Ultra Jungle Water Platform. I decided to spawn it and for unknown reasons, it gave me a 
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/00319baf-3203-4121-8bba-85af841bb695)

Really Confused with this but then it spawned, I looked around me and it was a Lvl 50 Valencian Poliwag that was swimming around me. I decided to look up what rarity it was and saw that it wasn't a Fishing Spawn but a Normal spawned.
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/939456ca-45d4-4b11-83e4-1e10bc4ac454)

After losing my 8 Ultra Fishing Shards, I went to make a ticket and was told by CPT to make a github. Hopefully you have all the information you need if not you can message me on discord at WxllyDox

**Comment by WisconsinWinters** [comment]
forwarded to devs.
