### ISSUE TITLE
Beedrill, Kuan-ti move tutor 

### ISSUE THREAD

**Issue by EpicArman1** [ObliqueNetwork/Terra#2371]
Beedrill is unable to learn knock off and throat chop on servers Orion, Atlas or Beta at move tutor kuan-ti

**To Reproduce**
1.join either Orion or Atlas
2. go to kuan-ti move tutor
3. click to learn move on beedrill

**Expected behavior**
move are not listed nor crossed out

**Screenshots**
Titan
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/154722074/aef4b0c2-466c-4499-95e9-c9b86275c70a)
Atlas
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/154722074/4700cdb9-2a7e-486f-bbca-73069040d622)

EpicArman

**Comment by WisconsinWinters** [comment]
should be fixed, enabled move tutor moves on this npc. currently looking at how we can implement a new system for event/move tutor/egg moves in the future.
