### ISSUE TITLE
Forced Spawn Legends not Spawning in Correct Time Frames.

### ISSUE THREAD

**Issue by kdy99** [ObliqueNetwork/Terra#2372]
Players have been using there shards for instance to spawn a Zamenzenta at night and are getting a zacian spawn which is a daytime spawn also had the same issue with Zekrom/Reshiram etc.

To reproduce attempt just force spawning a legend using the shards for a specific legend Day/Night and find the corresponding spawn not being correct. 

https://outplayed.tv/media/eXnrrn

Across all servers.

Expected behavior should be spawns should be spawning in correct time frames when attempted to be force spawned for players.

**Comment by Rasgnarok** [comment]
We've added some debug commands to force more information on these issues, this is a duplicate of the original issue which is already being investigated. Thanks!
