### ISSUE TITLE
[SignShop] Issue with Sign Shops in Different Dimensions

### ISSUE THREAD

**Issue by Ultamate2** [ObliqueNetwork/Terra#2373]
**Describe the bug**
Having a Sign Shop setup in a different Dimension like the End/Nether causes it to be reset(turned into a normal a normal sign) after the server restarts

**To Reproduce**
1. Setup a Sign Shop in End/Nether
2. Activate the Sign Shop
3. Wait for Server to do Daily Restart
4. See that the Sign Shop is now Normal

**Expected behavior**
It is supposed to leave the sign shop up and not be turned off after each restart

**Username: PriorJchico**

**Server name: Atlas**

**Additional context**
I highly doubt this bug can be fixed, but still reporting it due to being a bug

**Comment by Rasgnarok** [comment]
You're correct, this isn't something we can really fix - the plugin isn't ours, and it's failing due to Forge's way of loading worlds in a modded environment.
