### ISSUE TITLE
Ultra Fishing Shards wrong Spawns

### ISSUE THREAD

**Issue by WxllyDox** [ObliqueNetwork/Terra#2374]
It occur to me that whenever you use Ultra Rare Fishing Shards in the Ultra Jungle, nothing spawns because it can't find anything to spawn in the location. While using them in a big pool of water, a Whiscash would spawn after clicking approximately four times. Then it would force spawn something else.  
Here's image that a Whiscash spawned in a Ultra Jungle caused by using Ultra Rare Fishing Shards (Check MiniMap)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/ceff1917-c983-4420-a812-69753ac0581a)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/4a63e252-a679-4ea2-b8a6-b1715d930f62)

To Reproduce the bug
Surround yourself by 3x3 chunks of water that 8 blocks deep. You will have to be in a Ultra Jungle. Then use the shards.

My Username is WxllyDox

Server: Titan

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/ce65cfdc-0567-44b6-8bbf-010866b9645d)

I only have a picture of it cause it was of last night

Hopefully this is enough information to go with, if not you can always message me on discord or ingame (If online).
My discord username is WxllyDox

**Comment by WisconsinWinters** [comment]
this is a known issue and is on our internal tracker

**Comment by Rasgnarok** [comment]
This should now be fixed, https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/2345
