### ISSUE TITLE
[BattlePass] Raid Dens not Counting

### ISSUE THREAD

**Issue by Ultamate2** [ObliqueNetwork/Terra#2375]
**Describe the bug**
When Defeating a pokemon in a Raid Den, it does not count towards the BattlePass Challenges

**To Reproduce**
1. Have an open task to defeat a pokemon
2. Defeat it in the Raid Den
3. Not Register as completing the Task

**Expected behavior**
It should count for the task when defeating the Pokemon

**Username: Ultamate**

**Server name (all applicable): All**

**Additional context**
This is similar to the Horde Bug

**Comment by CenizaRey** [comment]
This is a Pixelmon bug, and is out of our hands, just like the Horde Bug

**Comment by Rasgnarok** [comment]
This can be forwarded to the internal tracker, we can likely do something hacky on our side to force Hordes and Raids to count as catch normally @WisconsinWinters

**Comment by WisconsinWinters** [comment]
forwarded to internal tracker
