### ISSUE TITLE
[Plushies] Can be placed in admin claims

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2377]
**Describe the bug**
After my previous ticket, I tested and you can also place plushies. In spawn you can only place them on certain blocks like stair blocks, PC's, Healers, Trade machines, Barrels, Chests, Signs and even The warp crates. That's all the blocks I have found so far but I'm sure there are more. Additionally, in the end they can be placed anywhere in the admin claim.

**To Reproduce**
1. Go to spawn or the end
2. Place a pushie on any of the listed blocks above
3. Watch it place
4. 
**Expected behavior**
They shouldn't be able to be placed

**Username: _Peyton_7**

**Server name: FunPolice (all applicable):**

**Comment by WisconsinWinters** [comment]
forwarded to internal tracker
