### ISSUE TITLE
Rufflet doesnt evolve into Hisuain Braviary during night time

### ISSUE THREAD

**Issue by WxllyDox** [ObliqueNetwork/Terra#2378]
PLayer has reported that Rufflet doesnt want to evolve into its Hisuain Braviary during night time. 

Have a Rufflet Level 50 on your team
Wait for night time 
Evolve it

Expected to evolve into its Hisuain Form

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/03694e62-64f4-4830-80ee-bd8ccdc963dd)

LittleInch

Orion

https://paste.helpch.at/uwejuqoliw
https://paste.helpch.at/tocexozane

All this isn't actually from me, its was from a non staff member. Just making the ticket for them

**Comment by Rasgnarok** [comment]
Was this reproduced? because we don't edit Rufflet, and if it is a bug in base Pixelmon, then it needs reporting to Pixelmon

**Comment by WisconsinWinters** [comment]
evo'd 4 rufflets at various times, unable to reproduce currently

**Comment by WisconsinWinters** [comment]
unable to reproduce, re-open if it happens again with more information
