### ISSUE TITLE
[party6] displaying the first slot in your party instead of 6th one

### ISSUE THREAD

**Issue by Raib0lt** [ObliqueNetwork/Terra#2379]
**Describe the bug**
I have a walking wake on my team and it is placed on the 6th slot, but whenever I type in [party6] in chat it'll show the mon in the first slot instead, which was a probopass.

**To Reproduce**
1. Have a mon that's in the 6th slot in your party
2. Write in [party6] in chat.
3. Chat displays the mon in your 1st slot instead.

**Expected behavior**
It's supposed to display the mon in your 6th slot.

**Screenshots**
https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/156371790/00de6f7f-f415-4485-8d4a-83868f738456

**Username:**
Raiboat

**Server name (all applicable):**
Titan but happens to all

**Logs:**
[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/14232672/latest.log)

**Additional context**
None

**Comment by WisconsinWinters** [comment]
forwarded to internal tracker
