### ISSUE TITLE
Boss Battle Illusion ability Bug

### ISSUE THREAD

**Issue by EpicArman1** [ObliqueNetwork/Terra#2380]
players who have zorua or zoroark are reporting they are unable to join /boss battle, and it shows 0.00 damage dealt before instantly closing the battle

**To Reproduce**
1. have an illusion pokemon on your team
2. join /boss battle with it as your lead
3. illusion bugs out the fight

**Expected behavior**
finishes the battle and says you dealt 0.00 damage total to the boss

EpicArman

**Additional context**
haven't had the issue affect me but a couple players have complained about it in chat and they all are using zorua or zoroark on there team

**Comment by WisconsinWinters** [comment]
forwarded to  internal tracker sicne it produces NPEs in console
