### ISSUE TITLE
Population Bomb Wide Lens not working

### ISSUE THREAD

**Issue by EpicArman1** [ObliqueNetwork/Terra#2381]
Population bomb is 90% accuracy and when putting a wide lens on moushold that number should go to 100% accuracy and hit all 10 times. works normally on pokemon showdown

1. Give Moushold wide lens
2. go into battle
3. Use Population Bomb

**Expected behavior**
doesn't hit all 10 times even though being 100% accuracy

EpicArman

**Comment by WisconsinWinters** [comment]
can you reproduce this in singleplayer as well?

**Comment by WxllyDox** [comment]
Bug was reproduced in Singleplayer. Meaning this becomes a Pixelmon Issue
Please make a Pixelmon Bug Report

https://pixelmonmod.com/tracker.php

**Comment by Rasgnarok** [comment]
Please confirm the bug has been reported to Pixelmon so this ticket can be closed, @WisconsinWinters

**Comment by EpicArman1** [comment]
Already has been reported, you can close the tracker now.
