### ISSUE TITLE
[Item Use] Valentines Wings

### ISSUE THREAD

**Issue by ThaBoogyMAN** [ObliqueNetwork/Terra#2383]
**Describe the bug**
Used a Valentines wings item on a valentines suicune. 

**To Reproduce**
Used the item on the suicune
a menu came up to confirm the change for 1 of them,
 i hit the green confirm, 
nothing happened,
 so i pressed the green again,
 still nothing happened, 
so i hit escape and both were consumed and no change had taken affect

**Expected behavior**
Consumes 1 Valentines wing 
Suicune would have the particle effects

**Screenshots**

**Username:** Pozimoto 

**Server name (all applicable):**

**Logs:**
[latest.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/14310783/latest.log)

**Additional context**
When tested on the Beta server, it was discovered that 2 wings were used everytime the effect was applied

**Comment by WisconsinWinters** [comment]
This is fixed but I found another bug in the process, which has been forwarded to internal tracker.
