### ISSUE TITLE
Master rank is missing ''An additional fifth slot for Daycare'' message.

### ISSUE THREAD

**Issue by JamieRRE** [ObliqueNetwork/Terra#2384]
**Describe the bug**
When checking the dexreward for master rank, it does not show that you gain an additional fifth slot for daycare

**To Reproduce**
1. Go to 'dexrewards'
2. Click on 'Pokédex rewards''
3. Hover over master rank
4. See missing line

**Expected behavior**
Giving the information about an additional slot for daycare

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/101290403/8b7c7380-cdfc-49bd-bc13-a22c0ea65ba9)

**Username:**
JamieRRE

**Server name (all applicable):**
Orion, Atlas, Titan

**Comment by WisconsinWinters** [comment]
fixed.
