### ISSUE TITLE
Boss battle waiting glitch 

### ISSUE THREAD

**Issue by G59Rhett** [ObliqueNetwork/Terra#2385]
battle log created at 5:38 am CST and 6:26 am CST. A 3rd battle log has been created at 7:27 am CST. 2 more battle logs created today at 2/23/24.  Bosses have been Ho-oh at 5:38 am CST 2/19/24, Charizard at 6:26 am CST on 2/19/24 , And Dialga at 7:27 am CST on 2/22/24. Darkrai boss waiting glitch occured 5:27 am CST 2/23/24 aswell as Ho-oh Waiting glitch occured again at 6:29 am CST 2/23/24
Server Titan
Username - Siiraevana
Player was doing a boss battle and getting stuck in a waiting glitch multiple times, battlelog should show why player is getting stuck in waiting.

**Comment by WisconsinWinters** [comment]
I need more info on what they're doing and how they're getting to the waiting glitch.

**Comment by Rasgnarok** [comment]
The battle logs mentioned by OP should be enough for us to submit a bug report to Pixelmon since they log exactly what happens in battle, @WisconsinWinters

**Comment by WisconsinWinters** [comment]
re-reviewed logs and forwarded to pixelmon
