### ISSUE TITLE
[EvolutionAbility] Some pokemon's abilities change upon evolution.

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2386]
**Describe the bug**
Evolving Abra or Ralts the ability doesn't always stay the same. Sometimes evolving ralts with trace nature, it will become synchronize. Same thing goes for abra. When evolving sometimes abras ability went from inner focus to synchronize. Both on Beta and Live, same issue. Replicable but unable to find the reason for the issue. The issue was not contingent with Gender, level, nature, IVs, EVs, or moves. With 5 of the same pokemon with all the same stats, nature, moves, etc the issue only happened sometimes. 
**To Reproduce**
2. Give yourself 5 Identical ralts
3. /trylevelevo them all
4. Check their stats summary and note the ability.

**Expected behavior**
The ability should stay consistent before and after evolution.

**Screenshots**

https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/95523378/836694fb-860e-43fc-aba8-9cef8aff9b0c

**Username:_Peyton_7**

**Server name: FunPolice (all applicable):**

**Comment by Rasgnarok** [comment]
This is likely a Pixelmon bug, you should confirm if it happens in base Pixelmon

**Comment by Peyton7** [comment]
I was able to replicate on base Pixelmon, definitely a pixelmon bug, ill make a Pixelmon bug ticket

**Comment by Rasgnarok** [comment]
Thank you Peyton! Could you link me back the report here?

**Comment by Rasgnarok** [comment]
https://pixelmonmod.com/tracker.php?p=2&t=21606
