### ISSUE TITLE
Iron Husk Evo line [custom move wyvern switch bugged}

### ISSUE THREAD

**Issue by KungFuHustler** [ObliqueNetwork/Terra#2387]
-Just have **any form of iron husk** on your team with the ability **Wyvern Switch**
-use the move if it hits it will allowed u switch Pokémon's to a Pokémon u want to get hit then swap again **in one turn**

Name- Kung_Fu_Hustler      Server-Titan

**Comment by Rasgnarok** [comment]
This likely needs changing in the datapack, either to a different move altogether, or diagnosing the issue. Likely it's a Pixelmon bug when we datapack new moves in using existing mechanics/data tags.

**Comment by WisconsinWinters** [comment]
per chi, this is fixed.
