### ISSUE TITLE
/staff and /staffonline Command Not Working

### ISSUE THREAD

**Issue by KungFuHustler** [ObliqueNetwork/Terra#2388]
When using /staff or /staffonline command it only shows the surrounding yellow lines nothing else.

- all servers 

- Kung_Fu_Hustler 
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/156841369/3fa44d70-8144-4bb5-9552-d7ad4384f401)

**Comment by WisconsinWinters** [comment]
forwarded to internal tracker
