### ISSUE TITLE
[ShinyMod] Applying a shiny mod to a pokemon that doesnt have a shiny palette 

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2390]
**Describe the bug**
For instance, Magearna form christmas 2022 doesn't have a shiny palette however it still allows a shiny mod to be applied thus consuming the shiny mod without turning the pokemon shiny.

**To Reproduce**
1. Get a xmas 2022 magearna or any other pokemon without a shiny palette
2. Apply a shiny mod
3. See that it did not change palettes.

**Expected behavior**
The pokemon shouldn't be able to accept the shiny mod since the palette doesn't exist on that form

**Username:_Peyton_7**

**Server name (all applicable):FunPolice**

**Comment by WisconsinWinters** [comment]
forwarded to internal tracker
