### ISSUE TITLE
Ability Modifier Bug

### ISSUE THREAD

**Issue by Mellozilla** [ObliqueNetwork/Terra#2391]
**Describe the bug**
Using an Ability Modifier and evolving a Pokémon reverts the ability back to its previous one.

**To Reproduce**
1. Use an Ability Modifier to change the Pokémon's Ability.
2. Evolve the Pokémon
3. Check summary to see if the ability changed.

**Expected behavior**
Using the ability modifier will change the Pokémon's ability to a more desired ability.

**What happens instead**
Sometimes the Pokémon will lose its ability and revert to the previous one on evolution.

**Username:** 
AFadedColor

**Server name (all applicable):**
All

**Additional context**
Using an Ability Modifier is supposed to change the ability of the Pokémon and keep it to whatever the ability was changed to. Sometimes the Pokémon will lose the ability and revert to its previous one upon evolving.

**Comment by WisconsinWinters** [comment]
can i have some specific examples for testing?

**Comment by Mellozilla** [comment]
> can i have some specific examples for testing?

i was using the pokewand to give myself the Pokémon. i used an ability modifier on it changing the ability from soundproof to bulletproof. upon testing i had about 10 ability modifiers and only 2 of the times did it lose the ability on evolution. it lost the ability through each evolution and not just the first evo. if you need more info or a better explanation lmk

**Comment by WisconsinWinters** [comment]
I meant specific pokemon to see if there's a pattern

**Comment by Mellozilla** [comment]
I was using Jangmo-o for this instance. Try any Pokémon that has another ability and use the ability mod to change its ability and then evolve it. sometimes it will revert it to the previous ability sometimes it will keep it. I wasn't able to try with other Pokémon because I didn't have anyone to give me more ability modifiers.

**Comment by WisconsinWinters** [comment]
forwarded to internal tracker
