### ISSUE TITLE
[Plushies] Can Place Plushies in Spawn

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#2392]
**Describe the bug**
You can put down plushies at /spawn and I bet this is true for all administrator claims.

**To Reproduce**
1. Go to /spawn
2. Hold a plushie and place it down

**Expected behavior**
Not being able to place plushies at spawn

**Screenshots**
![2024-02-26_00 10 39](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/37944220/f7fba8e9-c5fc-4f8d-aade-d0d66de9ad70)

**Username:**
DraconiacLatias

**Server name (all applicable):**
Orion

**Comment by WisconsinWinters** [comment]
i have an internal ticket up for this

**Comment by Rasgnarok** [comment]
Can we not solve this with GriefDefender, @WisconsinWinters ?

**Comment by WisconsinWinters** [comment]
it should be possible, i may need help tracking down which flags they are from the interact block category

**Comment by WisconsinWinters** [comment]
fixed with worldguard + clans
