### ISSUE TITLE
Meloetta Unable to learn relic song via move relearner. 

### ISSUE THREAD

**Issue by G59Rhett** [ObliqueNetwork/Terra#2393]
Players are unable to place relic song on their meloetta after it does not spawn with the move due to it spawning at level 50 and the move being learned by the pokemon at level 50.

get a meloetta without the move Relic Song then try to go to move re-learner and try to learn the move.

The meloetta will not be able to learn the move via Move Relearner

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/396da768-aaa2-4a1e-b17a-c2d584ee26ec)
![image1](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/ccce86e3-0f29-4a7b-bcd0-5779ad7d3c3e)

![Desktop Screenshot 2024 02 27 - 16 21 03 62](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/fa66cea7-1c2f-4a3f-9da4-bfa0f5b04a7a)

Kung_fu_hustler

Titan

**Comment by Rasgnarok** [comment]
This will be up for next restart! Thank you for the report.
