### ISSUE TITLE
Players not receiving loot boxes from ptrewards.

### ISSUE THREAD

**Issue by G59Rhett** [ObliqueNetwork/Terra#2394]
**Describe the bug**
Players do not receive the lootboxes from /ptrewards upon claiming the rewards

**To Reproduce**
Try claiming a play time reward that provides a lootbox. 

**Expected behavior**
Expected to receive the lootboxes from the ptrewards
**Screenshots**
![image2](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/a8182cf2-458a-422e-8a00-cf5e43bb9b41)
![image3](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/254bb1f2-569c-400b-9227-825c3e7c4203)
![2024-02-27_19 43 31](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/b8a1f84a-7968-4717-a5a9-a21f308e8ab4)
![2024-02-27_19 43 34](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/66a8108c-10a0-4cdc-9cdf-cf800094a85e)
![2024-02-27_21 08 13](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/76afd6c2-78a1-4167-9fda-2339a4135638)

**Username:**
Fardiamond3049 and Rose_bushes_

**Server name (all applicable):**
Both occurrences were on titan

**Comment by WisconsinWinters** [comment]
fixed typo with mythic lootbox
