### ISSUE TITLE
Hub Chat doesn't work.

### ISSUE THREAD

**Issue by Mellozilla** [ObliqueNetwork/Terra#2397]
**Describe the bug**
Speaking in hub chat doesn't work. you get the message "Chat disabled due to missing profile public key. Please try reconnecting" This issue persists with all players. Reconnecting doesn't fix it.

**To Reproduce**
1. Go to Hub
2. Try to chat
3. Get error message

**Expected behavior**
Speak in chat

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/116930379/9aad36f8-0ee0-45f8-9012-60f3fd85f1ef)

**Username:**
AFadedColor

**Server name (all applicable):**
Hub-1 Hub-2

**Comment by WisconsinWinters** [comment]
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/f49f1a6f-b8ef-4522-92ae-3b332a00310b)
appears to be fixed now
