### ISSUE TITLE
Trading Achievement Bug

### ISSUE THREAD

**Issue by G59Rhett** [ObliqueNetwork/Terra#2398]
**Describe the bug**
Sending and Receiving pokemon achievement will not count unless you are the first player in the trade machine.

**To Reproduce**
Grab a friend to trade with and have one of you go into the trade machine first then the other after, proceed to do a trade as normal then after the trade has completed check your /achievements. You will notice progression only counted for the player that entered the trade machine first.

**Expected behavior**
Expected both players to get progression counted toward their /achievements.

**Username:**
G59Rhett
**Server name (all applicable):**
Titan

**Comment by WisconsinWinters** [comment]
forwarded
