### ISSUE TITLE
[Pixelmon] Baxcalibur missing TM learnset

### ISSUE THREAD

**Issue by Shika-The-Deer** [ObliqueNetwork/Terra#2399]
Baxcalibur is missing the ability to learn Paldean TMs.

To reproduce:
Get a Baxcalibur
Get Paldean TM 100: Dragon Dance or Paldean TM 149: Earthquake
Try to teach Baxcalibur either of these TMs

Expected behavior:
Baxcalibur is able to learn both of these moves via TM in Singleplayer and in Pokemon Scarlet/Violet, so it should be able to learn them via TM on NebulaMC.

Singleplayer behavior:
[image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/34965947/e72e38e4-7697-4331-aac1-ee2c9e8f94c7)
NebulaMC behavior:
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/34965947/a2459556-cb8d-4c15-94c1-5179f634d6c2)

Username:
Shika_Ink

Server name:
Orion, I expect all but am unable to test.

Additional context:
Switching from the server into singleplayer to test made it where Baxcalibur couldn't learn any TMs, but a fresh launch of the client directly into singlerplayer let it learn the TMs just fine.

**Comment by WisconsinWinters** [comment]
fix planned soon

**Comment by WisconsinWinters** [comment]
should be fixed, reopen if still an issue
