### ISSUE TITLE
Floating tags in Ione

### ISSUE THREAD

**Issue by G59Rhett** [ObliqueNetwork/Terra#2400]
Forwarding this here from ticket-starwarschamp4-177 - Floating armor stands left from old Ione
Floating tags from the old Ione are still found in the ocean of the new Ione.

![Base Profile Screenshot 2024 03 06 - 03 55 04 88](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/4224c2ad-413a-4eba-89c0-73fc2eea7206)

![Base Profile Screenshot 2024 03 06 - 03 54 50 88](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/aa330118-6067-4ff0-8d16-3da81ca0771a)

![Base Profile Screenshot 2024 03 06 - 03 54 21 16](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/160484864/5568bbba-6e03-4f90-82d7-9b2d4d140970)

**Comment by WisconsinWinters** [comment]
fixed.
