### ISSUE TITLE
[Form Change] Necrozma Dusk-Mane Form change Failure

### ISSUE THREAD

**Issue by ThaBoogyMAN** [ObliqueNetwork/Terra#2401]
**Describe the bug**
Necrozma Dusk-Mane changes during battle when mega evolving while holding into ultra necrozma. After the battle it does not rechange form back. 

**To Reproduce**
1. Got into battle with Necrozma Dusk-Mane thats holding ultranecrozium - z
2. press the mega evolve button and use the move photon geyser 
3. changes into Ultra necrozma
4. After battle does not revert

This was tested in the beta and was replicatable.

**Comment by WisconsinWinters** [comment]
fixed
