### ISSUE TITLE
[Feature] Bug explanation

### ISSUE THREAD

**Issue by WxllyDox** [ObliqueNetwork/Terra#2402]
Using a Form Modifier to turn Centiskorch into its perm Mega Form

Using a Form Modifier (Work on Leg or Not)
Click on Centiskorch
It Should appear

Was told by CpT that it wasnt suppose to do that

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/5e01d59f-668a-4838-88de-07f005fe69a6)

WxllyDox

All of Them

You should give me a thumb up sticker for my hard work 👍

**Comment by WisconsinWinters** [comment]
fixed.
