### ISSUE TITLE
Alolan Marowak doesn't have Shadow Bone in its move list.

### ISSUE THREAD

**Issue by Oryso** [ObliqueNetwork/Terra#2404]
**Describe the bug**
Shadow Bone is alolan marowaks signature move that it's supposed to learn upon evolution, and if you evolve a Cubone into one it will learn the move properly. However, if you don't teach it the move right there, then there's no way to get it back as its not in A-Marowaks move list for the move relearner.

**To Reproduce**
1. Get an Alolan Marowak (without Shadow Bone)
2. Go to move relearner
3. Shadow Bone isn't there

**Expected behavior**
For it to be able to learn Shadow Bone via move relearner

**Screenshots**
![2024-03-09_01 14 12](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/8fdc7c9e-e132-49b9-9c93-192663526150)
![2024-03-09_01 14 23](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/ea24a3b4-522d-474e-a6d8-5d86311fa5fe)

**Username:**
Oryso
**Server name (all applicable):**
Orion, could be all

**Comment by WisconsinWinters** [comment]
fixed planned soon.

**Comment by WisconsinWinters** [comment]
should be fixed, reopen if still an issue
