### ISSUE TITLE
[Poke Gift Item] Putting Untradeable Pokemon in a Poke Gift Item loses them when someone else grabs it

### ISSUE THREAD

**Issue by Ultamate2** [ObliqueNetwork/Terra#2406]
**Describe the bug**
When you put an Untradeable pokemon in the Poke Gift item, crafted from 4 cherish balls, then you let someone else take it, that pokemon gets deleted.

**To Reproduce**
1. Get a Poke Gift
2. Place it Down
3. Put Untradeable pokemon inside (by right clicking)
4. Have someone else try to claim it
5. the pokemon gets deleted.

**Expected behavior**
It should not let you be able to put the pokemon in the Poke Gift if it is untradeable

**Username: Shiguemii**

**Server name: All**

**Comment by WisconsinWinters** [comment]
this is a pixelmon issue, and i have forwarded this to their tracker
