### ISSUE TITLE
[Custom Pokemon] Zephyreon Normal/Shiny Sprite has a Different Sprite Base than the Pride Sprite

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#2407]
**Describe the bug**
Zephyreon's Shiny and Normal sprite have the same base, just a different color (as it should be). However, the Pride palette's sprite has a completely different base.

**To Reproduce**
1. Put a normal Zephyreon in your party
2. Put a pride Zephyreon in your party
3. Compare the sprites

**Expected behavior**
All Zephyreon sprites having the same base

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/37944220/5e3b6802-5a29-4251-ad71-b3257e79dc5a)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/37944220/919c06b2-f9cf-4336-b36d-303b72228cda)

**Username:**
DraconiacLatias

**Server name (all applicable):**
Orion

**Comment by CenizaRey** [comment]
![Zephyr update](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/42212238/a2428634-9ab0-475a-8d43-48a18670aa31)

Fixed for next respack update, thanks for the report! Closing
