### ISSUE TITLE
Jirachi is not available on Titan through LoC but it is available on Orion, unsure about atlas since no players had one there.

### ISSUE THREAD

**Issue by Mellozilla** [ObliqueNetwork/Terra#2408]
**Describe the bug**
Jirachi missing from LoC

**To Reproduce**
1. Use an LoC
2. Select Jirachi (in this case you cannot since it isnt there)
3. Get Jirachi
4. No Jirachi available.

**Expected behavior**
Receive Jirachi

**Screenshots**
Titan LoC - 
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/116930379/0eaa49f8-4f1f-4676-b4b1-ab5308acff4d)

Orion LoC -
![Screenshot 2024-03-11 115511](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/116930379/693c4e4f-a9df-4222-ae07-5744e3d80bf9)

**Username:**
AFadedColor
**Server name (all applicable):**
Titan

**Comment by CenizaRey** [comment]
Fixed, thanks for the report! Closing
