### ISSUE TITLE
Uncommon Loot Box Reward

### ISSUE THREAD

**Issue by Aerinyan** [ObliqueNetwork/Terra#2410]
**Describe the bug**
Uncommon Loot Box says that you won 32 rare candies but actually gives you 3 uncommon fishing baits.

**To Reproduce**
1. Claim/Trigger an uncommon loot box
2. Win/be rewarded with 32 rare candies
3. See that you received 3 uncommon fishing baits instead

**Expected behavior**
Either fix to actually give you the 32 rare candies or have the loot box announce you won 3 uncommon fishing baits instead (whichever wa intended)

**Screenshots**
![Screenshot 2024-03-13 221927](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/135560173/19d91f48-c6a3-4965-a381-48037fc4fa2d)

**Username: Aeiriecakes**

**Server name (all applicable): Orion (Probably All)**

**Comment by WisconsinWinters** [comment]
😭will fix in a sec
