### ISSUE TITLE
[Achievements] First "Release Legend" Achievement is Incorrect

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#2411]
**Describe the bug**
The first "Release Legends" achievement says to release three legendary pokemon, however the counter will read 0/1 or 1/1. The other first "Release" achievements (except general pokemon) make you release only one pokemon for it to count.

**To Reproduce**
1. Execute /achievements
2. Click on Releasing 
3. Compare "Release Legendary Pokemon" to the other release achievements 

**Expected behavior**
To release one legendary for the achievement to count

**Screenshots**
![2024-03-13_16 43 03](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/37944220/a263acfe-949d-4fdf-a8ea-864ed8905861)

**Username:**
DraconiacLatias

**Server name (all applicable):**
Orion

**Comment by chefburne** [comment]
Achievements reworked post-reset
