### ISSUE TITLE
Incorrect amount of money listed on Rune Rank

### ISSUE THREAD

**Issue by Mellozilla** [ObliqueNetwork/Terra#2412]
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/116930379/04064658-3ffd-4867-8e77-79f7a73a6575)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/116930379/7583f20d-28d9-4a27-9074-eea69b35c4b4)
75,000 is given but on the store it says 100,000

**Comment by WisconsinWinters** [comment]
the command and storepage will both need to be updated, will be fixed soon
