### ISSUE TITLE
/glow is not working

### ISSUE THREAD

**Issue by JamieRRE** [ObliqueNetwork/Terra#2414]
**Describe the bug**
/glow is not a command even though the store site states it does with rune rank.

**To Reproduce**
1. go on to the server
2. Type in /glow
3. Unknown command error

**Expected behavior**
a /glow menu should show up where you can select your glow with the colours

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/101290403/009092ec-87e4-48ee-b2e7-ceb7a3bb1e7a)

**Username:**
JamieRRE
**Server name (all applicable):**
All

**Comment by WisconsinWinters** [comment]
it's a planned feature, coming soon

**Comment by WisconsinWinters** [comment]
closing this as a planned feature
