### ISSUE TITLE
Shiny Giratina Griseous Core Bug

### ISSUE THREAD

**Issue by WxllyDox** [ObliqueNetwork/Terra#2415]
Having a Shiny Giratina and using a Griseous Core on it turns it into his Origin form. However if you want to put an item or remove an item from him, he will be force back into his base form

1. Shiny Giratina
2. Turn him into Origin Form
3. Give him/remove item 
4. Turn into Shiny Giratina Base Form

Giratina should of stand his Origin form for Three days then be forced back into Base Form
That didn't happen.

SageofWind (Person that found out0

WxllyDox (Tested Bug)

https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/155786899/66cdb769-9f59-4659-a1c8-ab61e1edc235

**Comment by WisconsinWinters** [comment]
tested in singleplayer and confirmed, forwarded to pixelmon
