### ISSUE TITLE
When a pokemon is holding a item it can not Dynamax

### ISSUE THREAD

**Issue by HealthyCoyote32** [ObliqueNetwork/Terra#2416]
Not being able to Dynamax a pokemon when that pokemon is holding a item. I have tested this on multiple pokemon and for some reason it never works.

**Comment by Rasgnarok** [comment]
@WisconsinWinters Can you confirm this is still an issue, and if so, is it a Pixelmon issue or an us issue?

**Comment by WisconsinWinters** [comment]
Just tested with a porygon holding an up-grade and was able to dynamax, re-open this issue if you have other pokemon/sets that is causing this.

**Comment by HealthyCoyote32** [comment]
There had been a ticket that I had solved a while back but now when I test it there seem to be no problem so I belive it is fixed.
