### ISSUE TITLE
[Tags] Tags can be right clicked on pokemon

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2417]
**Describe the bug**
If you right click a tag onto a pokemon it consumes the tag but doesn't grant the player the tag in /tags. Probably because tags are name tags and its trying to apply it to the pokemon.

**To Reproduce**
1. Grab yourself any tag that you don't have already unlocked
2. Right click it on a pokemon
3. Notice it gets consumed and check /tags

**Expected behavior**
Either the tag shouldnt try to be applied to the pokemon or the player would still recieve the tag
**Screenshots**

**Username:_Peyton_7**

**Server name (all applicable):FunPolice**

**Comment by WisconsinWinters** [comment]
this isn't something we can really fix unless we change the physical item for the tags, which would invalidate all existing ones.
