### ISSUE TITLE
Abyssal Maw showing it can learn egg moves

### ISSUE THREAD

**Issue by ShapooK** [ObliqueNetwork/Terra#2418]
**Describe the bug**
When doing /wiki on a Abyssal Maw in your party and clicking moves it shows it can learn egg moves, but in reality it can't. Probably had same file as Kingdra and has Horsea's egg moves

**To Reproduce**
1. Having a abyssal maw in your party
2. Click on moves 
3. See it has egg moves

**Expected behavior**
Abyssal maw shouldn't be able to learn egg moves being a paradox pokemon

**Username:**
ShapooK

![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35164973/f4a71dc2-b243-4c85-a7c7-de1f3b0f3ce0)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35164973/1ce6afa3-6429-4015-ab12-adf33639bdb1)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35164973/f88f2653-a8f1-4067-8607-8843660df90a)

**Comment by WisconsinWinters** [comment]
fixd
