### ISSUE TITLE
Bingo board won't open

### ISSUE THREAD

**Issue by JamieRRE** [ObliqueNetwork/Terra#2419]
**Describe the bug**
When you type /bingo, you get into the bingo menu as normal. But you cannot get into the Bingo board

**To Reproduce**
1: type /bingo on any server (in this case atlas for me)
2: Get into the bingo selection menu
3: Try to select a board
4: The board will not open.

**Expected behavior**
When typing /bingo and selecting a board, you should be able to select it.

Video: 
https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/101290403/9ee26dc5-5406-46eb-984f-f6b91385b6b9

**Username:**
JamieRRE

**Server name (all applicable):**
Atlas (Pretty sure all servers are effected though)

**Comment by WisconsinWinters** [comment]
fixed? open again if issue occurs again.
