### ISSUE TITLE
[Datapack] Spectreon is replaced with "Missingno" in Eevee's /wiki

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#2420]
**Describe the bug**
When doing /wiki eevee evolution, it says you can evolve Eevee into missingno with a dusk stone. This is supposed to be Spectreon

**To Reproduce**
1. Execute /wiki eevee evolution
2. Check the evolutions

**Expected behavior**
Spectreon to be listed instead of Eevee

**Screenshots**
![2024-03-29_00 21 01](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/37944220/1a24bcc2-3980-4b2e-80e3-5e9c95d0cd61)

**Username:**
DraconiacLatias

**Server name (all applicable):**
Orion

**Comment by WisconsinWinters** [comment]
Not sure if this something we can fix, since it appears as if pixelmonextras doesn't accept datapacked evolutions

**Comment by Khrisstias** [comment]
> Not sure if this something we can fix, since it appears as if pixelmonextras doesn't accept datapacked evolutions

However, the other ones show up fine, it is JUST Spectreon.

**Comment by WisconsinWinters** [comment]
i've forwarded this to our internal tracker, may be something with our locales or datapack that needs to be looked at.
