### ISSUE TITLE
/poaching feature won't seem to work

### ISSUE THREAD

**Issue by TotallyNotAl** [ObliqueNetwork/Terra#2421]
**Describe the bug**
the /poaching feature doesn't seem to work. It won't accept pokemon. tried poaching a level 50 dondozo, but was given a 'does not fit requirements' when it also says no requirements. Also tried with level 1 charmanders and a level 1 springatito. 

**To Reproduce**
1. Have a poaching pokemon in your party
2. Go to '/poaching' to try and poach it
3. click onto the selective pokemon you wish to poach
4. Not allowed to poach it from it 'not meeting requirements'

**Expected behavior**
 Allowing pokemon to be poached for money 

**Screenshots**
![Screenshot (28)](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/165449793/767f6481-8771-4ae9-beec-efd650560a17)
![Screenshot (27)](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/165449793/7cc0999d-8119-4f0c-849a-36748891043d)
![Screenshot (26)](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/165449793/fbaebd3c-abf4-49ef-8140-782d45ba4467)

**Username:**
TotallyNotAl

**Server name (all applicable):**
I'm not to sure if it's doing the same on all servers but I know it's doing so on Atlas.

**Logs:**

**Additional context**
None of the available poaching pokemon are being allowed to be poached that I've tried. (Donozo, numerous level 1 charmanders, a level 1 springatito, Dratini, rookidee  gastly and Magikarp)

**Comment by Rasgnarok** [comment]
needs re-testing after the reset, forwarded to Wis

**Comment by PJLesure** [comment]
Fix now on live servers, thanks for the report
