### ISSUE TITLE
Being stuck in Ultra Necrozma

### ISSUE THREAD

**Issue by HealthyCoyote32** [ObliqueNetwork/Terra#2423]
When a player has a lunala or Sogoleo Necrozma fusion and when they use the Z stone to get ultra Necrozma it is stuck in the ultra Necrozma form

**To Reproduce**
1. Have ultranecrozium z on Necrozma lunala or Sogeleo fusion
2. Start a battle with any pokemon or trainer
3. Use Z crystal/move (ultranecrozium z)
4. Pokemon is now stuck as Ultra Necrozma

**Expected behavior**
When the battle is over the Ultra Necrozma it should go back to lunala/Sogoleo fusion

**Username:**

NebulaMC

**Comment by WisconsinWinters** [comment]
forwarded to internaal tracker
