### ISSUE TITLE
Basculegion M & F forms swapping Genders when evolving & No items cant revert

### ISSUE THREAD

**Issue by Blenosu** [ObliqueNetwork/Terra#2425]
**Describe the bug**
When evolving Basculin-White Stripe into Basculegion with a Reaper Cloth, the Basculin turns from male to female or female to male. Basculegion has 2 forms Male which is a Physical attacker and Female which is special. At the same time the Basculegion cannot be palette/form/gender modded.

**To Reproduce**
1. Evolve a Male/Female Basculin-White Stripe by clicking on him with a Reaper Cloth
2. That Basculin has a chance to turn into the opposite gender.
3. If the Basculin's gender change's, players cant use mods to change it.
4. Grab Palette/Form/gender mod 
5. Click to open menu 
6. Basculegion will be blocked

**Expected behavior**
Basculin should not have their gender changed while evolving, Basculegion should be able to be modded into its second form (either gender).

**Screenshots**
The Gender Swap Issue Proof
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/132908282/e89ae23d-6c76-467a-8f3b-a3a7e73a6710)
![basculin 2](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/132908282/8e65c28f-636a-4ebd-89a0-8df5f457cdc3)
The Mods not working Proof
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/132908282/cf7ccba5-796d-4a76-b65b-d3cb3c18a3cd)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/132908282/4af29efc-7783-4772-9764-549965cdd992)

**Username:**
Blenosu
**Server name (all applicable):**
All should have the same issue (Only tested on Atlas)
**Additional context**
To keep in mind that the gender swap doesnt always happen, My 1st and 4th Basculin got their gender swapped when evolving

**Comment by WisconsinWinters** [comment]
so far have unable to reproduce this, re-open issue if it happens again. i'd recommend trying in singleplayer too if it happens there as well.
