### ISSUE TITLE
Plushstore appears to be bugged, as well as plushy drops.

### ISSUE THREAD

**Issue by JamieRRE** [ObliqueNetwork/Terra#2426]
**Describe the bug**
Stickerbook appears to not give out the plushy you are supposed to obtain, and neither will the plushstore give you the plush you are trying to buy. It does take the money from you though.

**To Reproduce**
Plushstore:
type /plushstore and select any gen, buy one of the plushys and you do not get the plushy but the money gets taken.
do /stickerbook and select the book you want to fill out. You get all rewards except the plushy.

**Expected behavior**
Plushstore - Obtain the plushy you paid for
Stickerbook - Obtain the plushy you did the stickerbook for

**Username:**
JamieRRE

**Server name (all applicable):**
All

**Comment by JamieRRE** [comment]
https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/101290403/7aec7bd2-4eef-453e-9e38-f7bf7fc06382

Video of trying to buy a plushy from the store and it not working

**Comment by chefburne** [comment]
Resolved
