### ISSUE TITLE
[Feature] lost dexrank rewards in server crash

### ISSUE THREAD

**Issue by dadijo2002** [ObliqueNetwork/Terra#2427]
**Describe the bug**
Dexranks claimed before server crash do not save all physical items (ie all except pokemon and money) after crash. In my case, I kept the shiny associated with nest but lost the lucky egg and healer/pc/etc

**To Reproduce**
1. Claim dexrank reward
2. Server crashes
3. Log on again after reopening
4. Items are gone

**Expected behavior**
Items should remain in inventory

**Screenshots**

**Username:** dadijo2002

**Server name (all applicable):** Atlas but probably all of them

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**

**Comment by WisconsinWinters** [comment]
this should be ticketed with our discord support team.

https://discord.com/channels/151095626916954113/1102942606335418428/1239683818487549983
