### ISSUE TITLE
UBs/Paradoxes not spawning correctly

### ISSUE THREAD

**Issue by Oryso** [ObliqueNetwork/Terra#2428]
**Describe the bug**
Whenever a paradox or ultra beast spawns, there are some things thats not happening:
1. Message is not being announced in chat upon spawning like it was before reset
2. Not showing up in /poketracker when spawning
3. Not having guaranteed 3 perfect IVs when caught

**To Reproduce**
1. Have a UB/Paradox spawn
2. See no message in chat/picture in tracker
3. Catch, see no 3 31's

**Expected behavior**
Expected to announce in chat, show on poketracker, and have 3 31's in IVs.

**Screenshots**
![2024-05-20_02 38 04](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/988b02b5-c70c-4679-aad8-7fe9da3e5180)
![2024-05-22_22 09 53](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/cdb18d26-4583-4eba-bf7d-10f4e4c1bb3a)

**Username:**
Oryso

**Server name (all applicable):**
Orion, Atlas, probably Titan too

**Additional context**
The first SS was of an Iron Hibiscus I spawned with legend spawn shards, it didn't announce it spawning in chat, and as you can see it doesnt have 3 31's.

There was also an Iron Treads that I had spawn on me that I forgot to SS, and I know DraconicLatias also had a Great Tusk spawn on them, both of which are the same as the hibiscus.

**Comment by chefburne** [comment]
Ultra Beasts worked fine, now that we added the Ultra Beast tag to Paradox Pokémon, this should be resolved
