### ISSUE TITLE
Missing parents after breeding 

### ISSUE THREAD

**Issue by FatherKarp** [ObliqueNetwork/Terra#2429]
**Describe the bug**
After taking my egg from the day care , my Drilbur and Ditto disappeared and did not go to my pc

**Expected behavior**
my Drilbur and Ditto should be in my pc 

**Username:**
FatherKarp

**Server name (all applicable):**
Titan

Discord - .ratpriest

**Comment by WisconsinWinters** [comment]
this is a discord support ticket issue, file one here

https://discord.com/channels/151095626916954113/1102942606335418428/1239683818487549983
