### ISSUE TITLE
[Battle Perfect Spins] - Few errors/Fixes needed

### ISSUE THREAD

**Issue by x-Bran-x** [ObliqueNetwork/Terra#2430]
**Describe the bug**
Battle perfect spins have a few mistakes in the names, ability or forms of a few pokemon
1. Greninja - Ability needs changing to Protean
2. Cualan Macargo - Needs the description for spin updated (Since Cualan doesn't exist anymore)
3. Solrock and Lunatone - New updating to their new evolutions

**To Reproduce**
1. Open a Battle Perfect Spin
2. Receive any of the following 4 pokemon listed above
3. Battle perfect spin shows the player won a Cualan Macargo
- Greninja Ability is currently Torrent
- Solrock/Lunatone don't have the new evolution forms

**Expected behavior**
Could cause confusion with players and people not being happy about receiving pokemon that aren't 'battle perfect' as stated

**Username:**
xBranx

**Server name (all applicable):**
Titan, Orion, Atlas

**Comment by Peyton7** [comment]
Solrock changed to Solpernova, Lunatone changed to Lunaclipse, and Magcargo changed to Volcargo. Greninja's ability changed to protean.
