### ISSUE TITLE
Uncommon Lootbox

### ISSUE THREAD

**Issue by x-Bran-x** [ObliqueNetwork/Terra#2432]
**Describe the bug**
When you open an Uncommon lootbox and obtain 'TM Air Slash'
It gifts you Acrobatics instead

**To Reproduce**
1. Open an Uncommon Lootbox
2. Receive 'Air slash TM'
3. Turns to Acrobatics

**Expected behavior**
Confusion on players expecting to receive air slash, but get acrobatics instead

**Username:**
xBranx
- User reported: Orthusaku

**Server name (all applicable):**
Noted on Orion, but could be all

**Comment by chefburne** [comment]
Resolved
